	.align 2
	@********************** Voicegroup **********************@

	.global voicegroup000
voicegroup000:	@ 0x02019D30
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@02019D30
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@02019D3C
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@02019D48
mAlignWord
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@02019D54
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@02019D60
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019D6C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019D78
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019D84
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019D90
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019D9C
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@02019DA8
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@02019DB4
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@02019DC0
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@02019DCC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019DD8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019DE4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019DF0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019DFC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019E08
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019E14
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019E20
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019E2C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019E38
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019E44
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019E50
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019E5C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019E68
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019E74
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019E80
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019E8C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019E98
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019EA4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019EB0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019EBC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019EC8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019ED4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019EE0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019EEC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019EF8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019F04
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_201A3E4, 0, 4, 4, 0	@02019F10
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_201A3F4, 0, 0, 15, 0	@02019F1C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_201A404, 0, 0, 15, 0	@02019F28
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_201A414, 0, 0, 15, 0	@02019F34
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_201A424, 0, 0, 15, 0	@02019F40
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_201A434, 0, 0, 15, 0	@02019F4C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_201A444, 0, 0, 15, 0	@02019F58
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_201A454, 0, 0, 15, 0	@02019F64
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_201A464, 0, 3, 0, 2	@02019F70
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_201A3E4, 0, 5, 0, 2	@02019F7C
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@02019F88
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@02019F94
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 4	@02019FA0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_201A3F4, 0, 6, 1, 0	@02019FAC
mAlignWord
	voice_square_2_alt 2, 0, 4, 1, 0	@02019FB8
mAlignWord
	voice_directsound 60, 0, DirectSoundData_roland_sr_jv80_02__186_harp_1, 255, 242, 25, 0	@02019FC4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019FD0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019FDC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019FE8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@02019FF4
mAlignWord
	voice_square_1_alt 0, 2, 0, 3, 3, 0	@0201A000
mAlignWord
	voice_square_1_alt 0, 2, 1, 2, 3, 0	@0201A00C
mAlignWord
	voice_square_1_alt 0, 2, 0, 2, 3, 0	@0201A018
mAlignWord
	voice_square_1_alt 0, 2, 1, 5, 1, 0	@0201A024
mAlignWord
	voice_square_1_alt 0, 0, 1, 0, 15, 0	@0201A030
mAlignWord
	voice_square_1_alt 0, 0, 1, 5, 1, 0	@0201A03C
mAlignWord
	voice_square_1_alt 0, 2, 1, 4, 1, 0	@0201A048
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A054
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A060
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A06C
mAlignWord
	voice_square_2_alt 2, 1, 5, 7, 0	@0201A078
mAlignWord
	voice_directsound 60, 0, DirectSoundData_roland_jv2080__pr_d__banjo, 255, 246, 51, 127	@0201A084
mAlignWord
	voice_directsound 60, 0, DirectSoundData_roland_jv2080__pr_d__harmonica, 255, 246, 128, 127	@0201A090
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A09C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A0A8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A0B4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A0C0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A0CC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A0D8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A0E4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A0F0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A0FC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A108
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A114
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A120
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A12C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A138
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A144
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A150
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A15C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A168
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A174
