	.align 2
	@********************** Voicegroup **********************@

	.global voicegroup001
voicegroup001:	@ 0x0201A180
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A180
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A18C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A198
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A1A4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A1B0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A1BC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A1C8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A1D4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A1E0
mAlignWord
	voice_directsound 60, 0, DirectSoundData_roland_jv2080__pr_d__019_organ_3__5, 255, 0, 255, 127	@0201A1EC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A1F8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A204
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A210
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A21C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A228
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A234
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A240
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A24C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A258
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A264
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A270
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A27C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A288
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A294
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A2A0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A2AC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A2B8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A2C4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A2D0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A2DC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A2E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A2F4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A300
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A30C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A318
mAlignWord
	voice_keysplit_all voicegroup001	@0201A324
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundData_korg_trinity__standard_kit__1__shortened, 255, 255, 255, 0	@0201A330
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundData_korg_trinity__standard_kit__2__shortened, 255, 0, 255, 0	@0201A33C
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 1, 0, 0	@0201A348
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 2, 0, 0	@0201A354
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 3, 7, 0	@0201A360
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A36C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A378
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A384
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A390
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A39C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A3A8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A3B4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A3C0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@0201A3CC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundData_roland_jv2080__pr_e__jazz_drum_set1__2, 255, 0, 255, 0	@0201A3D8
