	.align 2
    .global gUnknown_08AD5F28
gUnknown_08AD5F28:
	.incbin "sound/direct_sound_samples/08AD5F28.bin"

	.align 2
	.global gUnknown_08AD73FC
gUnknown_08AD73FC:
	.incbin "sound/direct_sound_samples/08AD73FC.bin"

	.align 2
	.global gUnknown_08AD8810
gUnknown_08AD8810:
	.incbin "sound/direct_sound_samples/08AD8810.bin"

	.align 2
	.global gUnknown_08AD9140
gUnknown_08AD9140:
	.incbin "sound/direct_sound_samples/08AD9140.bin"

	.align 2
	.global gUnknown_08AD98B0
gUnknown_08AD98B0:
	.incbin "sound/direct_sound_samples/08AD98B0.bin"

	.align 2
	.global gUnknown_08ADB1A4
gUnknown_08ADB1A4:
	.incbin "sound/direct_sound_samples/08ADB1A4.bin"

	.align 2
	.global gUnknown_08ADE2D0
gUnknown_08ADE2D0:
	.incbin "sound/direct_sound_samples/08ADE2D0.bin"

	.align 2
	.global gUnknown_08ADE918
gUnknown_08ADE918:
	.incbin "sound/direct_sound_samples/08ADE918.bin"

	.align 2
	.global gUnknown_08AE200C
gUnknown_08AE200C:
	.incbin "sound/direct_sound_samples/08AE200C.bin"

	.align 2
	.global gUnknown_08AE4FE8
gUnknown_08AE4FE8:
	.incbin "sound/direct_sound_samples/08AE4FE8.bin"

	.align 2
	.global gUnknown_08AE7F2C
gUnknown_08AE7F2C:
	.incbin "sound/direct_sound_samples/08AE7F2C.bin"

	.align 2
	.global gUnknown_08AE98B4
gUnknown_08AE98B4:
	.incbin "sound/direct_sound_samples/08AE98B4.bin"

	.align 2
	.global gUnknown_08AE9BB4
gUnknown_08AE9BB4:
	.incbin "sound/direct_sound_samples/08AE9BB4.bin"

	.align 2
	.global gUnknown_08AEA788
gUnknown_08AEA788:
	.incbin "sound/direct_sound_samples/08AEA788.bin"

	.align 2
	.global gUnknown_08AED36C
gUnknown_08AED36C:
	.incbin "sound/direct_sound_samples/08AED36C.bin"

	.align 2
	.global gUnknown_08AF0160
gUnknown_08AF0160:
	.incbin "sound/direct_sound_samples/08AF0160.bin"

	.align 2
	.global gUnknown_08AF2584
gUnknown_08AF2584:
	.incbin "sound/direct_sound_samples/08AF2584.bin"

	.align 2
	.global gUnknown_08AF2C98
gUnknown_08AF2C98:
	.incbin "sound/direct_sound_samples/08AF2C98.bin"

	.align 2
	.global gUnknown_08AF39C8
gUnknown_08AF39C8:
	.incbin "sound/direct_sound_samples/08AF39C8.bin"

	.align 2
	.global gUnknown_08AF5F44
gUnknown_08AF5F44:
	.incbin "sound/direct_sound_samples/08AF5F44.bin"

	.align 2
	.global gUnknown_08AF65D8
gUnknown_08AF65D8:
	.incbin "sound/direct_sound_samples/08AF65D8.bin"

	.align 2
	.global gUnknown_08AF6F80
gUnknown_08AF6F80:
	.incbin "sound/direct_sound_samples/08AF6F80.bin"

	.align 2
	.global gUnknown_08AFA040
gUnknown_08AFA040:
	.incbin "sound/direct_sound_samples/08AFA040.bin"

	.align 2
	.global gUnknown_08AFAD54
gUnknown_08AFAD54:
	.incbin "sound/direct_sound_samples/08AFAD54.bin"

	.align 2
	.global gUnknown_08AFDF30
gUnknown_08AFDF30:
	.incbin "sound/direct_sound_samples/08AFDF30.bin"

	.align 2
	.global gUnknown_08B00004
gUnknown_08B00004:
	.incbin "sound/direct_sound_samples/08B00004.bin"

	.align 2
	.global gUnknown_08B02518
gUnknown_08B02518:
	.incbin "sound/direct_sound_samples/08B02518.bin"

	.align 2
	.global gUnknown_08B04840
gUnknown_08B04840:
	.incbin "sound/direct_sound_samples/08B04840.bin"

	.align 2
	.global gUnknown_08B051E4
gUnknown_08B051E4:
	.incbin "sound/direct_sound_samples/08B051E4.bin"

	.align 2
	.global gUnknown_08B0C95C
gUnknown_08B0C95C:
	.incbin "sound/direct_sound_samples/08B0C95C.bin"

	.align 2
	.global gUnknown_08B0F724
gUnknown_08B0F724:
	.incbin "sound/direct_sound_samples/08B0F724.bin"

	.align 2
	.global gUnknown_08B109B8
gUnknown_08B109B8:
	.incbin "sound/direct_sound_samples/08B109B8.bin"

	.align 2
	.global gUnknown_08B18DD0
gUnknown_08B18DD0:
	.incbin "sound/direct_sound_samples/08B18DD0.bin"

	.align 2
	.global gUnknown_08B1E9F0
gUnknown_08B1E9F0:
	.incbin "sound/direct_sound_samples/08B1E9F0.bin"

	.align 2
	.global gUnknown_08B20204
gUnknown_08B20204:
	.incbin "sound/direct_sound_samples/08B20204.bin"

	.align 2
	.global gUnknown_08B21DC8
gUnknown_08B21DC8:
	.incbin "sound/direct_sound_samples/08B21DC8.bin"

	.align 2
	.global gUnknown_08B22678
gUnknown_08B22678:
	.incbin "sound/direct_sound_samples/08B22678.bin"

	.align 2
	.global gUnknown_08B232F0
gUnknown_08B232F0:
	.incbin "sound/direct_sound_samples/08B232F0.bin"

	.align 2
	.global gUnknown_08B24488
gUnknown_08B24488:
	.incbin "sound/direct_sound_samples/08B24488.bin"

	.align 2
	.global gUnknown_08B24D8C
gUnknown_08B24D8C:
	.incbin "sound/direct_sound_samples/08B24D8C.bin"

	.align 2
	.global gUnknown_08B257FC
gUnknown_08B257FC:
	.incbin "sound/direct_sound_samples/08B257FC.bin"

	.align 2
	.global gUnknown_08B2993C
gUnknown_08B2993C:
	.incbin "sound/direct_sound_samples/08B2993C.bin"

	.align 2
	.global gUnknown_08B2D744
gUnknown_08B2D744:
	.incbin "sound/direct_sound_samples/08B2D744.bin"

	.align 2
	.global gUnknown_08B2DEF8
gUnknown_08B2DEF8:
	.incbin "sound/direct_sound_samples/08B2DEF8.bin"

	.align 2
	.global gUnknown_08B2E708
gUnknown_08B2E708:
	.incbin "sound/direct_sound_samples/08B2E708.bin"

	.align 2
	.global gUnknown_08B2EEB8
gUnknown_08B2EEB8:
	.incbin "sound/direct_sound_samples/08B2EEB8.bin"

	.align 2
	.global gUnknown_08B2F9FC
gUnknown_08B2F9FC:
	.incbin "sound/direct_sound_samples/08B2F9FC.bin"

	.align 2
	.global gUnknown_08B3125C
gUnknown_08B3125C:
	.incbin "sound/direct_sound_samples/08B3125C.bin"

	.align 2
	.global gUnknown_08B36678
gUnknown_08B36678:
	.incbin "sound/direct_sound_samples/08B36678.bin"

	.align 2
	.global gUnknown_08B3B740
gUnknown_08B3B740:
	.incbin "sound/direct_sound_samples/08B3B740.bin"

	.align 2
	.global gUnknown_08B3D2F8
gUnknown_08B3D2F8:
	.incbin "sound/direct_sound_samples/08B3D2F8.bin"

	.align 2
	.global gUnknown_08B413E0
gUnknown_08B413E0:
	.incbin "sound/direct_sound_samples/08B413E0.bin"

	.align 2
	.global gUnknown_08B4603C
gUnknown_08B4603C:
	.incbin "sound/direct_sound_samples/08B4603C.bin"

	.align 2
	.global gUnknown_08B481E0
gUnknown_08B481E0:
	.incbin "sound/direct_sound_samples/08B481E0.bin"

	.align 2
	.global gUnknown_08B49D64
gUnknown_08B49D64:
	.incbin "sound/direct_sound_samples/08B49D64.bin"

	.align 2
	.global gUnknown_08B4BB5C
gUnknown_08B4BB5C:
	.incbin "sound/direct_sound_samples/08B4BB5C.bin"

	.align 2
	.global gUnknown_08B4C398
gUnknown_08B4C398:
	.incbin "sound/direct_sound_samples/08B4C398.bin"

	.align 2
	.global gUnknown_08B4F264
gUnknown_08B4F264:
	.incbin "sound/direct_sound_samples/08B4F264.bin"

	.align 2
	.global gUnknown_08B503F8
gUnknown_08B503F8:
	.incbin "sound/direct_sound_samples/08B503F8.bin"

	.align 2
	.global gUnknown_08B5121C
gUnknown_08B5121C:
	.incbin "sound/direct_sound_samples/08B5121C.bin"

	.align 2
	.global gUnknown_08B51EBC
gUnknown_08B51EBC:
	.incbin "sound/direct_sound_samples/08B51EBC.bin"

	.align 2
	.global gUnknown_08B53440
gUnknown_08B53440:
	.incbin "sound/direct_sound_samples/08B53440.bin"

	.align 2
	.global gUnknown_08B58484
gUnknown_08B58484:
	.incbin "sound/direct_sound_samples/08B58484.bin"

	.align 2
	.global gUnknown_08B5AA00
gUnknown_08B5AA00:
	.incbin "sound/direct_sound_samples/08B5AA00.bin"

	.align 2
	.global gUnknown_08B5C858
gUnknown_08B5C858:
	.incbin "sound/direct_sound_samples/08B5C858.bin"

	.align 2
	.global gUnknown_08B5F64C
gUnknown_08B5F64C:
	.incbin "sound/direct_sound_samples/08B5F64C.bin"

	.align 2
	.global gUnknown_08B61D94
gUnknown_08B61D94:
	.incbin "sound/direct_sound_samples/08B61D94.bin"

	.align 2
	.global gUnknown_08B6410C
gUnknown_08B6410C:
	.incbin "sound/direct_sound_samples/08B6410C.bin"

	.align 2
	.global gUnknown_08B65154
gUnknown_08B65154:
	.incbin "sound/direct_sound_samples/08B65154.bin"

	.align 2
	.global gUnknown_08B663E0
gUnknown_08B663E0:
	.incbin "sound/direct_sound_samples/08B663E0.bin"

	.align 2
	.global gUnknown_08B67464
gUnknown_08B67464:
	.incbin "sound/direct_sound_samples/08B67464.bin"

	.align 2
	.global gUnknown_08B688B8
gUnknown_08B688B8:
	.incbin "sound/direct_sound_samples/08B688B8.bin"

	.align 2
	.global gUnknown_08B6BA40
gUnknown_08B6BA40:
	.incbin "sound/direct_sound_samples/08B6BA40.bin"

	.align 2
	.global gUnknown_08B6FA94
gUnknown_08B6FA94:
	.incbin "sound/direct_sound_samples/08B6FA94.bin"

	.align 2
	.global gUnknown_08B70C1C
gUnknown_08B70C1C:
	.incbin "sound/direct_sound_samples/08B70C1C.bin"

	.align 2
	.global gUnknown_08B72E4C
gUnknown_08B72E4C:
	.incbin "sound/direct_sound_samples/08B72E4C.bin"

	.align 2
	.global gUnknown_08B756E4
gUnknown_08B756E4:
	.incbin "sound/direct_sound_samples/08B756E4.bin"

	.align 2
	.global gUnknown_08B78148
gUnknown_08B78148:
	.incbin "sound/direct_sound_samples/08B78148.bin"

	.align 2
	.global gUnknown_08B7A79C
gUnknown_08B7A79C:
	.incbin "sound/direct_sound_samples/08B7A79C.bin"

	.align 2
	.global gUnknown_08B7E428
gUnknown_08B7E428:
	.incbin "sound/direct_sound_samples/08B7E428.bin"

	.align 2
	.global gUnknown_08B80688
gUnknown_08B80688:
	.incbin "sound/direct_sound_samples/08B80688.bin"

	.align 2
	.global gUnknown_08B84450
gUnknown_08B84450:
	.incbin "sound/direct_sound_samples/08B84450.bin"

	.align 2
	.global gUnknown_08B8A5F8
gUnknown_08B8A5F8:
	.incbin "sound/direct_sound_samples/08B8A5F8.bin"

	.align 2
	.global gUnknown_08B91D70
gUnknown_08B91D70:
	.incbin "sound/direct_sound_samples/08B91D70.bin"

	.align 2
	.global gUnknown_08B940F0
gUnknown_08B940F0:
	.incbin "sound/direct_sound_samples/08B940F0.bin"

	.align 2
	.global gUnknown_08B98840
gUnknown_08B98840:
	.incbin "sound/direct_sound_samples/08B98840.bin"

	.align 2
	.global gUnknown_08B9A988
gUnknown_08B9A988:
	.incbin "sound/direct_sound_samples/08B9A988.bin"

	.align 2
	.global gUnknown_08B9AD68
gUnknown_08B9AD68:
	.incbin "sound/direct_sound_samples/08B9AD68.bin"

	.align 2
	.global gUnknown_08B9B1C0
gUnknown_08B9B1C0:
	.incbin "sound/direct_sound_samples/08B9B1C0.bin"

	.align 2
	.global gUnknown_08B9BB3C
gUnknown_08B9BB3C:
	.incbin "sound/direct_sound_samples/08B9BB3C.bin"

	.align 2
	.global gUnknown_08B9BF9C
gUnknown_08B9BF9C:
	.incbin "sound/direct_sound_samples/08B9BF9C.bin"

	.align 2
	.global gUnknown_08B9C408
gUnknown_08B9C408:
	.incbin "sound/direct_sound_samples/08B9C408.bin"

	.align 2
	.global gUnknown_08B9C894
gUnknown_08B9C894:
	.incbin "sound/direct_sound_samples/08B9C894.bin"

	.align 2
	.global gUnknown_08B9D1C0
gUnknown_08B9D1C0:
	.incbin "sound/direct_sound_samples/08B9D1C0.bin"

	.align 2
	.global gUnknown_08B9D718
gUnknown_08B9D718:
	.incbin "sound/direct_sound_samples/08B9D718.bin"

	.align 2
	.global gUnknown_08B9DB80
gUnknown_08B9DB80:
	.incbin "sound/direct_sound_samples/08B9DB80.bin"

	.align 2
	.global gUnknown_08BA2C60
gUnknown_08BA2C60:
	.incbin "sound/direct_sound_samples/08BA2C60.bin"

	.align 2
	.global gUnknown_08BA3AB8
gUnknown_08BA3AB8:
	.incbin "sound/direct_sound_samples/08BA3AB8.bin"

	.align 2
	.global gUnknown_08BA4DA4
gUnknown_08BA4DA4:
	.incbin "sound/direct_sound_samples/08BA4DA4.bin"

	.align 2
	.global gUnknown_08BA62E0
gUnknown_08BA62E0:
	.incbin "sound/direct_sound_samples/08BA62E0.bin"

	.align 2
	.global gUnknown_08BA6AA0
gUnknown_08BA6AA0:
	.incbin "sound/direct_sound_samples/08BA6AA0.bin"

	.align 2
	.global gUnknown_08BAA2DC
gUnknown_08BAA2DC:
	.incbin "sound/direct_sound_samples/08BAA2DC.bin"

	.align 2
	.global gUnknown_08BAFDC0
gUnknown_08BAFDC0:
	.incbin "sound/direct_sound_samples/08BAFDC0.bin"

	.align 2
	.global gUnknown_08BB152C
gUnknown_08BB152C:
	.incbin "sound/direct_sound_samples/08BB152C.bin"

	.align 2
	.global gUnknown_08BB2CAC
gUnknown_08BB2CAC:
	.incbin "sound/direct_sound_samples/08BB2CAC.bin"

	.align 2
	.global gUnknown_08BB4C60
gUnknown_08BB4C60:
	.incbin "sound/direct_sound_samples/08BB4C60.bin"

	.align 2
	.global gUnknown_08BB672C
gUnknown_08BB672C:
	.incbin "sound/direct_sound_samples/08BB672C.bin"

	.align 2
	.global gUnknown_08BB8F2C
gUnknown_08BB8F2C:
	.incbin "sound/direct_sound_samples/08BB8F2C.bin"

	.align 2
	.global gUnknown_08BBA360
gUnknown_08BBA360:
	.incbin "sound/direct_sound_samples/08BBA360.bin"

	.align 2
	.global gUnknown_08BBB180
gUnknown_08BBB180:
	.incbin "sound/direct_sound_samples/08BBB180.bin"

	.align 2
	.global gUnknown_08BBC26C
gUnknown_08BBC26C:
	.incbin "sound/direct_sound_samples/08BBC26C.bin"

	.align 2
	.global gUnknown_08BBD0E4
gUnknown_08BBD0E4:
	.incbin "sound/direct_sound_samples/08BBD0E4.bin"

	.align 2
	.global gUnknown_08BC0D9C
gUnknown_08BC0D9C:
	.incbin "sound/direct_sound_samples/08BC0D9C.bin"

	.align 2
	.global gUnknown_08BC311C
gUnknown_08BC311C:
	.incbin "sound/direct_sound_samples/08BC311C.bin"

	.align 2
	.global gUnknown_08BC3DD4
gUnknown_08BC3DD4:
	.incbin "sound/direct_sound_samples/08BC3DD4.bin"

	.align 2
	.global gUnknown_08BC6304
gUnknown_08BC6304:
	.incbin "sound/direct_sound_samples/08BC6304.bin"

	.align 2
	.global gUnknown_08BC7C58
gUnknown_08BC7C58:
	.incbin "sound/direct_sound_samples/08BC7C58.bin"

	.align 2
	.global gUnknown_08BCCBD4
gUnknown_08BCCBD4:
	.incbin "sound/direct_sound_samples/08BCCBD4.bin"

	.align 2
	.global gUnknown_08BCD1DC
gUnknown_08BCD1DC:
	.incbin "sound/direct_sound_samples/08BCD1DC.bin"

	.align 2
	.global gUnknown_08BCD85C
gUnknown_08BCD85C:
	.incbin "sound/direct_sound_samples/08BCD85C.bin"

	.align 2
	.global gUnknown_08BCDF04
gUnknown_08BCDF04:
	.incbin "sound/direct_sound_samples/08BCDF04.bin"

	.align 2
	.global gUnknown_08BCF078
gUnknown_08BCF078:
	.incbin "sound/direct_sound_samples/08BCF078.bin"

	.align 2
	.global gUnknown_08BCFC30
gUnknown_08BCFC30:
	.incbin "sound/direct_sound_samples/08BCFC30.bin"

	.align 2
	.global gUnknown_08BD0EC0
gUnknown_08BD0EC0:
	.incbin "sound/direct_sound_samples/08BD0EC0.bin"

	.align 2
	.global gUnknown_08BD154C
gUnknown_08BD154C:
	.incbin "sound/direct_sound_samples/08BD154C.bin"

	.align 2
	.global gUnknown_08BD26FC
gUnknown_08BD26FC:
	.incbin "sound/direct_sound_samples/08BD26FC.bin"

	.align 2
	.global gUnknown_08BD2F00
gUnknown_08BD2F00:
	.incbin "sound/direct_sound_samples/08BD2F00.bin"

	.align 2
	.global gUnknown_08BD3704
gUnknown_08BD3704:
	.incbin "sound/direct_sound_samples/08BD3704.bin"

	.align 2
	.global gUnknown_08BD4838
gUnknown_08BD4838:
	.incbin "sound/direct_sound_samples/08BD4838.bin"

	.align 2
	.global gUnknown_08BD554C
gUnknown_08BD554C:
	.incbin "sound/direct_sound_samples/08BD554C.bin"

	.align 2
	.global gUnknown_08BD624C
gUnknown_08BD624C:
	.incbin "sound/direct_sound_samples/08BD624C.bin"

	.align 2
	.global gUnknown_08BD69B0
gUnknown_08BD69B0:
	.incbin "sound/direct_sound_samples/08BD69B0.bin"

	.align 2
	.global gUnknown_08BD7148
gUnknown_08BD7148:
	.incbin "sound/direct_sound_samples/08BD7148.bin"

	.align 2
	.global gUnknown_08BD78B0
gUnknown_08BD78B0:
	.incbin "sound/direct_sound_samples/08BD78B0.bin"

	.align 2
	.global gUnknown_08BD8038
gUnknown_08BD8038:
	.incbin "sound/direct_sound_samples/08BD8038.bin"

	.align 2
	.global gUnknown_08BD8F8C
gUnknown_08BD8F8C:
	.incbin "sound/direct_sound_samples/08BD8F8C.bin"

	.align 2
	.global gUnknown_08BD974C
gUnknown_08BD974C:
	.incbin "sound/direct_sound_samples/08BD974C.bin"

	.align 2
	.global gUnknown_08BD9E98
gUnknown_08BD9E98:
	.incbin "sound/direct_sound_samples/08BD9E98.bin"

	.align 2
	.global gUnknown_08BDA604
gUnknown_08BDA604:
	.incbin "sound/direct_sound_samples/08BDA604.bin"

	.align 2
	.global gUnknown_08BDADF0
gUnknown_08BDADF0:
	.incbin "sound/direct_sound_samples/08BDADF0.bin"

	.align 2
	.global gUnknown_08BDB550
gUnknown_08BDB550:
	.incbin "sound/direct_sound_samples/08BDB550.bin"

	.align 2
	.global gUnknown_08BDBBDC
gUnknown_08BDBBDC:
	.incbin "sound/direct_sound_samples/08BDBBDC.bin"

	.align 2
	.global gUnknown_08BDC2B0
gUnknown_08BDC2B0:
	.incbin "sound/direct_sound_samples/08BDC2B0.bin"

	.align 2
	.global gUnknown_08BDC990
gUnknown_08BDC990:
	.incbin "sound/direct_sound_samples/08BDC990.bin"

	.align 2
	.global gUnknown_08BDD1E0
gUnknown_08BDD1E0:
	.incbin "sound/direct_sound_samples/08BDD1E0.bin"

	.align 2
	.global gUnknown_08BDD84C
gUnknown_08BDD84C:
	.incbin "sound/direct_sound_samples/08BDD84C.bin"

	.align 2
	.global gUnknown_08BDE000
gUnknown_08BDE000:
	.incbin "sound/direct_sound_samples/08BDE000.bin"

	.align 2
	.global gUnknown_08BDE740
gUnknown_08BDE740:
	.incbin "sound/direct_sound_samples/08BDE740.bin"

	.align 2
	.global gUnknown_08BDEE64
gUnknown_08BDEE64:
	.incbin "sound/direct_sound_samples/08BDEE64.bin"

	.align 2
	.global gUnknown_08BDF514
gUnknown_08BDF514:
	.incbin "sound/direct_sound_samples/08BDF514.bin"

	.align 2
	.global gUnknown_08BDFC2C
gUnknown_08BDFC2C:
	.incbin "sound/direct_sound_samples/08BDFC2C.bin"

	.align 2
	.global gUnknown_08BE0354
gUnknown_08BE0354:
	.incbin "sound/direct_sound_samples/08BE0354.bin"

	.align 2
	.global gUnknown_08BE0AC0
gUnknown_08BE0AC0:
	.incbin "sound/direct_sound_samples/08BE0AC0.bin"

	.align 2
	.global gUnknown_08BE11F0
gUnknown_08BE11F0:
	.incbin "sound/direct_sound_samples/08BE11F0.bin"

	.align 2
	.global gUnknown_08BE18E4
gUnknown_08BE18E4:
	.incbin "sound/direct_sound_samples/08BE18E4.bin"

	.align 2
	.global gUnknown_08BE2034
gUnknown_08BE2034:
	.incbin "sound/direct_sound_samples/08BE2034.bin"

	.align 2
	.global gUnknown_08BE2770
gUnknown_08BE2770:
	.incbin "sound/direct_sound_samples/08BE2770.bin"

	.align 2
	.global gUnknown_08BE2E54
gUnknown_08BE2E54:
	.incbin "sound/direct_sound_samples/08BE2E54.bin"

	.align 2
	.global gUnknown_08BE3350
gUnknown_08BE3350:
	.incbin "sound/direct_sound_samples/08BE3350.bin"

	.align 2
	.global gUnknown_08BE39D8
gUnknown_08BE39D8:
	.incbin "sound/direct_sound_samples/08BE39D8.bin"

	.align 2
	.global gUnknown_08BE3EBC
gUnknown_08BE3EBC:
	.incbin "sound/direct_sound_samples/08BE3EBC.bin"

	.align 2
	.global gUnknown_08BE4B28
gUnknown_08BE4B28:
	.incbin "sound/direct_sound_samples/08BE4B28.bin"

	.align 2
	.global gUnknown_08BE5160
gUnknown_08BE5160:
	.incbin "sound/direct_sound_samples/08BE5160.bin"

	.align 2
	.global gUnknown_08BE5720
gUnknown_08BE5720:
	.incbin "sound/direct_sound_samples/08BE5720.bin"

	.align 2
	.global gUnknown_08BE5CD4
gUnknown_08BE5CD4:
	.incbin "sound/direct_sound_samples/08BE5CD4.bin"

	.align 2
	.global gUnknown_08BE6294
gUnknown_08BE6294:
	.incbin "sound/direct_sound_samples/08BE6294.bin"

	.align 2
	.global gUnknown_08BE68B0
gUnknown_08BE68B0:
	.incbin "sound/direct_sound_samples/08BE68B0.bin"

	.align 2
	.global gUnknown_08BE6DE4
gUnknown_08BE6DE4:
	.incbin "sound/direct_sound_samples/08BE6DE4.bin"

	.align 2
	.global gUnknown_08BE7464
gUnknown_08BE7464:
	.incbin "sound/direct_sound_samples/08BE7464.bin"

	.align 2
	.global gUnknown_08BE79E8
gUnknown_08BE79E8:
	.incbin "sound/direct_sound_samples/08BE79E8.bin"

	.align 2
	.global gUnknown_08BE7F6C
gUnknown_08BE7F6C:
	.incbin "sound/direct_sound_samples/08BE7F6C.bin"

	.align 2
	.global gUnknown_08BE84CC
gUnknown_08BE84CC:
	.incbin "sound/direct_sound_samples/08BE84CC.bin"

	.align 2
	.global gUnknown_08BE8B70
gUnknown_08BE8B70:
	.incbin "sound/direct_sound_samples/08BE8B70.bin"

	.align 2
	.global gUnknown_08BE8F8C
gUnknown_08BE8F8C:
	.incbin "sound/direct_sound_samples/08BE8F8C.bin"

	.align 2
	.global gUnknown_08BE96B0
gUnknown_08BE96B0:
	.incbin "sound/direct_sound_samples/08BE96B0.bin"

	.align 2
	.global gUnknown_08BE9A64
gUnknown_08BE9A64:
	.incbin "sound/direct_sound_samples/08BE9A64.bin"

	.align 2
	.global gUnknown_08BEA558
gUnknown_08BEA558:
	.incbin "sound/direct_sound_samples/08BEA558.bin"

	.align 2
	.global gUnknown_08BEAC68
gUnknown_08BEAC68:
	.incbin "sound/direct_sound_samples/08BEAC68.bin"

	.align 2
	.global gUnknown_08BEB050
gUnknown_08BEB050:
	.incbin "sound/direct_sound_samples/08BEB050.bin"

	.align 2
	.global gUnknown_08BEB6F8
gUnknown_08BEB6F8:
	.incbin "sound/direct_sound_samples/08BEB6F8.bin"

	.align 2
	.global gUnknown_08BEBB08
gUnknown_08BEBB08:
	.incbin "sound/direct_sound_samples/08BEBB08.bin"

	.align 2
	.global gUnknown_08BEC1F4
gUnknown_08BEC1F4:
	.incbin "sound/direct_sound_samples/08BEC1F4.bin"

	.align 2
	.global gUnknown_08BEC5E0
gUnknown_08BEC5E0:
	.incbin "sound/direct_sound_samples/08BEC5E0.bin"

	.align 2
	.global gUnknown_08BECC28
gUnknown_08BECC28:
	.incbin "sound/direct_sound_samples/08BECC28.bin"

	.align 2
	.global gUnknown_08BED0D0
gUnknown_08BED0D0:
	.incbin "sound/direct_sound_samples/08BED0D0.bin"

	.align 2
	.global gUnknown_08BED77C
gUnknown_08BED77C:
	.incbin "sound/direct_sound_samples/08BED77C.bin"

	.align 2
	.global gUnknown_08BEDBC4
gUnknown_08BEDBC4:
	.incbin "sound/direct_sound_samples/08BEDBC4.bin"

	.align 2
	.global gUnknown_08BEE23C
gUnknown_08BEE23C:
	.incbin "sound/direct_sound_samples/08BEE23C.bin"

	.align 2
	.global gUnknown_08BEE66C
gUnknown_08BEE66C:
	.incbin "sound/direct_sound_samples/08BEE66C.bin"

	.align 2
	.global gUnknown_08BEECEC
gUnknown_08BEECEC:
	.incbin "sound/direct_sound_samples/08BEECEC.bin"

	.align 2
	.global gUnknown_08BEF12C
gUnknown_08BEF12C:
	.incbin "sound/direct_sound_samples/08BEF12C.bin"

	.align 2
	.global gUnknown_08BEF76C
gUnknown_08BEF76C:
	.incbin "sound/direct_sound_samples/08BEF76C.bin"

	.align 2
	.global gUnknown_08BEFBF8
gUnknown_08BEFBF8:
	.incbin "sound/direct_sound_samples/08BEFBF8.bin"

	.align 2
	.global gUnknown_08BF0268
gUnknown_08BF0268:
	.incbin "sound/direct_sound_samples/08BF0268.bin"

	.align 2
	.global gUnknown_08BF0708
gUnknown_08BF0708:
	.incbin "sound/direct_sound_samples/08BF0708.bin"

	.align 2
	.global gUnknown_08BF0DBC
gUnknown_08BF0DBC:
	.incbin "sound/direct_sound_samples/08BF0DBC.bin"

	.align 2
	.global gUnknown_08BF11CC
gUnknown_08BF11CC:
	.incbin "sound/direct_sound_samples/08BF11CC.bin"

	.align 2
	.global gUnknown_08BF1878
gUnknown_08BF1878:
	.incbin "sound/direct_sound_samples/08BF1878.bin"

	.align 2
	.global gUnknown_08BF1CA4
gUnknown_08BF1CA4:
	.incbin "sound/direct_sound_samples/08BF1CA4.bin"

	.align 2
	.global gUnknown_08BF27BC
gUnknown_08BF27BC:
	.incbin "sound/direct_sound_samples/08BF27BC.bin"

	.align 2
	.global gUnknown_08BF2DCC
gUnknown_08BF2DCC:
	.incbin "sound/direct_sound_samples/08BF2DCC.bin"

	.align 2
	.global gUnknown_08BF32F8
gUnknown_08BF32F8:
	.incbin "sound/direct_sound_samples/08BF32F8.bin"

	.align 2
	.global gUnknown_08BF3860
gUnknown_08BF3860:
	.incbin "sound/direct_sound_samples/08BF3860.bin"

	.align 2
	.global gUnknown_08BF3D74
gUnknown_08BF3D74:
	.incbin "sound/direct_sound_samples/08BF3D74.bin"

	.align 2
	.global gUnknown_08BF42D8
gUnknown_08BF42D8:
	.incbin "sound/direct_sound_samples/08BF42D8.bin"

	.align 2
	.global gUnknown_08BF4834
gUnknown_08BF4834:
	.incbin "sound/direct_sound_samples/08BF4834.bin"

	.align 2
	.global gUnknown_08BF4D94
gUnknown_08BF4D94:
	.incbin "sound/direct_sound_samples/08BF4D94.bin"

	.align 2
	.global gUnknown_08BF52B0
gUnknown_08BF52B0:
	.incbin "sound/direct_sound_samples/08BF52B0.bin"

	.align 2
	.global gUnknown_08BF5814
gUnknown_08BF5814:
	.incbin "sound/direct_sound_samples/08BF5814.bin"

	.align 2
	.global gUnknown_08BF5D34
gUnknown_08BF5D34:
	.incbin "sound/direct_sound_samples/08BF5D34.bin"

	.align 2
	.global gUnknown_08BF6250
gUnknown_08BF6250:
	.incbin "sound/direct_sound_samples/08BF6250.bin"

	.align 2
	.global gUnknown_08BF6774
gUnknown_08BF6774:
	.incbin "sound/direct_sound_samples/08BF6774.bin"

	.align 2
	.global gUnknown_08BF6C70
gUnknown_08BF6C70:
	.incbin "sound/direct_sound_samples/08BF6C70.bin"

	.align 2
	.global gUnknown_08BF7244
gUnknown_08BF7244:
	.incbin "sound/direct_sound_samples/08BF7244.bin"

	.align 2
	.global gUnknown_08BF7794
gUnknown_08BF7794:
	.incbin "sound/direct_sound_samples/08BF7794.bin"

	.align 2
	.global gUnknown_08BF7CBC
gUnknown_08BF7CBC:
	.incbin "sound/direct_sound_samples/08BF7CBC.bin"

	.align 2
	.global gUnknown_08BF820C
gUnknown_08BF820C:
	.incbin "sound/direct_sound_samples/08BF820C.bin"

	.align 2
	.global gUnknown_08BF92B4
gUnknown_08BF92B4:
	.incbin "sound/direct_sound_samples/08BF92B4.bin"

	.align 2
	.global gUnknown_08BF9DB0
gUnknown_08BF9DB0:
	.incbin "sound/direct_sound_samples/08BF9DB0.bin"

	.align 2
	.global gUnknown_08BFA5B8
gUnknown_08BFA5B8:
	.incbin "sound/direct_sound_samples/08BFA5B8.bin"

	.align 2
	.global gUnknown_08BFAE34
gUnknown_08BFAE34:
	.incbin "sound/direct_sound_samples/08BFAE34.bin"

	.align 2
	.global gUnknown_08BFBEEC
gUnknown_08BFBEEC:
	.incbin "sound/direct_sound_samples/08BFBEEC.bin"

	.align 2
	.global gUnknown_08BFCF88
gUnknown_08BFCF88:
	.incbin "sound/direct_sound_samples/08BFCF88.bin"

	.align 2
	.global gUnknown_08BFDA70
gUnknown_08BFDA70:
	.incbin "sound/direct_sound_samples/08BFDA70.bin"

	.align 2
	.global gUnknown_08BFDF50
gUnknown_08BFDF50:
	.incbin "sound/direct_sound_samples/08BFDF50.bin"

	.align 2
	.global gUnknown_08BFE458
gUnknown_08BFE458:
	.incbin "sound/direct_sound_samples/08BFE458.bin"

	.align 2
	.global gUnknown_08BFEA24
gUnknown_08BFEA24:
	.incbin "sound/direct_sound_samples/08BFEA24.bin"

	.align 2
	.global gUnknown_08BFEFA8
gUnknown_08BFEFA8:
	.incbin "sound/direct_sound_samples/08BFEFA8.bin"

	.align 2
	.global gUnknown_08BFF56C
gUnknown_08BFF56C:
	.incbin "sound/direct_sound_samples/08BFF56C.bin"

	.align 2
	.global gUnknown_08BFFAC0
gUnknown_08BFFAC0:
	.incbin "sound/direct_sound_samples/08BFFAC0.bin"

	.align 2
	.global gUnknown_08C00064
gUnknown_08C00064:
	.incbin "sound/direct_sound_samples/08C00064.bin"

	.align 2
	.global gUnknown_08C005CC
gUnknown_08C005CC:
	.incbin "sound/direct_sound_samples/08C005CC.bin"

	.align 2
	.global gUnknown_08C00A50
gUnknown_08C00A50:
	.incbin "sound/direct_sound_samples/08C00A50.bin"

	.align 2
	.global gUnknown_08C01068
gUnknown_08C01068:
	.incbin "sound/direct_sound_samples/08C01068.bin"

	.align 2
	.global gUnknown_08C015CC
gUnknown_08C015CC:
	.incbin "sound/direct_sound_samples/08C015CC.bin"

	.align 2
	.global gUnknown_08C01B38
gUnknown_08C01B38:
	.incbin "sound/direct_sound_samples/08C01B38.bin"

	.align 2
	.global gUnknown_08C020E4
gUnknown_08C020E4:
	.incbin "sound/direct_sound_samples/08C020E4.bin"

	.align 2
	.global gUnknown_08C025EC
gUnknown_08C025EC:
	.incbin "sound/direct_sound_samples/08C025EC.bin"

	.align 2
	.global gUnknown_08C02AF4
gUnknown_08C02AF4:
	.incbin "sound/direct_sound_samples/08C02AF4.bin"

	.align 2
	.global gUnknown_08C03000
gUnknown_08C03000:
	.incbin "sound/direct_sound_samples/08C03000.bin"

	.align 2
	.global gUnknown_08C03134
gUnknown_08C03134:
	.incbin "sound/direct_sound_samples/08C03134.bin"

	.align 2
	.global gUnknown_08C03674
gUnknown_08C03674:
	.incbin "sound/direct_sound_samples/08C03674.bin"

	.align 2
	.global gUnknown_08C03B7C
gUnknown_08C03B7C:
	.incbin "sound/direct_sound_samples/08C03B7C.bin"

	.align 2
	.global gUnknown_08C041A4
gUnknown_08C041A4:
	.incbin "sound/direct_sound_samples/08C041A4.bin"

	.align 2
	.global gUnknown_08C046A8
gUnknown_08C046A8:
	.incbin "sound/direct_sound_samples/08C046A8.bin"

	.align 2
	.global gUnknown_08C04C44
gUnknown_08C04C44:
	.incbin "sound/direct_sound_samples/08C04C44.bin"

	.align 2
	.global gUnknown_08C051BC
gUnknown_08C051BC:
	.incbin "sound/direct_sound_samples/08C051BC.bin"

	.align 2
	.global gUnknown_08C05700
gUnknown_08C05700:
	.incbin "sound/direct_sound_samples/08C05700.bin"

	.align 2
	.global gUnknown_08C05CB4
gUnknown_08C05CB4:
	.incbin "sound/direct_sound_samples/08C05CB4.bin"

	.align 2
	.global gUnknown_08C061F8
gUnknown_08C061F8:
	.incbin "sound/direct_sound_samples/08C061F8.bin"

	.align 2
	.global gUnknown_08C0673C
gUnknown_08C0673C:
	.incbin "sound/direct_sound_samples/08C0673C.bin"

	.align 2
	.global gUnknown_08C06C6C
gUnknown_08C06C6C:
	.incbin "sound/direct_sound_samples/08C06C6C.bin"

	.align 2
	.global gUnknown_08C071FC
gUnknown_08C071FC:
	.incbin "sound/direct_sound_samples/08C071FC.bin"

	.align 2
	.global gUnknown_08C07770
gUnknown_08C07770:
	.incbin "sound/direct_sound_samples/08C07770.bin"

	.align 2
	.global gUnknown_08C07C9C
gUnknown_08C07C9C:
	.incbin "sound/direct_sound_samples/08C07C9C.bin"

	.align 2
	.global gUnknown_08C081C0
gUnknown_08C081C0:
	.incbin "sound/direct_sound_samples/08C081C0.bin"

	.align 2
	.global gUnknown_08C086CC
gUnknown_08C086CC:
	.incbin "sound/direct_sound_samples/08C086CC.bin"

	.align 2
	.global gUnknown_08C087B4
gUnknown_08C087B4:
	.incbin "sound/direct_sound_samples/08C087B4.bin"

	.align 2
	.global gUnknown_08C08CD0
gUnknown_08C08CD0:
	.incbin "sound/direct_sound_samples/08C08CD0.bin"

	.align 2
	.global gUnknown_08C09240
gUnknown_08C09240:
	.incbin "sound/direct_sound_samples/08C09240.bin"

	.align 2
	.global gUnknown_08C097F0
gUnknown_08C097F0:
	.incbin "sound/direct_sound_samples/08C097F0.bin"

	.align 2
	.global gUnknown_08C09DC4
gUnknown_08C09DC4:
	.incbin "sound/direct_sound_samples/08C09DC4.bin"

	.align 2
	.global gUnknown_08C0A2B0
gUnknown_08C0A2B0:
	.incbin "sound/direct_sound_samples/08C0A2B0.bin"

	.align 2
	.global gUnknown_08C0A814
gUnknown_08C0A814:
	.incbin "sound/direct_sound_samples/08C0A814.bin"

	.align 2
	.global gUnknown_08C0ADC0
gUnknown_08C0ADC0:
	.incbin "sound/direct_sound_samples/08C0ADC0.bin"

	.align 2
	.global gUnknown_08C0B310
gUnknown_08C0B310:
	.incbin "sound/direct_sound_samples/08C0B310.bin"

	.align 2
	.global gUnknown_08C0B874
gUnknown_08C0B874:
	.incbin "sound/direct_sound_samples/08C0B874.bin"

	.align 2
	.global gUnknown_08C0BE18
gUnknown_08C0BE18:
	.incbin "sound/direct_sound_samples/08C0BE18.bin"

	.align 2
	.global gUnknown_08C0C3E4
gUnknown_08C0C3E4:
	.incbin "sound/direct_sound_samples/08C0C3E4.bin"

	.align 2
	.global gUnknown_08C0C89C
gUnknown_08C0C89C:
	.incbin "sound/direct_sound_samples/08C0C89C.bin"

	.align 2
	.global gUnknown_08C0CE1C
gUnknown_08C0CE1C:
	.incbin "sound/direct_sound_samples/08C0CE1C.bin"

	.align 2
	.global gUnknown_08C0D368
gUnknown_08C0D368:
	.incbin "sound/direct_sound_samples/08C0D368.bin"

	.align 2
	.global gUnknown_08C0D8A0
gUnknown_08C0D8A0:
	.incbin "sound/direct_sound_samples/08C0D8A0.bin"

	.align 2
	.global gUnknown_08C0DE50
gUnknown_08C0DE50:
	.incbin "sound/direct_sound_samples/08C0DE50.bin"

	.align 2
	.global gUnknown_08C0E9F8
gUnknown_08C0E9F8:
	.incbin "sound/direct_sound_samples/08C0E9F8.bin"

	.align 2
	.global gUnknown_08C0F12C
gUnknown_08C0F12C:
	.incbin "sound/direct_sound_samples/08C0F12C.bin"

	.align 2
	.global gUnknown_08C0F654
gUnknown_08C0F654:
	.incbin "sound/direct_sound_samples/08C0F654.bin"

	.align 2
	.global gUnknown_08C0FC88
gUnknown_08C0FC88:
	.incbin "sound/direct_sound_samples/08C0FC88.bin"

	.align 2
	.global gUnknown_08C10254
gUnknown_08C10254:
	.incbin "sound/direct_sound_samples/08C10254.bin"

	.align 2
	.global gUnknown_08C10934
gUnknown_08C10934:
	.incbin "sound/direct_sound_samples/08C10934.bin"

	.align 2
	.global gUnknown_08C10E74
gUnknown_08C10E74:
	.incbin "sound/direct_sound_samples/08C10E74.bin"

	.align 2
	.global gUnknown_08C1153C
gUnknown_08C1153C:
	.incbin "sound/direct_sound_samples/08C1153C.bin"

	.align 2
	.global gUnknown_08C11A60
gUnknown_08C11A60:
	.incbin "sound/direct_sound_samples/08C11A60.bin"

	.align 2
	.global gUnknown_08C12124
gUnknown_08C12124:
	.incbin "sound/direct_sound_samples/08C12124.bin"

	.align 2
	.global gUnknown_08C12674
gUnknown_08C12674:
	.incbin "sound/direct_sound_samples/08C12674.bin"

	.align 2
	.global gUnknown_08C12D24
gUnknown_08C12D24:
	.incbin "sound/direct_sound_samples/08C12D24.bin"

	.align 2
	.global gUnknown_08C13254
gUnknown_08C13254:
	.incbin "sound/direct_sound_samples/08C13254.bin"

	.align 2
	.global gUnknown_08C13928
gUnknown_08C13928:
	.incbin "sound/direct_sound_samples/08C13928.bin"

	.align 2
	.global gUnknown_08C13E3C
gUnknown_08C13E3C:
	.incbin "sound/direct_sound_samples/08C13E3C.bin"

	.align 2
	.global gUnknown_08C14524
gUnknown_08C14524:
	.incbin "sound/direct_sound_samples/08C14524.bin"

	.align 2
	.global gUnknown_08C14AA0
gUnknown_08C14AA0:
	.incbin "sound/direct_sound_samples/08C14AA0.bin"

	.align 2
	.global gUnknown_08C15164
gUnknown_08C15164:
	.incbin "sound/direct_sound_samples/08C15164.bin"

	.align 2
	.global gUnknown_08C15698
gUnknown_08C15698:
	.incbin "sound/direct_sound_samples/08C15698.bin"

	.align 2
	.global gUnknown_08C15C60
gUnknown_08C15C60:
	.incbin "sound/direct_sound_samples/08C15C60.bin"

	.align 2
	.global gUnknown_08C162A4
gUnknown_08C162A4:
	.incbin "sound/direct_sound_samples/08C162A4.bin"

	.align 2
	.global gUnknown_08C16970
gUnknown_08C16970:
	.incbin "sound/direct_sound_samples/08C16970.bin"

	.align 2
	.global gUnknown_08C16EB8
gUnknown_08C16EB8:
	.incbin "sound/direct_sound_samples/08C16EB8.bin"

	.align 2
	.global gUnknown_08C17584
gUnknown_08C17584:
	.incbin "sound/direct_sound_samples/08C17584.bin"

	.align 2
	.global gUnknown_08C17A94
gUnknown_08C17A94:
	.incbin "sound/direct_sound_samples/08C17A94.bin"

	.align 2
	.global gUnknown_08C18188
gUnknown_08C18188:
	.incbin "sound/direct_sound_samples/08C18188.bin"

	.align 2
	.global gUnknown_08C186E8
gUnknown_08C186E8:
	.incbin "sound/direct_sound_samples/08C186E8.bin"

	.align 2
	.global gUnknown_08C18D8C
gUnknown_08C18D8C:
	.incbin "sound/direct_sound_samples/08C18D8C.bin"

	.align 2
	.global gUnknown_08C192A8
gUnknown_08C192A8:
	.incbin "sound/direct_sound_samples/08C192A8.bin"

	.align 2
	.global gUnknown_08C1998C
gUnknown_08C1998C:
	.incbin "sound/direct_sound_samples/08C1998C.bin"

	.align 2
	.global gUnknown_08C19EB8
gUnknown_08C19EB8:
	.incbin "sound/direct_sound_samples/08C19EB8.bin"

	.align 2
	.global gUnknown_08C1A3F4
gUnknown_08C1A3F4:
	.incbin "sound/direct_sound_samples/08C1A3F4.bin"

	.align 2
	.global gUnknown_08C1A900
gUnknown_08C1A900:
	.incbin "sound/direct_sound_samples/08C1A900.bin"

	.align 2
	.global gUnknown_08C1AE50
gUnknown_08C1AE50:
	.incbin "sound/direct_sound_samples/08C1AE50.bin"

	.align 2
	.global gUnknown_08C1B380
gUnknown_08C1B380:
	.incbin "sound/direct_sound_samples/08C1B380.bin"

	.align 2
	.global gUnknown_08C1B928
gUnknown_08C1B928:
	.incbin "sound/direct_sound_samples/08C1B928.bin"

	.align 2
	.global gUnknown_08C1BE0C
gUnknown_08C1BE0C:
	.incbin "sound/direct_sound_samples/08C1BE0C.bin"

	.align 2
	.global gUnknown_08C1C378
gUnknown_08C1C378:
	.incbin "sound/direct_sound_samples/08C1C378.bin"

	.align 2
	.global gUnknown_08C1C884
gUnknown_08C1C884:
	.incbin "sound/direct_sound_samples/08C1C884.bin"

	.align 2
	.global gUnknown_08C1CDB8
gUnknown_08C1CDB8:
	.incbin "sound/direct_sound_samples/08C1CDB8.bin"

	.align 2
	.global gUnknown_08C1D2E0
gUnknown_08C1D2E0:
	.incbin "sound/direct_sound_samples/08C1D2E0.bin"

	.align 2
	.global gUnknown_08C1D7EC
gUnknown_08C1D7EC:
	.incbin "sound/direct_sound_samples/08C1D7EC.bin"

	.align 2
	.global gUnknown_08C1DD2C
gUnknown_08C1DD2C:
	.incbin "sound/direct_sound_samples/08C1DD2C.bin"

	.align 2
	.global gUnknown_08C1E29C
gUnknown_08C1E29C:
	.incbin "sound/direct_sound_samples/08C1E29C.bin"

	.align 2
	.global gUnknown_08C1E760
gUnknown_08C1E760:
	.incbin "sound/direct_sound_samples/08C1E760.bin"

	.align 2
	.global gUnknown_08C1ED70
gUnknown_08C1ED70:
	.incbin "sound/direct_sound_samples/08C1ED70.bin"

	.align 2
	.global gUnknown_08C1F268
gUnknown_08C1F268:
	.incbin "sound/direct_sound_samples/08C1F268.bin"

	.align 2
	.global gUnknown_08C1FD70
gUnknown_08C1FD70:
	.incbin "sound/direct_sound_samples/08C1FD70.bin"

	.align 2
	.global gUnknown_08C202D0
gUnknown_08C202D0:
	.incbin "sound/direct_sound_samples/08C202D0.bin"

	.align 2
	.global gUnknown_08C207D0
gUnknown_08C207D0:
	.incbin "sound/direct_sound_samples/08C207D0.bin"

	.align 2
	.global gUnknown_08C212B8
gUnknown_08C212B8:
	.incbin "sound/direct_sound_samples/08C212B8.bin"

	.align 2
	.global gUnknown_08C218C0
gUnknown_08C218C0:
	.incbin "sound/direct_sound_samples/08C218C0.bin"

	.align 2
	.global gUnknown_08C21D18
gUnknown_08C21D18:
	.incbin "sound/direct_sound_samples/08C21D18.bin"

	.align 2
	.global gUnknown_08C22298
gUnknown_08C22298:
	.incbin "sound/direct_sound_samples/08C22298.bin"

	.align 2
	.global gUnknown_08C22760
gUnknown_08C22760:
	.incbin "sound/direct_sound_samples/08C22760.bin"

	.align 2
	.global gUnknown_08C23218
gUnknown_08C23218:
	.incbin "sound/direct_sound_samples/08C23218.bin"

	.align 2
	.global gUnknown_08C23CA8
gUnknown_08C23CA8:
	.incbin "sound/direct_sound_samples/08C23CA8.bin"

	.align 2
	.global gUnknown_08C242A8
gUnknown_08C242A8:
	.incbin "sound/direct_sound_samples/08C242A8.bin"

	.align 2
	.global gUnknown_08C24730
gUnknown_08C24730:
	.incbin "sound/direct_sound_samples/08C24730.bin"

	.align 2
	.global gUnknown_08C24C80
gUnknown_08C24C80:
	.incbin "sound/direct_sound_samples/08C24C80.bin"

	.align 2
	.global gUnknown_08C2572C
gUnknown_08C2572C:
	.incbin "sound/direct_sound_samples/08C2572C.bin"

	.align 2
	.global gUnknown_08C25D2C
gUnknown_08C25D2C:
	.incbin "sound/direct_sound_samples/08C25D2C.bin"

	.align 2
	.global gUnknown_08C261B4
gUnknown_08C261B4:
	.incbin "sound/direct_sound_samples/08C261B4.bin"

	.align 2
	.global gUnknown_08C26724
gUnknown_08C26724:
	.incbin "sound/direct_sound_samples/08C26724.bin"

	.align 2
	.global gUnknown_08C26CA0
gUnknown_08C26CA0:
	.incbin "sound/direct_sound_samples/08C26CA0.bin"

	.align 2
	.global gUnknown_08C271B8
gUnknown_08C271B8:
	.incbin "sound/direct_sound_samples/08C271B8.bin"

	.align 2
	.global gUnknown_08C27770
gUnknown_08C27770:
	.incbin "sound/direct_sound_samples/08C27770.bin"

	.align 2
	.global gUnknown_08C27C58
gUnknown_08C27C58:
	.incbin "sound/direct_sound_samples/08C27C58.bin"

	.align 2
	.global gUnknown_08C281A8
gUnknown_08C281A8:
	.incbin "sound/direct_sound_samples/08C281A8.bin"

	.align 2
	.global gUnknown_08C28CFC
gUnknown_08C28CFC:
	.incbin "sound/direct_sound_samples/08C28CFC.bin"

	.align 2
	.global gUnknown_08C295D0
gUnknown_08C295D0:
	.incbin "sound/direct_sound_samples/08C295D0.bin"

	.align 2
	.global gUnknown_08C29BF0
gUnknown_08C29BF0:
	.incbin "sound/direct_sound_samples/08C29BF0.bin"

	.align 2
	.global gUnknown_08C2A158
gUnknown_08C2A158:
	.incbin "sound/direct_sound_samples/08C2A158.bin"

	.align 2
	.global gUnknown_08C2AC00
gUnknown_08C2AC00:
	.incbin "sound/direct_sound_samples/08C2AC00.bin"

	.align 2
	.global gUnknown_08C2B22C
gUnknown_08C2B22C:
	.incbin "sound/direct_sound_samples/08C2B22C.bin"

	.align 2
	.global gUnknown_08C2B6EC
gUnknown_08C2B6EC:
	.incbin "sound/direct_sound_samples/08C2B6EC.bin"

	.align 2
	.global gUnknown_08C2BC58
gUnknown_08C2BC58:
	.incbin "sound/direct_sound_samples/08C2BC58.bin"

	.align 2
	.global gUnknown_08C2C0F8
gUnknown_08C2C0F8:
	.incbin "sound/direct_sound_samples/08C2C0F8.bin"

	.align 2
	.global gUnknown_08C2CBC4
gUnknown_08C2CBC4:
	.incbin "sound/direct_sound_samples/08C2CBC4.bin"

	.align 2
	.global gUnknown_08C2D494
gUnknown_08C2D494:
	.incbin "sound/direct_sound_samples/08C2D494.bin"

	.align 2
	.global gUnknown_08C2DEF4
gUnknown_08C2DEF4:
	.incbin "sound/direct_sound_samples/08C2DEF4.bin"

	.align 2
	.global gUnknown_08C2E44C
gUnknown_08C2E44C:
	.incbin "sound/direct_sound_samples/08C2E44C.bin"

	.align 2
	.global gUnknown_08C2E8CC
gUnknown_08C2E8CC:
	.incbin "sound/direct_sound_samples/08C2E8CC.bin"

	.align 2
	.global gUnknown_08C2ED58
gUnknown_08C2ED58:
	.incbin "sound/direct_sound_samples/08C2ED58.bin"

	.align 2
	.global gUnknown_08C2F314
gUnknown_08C2F314:
	.incbin "sound/direct_sound_samples/08C2F314.bin"

	.align 2
	.global gUnknown_08C2F978
gUnknown_08C2F978:
	.incbin "sound/direct_sound_samples/08C2F978.bin"

	.align 2
	.global gUnknown_08C30F08
gUnknown_08C30F08:
	.incbin "sound/direct_sound_samples/08C30F08.bin"

	.align 2
	.global gUnknown_08C34DFC
gUnknown_08C34DFC:
	.incbin "sound/direct_sound_samples/08C34DFC.bin"

	.align 2
	.global gUnknown_08C35C68
gUnknown_08C35C68:
	.incbin "sound/direct_sound_samples/08C35C68.bin"

	.align 2
	.global gUnknown_08C37240
gUnknown_08C37240:
	.incbin "sound/direct_sound_samples/08C37240.bin"

	.align 2
	.global gUnknown_08C382F4
gUnknown_08C382F4:
	.incbin "sound/direct_sound_samples/08C382F4.bin"

	.align 2
	.global gUnknown_08C3A298
gUnknown_08C3A298:
	.incbin "sound/direct_sound_samples/08C3A298.bin"

	.align 2
	.global gUnknown_08C3BC34
gUnknown_08C3BC34:
	.incbin "sound/direct_sound_samples/08C3BC34.bin"

	.align 2
	.global gUnknown_08C3D53C
gUnknown_08C3D53C:
	.incbin "sound/direct_sound_samples/08C3D53C.bin"

	.align 2
	.global gUnknown_08C3F3E0
gUnknown_08C3F3E0:
	.incbin "sound/direct_sound_samples/08C3F3E0.bin"

	.align 2
	.global gUnknown_08C40314
gUnknown_08C40314:
	.incbin "sound/direct_sound_samples/08C40314.bin"

	.align 2
	.global gUnknown_08C41284
gUnknown_08C41284:
	.incbin "sound/direct_sound_samples/08C41284.bin"

	.align 2
	.global gUnknown_08C41820
gUnknown_08C41820:
	.incbin "sound/direct_sound_samples/08C41820.bin"

	.align 2
	.global gUnknown_08C42488
gUnknown_08C42488:
	.incbin "sound/direct_sound_samples/08C42488.bin"

	.align 2
	.global gUnknown_08C46A48
gUnknown_08C46A48:
	.incbin "sound/direct_sound_samples/08C46A48.bin"

	.align 2
	.global gUnknown_08C4991C
gUnknown_08C4991C:
	.incbin "sound/direct_sound_samples/08C4991C.bin"

	.align 2
	.global gUnknown_08C4C92C
gUnknown_08C4C92C:
	.incbin "sound/direct_sound_samples/08C4C92C.bin"

	.align 2
	.global gUnknown_08C4E120
gUnknown_08C4E120:
	.incbin "sound/direct_sound_samples/08C4E120.bin"

	.align 2
	.global gUnknown_08C50304
gUnknown_08C50304:
	.incbin "sound/direct_sound_samples/08C50304.bin"

	.align 2
	.global gUnknown_08C517B0
gUnknown_08C517B0:
	.incbin "sound/direct_sound_samples/08C517B0.bin"

	.align 2
	.global gUnknown_08C526AC
gUnknown_08C526AC:
	.incbin "sound/direct_sound_samples/08C526AC.bin"

	.align 2
	.global gUnknown_08C52BAC
gUnknown_08C52BAC:
	.incbin "sound/direct_sound_samples/08C52BAC.bin"

	.align 2
	.global gUnknown_08C530E4
gUnknown_08C530E4:
	.incbin "sound/direct_sound_samples/08C530E4.bin"
