	.align 2
    .global DirectSoundWaveData_1
DirectSoundWaveData_1:
	.incbin "sound/direct_sound_samples/unknown_001.bin"

	.align 2
DirectSoundWaveData_2:
	.incbin "sound/direct_sound_samples/unknown_002.bin"

	.align 2
DirectSoundWaveData_3:
	.incbin "sound/direct_sound_samples/unknown_003.bin"

	.align 2
DirectSoundWaveData_4:
	.incbin "sound/direct_sound_samples/unknown_004.bin"

	.align 2
DirectSoundWaveData_5:
	.incbin "sound/direct_sound_samples/unknown_005.bin"

	.align 2
DirectSoundWaveData_6:
	.incbin "sound/direct_sound_samples/unknown_006.bin"

	.align 2
DirectSoundWaveData_7:
	.incbin "sound/direct_sound_samples/unknown_007.bin"

	.align 2
DirectSoundWaveData_8:
	.incbin "sound/direct_sound_samples/unknown_008.bin"

	.align 2
DirectSoundWaveData_9:
	.incbin "sound/direct_sound_samples/unknown_009.bin"

	.align 2
DirectSoundWaveData_10:
	.incbin "sound/direct_sound_samples/unknown_010.bin"

	.align 2
DirectSoundWaveData_11:
	.incbin "sound/direct_sound_samples/unknown_011.bin"

	.align 2
DirectSoundWaveData_12:
	.incbin "sound/direct_sound_samples/unknown_012.bin"

	.align 2
DirectSoundWaveData_13:
	.incbin "sound/direct_sound_samples/unknown_013.bin"

	.align 2
DirectSoundWaveData_14:
	.incbin "sound/direct_sound_samples/unknown_014.bin"

	.align 2
DirectSoundWaveData_15:
	.incbin "sound/direct_sound_samples/unknown_015.bin"

	.align 2
DirectSoundWaveData_16:
	.incbin "sound/direct_sound_samples/unknown_016.bin"

	.align 2
DirectSoundWaveData_17:
	.incbin "sound/direct_sound_samples/unknown_017.bin"

	.align 2
DirectSoundWaveData_18:
	.incbin "sound/direct_sound_samples/unknown_018.bin"

	.align 2
DirectSoundWaveData_19:
	.incbin "sound/direct_sound_samples/unknown_019.bin"

	.align 2
DirectSoundWaveData_20:
	.incbin "sound/direct_sound_samples/unknown_020.bin"

	.align 2
DirectSoundWaveData_21:
	.incbin "sound/direct_sound_samples/unknown_021.bin"

	.align 2
DirectSoundWaveData_22:
	.incbin "sound/direct_sound_samples/unknown_022.bin"

	.align 2
DirectSoundWaveData_23:
	.incbin "sound/direct_sound_samples/unknown_023.bin"

	.align 2
DirectSoundWaveData_24:
	.incbin "sound/direct_sound_samples/unknown_024.bin"

	.align 2
DirectSoundWaveData_25:
	.incbin "sound/direct_sound_samples/unknown_025.bin"

	.align 2
DirectSoundWaveData_26:
	.incbin "sound/direct_sound_samples/unknown_026.bin"

	.align 2
DirectSoundWaveData_27:
	.incbin "sound/direct_sound_samples/unknown_027.bin"

	.align 2
DirectSoundWaveData_28:
	.incbin "sound/direct_sound_samples/unknown_028.bin"

	.align 2
DirectSoundWaveData_29:
	.incbin "sound/direct_sound_samples/unknown_029.bin"

	.align 2
DirectSoundWaveData_30:
	.incbin "sound/direct_sound_samples/unknown_030.bin"

	.align 2
DirectSoundWaveData_31:
	.incbin "sound/direct_sound_samples/unknown_031.bin"

	.align 2
DirectSoundWaveData_32:
	.incbin "sound/direct_sound_samples/unknown_032.bin"

	.align 2
DirectSoundWaveData_33:
	.incbin "sound/direct_sound_samples/unknown_033.bin"

	.align 2
DirectSoundWaveData_34:
	.incbin "sound/direct_sound_samples/unknown_034.bin"

	.align 2
DirectSoundWaveData_35:
	.incbin "sound/direct_sound_samples/unknown_035.bin"

	.align 2
DirectSoundWaveData_36:
	.incbin "sound/direct_sound_samples/unknown_036.bin"

	.align 2
DirectSoundWaveData_37:
	.incbin "sound/direct_sound_samples/unknown_037.bin"

	.align 2
DirectSoundWaveData_38:
	.incbin "sound/direct_sound_samples/unknown_038.bin"

	.align 2
DirectSoundWaveData_39:
	.incbin "sound/direct_sound_samples/unknown_039.bin"

	.align 2
DirectSoundWaveData_40:
	.incbin "sound/direct_sound_samples/unknown_040.bin"

	.align 2
DirectSoundWaveData_41:
	.incbin "sound/direct_sound_samples/unknown_041.bin"

	.align 2
DirectSoundWaveData_42:
	.incbin "sound/direct_sound_samples/unknown_042.bin"

	.align 2
DirectSoundWaveData_43:
	.incbin "sound/direct_sound_samples/unknown_043.bin"

	.align 2
DirectSoundWaveData_44:
	.incbin "sound/direct_sound_samples/unknown_044.bin"

	.align 2
DirectSoundWaveData_45:
	.incbin "sound/direct_sound_samples/unknown_045.bin"

	.align 2
DirectSoundWaveData_46:
	.incbin "sound/direct_sound_samples/unknown_046.bin"

	.align 2
DirectSoundWaveData_47:
	.incbin "sound/direct_sound_samples/unknown_047.bin"

	.align 2
DirectSoundWaveData_48:
	.incbin "sound/direct_sound_samples/unknown_048.bin"

	.align 2
DirectSoundWaveData_49:
	.incbin "sound/direct_sound_samples/unknown_049.bin"

	.align 2
DirectSoundWaveData_50:
	.incbin "sound/direct_sound_samples/unknown_050.bin"

	.align 2
DirectSoundWaveData_51:
	.incbin "sound/direct_sound_samples/unknown_051.bin"

	.align 2
DirectSoundWaveData_52:
	.incbin "sound/direct_sound_samples/unknown_052.bin"

	.align 2
DirectSoundWaveData_53:
	.incbin "sound/direct_sound_samples/unknown_053.bin"

	.align 2
DirectSoundWaveData_54:
	.incbin "sound/direct_sound_samples/unknown_054.bin"

	.align 2
DirectSoundWaveData_55:
	.incbin "sound/direct_sound_samples/unknown_055.bin"

	.align 2
DirectSoundWaveData_56:
	.incbin "sound/direct_sound_samples/unknown_056.bin"

	.align 2
DirectSoundWaveData_57:
	.incbin "sound/direct_sound_samples/unknown_057.bin"

	.align 2
DirectSoundWaveData_58:
	.incbin "sound/direct_sound_samples/unknown_058.bin"

	.align 2
DirectSoundWaveData_59:
	.incbin "sound/direct_sound_samples/unknown_059.bin"

	.align 2
DirectSoundWaveData_60:
	.incbin "sound/direct_sound_samples/unknown_060.bin"

	.align 2
DirectSoundWaveData_61:
	.incbin "sound/direct_sound_samples/unknown_061.bin"

	.align 2
DirectSoundWaveData_voice__announcer__sonic_advance_2:
	.incbin "sound/direct_sound_samples/voice__announcer__sonic_advance_2.bin"

	.align 2
DirectSoundWaveData_voice__announcer__sonic:
	.incbin "sound/direct_sound_samples/voice__announcer__sonic.bin"

	.align 2
DirectSoundWaveData_62:
	.incbin "sound/direct_sound_samples/unknown_062.bin"

	.align 2
DirectSoundWaveData_63:
	.incbin "sound/direct_sound_samples/unknown_063.bin"

	.align 2
DirectSoundWaveData_64:
	.incbin "sound/direct_sound_samples/unknown_064.bin"

	.align 2
DirectSoundWaveData_voice__announcer__cream:
	.incbin "sound/direct_sound_samples/voice__announcer__cream.bin"

	.align 2
DirectSoundWaveData_65:
	.incbin "sound/direct_sound_samples/unknown_065.bin"

	.align 2
DirectSoundWaveData_66:
	.incbin "sound/direct_sound_samples/unknown_066.bin"

	.align 2
DirectSoundWaveData_67:
	.incbin "sound/direct_sound_samples/unknown_067.bin"

	.align 2
DirectSoundWaveData_68:
	.incbin "sound/direct_sound_samples/unknown_068.bin"

	.align 2
DirectSoundWaveData_69:
	.incbin "sound/direct_sound_samples/unknown_069.bin"

	.align 2
DirectSoundWaveData_70:
	.incbin "sound/direct_sound_samples/unknown_070.bin"

	.align 2
DirectSoundWaveData_71:
	.incbin "sound/direct_sound_samples/unknown_071.bin"

	.align 2
DirectSoundWaveData_72:
	.incbin "sound/direct_sound_samples/unknown_072.bin"

	.align 2
DirectSoundWaveData_73:
	.incbin "sound/direct_sound_samples/unknown_073.bin"

	.align 2
DirectSoundWaveData_74:
	.incbin "sound/direct_sound_samples/unknown_074.bin"

	.align 2
DirectSoundWaveData_75:
	.incbin "sound/direct_sound_samples/unknown_075.bin"

	.align 2
DirectSoundWaveData_76:
	.incbin "sound/direct_sound_samples/unknown_076.bin"

	.align 2
DirectSoundWaveData_77:
	.incbin "sound/direct_sound_samples/unknown_077.bin"

	.align 2
DirectSoundWaveData_78:
	.incbin "sound/direct_sound_samples/unknown_078.bin"

	.align 2
DirectSoundWaveData_79:
	.incbin "sound/direct_sound_samples/unknown_079.bin"

	.align 2
DirectSoundWaveData_80:
	.incbin "sound/direct_sound_samples/unknown_080.bin"

	.align 2
DirectSoundWaveData_81:
	.incbin "sound/direct_sound_samples/unknown_081.bin"

	.align 2
DirectSoundWaveData_82:
	.incbin "sound/direct_sound_samples/unknown_082.bin"

	.align 2
DirectSoundWaveData_83:
	.incbin "sound/direct_sound_samples/unknown_083.bin"

	.align 2
DirectSoundWaveData_84:
	.incbin "sound/direct_sound_samples/unknown_084.bin"

	.align 2
DirectSoundWaveData_85:
	.incbin "sound/direct_sound_samples/unknown_085.bin"

	.align 2
DirectSoundWaveData_86:
	.incbin "sound/direct_sound_samples/unknown_086.bin"

	.align 2
DirectSoundWaveData_87:
	.incbin "sound/direct_sound_samples/unknown_087.bin"

	.align 2
DirectSoundWaveData_88:
	.incbin "sound/direct_sound_samples/unknown_088.bin"

	.align 2
DirectSoundWaveData_89:
	.incbin "sound/direct_sound_samples/unknown_089.bin"

	.align 2
DirectSoundWaveData_90:
	.incbin "sound/direct_sound_samples/unknown_090.bin"

	.align 2
DirectSoundWaveData_91:
	.incbin "sound/direct_sound_samples/unknown_091.bin"

	.align 2
DirectSoundWaveData_92:
	.incbin "sound/direct_sound_samples/unknown_092.bin"

	.align 2
DirectSoundWaveData_93:
	.incbin "sound/direct_sound_samples/unknown_093.bin"

	.align 2
DirectSoundWaveData_94:
	.incbin "sound/direct_sound_samples/unknown_094.bin"

	.align 2
DirectSoundWaveData_95:
	.incbin "sound/direct_sound_samples/unknown_095.bin"

	.align 2
DirectSoundWaveData_96:
	.incbin "sound/direct_sound_samples/unknown_096.bin"

	.align 2
DirectSoundWaveData_97:
	.incbin "sound/direct_sound_samples/unknown_097.bin"

	.align 2
DirectSoundWaveData_98:
	.incbin "sound/direct_sound_samples/unknown_098.bin"

	.align 2
DirectSoundWaveData_99:
	.incbin "sound/direct_sound_samples/unknown_099.bin"

	.align 2
DirectSoundWaveData_100:
	.incbin "sound/direct_sound_samples/unknown_100.bin"

	.align 2
DirectSoundWaveData_101:
	.incbin "sound/direct_sound_samples/unknown_101.bin"

	.align 2
DirectSoundWaveData_102:
	.incbin "sound/direct_sound_samples/unknown_102.bin"

	.align 2
DirectSoundWaveData_103:
	.incbin "sound/direct_sound_samples/unknown_103.bin"

	.align 2
DirectSoundWaveData_104:
	.incbin "sound/direct_sound_samples/unknown_104.bin"

	.align 2
DirectSoundWaveData_105:
	.incbin "sound/direct_sound_samples/unknown_105.bin"

	.align 2
DirectSoundWaveData_106:
	.incbin "sound/direct_sound_samples/unknown_106.bin"

	.align 2
DirectSoundWaveData_107:
	.incbin "sound/direct_sound_samples/unknown_107.bin"

	.align 2
DirectSoundWaveData_108:
	.incbin "sound/direct_sound_samples/unknown_108.bin"

	.align 2
DirectSoundWaveData_109:
	.incbin "sound/direct_sound_samples/unknown_109.bin"

	.align 2
DirectSoundWaveData_110:
	.incbin "sound/direct_sound_samples/unknown_110.bin"

	.align 2
DirectSoundWaveData_111:
	.incbin "sound/direct_sound_samples/unknown_111.bin"

	.align 2
DirectSoundWaveData_112:
	.incbin "sound/direct_sound_samples/unknown_112.bin"

	.align 2
DirectSoundWaveData_113:
	.incbin "sound/direct_sound_samples/unknown_113.bin"

	.align 2
DirectSoundWaveData_114:
	.incbin "sound/direct_sound_samples/unknown_114.bin"

	.align 2
DirectSoundWaveData_115:
	.incbin "sound/direct_sound_samples/unknown_115.bin"

	.align 2
DirectSoundWaveData_116:
	.incbin "sound/direct_sound_samples/unknown_116.bin"

	.align 2
DirectSoundWaveData_117:
	.incbin "sound/direct_sound_samples/unknown_117.bin"

	.align 2
DirectSoundWaveData_118:
	.incbin "sound/direct_sound_samples/unknown_118.bin"

	.align 2
DirectSoundWaveData_119:
	.incbin "sound/direct_sound_samples/unknown_119.bin"

	.align 2
DirectSoundWaveData_120:
	.incbin "sound/direct_sound_samples/unknown_120.bin"

	.align 2
DirectSoundWaveData_121:
	.incbin "sound/direct_sound_samples/unknown_121.bin"

	.align 2
DirectSoundWaveData_122:
	.incbin "sound/direct_sound_samples/unknown_122.bin"

	.align 2
DirectSoundWaveData_123:
	.incbin "sound/direct_sound_samples/unknown_123.bin"

	.align 2
DirectSoundWaveData_124:
	.incbin "sound/direct_sound_samples/unknown_124.bin"

	.align 2
DirectSoundWaveData_125:
	.incbin "sound/direct_sound_samples/unknown_125.bin"

	.align 2
DirectSoundWaveData_126:
	.incbin "sound/direct_sound_samples/unknown_126.bin"

	.align 2
DirectSoundWaveData_127:
	.incbin "sound/direct_sound_samples/unknown_127.bin"

	.align 2
DirectSoundWaveData_128:
	.incbin "sound/direct_sound_samples/unknown_128.bin"

	.align 2
DirectSoundWaveData_129:
	.incbin "sound/direct_sound_samples/unknown_129.bin"

	.align 2
DirectSoundWaveData_130:
	.incbin "sound/direct_sound_samples/unknown_130.bin"

	.align 2
DirectSoundWaveData_131:
	.incbin "sound/direct_sound_samples/unknown_131.bin"

	.align 2
DirectSoundWaveData_132:
	.incbin "sound/direct_sound_samples/unknown_132.bin"

	.align 2
DirectSoundWaveData_133:
	.incbin "sound/direct_sound_samples/unknown_133.bin"

	.align 2
DirectSoundWaveData_134:
	.incbin "sound/direct_sound_samples/unknown_134.bin"

	.align 2
DirectSoundWaveData_135:
	.incbin "sound/direct_sound_samples/unknown_135.bin"

	.align 2
DirectSoundWaveData_136:
	.incbin "sound/direct_sound_samples/unknown_136.bin"

	.align 2
DirectSoundWaveData_137:
	.incbin "sound/direct_sound_samples/unknown_137.bin"

	.align 2
DirectSoundWaveData_138:
	.incbin "sound/direct_sound_samples/unknown_138.bin"

	.align 2
DirectSoundWaveData_139:
	.incbin "sound/direct_sound_samples/unknown_139.bin"

	.align 2
DirectSoundWaveData_140:
	.incbin "sound/direct_sound_samples/unknown_140.bin"

	.align 2
DirectSoundWaveData_141:
	.incbin "sound/direct_sound_samples/unknown_141.bin"

	.align 2
DirectSoundWaveData_142:
	.incbin "sound/direct_sound_samples/unknown_142.bin"

	.align 2
DirectSoundWaveData_143:
	.incbin "sound/direct_sound_samples/unknown_143.bin"

	.align 2
DirectSoundWaveData_144:
	.incbin "sound/direct_sound_samples/unknown_144.bin"

	.align 2
DirectSoundWaveData_145:
	.incbin "sound/direct_sound_samples/unknown_145.bin"

	.align 2
DirectSoundWaveData_146:
	.incbin "sound/direct_sound_samples/unknown_146.bin"

	.align 2
DirectSoundWaveData_147:
	.incbin "sound/direct_sound_samples/unknown_147.bin"

	.align 2
DirectSoundWaveData_148:
	.incbin "sound/direct_sound_samples/unknown_148.bin"

	.align 2
DirectSoundWaveData_149:
	.incbin "sound/direct_sound_samples/unknown_149.bin"

	.align 2
DirectSoundWaveData_150:
	.incbin "sound/direct_sound_samples/unknown_150.bin"

	.align 2
DirectSoundWaveData_151:
	.incbin "sound/direct_sound_samples/unknown_151.bin"

	.align 2
DirectSoundWaveData_152:
	.incbin "sound/direct_sound_samples/unknown_152.bin"

	.align 2
DirectSoundWaveData_153:
	.incbin "sound/direct_sound_samples/unknown_153.bin"

	.align 2
DirectSoundWaveData_154:
	.incbin "sound/direct_sound_samples/unknown_154.bin"

	.align 2
DirectSoundWaveData_155:
	.incbin "sound/direct_sound_samples/unknown_155.bin"

	.align 2
DirectSoundWaveData_156:
	.incbin "sound/direct_sound_samples/unknown_156.bin"

	.align 2
DirectSoundWaveData_157:
	.incbin "sound/direct_sound_samples/unknown_157.bin"

	.align 2
DirectSoundWaveData_158:
	.incbin "sound/direct_sound_samples/unknown_158.bin"

	.align 2
DirectSoundWaveData_159:
	.incbin "sound/direct_sound_samples/unknown_159.bin"

	.align 2
DirectSoundWaveData_160:
	.incbin "sound/direct_sound_samples/unknown_160.bin"

	.align 2
DirectSoundWaveData_161:
	.incbin "sound/direct_sound_samples/unknown_161.bin"

	.align 2
DirectSoundWaveData_162:
	.incbin "sound/direct_sound_samples/unknown_162.bin"

	.align 2
DirectSoundWaveData_163:
	.incbin "sound/direct_sound_samples/unknown_163.bin"

	.align 2
DirectSoundWaveData_164:
	.incbin "sound/direct_sound_samples/unknown_164.bin"

	.align 2
DirectSoundWaveData_165:
	.incbin "sound/direct_sound_samples/unknown_165.bin"

	.align 2
DirectSoundWaveData_166:
	.incbin "sound/direct_sound_samples/unknown_166.bin"

	.align 2
DirectSoundWaveData_167:
	.incbin "sound/direct_sound_samples/unknown_167.bin"

	.align 2
DirectSoundWaveData_168:
	.incbin "sound/direct_sound_samples/unknown_168.bin"

	.align 2
DirectSoundWaveData_169:
	.incbin "sound/direct_sound_samples/unknown_169.bin"

	.align 2
DirectSoundWaveData_170:
	.incbin "sound/direct_sound_samples/unknown_170.bin"

	.align 2
DirectSoundWaveData_171:
	.incbin "sound/direct_sound_samples/unknown_171.bin"

	.align 2
DirectSoundWaveData_172:
	.incbin "sound/direct_sound_samples/unknown_172.bin"

	.align 2
DirectSoundWaveData_173:
	.incbin "sound/direct_sound_samples/unknown_173.bin"

	.align 2
DirectSoundWaveData_174:
	.incbin "sound/direct_sound_samples/unknown_174.bin"

	.align 2
DirectSoundWaveData_175:
	.incbin "sound/direct_sound_samples/unknown_175.bin"

	.align 2
DirectSoundWaveData_176:
	.incbin "sound/direct_sound_samples/unknown_176.bin"

	.align 2
DirectSoundWaveData_177:
	.incbin "sound/direct_sound_samples/unknown_177.bin"

	.align 2
DirectSoundWaveData_178:
	.incbin "sound/direct_sound_samples/unknown_178.bin"

	.align 2
DirectSoundWaveData_179:
	.incbin "sound/direct_sound_samples/unknown_179.bin"

	.align 2
DirectSoundWaveData_180:
	.incbin "sound/direct_sound_samples/unknown_180.bin"

	.align 2
DirectSoundWaveData_181:
	.incbin "sound/direct_sound_samples/unknown_181.bin"

	.align 2
DirectSoundWaveData_182:
	.incbin "sound/direct_sound_samples/unknown_182.bin"

	.align 2
DirectSoundWaveData_183:
	.incbin "sound/direct_sound_samples/unknown_183.bin"

	.align 2
DirectSoundWaveData_184:
	.incbin "sound/direct_sound_samples/unknown_184.bin"

	.align 2
DirectSoundWaveData_185:
	.incbin "sound/direct_sound_samples/unknown_185.bin"

	.align 2
DirectSoundWaveData_186:
	.incbin "sound/direct_sound_samples/unknown_186.bin"

	.align 2
DirectSoundWaveData_187:
	.incbin "sound/direct_sound_samples/unknown_187.bin"

	.align 2
DirectSoundWaveData_188:
	.incbin "sound/direct_sound_samples/unknown_188.bin"

	.align 2
DirectSoundWaveData_189:
	.incbin "sound/direct_sound_samples/unknown_189.bin"

	.align 2
DirectSoundWaveData_190:
	.incbin "sound/direct_sound_samples/unknown_190.bin"

	.align 2
DirectSoundWaveData_191:
	.incbin "sound/direct_sound_samples/unknown_191.bin"

	.align 2
DirectSoundWaveData_192:
	.incbin "sound/direct_sound_samples/unknown_192.bin"

	.align 2
DirectSoundWaveData_193:
	.incbin "sound/direct_sound_samples/unknown_193.bin"

	.align 2
DirectSoundWaveData_194:
	.incbin "sound/direct_sound_samples/unknown_194.bin"

	.align 2
DirectSoundWaveData_195:
	.incbin "sound/direct_sound_samples/unknown_195.bin"

	.align 2
DirectSoundWaveData_196:
	.incbin "sound/direct_sound_samples/unknown_196.bin"

	.align 2
DirectSoundWaveData_197:
	.incbin "sound/direct_sound_samples/unknown_197.bin"

	.align 2
DirectSoundWaveData_198:
	.incbin "sound/direct_sound_samples/unknown_198.bin"

	.align 2
DirectSoundWaveData_199:
	.incbin "sound/direct_sound_samples/unknown_199.bin"

	.align 2
DirectSoundWaveData_200:
	.incbin "sound/direct_sound_samples/unknown_200.bin"

	.align 2
DirectSoundWaveData_201:
	.incbin "sound/direct_sound_samples/unknown_201.bin"

	.align 2
DirectSoundWaveData_202:
	.incbin "sound/direct_sound_samples/unknown_202.bin"

	.align 2
DirectSoundWaveData_203:
	.incbin "sound/direct_sound_samples/unknown_203.bin"

	.align 2
DirectSoundWaveData_204:
	.incbin "sound/direct_sound_samples/unknown_204.bin"

	.align 2
DirectSoundWaveData_205:
	.incbin "sound/direct_sound_samples/unknown_205.bin"

	.align 2
DirectSoundWaveData_206:
	.incbin "sound/direct_sound_samples/unknown_206.bin"

	.align 2
DirectSoundWaveData_207:
	.incbin "sound/direct_sound_samples/unknown_207.bin"

	.align 2
DirectSoundWaveData_208:
	.incbin "sound/direct_sound_samples/unknown_208.bin"

	.align 2
DirectSoundWaveData_209:
	.incbin "sound/direct_sound_samples/unknown_209.bin"

	.align 2
DirectSoundWaveData_210:
	.incbin "sound/direct_sound_samples/unknown_210.bin"

	.align 2
DirectSoundWaveData_211:
	.incbin "sound/direct_sound_samples/unknown_211.bin"

	.align 2
DirectSoundWaveData_212:
	.incbin "sound/direct_sound_samples/unknown_212.bin"

	.align 2
DirectSoundWaveData_213:
	.incbin "sound/direct_sound_samples/unknown_213.bin"

	.align 2
DirectSoundWaveData_214:
	.incbin "sound/direct_sound_samples/unknown_214.bin"

	.align 2
DirectSoundWaveData_215:
	.incbin "sound/direct_sound_samples/unknown_215.bin"

	.align 2
DirectSoundWaveData_216:
	.incbin "sound/direct_sound_samples/unknown_216.bin"

	.align 2
DirectSoundWaveData_217:
	.incbin "sound/direct_sound_samples/unknown_217.bin"

	.align 2
DirectSoundWaveData_218:
	.incbin "sound/direct_sound_samples/unknown_218.bin"

	.align 2
DirectSoundWaveData_219:
	.incbin "sound/direct_sound_samples/unknown_219.bin"

	.align 2
DirectSoundWaveData_220:
	.incbin "sound/direct_sound_samples/unknown_220.bin"

	.align 2
DirectSoundWaveData_221:
	.incbin "sound/direct_sound_samples/unknown_221.bin"

	.align 2
DirectSoundWaveData_222:
	.incbin "sound/direct_sound_samples/unknown_222.bin"

	.align 2
DirectSoundWaveData_223:
	.incbin "sound/direct_sound_samples/unknown_223.bin"

	.align 2
DirectSoundWaveData_224:
	.incbin "sound/direct_sound_samples/unknown_224.bin"

	.align 2
DirectSoundWaveData_225:
	.incbin "sound/direct_sound_samples/unknown_225.bin"

	.align 2
DirectSoundWaveData_226:
	.incbin "sound/direct_sound_samples/unknown_226.bin"

	.align 2
DirectSoundWaveData_227:
	.incbin "sound/direct_sound_samples/unknown_227.bin"

	.align 2
DirectSoundWaveData_228:
	.incbin "sound/direct_sound_samples/unknown_228.bin"

	.align 2
DirectSoundWaveData_229:
	.incbin "sound/direct_sound_samples/unknown_229.bin"

	.align 2
DirectSoundWaveData_230:
	.incbin "sound/direct_sound_samples/unknown_230.bin"

	.align 2
DirectSoundWaveData_231:
	.incbin "sound/direct_sound_samples/unknown_231.bin"

	.align 2
DirectSoundWaveData_232:
	.incbin "sound/direct_sound_samples/unknown_232.bin"

	.align 2
DirectSoundWaveData_233:
	.incbin "sound/direct_sound_samples/unknown_233.bin"

	.align 2
DirectSoundWaveData_234:
	.incbin "sound/direct_sound_samples/unknown_234.bin"

	.align 2
DirectSoundWaveData_235:
	.incbin "sound/direct_sound_samples/unknown_235.bin"

	.align 2
DirectSoundWaveData_236:
	.incbin "sound/direct_sound_samples/unknown_236.bin"

	.align 2
DirectSoundWaveData_237:
	.incbin "sound/direct_sound_samples/unknown_237.bin"

	.align 2
DirectSoundWaveData_238:
	.incbin "sound/direct_sound_samples/unknown_238.bin"

	.align 2
DirectSoundWaveData_239:
	.incbin "sound/direct_sound_samples/unknown_239.bin"

	.align 2
DirectSoundWaveData_240:
	.incbin "sound/direct_sound_samples/unknown_240.bin"

	.align 2
DirectSoundWaveData_241:
	.incbin "sound/direct_sound_samples/unknown_241.bin"

	.align 2
DirectSoundWaveData_242:
	.incbin "sound/direct_sound_samples/unknown_242.bin"

	.align 2
DirectSoundWaveData_243:
	.incbin "sound/direct_sound_samples/unknown_243.bin"

	.align 2
DirectSoundWaveData_244:
	.incbin "sound/direct_sound_samples/unknown_244.bin"

	.align 2
DirectSoundWaveData_245:
	.incbin "sound/direct_sound_samples/unknown_245.bin"

	.align 2
DirectSoundWaveData_246:
	.incbin "sound/direct_sound_samples/unknown_246.bin"

	.align 2
DirectSoundWaveData_247:
	.incbin "sound/direct_sound_samples/unknown_247.bin"

	.align 2
DirectSoundWaveData_248:
	.incbin "sound/direct_sound_samples/unknown_248.bin"

	.align 2
DirectSoundWaveData_249:
	.incbin "sound/direct_sound_samples/unknown_249.bin"

	.align 2
DirectSoundWaveData_250:
	.incbin "sound/direct_sound_samples/unknown_250.bin"

	.align 2
DirectSoundWaveData_251:
	.incbin "sound/direct_sound_samples/unknown_251.bin"

	.align 2
DirectSoundWaveData_252:
	.incbin "sound/direct_sound_samples/unknown_252.bin"

	.align 2
DirectSoundWaveData_253:
	.incbin "sound/direct_sound_samples/unknown_253.bin"

	.align 2
DirectSoundWaveData_254:
	.incbin "sound/direct_sound_samples/unknown_254.bin"

	.align 2
DirectSoundWaveData_255:
	.incbin "sound/direct_sound_samples/unknown_255.bin"

	.align 2
DirectSoundWaveData_256:
	.incbin "sound/direct_sound_samples/unknown_256.bin"

	.align 2
DirectSoundWaveData_257:
	.incbin "sound/direct_sound_samples/unknown_257.bin"

	.align 2
DirectSoundWaveData_258:
	.incbin "sound/direct_sound_samples/unknown_258.bin"

	.align 2
DirectSoundWaveData_259:
	.incbin "sound/direct_sound_samples/unknown_259.bin"

	.align 2
DirectSoundWaveData_260:
	.incbin "sound/direct_sound_samples/unknown_260.bin"

	.align 2
DirectSoundWaveData_261:
	.incbin "sound/direct_sound_samples/unknown_261.bin"

	.align 2
DirectSoundWaveData_262:
	.incbin "sound/direct_sound_samples/unknown_262.bin"

	.align 2
DirectSoundWaveData_263:
	.incbin "sound/direct_sound_samples/unknown_263.bin"

	.align 2
DirectSoundWaveData_264:
	.incbin "sound/direct_sound_samples/unknown_264.bin"

	.align 2
DirectSoundWaveData_265:
	.incbin "sound/direct_sound_samples/unknown_265.bin"

	.align 2
DirectSoundWaveData_266:
	.incbin "sound/direct_sound_samples/unknown_266.bin"

	.align 2
DirectSoundWaveData_267:
	.incbin "sound/direct_sound_samples/unknown_267.bin"

	.align 2
DirectSoundWaveData_268:
	.incbin "sound/direct_sound_samples/unknown_268.bin"

	.align 2
DirectSoundWaveData_269:
	.incbin "sound/direct_sound_samples/unknown_269.bin"

	.align 2
DirectSoundWaveData_270:
	.incbin "sound/direct_sound_samples/unknown_270.bin"

	.align 2
DirectSoundWaveData_271:
	.incbin "sound/direct_sound_samples/unknown_271.bin"

	.align 2
DirectSoundWaveData_272:
	.incbin "sound/direct_sound_samples/unknown_272.bin"

	.align 2
DirectSoundWaveData_273:
	.incbin "sound/direct_sound_samples/unknown_273.bin"

	.align 2
DirectSoundWaveData_274:
	.incbin "sound/direct_sound_samples/unknown_274.bin"

	.align 2
DirectSoundWaveData_275:
	.incbin "sound/direct_sound_samples/unknown_275.bin"

	.align 2
DirectSoundWaveData_276:
	.incbin "sound/direct_sound_samples/unknown_276.bin"

	.align 2
DirectSoundWaveData_277:
	.incbin "sound/direct_sound_samples/unknown_277.bin"

	.align 2
DirectSoundWaveData_278:
	.incbin "sound/direct_sound_samples/unknown_278.bin"

	.align 2
DirectSoundWaveData_279:
	.incbin "sound/direct_sound_samples/unknown_279.bin"

	.align 2
DirectSoundWaveData_280:
	.incbin "sound/direct_sound_samples/unknown_280.bin"

	.align 2
DirectSoundWaveData_281:
	.incbin "sound/direct_sound_samples/unknown_281.bin"

	.align 2
DirectSoundWaveData_282:
	.incbin "sound/direct_sound_samples/unknown_282.bin"

	.align 2
DirectSoundWaveData_283:
	.incbin "sound/direct_sound_samples/unknown_283.bin"

	.align 2
DirectSoundWaveData_284:
	.incbin "sound/direct_sound_samples/unknown_284.bin"

	.align 2
DirectSoundWaveData_285:
	.incbin "sound/direct_sound_samples/unknown_285.bin"

	.align 2
DirectSoundWaveData_286:
	.incbin "sound/direct_sound_samples/unknown_286.bin"

	.align 2
DirectSoundWaveData_287:
	.incbin "sound/direct_sound_samples/unknown_287.bin"

	.align 2
DirectSoundWaveData_288:
	.incbin "sound/direct_sound_samples/unknown_288.bin"

	.align 2
DirectSoundWaveData_289:
	.incbin "sound/direct_sound_samples/unknown_289.bin"

	.align 2
DirectSoundWaveData_290:
	.incbin "sound/direct_sound_samples/unknown_290.bin"

	.align 2
DirectSoundWaveData_291:
	.incbin "sound/direct_sound_samples/unknown_291.bin"

	.align 2
DirectSoundWaveData_292:
	.incbin "sound/direct_sound_samples/unknown_292.bin"

	.align 2
DirectSoundWaveData_293:
	.incbin "sound/direct_sound_samples/unknown_293.bin"

	.align 2
DirectSoundWaveData_294:
	.incbin "sound/direct_sound_samples/unknown_294.bin"

	.align 2
DirectSoundWaveData_295:
	.incbin "sound/direct_sound_samples/unknown_295.bin"

	.align 2
DirectSoundWaveData_296:
	.incbin "sound/direct_sound_samples/unknown_296.bin"

	.align 2
DirectSoundWaveData_297:
	.incbin "sound/direct_sound_samples/unknown_297.bin"

	.align 2
DirectSoundWaveData_298:
	.incbin "sound/direct_sound_samples/unknown_298.bin"

	.align 2
DirectSoundWaveData_299:
	.incbin "sound/direct_sound_samples/unknown_299.bin"

	.align 2
DirectSoundWaveData_300:
	.incbin "sound/direct_sound_samples/unknown_300.bin"

	.align 2
DirectSoundWaveData_301:
	.incbin "sound/direct_sound_samples/unknown_301.bin"

	.align 2
DirectSoundWaveData_302:
	.incbin "sound/direct_sound_samples/unknown_302.bin"

	.align 2
DirectSoundWaveData_303:
	.incbin "sound/direct_sound_samples/unknown_303.bin"

	.align 2
DirectSoundWaveData_304:
	.incbin "sound/direct_sound_samples/unknown_304.bin"

	.align 2
DirectSoundWaveData_305:
	.incbin "sound/direct_sound_samples/unknown_305.bin"

	.align 2
DirectSoundWaveData_306:
	.incbin "sound/direct_sound_samples/unknown_306.bin"

	.align 2
DirectSoundWaveData_307:
	.incbin "sound/direct_sound_samples/unknown_307.bin"

	.align 2
DirectSoundWaveData_308:
	.incbin "sound/direct_sound_samples/unknown_308.bin"

	.align 2
DirectSoundWaveData_309:
	.incbin "sound/direct_sound_samples/unknown_309.bin"

	.align 2
DirectSoundWaveData_310:
	.incbin "sound/direct_sound_samples/unknown_310.bin"

	.align 2
DirectSoundWaveData_311:
	.incbin "sound/direct_sound_samples/unknown_311.bin"

	.align 2
DirectSoundWaveData_312:
	.incbin "sound/direct_sound_samples/unknown_312.bin"

	.align 2
DirectSoundWaveData_313:
	.incbin "sound/direct_sound_samples/unknown_313.bin"

	.align 2
DirectSoundWaveData_314:
	.incbin "sound/direct_sound_samples/unknown_314.bin"

	.align 2
DirectSoundWaveData_315:
	.incbin "sound/direct_sound_samples/unknown_315.bin"

	.align 2
DirectSoundWaveData_316:
	.incbin "sound/direct_sound_samples/unknown_316.bin"

	.align 2
DirectSoundWaveData_317:
	.incbin "sound/direct_sound_samples/unknown_317.bin"

	.align 2
DirectSoundWaveData_318:
	.incbin "sound/direct_sound_samples/unknown_318.bin"

	.align 2
DirectSoundWaveData_319:
	.incbin "sound/direct_sound_samples/unknown_319.bin"

	.align 2
DirectSoundWaveData_320:
	.incbin "sound/direct_sound_samples/unknown_320.bin"

	.align 2
DirectSoundWaveData_321:
	.incbin "sound/direct_sound_samples/unknown_321.bin"

	.align 2
DirectSoundWaveData_322:
	.incbin "sound/direct_sound_samples/unknown_322.bin"

	.align 2
DirectSoundWaveData_323:
	.incbin "sound/direct_sound_samples/unknown_323.bin"

	.align 2
DirectSoundWaveData_324:
	.incbin "sound/direct_sound_samples/unknown_324.bin"

	.align 2
DirectSoundWaveData_325:
	.incbin "sound/direct_sound_samples/unknown_325.bin"

	.align 2
DirectSoundWaveData_326:
	.incbin "sound/direct_sound_samples/unknown_326.bin"

	.align 2
DirectSoundWaveData_327:
	.incbin "sound/direct_sound_samples/unknown_327.bin"

	.align 2
DirectSoundWaveData_328:
	.incbin "sound/direct_sound_samples/unknown_328.bin"

	.align 2
DirectSoundWaveData_329:
	.incbin "sound/direct_sound_samples/unknown_329.bin"

	.align 2
DirectSoundWaveData_330:
	.incbin "sound/direct_sound_samples/unknown_330.bin"

	.align 2
DirectSoundWaveData_331:
	.incbin "sound/direct_sound_samples/unknown_331.bin"

	.align 2
DirectSoundWaveData_332:
	.incbin "sound/direct_sound_samples/unknown_332.bin"

	.align 2
DirectSoundWaveData_333:
	.incbin "sound/direct_sound_samples/unknown_333.bin"

	.align 2
DirectSoundWaveData_334:
	.incbin "sound/direct_sound_samples/unknown_334.bin"

	.align 2
DirectSoundWaveData_335:
	.incbin "sound/direct_sound_samples/unknown_335.bin"

	.align 2
DirectSoundWaveData_336:
	.incbin "sound/direct_sound_samples/unknown_336.bin"

	.align 2
DirectSoundWaveData_337:
	.incbin "sound/direct_sound_samples/unknown_337.bin"

	.align 2
DirectSoundWaveData_338:
	.incbin "sound/direct_sound_samples/unknown_338.bin"

	.align 2
DirectSoundWaveData_339:
	.incbin "sound/direct_sound_samples/unknown_339.bin"

	.align 2
DirectSoundWaveData_340:
	.incbin "sound/direct_sound_samples/unknown_340.bin"

	.align 2
DirectSoundWaveData_341:
	.incbin "sound/direct_sound_samples/unknown_341.bin"

	.align 2
DirectSoundWaveData_342:
	.incbin "sound/direct_sound_samples/unknown_342.bin"

	.align 2
DirectSoundWaveData_343:
	.incbin "sound/direct_sound_samples/unknown_343.bin"

	.align 2
DirectSoundWaveData_344:
	.incbin "sound/direct_sound_samples/unknown_344.bin"

	.align 2
DirectSoundWaveData_345:
	.incbin "sound/direct_sound_samples/unknown_345.bin"

	.align 2
DirectSoundWaveData_346:
	.incbin "sound/direct_sound_samples/unknown_346.bin"

	.align 2
DirectSoundWaveData_347:
	.incbin "sound/direct_sound_samples/unknown_347.bin"

	.align 2
DirectSoundWaveData_348:
	.incbin "sound/direct_sound_samples/unknown_348.bin"

	.align 2
DirectSoundWaveData_349:
	.incbin "sound/direct_sound_samples/unknown_349.bin"

	.align 2
DirectSoundWaveData_350:
	.incbin "sound/direct_sound_samples/unknown_350.bin"

	.align 2
DirectSoundWaveData_351:
	.incbin "sound/direct_sound_samples/unknown_351.bin"

	.align 2
DirectSoundWaveData_352:
	.incbin "sound/direct_sound_samples/unknown_352.bin"

	.align 2
DirectSoundWaveData_353:
	.incbin "sound/direct_sound_samples/unknown_353.bin"

	.align 2
DirectSoundWaveData_354:
	.incbin "sound/direct_sound_samples/unknown_354.bin"

	.align 2
DirectSoundWaveData_355:
	.incbin "sound/direct_sound_samples/unknown_355.bin"

	.align 2
DirectSoundWaveData_356:
	.incbin "sound/direct_sound_samples/unknown_356.bin"

	.align 2
DirectSoundWaveData_357:
	.incbin "sound/direct_sound_samples/unknown_357.bin"

	.align 2
DirectSoundWaveData_358:
	.incbin "sound/direct_sound_samples/unknown_358.bin"

	.align 2
DirectSoundWaveData_359:
	.incbin "sound/direct_sound_samples/unknown_359.bin"

	.align 2
DirectSoundWaveData_360:
	.incbin "sound/direct_sound_samples/unknown_360.bin"

	.align 2
DirectSoundWaveData_361:
	.incbin "sound/direct_sound_samples/unknown_361.bin"

	.align 2
DirectSoundWaveData_362:
	.incbin "sound/direct_sound_samples/unknown_362.bin"

	.align 2
DirectSoundWaveData_363:
	.incbin "sound/direct_sound_samples/unknown_363.bin"

	.align 2
DirectSoundWaveData_364:
	.incbin "sound/direct_sound_samples/unknown_364.bin"

	.align 2
DirectSoundWaveData_365:
	.incbin "sound/direct_sound_samples/unknown_365.bin"

	.align 2
DirectSoundWaveData_366:
	.incbin "sound/direct_sound_samples/unknown_366.bin"

	.align 2
DirectSoundWaveData_367:
	.incbin "sound/direct_sound_samples/unknown_367.bin"

	.align 2
DirectSoundWaveData_368:
	.incbin "sound/direct_sound_samples/unknown_368.bin"

	.align 2
DirectSoundWaveData_369:
	.incbin "sound/direct_sound_samples/unknown_369.bin"

	.align 2
DirectSoundWaveData_370:
	.incbin "sound/direct_sound_samples/unknown_370.bin"

	.align 2
DirectSoundWaveData_371:
	.incbin "sound/direct_sound_samples/unknown_371.bin"

	.align 2
DirectSoundWaveData_372:
	.incbin "sound/direct_sound_samples/unknown_372.bin"

	.align 2
DirectSoundWaveData_373:
	.incbin "sound/direct_sound_samples/unknown_373.bin"

	.align 2
DirectSoundWaveData_374:
	.incbin "sound/direct_sound_samples/unknown_374.bin"

	.align 2
DirectSoundWaveData_375:
	.incbin "sound/direct_sound_samples/unknown_375.bin"

	.align 2
DirectSoundWaveData_376:
	.incbin "sound/direct_sound_samples/unknown_376.bin"

	.align 2
DirectSoundWaveData_377:
	.incbin "sound/direct_sound_samples/unknown_377.bin"

	.align 2
DirectSoundWaveData_378:
	.incbin "sound/direct_sound_samples/unknown_378.bin"

	.align 2
DirectSoundWaveData_379:
	.incbin "sound/direct_sound_samples/unknown_379.bin"
