	mAlignWord
    .global DirectSoundWaveData_1
DirectSoundWaveData_1:
	.incbin "sound/direct_sound_samples/roland_jv2080__organ_3_charselect_1.bin"

	mAlignWord
    .global DirectSoundWaveData_2
DirectSoundWaveData_2:
	.incbin "sound/direct_sound_samples/roland_jv2080__organ_3_charselect_2.bin"

	mAlignWord
    .global DirectSoundWaveData_3
DirectSoundWaveData_3:
	.incbin "sound/direct_sound_samples/roland_jv2080__pr_d__019_organ_3__1.bin"

	mAlignWord
    .global DirectSoundWaveData_4
DirectSoundWaveData_4:
	.incbin "sound/direct_sound_samples/roland_jv2080__pr_d__019_organ_3__2.bin"

	mAlignWord
    .global DirectSoundWaveData_5
DirectSoundWaveData_5:
	.incbin "sound/direct_sound_samples/korg_trinity__stereo_brass_1.bin"

	mAlignWord
    .global DirectSoundWaveData_6
DirectSoundWaveData_6:
	.incbin "sound/direct_sound_samples/korg_trinity__synth_brass2_1.bin"

	mAlignWord
    .global DirectSoundWaveData_7
DirectSoundWaveData_7:
	.incbin "sound/direct_sound_samples/roland_jv2080__pr_d__019_organ_3__3.bin"

	mAlignWord
    .global DirectSoundWaveData_8
DirectSoundWaveData_8:
	.incbin "sound/direct_sound_samples/unknown_8ade918.bin"

	mAlignWord
    .global DirectSoundWaveData_9
DirectSoundWaveData_9:
	.incbin "sound/direct_sound_samples/korg_trinity__stereo_brass_2.bin"

	mAlignWord
    .global DirectSoundWaveData_10
DirectSoundWaveData_10:
	.incbin "sound/direct_sound_samples/korg_trinity__synth_brass2_2.bin"

	mAlignWord
    .global DirectSoundWaveData_11
DirectSoundWaveData_11:
	.incbin "sound/direct_sound_samples/roland_jv2080__pr_d__019_organ_3__4.bin"

	mAlignWord
    .global DirectSoundWaveData_12
DirectSoundWaveData_12:
	 .incbin "sound/direct_sound_samples/roland_sr_jv80_02__bassoon_1.bin"

	mAlignWord
    .global DirectSoundWaveData_13
DirectSoundWaveData_13:
	.incbin "sound/direct_sound_samples/unknown_8ae9bb4.bin"

	mAlignWord
    .global DirectSoundWaveData_14
DirectSoundWaveData_14:
	.incbin "sound/direct_sound_samples/unknown_8aea788.bin"

	mAlignWord
    .global DirectSoundWaveData_15
DirectSoundWaveData_15:
	.incbin "sound/direct_sound_samples/korg_trinity__30303_mega_bass_1.bin"

	mAlignWord
    .global DirectSoundWaveData_16
DirectSoundWaveData_16:
	.incbin "sound/direct_sound_samples/korg_trinity__30303_mega_bass_2.bin"

	mAlignWord
    .global DirectSoundWaveData_17
DirectSoundWaveData_17:
	.incbin "sound/direct_sound_samples/roland_jv2080__pr_d__019_organ_3__5.bin"

	mAlignWord
DirectSoundWaveData_18:
	.incbin "sound/direct_sound_samples/roland_jv2080__alto_sax.bin"

	mAlignWord
DirectSoundWaveData_19:
	.incbin "sound/direct_sound_samples/roland_jv2080__timpani.bin"

	mAlignWord
DirectSoundWaveData_20:
	.incbin "sound/direct_sound_samples/roland_sr_jv80_02__186_harp_1.bin"

	mAlignWord
DirectSoundWaveData_21:
	.incbin "sound/direct_sound_samples/roland_jv2080__pr_d__019_organ_3__6.bin"

	mAlignWord
DirectSoundWaveData_22:
	.incbin "sound/direct_sound_samples/roland_jv2080__piano_2.bin"

	mAlignWord
DirectSoundWaveData_23:
	.incbin "sound/direct_sound_samples/korg_trinity__music_box_sw1.bin"

	mAlignWord
DirectSoundWaveData_24:
	.incbin "sound/direct_sound_samples/roland_sr_jv80_02__french_horn_sc_x4.bin"

	mAlignWord
DirectSoundWaveData_25:
	.incbin "sound/direct_sound_samples/roland_jv2080__orchestra_hit.bin"

	mAlignWord
DirectSoundWaveData_26:
	.incbin "sound/direct_sound_samples/roland_sr_jv80_02__vi_sect_mono.bin"

	mAlignWord
DirectSoundWaveData_27:
	.incbin "sound/direct_sound_samples/korg_01_w__16_piano.bin"

	mAlignWord
DirectSoundWaveData_28:
	.incbin "sound/direct_sound_samples/unknown_8B04840.bin"

	mAlignWord
DirectSoundWaveData_29:
	.incbin "sound/direct_sound_samples/korg_01_w__vs_bells_1_1.bin"

	mAlignWord
DirectSoundWaveData_30:
	.incbin "sound/direct_sound_samples/unknown_8B0C95C.bin"

	mAlignWord
DirectSoundWaveData_31:
	.incbin "sound/direct_sound_samples/unknown_8B0F724_sa1_final_boss_choir.bin"

	mAlignWord
DirectSoundWaveData_32: @ 0x8B109B8
	.incbin "sound/direct_sound_samples/sfx/sa1_intro_wind.bin"

	mAlignWord
DirectSoundWaveData_33: @ 0x8B18DD0
	.incbin "sound/direct_sound_samples/sfx/sa1_intro_emerald.bin"

	mAlignWord
DirectSoundWaveData_34: @ 0x8B1E9F0
	.incbin "sound/direct_sound_samples/korg_trinity__dads_jazz_guitar.bin"

	mAlignWord
DirectSoundWaveData_35: @ 0x8B20204
	.incbin "sound/direct_sound_samples/unknown_8B20204.bin"

	mAlignWord
DirectSoundWaveData_36: @ 0x8B21DC8
	.incbin "sound/direct_sound_samples/korg_trinity__standard_kit_1.bin"

	mAlignWord
DirectSoundWaveData_37: @ 0x8B22678
	.incbin "sound/direct_sound_samples/korg_trinity__standard_kit_2.bin"

	mAlignWord
DirectSoundWaveData_38: @ 0x8B232F0
	.incbin "sound/direct_sound_samples/korg_trinity__standard_kit_3.bin"

	mAlignWord
DirectSoundWaveData_39: @ 0x8B24488
	.incbin "sound/direct_sound_samples/korg_trinity__standard_kit_4.bin"

	mAlignWord
DirectSoundWaveData_40:
	.incbin "sound/direct_sound_samples/korg_trinity__standard_kit_5.bin"

	mAlignWord
DirectSoundWaveData_41:
	.incbin "sound/direct_sound_samples/unknown_8B257FC__maybe_roland_jv2080_jazz_drum_set1.bin"

	mAlignWord
DirectSoundWaveData_42:
	.incbin "sound/direct_sound_samples/roland_jv2080__jazz_drum_set1__1.bin"

	mAlignWord
DirectSoundWaveData_43:
	.incbin "sound/direct_sound_samples/roland_jv2080__jazz_drum_set1__2.bin"

	mAlignWord
DirectSoundWaveData_44:
	.incbin "sound/direct_sound_samples/korg_trinity__mega_mix_kit_1.bin"

	mAlignWord
DirectSoundWaveData_45:
	.incbin "sound/direct_sound_samples/korg_trinity__mega_mix_kit_2.bin"

	mAlignWord
DirectSoundWaveData_46:
	.incbin "sound/direct_sound_samples/unknown_8B2EEB8.bin"

	mAlignWord
DirectSoundWaveData_47:
	.incbin "sound/direct_sound_samples/roland_jv2080_power_drum_set.bin"

	mAlignWord
DirectSoundWaveData_48:
	.incbin "sound/direct_sound_samples/sfx/spin_attack.bin"

	mAlignWord
DirectSoundWaveData_49:
	.incbin "sound/direct_sound_samples/sfx/score_count_complete.bin"

	mAlignWord
DirectSoundWaveData_50:
	.incbin "sound/direct_sound_samples/sfx/ring.bin"

	mAlignWord
DirectSoundWaveData_51:
	.incbin "sound/direct_sound_samples/sfx/rings_lost.bin"

	mAlignWord
DirectSoundWaveData_52:
	.incbin "sound/direct_sound_samples/sfx/sa1_goal.bin"

	mAlignWord
DirectSoundWaveData_53:
	.incbin "sound/direct_sound_samples/voices/cheese/wheewopog.bin"

	mAlignWord
DirectSoundWaveData_54:
	.incbin "sound/direct_sound_samples/voices/cheese/baa.bin"

	mAlignWord
DirectSoundWaveData_55:
	.incbin "sound/direct_sound_samples/voices/cheese/ooooh.bin"

	mAlignWord
DirectSoundWaveData_56:
	.incbin "sound/direct_sound_samples/voices/cheese/attack.bin"

	mAlignWord
DirectSoundWaveData_57:
	.incbin "sound/direct_sound_samples/voices/cheese/hmm_huh.bin"

	mAlignWord
DirectSoundWaveData_58:
	.incbin "sound/direct_sound_samples/voices/cheese/huh.bin"

	mAlignWord
DirectSoundWaveData_59:
	.incbin "sound/direct_sound_samples/voices/cheese/hihihi.bin"

	mAlignWord
DirectSoundWaveData_60:
	.incbin "sound/direct_sound_samples/korg_trinity__jazz_brush_kits.bin"

	mAlignWord
DirectSoundWaveData_61:
	.incbin "sound/direct_sound_samples/sfx/8B51EBC.bin"

	mAlignWord
DirectSoundWaveData_voice__announcer__sonic_advance_2:
	.incbin "sound/direct_sound_samples/voices/announcer/sonic_advance_2.bin"

	mAlignWord
DirectSoundWaveData_voice__announcer__sonic:
	.incbin "sound/direct_sound_samples/voices/announcer/sonic.bin"

	mAlignWord
DirectSoundWaveData_62:
	.incbin "sound/direct_sound_samples/voices/announcer/tails.bin"

	mAlignWord
DirectSoundWaveData_63:
	.incbin "sound/direct_sound_samples/voices/announcer/knuckles.bin"

	mAlignWord
DirectSoundWaveData_64:
	.incbin "sound/direct_sound_samples/voices/announcer/amy.bin"

	mAlignWord
DirectSoundWaveData_voice__announcer__cream:
	.incbin "sound/direct_sound_samples/voices/announcer/cream.bin"

	mAlignWord
DirectSoundWaveData_65:
	.incbin "sound/direct_sound_samples/voices/announcer/countdown_3.bin"

	mAlignWord
DirectSoundWaveData_66:
	.incbin "sound/direct_sound_samples/voices/announcer/countdown_2.bin"

	mAlignWord
DirectSoundWaveData_67:
	.incbin "sound/direct_sound_samples/voices/announcer/countdown_1.bin"

	mAlignWord
DirectSoundWaveData_68:
	.incbin "sound/direct_sound_samples/voices/announcer/countdown_go.bin"

	mAlignWord
DirectSoundWaveData_69:
	.incbin "sound/direct_sound_samples/voices/announcer/congratulations.bin"

	mAlignWord
DirectSoundWaveData_70: @ 0x8B6BA40
	.incbin "sound/direct_sound_samples/sfx/music_plant_spring.bin"

    @ Music Plant - 
	mAlignWord
DirectSoundWaveData_71: @ 0x8B6FA94
	.incbin "sound/direct_sound_samples/sfx/8B6FA94.bin"

	mAlignWord
DirectSoundWaveData_72: @ 0x8B70C1C
	.incbin "sound/direct_sound_samples/sfx/music_plant_note.bin"

	mAlignWord
DirectSoundWaveData_73: @ 0x8B72E4C
	.incbin "sound/direct_sound_samples/sfx/music_plant_note_block.bin"

	mAlignWord
DirectSoundWaveData_74:
	.incbin "sound/direct_sound_samples/unknown_8B756E4.bin"

	mAlignWord
DirectSoundWaveData_75:
	.incbin "sound/direct_sound_samples/unknown_8B78148.bin"

	mAlignWord
DirectSoundWaveData_76: @ 0x8B7A79C
	.incbin "sound/direct_sound_samples/sfx/music_plant_guitar.bin"

	mAlignWord
DirectSoundWaveData_77: @ 0x8B7E428
	.incbin "sound/direct_sound_samples/sfx/german_flute.bin"

	mAlignWord
DirectSoundWaveData_78:
	.incbin "sound/direct_sound_samples/unknown_8B80688.bin"

	mAlignWord
DirectSoundWaveData_79:
	.incbin "sound/direct_sound_samples/unknown_8B84450.bin"

	mAlignWord
DirectSoundWaveData_80:
	.incbin "sound/direct_sound_samples/korg_01_w__vs_bells_1_2.bin"

	mAlignWord
DirectSoundWaveData_81:
	.incbin "sound/direct_sound_samples/unknown_8B91D70.bin"

	mAlignWord
DirectSoundWaveData_82:
	.incbin "sound/direct_sound_samples/unknown_8B940F0.bin"

	mAlignWord
DirectSoundWaveData_83:
	.incbin "sound/direct_sound_samples/korg_01_w__expecting.bin"

	mAlignWord
DirectSoundWaveData_84:
	.incbin "sound/direct_sound_samples/unknown_8B9A988.bin"

	mAlignWord
DirectSoundWaveData_85:
	.incbin "sound/direct_sound_samples/unknown_8B9AD68.bin"

	mAlignWord
DirectSoundWaveData_86:
	.incbin "sound/direct_sound_samples/unknown_8B9B1C0.bin"

	mAlignWord
DirectSoundWaveData_87:
	.incbin "sound/direct_sound_samples/unknown_8B9BB3C.bin"

	mAlignWord
DirectSoundWaveData_88:
	.incbin "sound/direct_sound_samples/unknown_8B9BF9C.bin"

	mAlignWord
DirectSoundWaveData_89:
	.incbin "sound/direct_sound_samples/unknown_8B9C408.bin"

	mAlignWord
DirectSoundWaveData_90:
	.incbin "sound/direct_sound_samples/unknown_8B9C894.bin"

	mAlignWord
DirectSoundWaveData_91:
	.incbin "sound/direct_sound_samples/unknown_8B9D1C0.bin"

	mAlignWord
DirectSoundWaveData_92:
	.incbin "sound/direct_sound_samples/unknown_8B9D718.bin"

	mAlignWord
DirectSoundWaveData_93:
	.incbin "sound/direct_sound_samples/korg_01_w__spectrum.bin"

	mAlignWord
DirectSoundWaveData_94:
	.incbin "sound/direct_sound_samples/roland_jv2080__harmonica.bin"

	mAlignWord
DirectSoundWaveData_95:
	.incbin "sound/direct_sound_samples/roland_jv2080__pr_d__019_organ_3__7.bin"

	mAlignWord
DirectSoundWaveData_96:
	.incbin "sound/direct_sound_samples/roland_jv2080__pr_d__019_organ_3__8.bin"

	mAlignWord
DirectSoundWaveData_97:
	.incbin "sound/direct_sound_samples/unknown_8BA62E0.bin"

	mAlignWord
DirectSoundWaveData_98:
	.incbin "sound/direct_sound_samples/unknown_8BA6AA0.bin"

	mAlignWord
DirectSoundWaveData_99: @ 0x8BAA2DC
	.incbin "sound/direct_sound_samples/e_mu_morpheus__factory_rom_presets__bank_0__PAD__45_mechanik.bin"

	mAlignWord
DirectSoundWaveData_100:
	.incbin "sound/direct_sound_samples/unknown_8BAFDC0.bin"

	mAlignWord
DirectSoundWaveData_101:
	.incbin "sound/direct_sound_samples/unknown_8BB152C.bin"

	mAlignWord
DirectSoundWaveData_102:
	.incbin "sound/direct_sound_samples/unknown_8BB2CAC.bin"

	mAlignWord
DirectSoundWaveData_103:
	.incbin "sound/direct_sound_samples/unknown_8BB4C60.bin"

	mAlignWord
DirectSoundWaveData_104:
	.incbin "sound/direct_sound_samples/unknown_8BB672C.bin"

	mAlignWord
DirectSoundWaveData_105:
	.incbin "sound/direct_sound_samples/unknown_BB8F2C.bin"

	mAlignWord
DirectSoundWaveData_106: @ 0x8BBA360
	.incbin "sound/direct_sound_samples/roland_jv2080__pr_d__019_organ_3__9.bin"

	mAlignWord
DirectSoundWaveData_107:
	.incbin "sound/direct_sound_samples/roland_jv2080__pan_flute.bin"

	mAlignWord
DirectSoundWaveData_108:
	.incbin "sound/direct_sound_samples/korg_trinity__studio_strato.bin"

	mAlignWord
DirectSoundWaveData_109:
	.incbin "sound/direct_sound_samples/unknown_8bbd0e4.bin"

	mAlignWord
DirectSoundWaveData_110:
	.incbin "sound/direct_sound_samples/roland_sr_jv80_02__oboe_1.bin"

	mAlignWord
DirectSoundWaveData_111:
	.incbin "sound/direct_sound_samples/unknown_8BC311C.bin"

	mAlignWord
DirectSoundWaveData_112:
	.incbin "sound/direct_sound_samples/unknown_8BC3DD4__roland_sr_jv80_02__someTubular.bin"

	mAlignWord
DirectSoundWaveData_113: @ 0x8BC6304
	.incbin "sound/direct_sound_samples/steinberg_virtual_guitarist__electric_guitar__ultra_ii__punish.bin"

	mAlignWord
DirectSoundWaveData_114:
	.incbin "sound/direct_sound_samples/unknown_8BC7C58.bin"

	mAlignWord
DirectSoundWaveData_115:
	.incbin "sound/direct_sound_samples/unknown_8BCCBD4.bin"

	mAlignWord
DirectSoundWaveData_116:
	.incbin "sound/direct_sound_samples/unknown_8BCD1DC.bin"

	mAlignWord
DirectSoundWaveData_117:
	.incbin "sound/direct_sound_samples/unknown_8BCD85C.bin"

	mAlignWord
DirectSoundWaveData_118:
	.incbin "sound/direct_sound_samples/steinberg_virtual_guitarist__acoustic_guitar__teenie__ringing_1.bin"

	mAlignWord
DirectSoundWaveData_119:
	.incbin "sound/direct_sound_samples/steinberg_virtual_guitarist__acoustic_guitar__teenie__ringing_2.bin"

	mAlignWord
DirectSoundWaveData_120:
	.incbin "sound/direct_sound_samples/steinberg_virtual_guitarist__acoustic_guitar__teenie__ringing_3.bin"

	mAlignWord
DirectSoundWaveData_121:
	.incbin "sound/direct_sound_samples/steinberg_virtual_guitarist__acoustic_guitar__teenie__ringing_4.bin"

	mAlignWord
DirectSoundWaveData_122:
	.incbin "sound/direct_sound_samples/steinberg_virtual_guitarist__acoustic_guitar__teenie__ringing_5.bin"

	mAlignWord
DirectSoundWaveData_123:
	.incbin "sound/direct_sound_samples/unknown_8BD26FC.bin"

	mAlignWord
DirectSoundWaveData_124:
	.incbin "sound/direct_sound_samples/unknown_8BD2F00.bin"

	mAlignWord
DirectSoundWaveData_125:
	.incbin "sound/direct_sound_samples/unknown_8BD3704.bin"

	mAlignWord
DirectSoundWaveData_126:
	.incbin "sound/direct_sound_samples/unknown_8BD4838.bin"

	mAlignWord
DirectSoundWaveData_127:
	.incbin "sound/direct_sound_samples/unknown_8BD554C.bin"

	mAlignWord
DirectSoundWaveData_128:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_4_loop_1.bin"

	mAlignWord
DirectSoundWaveData_129:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_4_loop_2.bin"

	mAlignWord
DirectSoundWaveData_130:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_4_loop_3.bin"

	mAlignWord
DirectSoundWaveData_131:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_4_loop_4.bin"

	mAlignWord
DirectSoundWaveData_132:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_4_loop_5.bin"

	mAlignWord
DirectSoundWaveData_133:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_4_loop_6.bin"

	mAlignWord
DirectSoundWaveData_134:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_4_loop_7.bin"

	mAlignWord
DirectSoundWaveData_135:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_4_loop_8.bin"

	mAlignWord
DirectSoundWaveData_136:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_4_loop_9.bin"

	mAlignWord
DirectSoundWaveData_137:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_4_loop_10.bin"

	mAlignWord
DirectSoundWaveData_138:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_0.bin"

	mAlignWord
DirectSoundWaveData_139:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_1.bin"

	mAlignWord
DirectSoundWaveData_140:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_2.bin"

	mAlignWord
DirectSoundWaveData_141:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_3.bin"

	mAlignWord
DirectSoundWaveData_142:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_4.bin"

	mAlignWord
DirectSoundWaveData_143:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_5.bin"

	mAlignWord
DirectSoundWaveData_144:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_6.bin"

	mAlignWord
DirectSoundWaveData_145:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_7.bin"

	mAlignWord
DirectSoundWaveData_146:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_8.bin"

	mAlignWord
DirectSoundWaveData_147:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_9.bin"

	mAlignWord
DirectSoundWaveData_148:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_10.bin"

	mAlignWord
DirectSoundWaveData_149:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_11.bin"

	mAlignWord
DirectSoundWaveData_150:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_12.bin"

	mAlignWord
DirectSoundWaveData_151:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_13.bin"

	mAlignWord
DirectSoundWaveData_152:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_14.bin"

	mAlignWord
DirectSoundWaveData_153:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pH_v1__84_5_loop_15.bin"

	mAlignWord
DirectSoundWaveData_154:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pG_v5__83_5_loop_1.bin"

	mAlignWord
DirectSoundWaveData_155:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pG_v5__83_5_loop_2.bin"

	mAlignWord
DirectSoundWaveData_156:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pG_v5__83_5_loop_3.bin"

	mAlignWord
DirectSoundWaveData_157:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pG_v5__83_5_loop_4.bin"

	mAlignWord
DirectSoundWaveData_158:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pG_v5__83_5_loop_5.bin"

	mAlignWord
DirectSoundWaveData_159:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pG_v5__83_5_loop_6.bin"

	mAlignWord
DirectSoundWaveData_160:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pG_v5__83_5_loop_7.bin"

	mAlignWord
DirectSoundWaveData_161:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pG_v5__83_5_loop_8.bin"

	mAlignWord
DirectSoundWaveData_162:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pG_v5__83_5_loop_9.bin"

	mAlignWord
DirectSoundWaveData_163:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pG_v5__83_5_loop_10.bin"

	mAlignWord
DirectSoundWaveData_164:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pG_v5__83_5_loop_11.bin"

	mAlignWord
DirectSoundWaveData_165:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pG_v5__83_5_loop_12.bin"

	mAlignWord
DirectSoundWaveData_166:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pG_v5__83_5_loop_13.bin"

	mAlignWord
DirectSoundWaveData_167:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pG_v5__83_5_loop_14.bin"

	mAlignWord
DirectSoundWaveData_168:
	.incbin "sound/direct_sound_samples/eastwest_techno__industrial_pG_v5__83_5_loop_15.bin"

	mAlignWord
DirectSoundWaveData_169:
	.incbin "sound/direct_sound_samples/unknown_8BE84CC.bin"

	mAlignWord
DirectSoundWaveData_170:
	.incbin "sound/direct_sound_samples/unknown_8BE8B70.bin"

	mAlignWord
DirectSoundWaveData_171:
	.incbin "sound/direct_sound_samples/unknown_8BE8F8C.bin"

	mAlignWord
DirectSoundWaveData_172:
	.incbin "sound/direct_sound_samples/unknown_8BE96B0.bin"

	mAlignWord
DirectSoundWaveData_173:
	.incbin "sound/direct_sound_samples/unknown_8BE9A64.bin"

	mAlignWord
DirectSoundWaveData_174:
	.incbin "sound/direct_sound_samples/unknown_8BEA558.bin"

	mAlignWord
DirectSoundWaveData_175:
	.incbin "sound/direct_sound_samples/unknown_8BEAC68.bin"

	mAlignWord
DirectSoundWaveData_176:
	.incbin "sound/direct_sound_samples/unknown_8BEB050.bin"

	mAlignWord
DirectSoundWaveData_177:
	.incbin "sound/direct_sound_samples/unknown_8BEB6F8.bin"

	mAlignWord
DirectSoundWaveData_178:
	.incbin "sound/direct_sound_samples/unknown_8BEBB08.bin"

	mAlignWord
DirectSoundWaveData_179:
	.incbin "sound/direct_sound_samples/unknown_8BEC1F4.bin"

	mAlignWord
DirectSoundWaveData_180:
	.incbin "sound/direct_sound_samples/unknown_8BEC5E0.bin"

	mAlignWord
DirectSoundWaveData_181:
	.incbin "sound/direct_sound_samples/unknown_8BECC28.bin"

	mAlignWord
DirectSoundWaveData_182:
	.incbin "sound/direct_sound_samples/unknown_8BED0D0.bin"

	mAlignWord
DirectSoundWaveData_183:
	.incbin "sound/direct_sound_samples/unknown_8BED77C.bin"

	mAlignWord
DirectSoundWaveData_184:
	.incbin "sound/direct_sound_samples/unknown_8BEDBC4.bin"

	mAlignWord
DirectSoundWaveData_185:
	.incbin "sound/direct_sound_samples/unknown_8BEE23C.bin"

	mAlignWord
DirectSoundWaveData_186:
	.incbin "sound/direct_sound_samples/unknown_8BEE66C.bin"

	mAlignWord
DirectSoundWaveData_187:
	.incbin "sound/direct_sound_samples/unknown_8BEECEC.bin"

	mAlignWord
DirectSoundWaveData_188:
	.incbin "sound/direct_sound_samples/unknown_8BEF12C.bin"

	mAlignWord
DirectSoundWaveData_189:
	.incbin "sound/direct_sound_samples/unknown_8BEF76C.bin"

	mAlignWord
DirectSoundWaveData_190:
	.incbin "sound/direct_sound_samples/unknown_8BEFBF8.bin"

	mAlignWord
DirectSoundWaveData_191:
	.incbin "sound/direct_sound_samples/unknown_8BF0268.bin"

	mAlignWord
DirectSoundWaveData_192:
	.incbin "sound/direct_sound_samples/unknown_8BF0708.bin"

	mAlignWord
DirectSoundWaveData_193:
	.incbin "sound/direct_sound_samples/unknown_8BF0DBC.bin"

	mAlignWord
DirectSoundWaveData_194:
	.incbin "sound/direct_sound_samples/unknown_8BF11CC.bin"

	mAlignWord
DirectSoundWaveData_195:
	.incbin "sound/direct_sound_samples/unknown_8BF1878.bin"

	mAlignWord
DirectSoundWaveData_196:
	.incbin "sound/direct_sound_samples/unknown_8BF1CA4.bin"

	mAlignWord
DirectSoundWaveData_197:
	.incbin "sound/direct_sound_samples/unknown_8BF27BC.bin"

	mAlignWord
DirectSoundWaveData_198:
	.incbin "sound/direct_sound_samples/unknown_8BF2DCC.bin"

	mAlignWord
DirectSoundWaveData_199:
	.incbin "sound/direct_sound_samples/unknown_8BF32F8.bin"

	mAlignWord
DirectSoundWaveData_200:
	.incbin "sound/direct_sound_samples/unknown_8BF3860.bin"

	mAlignWord
DirectSoundWaveData_201:
	.incbin "sound/direct_sound_samples/unknown_8BF3D74.bin"

	mAlignWord
DirectSoundWaveData_202:
	.incbin "sound/direct_sound_samples/unknown_8BF42D8.bin"

	mAlignWord
DirectSoundWaveData_203:
	.incbin "sound/direct_sound_samples/unknown_8BF4834.bin"

	mAlignWord
DirectSoundWaveData_204:
	.incbin "sound/direct_sound_samples/unknown_8BF4D94.bin"

	mAlignWord
DirectSoundWaveData_205:
	.incbin "sound/direct_sound_samples/unknown_8BF52B0.bin"

	mAlignWord
DirectSoundWaveData_206:
	.incbin "sound/direct_sound_samples/unknown_8BF5814.bin"

	mAlignWord
DirectSoundWaveData_207:
	.incbin "sound/direct_sound_samples/unknown_8BF5D34.bin"

	mAlignWord
DirectSoundWaveData_208:
	.incbin "sound/direct_sound_samples/unknown_8BF6250.bin"

	mAlignWord
DirectSoundWaveData_209:
	.incbin "sound/direct_sound_samples/unknown_8BF6774.bin"

	mAlignWord
DirectSoundWaveData_210:
	.incbin "sound/direct_sound_samples/unknown_8BF6C70.bin"

	mAlignWord
DirectSoundWaveData_211:
	.incbin "sound/direct_sound_samples/unknown_8BF7244.bin"

	mAlignWord
DirectSoundWaveData_212:
	.incbin "sound/direct_sound_samples/unknown_8BF7794.bin"

	mAlignWord
DirectSoundWaveData_213:
	.incbin "sound/direct_sound_samples/unknown_8BF7CBC.bin"

@ Starts synth sample section (samples 214->270)
	mAlignWord
DirectSoundWaveData_214:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8BF820C.bin"

	mAlignWord
DirectSoundWaveData_215:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8BF92B4.bin"

	mAlignWord
DirectSoundWaveData_216:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8BF9DB0.bin"

	mAlignWord
DirectSoundWaveData_217:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8BFA5B8.bin"

	mAlignWord
DirectSoundWaveData_218:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8BFAE34.bin"

	mAlignWord
DirectSoundWaveData_219:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8BFBEEC.bin"

	mAlignWord
DirectSoundWaveData_220:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8BFCF88.bin"

	mAlignWord
DirectSoundWaveData_221:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8BFDA70.bin"

	mAlignWord
DirectSoundWaveData_222:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8BFDF50.bin"

	mAlignWord
DirectSoundWaveData_223:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8BFE458.bin"

	mAlignWord
DirectSoundWaveData_224:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8BFEA24.bin"

	mAlignWord
DirectSoundWaveData_225:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8BFEFA8.bin"

	mAlignWord
DirectSoundWaveData_226:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8BFF56C.bin"

	mAlignWord
DirectSoundWaveData_227:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8BFFAC0.bin"

	mAlignWord
DirectSoundWaveData_228:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C00064.bin"

	mAlignWord
DirectSoundWaveData_229:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C005CC.bin"

	mAlignWord
DirectSoundWaveData_230:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C00A50.bin"

	mAlignWord
DirectSoundWaveData_231:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C01068.bin"

	mAlignWord
DirectSoundWaveData_232:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C015CC.bin"

	mAlignWord
DirectSoundWaveData_233:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C01B38.bin"

	mAlignWord
DirectSoundWaveData_234:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C020E4.bin"

	mAlignWord
DirectSoundWaveData_235:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C025EC.bin"

	mAlignWord
DirectSoundWaveData_236:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C02AF4.bin"

	mAlignWord
DirectSoundWaveData_237:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C03000.bin"

	mAlignWord
DirectSoundWaveData_238:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C03134.bin"

	mAlignWord
DirectSoundWaveData_239:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C03674.bin"

	mAlignWord
DirectSoundWaveData_240:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C03B7C.bin"

	mAlignWord
DirectSoundWaveData_241:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C041A4.bin"

	mAlignWord
DirectSoundWaveData_242:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C046A8.bin"

	mAlignWord
DirectSoundWaveData_243:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C04C44.bin"

	mAlignWord
DirectSoundWaveData_244:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C051BC.bin"

	mAlignWord
DirectSoundWaveData_245:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C05700.bin"

	mAlignWord
DirectSoundWaveData_246:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C05CB4.bin"

	mAlignWord
DirectSoundWaveData_247:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C061F8.bin"

	mAlignWord
DirectSoundWaveData_248:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C0673C.bin"

	mAlignWord
DirectSoundWaveData_249:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C06C6C.bin"

	mAlignWord
DirectSoundWaveData_250:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C071FC.bin"

	mAlignWord
DirectSoundWaveData_251:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C07770.bin"

	mAlignWord
DirectSoundWaveData_252:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C07C9C.bin"

	mAlignWord
DirectSoundWaveData_253:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C081C0.bin"

	mAlignWord
DirectSoundWaveData_254:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C086CC.bin"

	mAlignWord
DirectSoundWaveData_255:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C087B4.bin"

	mAlignWord
DirectSoundWaveData_256:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C08CD0.bin"

	mAlignWord
DirectSoundWaveData_257:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C09240.bin"

	mAlignWord
DirectSoundWaveData_258:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C097F0.bin"

	mAlignWord
DirectSoundWaveData_259:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C09DC4.bin"

	mAlignWord
DirectSoundWaveData_260:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C0A2B0.bin"

	mAlignWord
DirectSoundWaveData_261:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C0A814.bin"

	mAlignWord
DirectSoundWaveData_262:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C0ADC0.bin"

	mAlignWord
DirectSoundWaveData_263:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C0B310.bin"

	mAlignWord
DirectSoundWaveData_264:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C0B874.bin"

	mAlignWord
DirectSoundWaveData_265:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C0BE18.bin"

	mAlignWord
DirectSoundWaveData_266:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C0C3E4.bin"

	mAlignWord
DirectSoundWaveData_267:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C0C89C.bin"

	mAlignWord
DirectSoundWaveData_268:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C0CE1C.bin"

	mAlignWord
DirectSoundWaveData_269:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C0D368.bin"

	mAlignWord
DirectSoundWaveData_270:
	.incbin "sound/direct_sound_samples/unk_synth_2/synth_8C0D8A0.bin"

	mAlignWord
DirectSoundWaveData_271:
	.incbin "sound/direct_sound_samples/unknown_8C0DE50.bin"

	mAlignWord
DirectSoundWaveData_272:
	.incbin "sound/direct_sound_samples/unknown_8C0E9F8.bin"

	mAlignWord
DirectSoundWaveData_273:
	.incbin "sound/direct_sound_samples/unknown_8C0F12C.bin"

	mAlignWord
DirectSoundWaveData_274:
	.incbin "sound/direct_sound_samples/unknown_8C0F654.bin"

	mAlignWord
DirectSoundWaveData_275:
	.incbin "sound/direct_sound_samples/unknown_8C0FC88.bin"

	mAlignWord
DirectSoundWaveData_276:
	.incbin "sound/direct_sound_samples/unknown_8C10254.bin"

	mAlignWord
DirectSoundWaveData_277:
	.incbin "sound/direct_sound_samples/unknown_8C10934.bin"

	mAlignWord
DirectSoundWaveData_278:
	.incbin "sound/direct_sound_samples/unknown_8C10E74.bin"

	mAlignWord
DirectSoundWaveData_279:
	.incbin "sound/direct_sound_samples/unknown_8C1153C.bin"

	mAlignWord
DirectSoundWaveData_280:
	.incbin "sound/direct_sound_samples/unknown_8C11A60.bin"

	mAlignWord
DirectSoundWaveData_281:
	.incbin "sound/direct_sound_samples/unknown_8C12124.bin"

	mAlignWord
DirectSoundWaveData_282:
	.incbin "sound/direct_sound_samples/unknown_8C12674.bin"

	mAlignWord
DirectSoundWaveData_283:
	.incbin "sound/direct_sound_samples/unknown_8C12D24.bin"

	mAlignWord
DirectSoundWaveData_284:
	.incbin "sound/direct_sound_samples/unknown_8C13254.bin"

	mAlignWord
DirectSoundWaveData_285:
	.incbin "sound/direct_sound_samples/unknown_8C13928.bin"

	mAlignWord
DirectSoundWaveData_286:
	.incbin "sound/direct_sound_samples/unknown_8C13E3C.bin"

	mAlignWord
DirectSoundWaveData_287:
	.incbin "sound/direct_sound_samples/unknown_8C14524.bin"

	mAlignWord
DirectSoundWaveData_288:
	.incbin "sound/direct_sound_samples/unknown_8C14AA0.bin"

	mAlignWord
DirectSoundWaveData_289:
	.incbin "sound/direct_sound_samples/unknown_8C15164.bin"

	mAlignWord
DirectSoundWaveData_290:
	.incbin "sound/direct_sound_samples/unknown_8C15698.bin"

	mAlignWord
DirectSoundWaveData_291:
	.incbin "sound/direct_sound_samples/unknown_8C15C60.bin"

	mAlignWord
DirectSoundWaveData_292:
	.incbin "sound/direct_sound_samples/unknown_8C162A4.bin"

	mAlignWord
DirectSoundWaveData_293:
	.incbin "sound/direct_sound_samples/unknown_8C16970.bin"

	mAlignWord
DirectSoundWaveData_294:
	.incbin "sound/direct_sound_samples/unknown_8C16EB8.bin"

	mAlignWord
DirectSoundWaveData_295:
	.incbin "sound/direct_sound_samples/unknown_8C17584.bin"

	mAlignWord
DirectSoundWaveData_296:
	.incbin "sound/direct_sound_samples/unknown_8C17A94.bin"

	mAlignWord
DirectSoundWaveData_297:
	.incbin "sound/direct_sound_samples/unknown_8C18188.bin"

	mAlignWord
DirectSoundWaveData_298:
	.incbin "sound/direct_sound_samples/unknown_8C186E8.bin"

	mAlignWord
DirectSoundWaveData_299:
	.incbin "sound/direct_sound_samples/unknown_8C18D8C.bin"

	mAlignWord
DirectSoundWaveData_300:
	.incbin "sound/direct_sound_samples/unknown_8C192A8.bin"

	mAlignWord
DirectSoundWaveData_301:
	.incbin "sound/direct_sound_samples/unknown_8C1998C.bin"

	mAlignWord
DirectSoundWaveData_302:
	.incbin "sound/direct_sound_samples/unknown_8C19EB8.bin"

	mAlignWord
DirectSoundWaveData_303:
	.incbin "sound/direct_sound_samples/unknown_8C1A3F4.bin"

	mAlignWord
DirectSoundWaveData_304:
	.incbin "sound/direct_sound_samples/unknown_8C1A900.bin"

	mAlignWord
DirectSoundWaveData_305:
	.incbin "sound/direct_sound_samples/unknown_8C1AE50.bin"

	mAlignWord
DirectSoundWaveData_306:
	.incbin "sound/direct_sound_samples/unknown_8C1B380.bin"

	mAlignWord
DirectSoundWaveData_307:
	.incbin "sound/direct_sound_samples/unknown_8C1B928.bin"

	mAlignWord
DirectSoundWaveData_308:
	.incbin "sound/direct_sound_samples/unknown_8C1BE0C.bin"

	mAlignWord
DirectSoundWaveData_309:
	.incbin "sound/direct_sound_samples/unknown_8C1C378.bin"

	mAlignWord
DirectSoundWaveData_310:
	.incbin "sound/direct_sound_samples/unknown_8C1C884.bin"

	mAlignWord
DirectSoundWaveData_311:
	.incbin "sound/direct_sound_samples/unknown_8C1CDB8.bin"

	mAlignWord
DirectSoundWaveData_312:
	.incbin "sound/direct_sound_samples/unknown_8C1D2E0.bin"

	mAlignWord
DirectSoundWaveData_313:
	.incbin "sound/direct_sound_samples/unknown_8C1D7EC.bin"

	mAlignWord
DirectSoundWaveData_314:
	.incbin "sound/direct_sound_samples/unknown_8C1DD2C.bin"

	mAlignWord
DirectSoundWaveData_315:
	.incbin "sound/direct_sound_samples/unknown_8C1E29C.bin"

	mAlignWord
DirectSoundWaveData_316:
	.incbin "sound/direct_sound_samples/unknown_8C1E760.bin"

	mAlignWord
DirectSoundWaveData_317:
	.incbin "sound/direct_sound_samples/unknown_8C1ED70.bin"

	mAlignWord
DirectSoundWaveData_318:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C1F268.bin"

	mAlignWord
DirectSoundWaveData_319:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C1FD70.bin"

	mAlignWord
DirectSoundWaveData_320:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C202D0.bin"

	mAlignWord
DirectSoundWaveData_321:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C207D0.bin"

	mAlignWord
DirectSoundWaveData_322:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C212B8.bin"

	mAlignWord
DirectSoundWaveData_323:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C218C0.bin"

	mAlignWord
DirectSoundWaveData_324:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C21D18.bin"

	mAlignWord
DirectSoundWaveData_325:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C22298.bin"

	mAlignWord
DirectSoundWaveData_326:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C22760.bin"

	mAlignWord
DirectSoundWaveData_327:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C23218.bin"

	mAlignWord
DirectSoundWaveData_328:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C23CA8.bin"

	mAlignWord
DirectSoundWaveData_329:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C242A8.bin"

	mAlignWord
DirectSoundWaveData_330:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C24730.bin"

	mAlignWord
DirectSoundWaveData_331:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C24C80.bin"

	mAlignWord
DirectSoundWaveData_332:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C2572C.bin"

	mAlignWord
DirectSoundWaveData_333:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C25D2C.bin"

	mAlignWord
DirectSoundWaveData_334:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C261B4.bin"

	mAlignWord
DirectSoundWaveData_335:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C26724.bin"

	mAlignWord
DirectSoundWaveData_336:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C26CA0.bin"

	mAlignWord
DirectSoundWaveData_337:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C271B8.bin"

	mAlignWord
DirectSoundWaveData_338:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C27770.bin"

	mAlignWord
DirectSoundWaveData_339:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C27C58.bin"

	mAlignWord
DirectSoundWaveData_340:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C281A8.bin"

	mAlignWord
DirectSoundWaveData_341:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C28CFC.bin"

	mAlignWord
DirectSoundWaveData_342:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C295D0.bin"

	mAlignWord
DirectSoundWaveData_343:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C29BF0.bin"

	mAlignWord
DirectSoundWaveData_344:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C2A158.bin"

	mAlignWord
DirectSoundWaveData_345:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C2AC00.bin"

	mAlignWord
DirectSoundWaveData_346:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C2B22C.bin"

	mAlignWord
DirectSoundWaveData_347:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C2B6EC.bin"

	mAlignWord
DirectSoundWaveData_348:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C2BC58.bin"

	mAlignWord
DirectSoundWaveData_349:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C2C0F8.bin"

	mAlignWord
DirectSoundWaveData_350:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C2CBC4.bin"

	mAlignWord
DirectSoundWaveData_351:
	.incbin "sound/direct_sound_samples/amen_break/amen_break_8C2D494.bin"

	mAlignWord
DirectSoundWaveData_352:
	.incbin "sound/direct_sound_samples/unknown_8C2DEF4.bin"

	mAlignWord
DirectSoundWaveData_353:
	.incbin "sound/direct_sound_samples/unknown_8C2E44C.bin"

	mAlignWord
DirectSoundWaveData_354:
	.incbin "sound/direct_sound_samples/unknown_8C2E8CC.bin"

	mAlignWord
DirectSoundWaveData_355:
	.incbin "sound/direct_sound_samples/guitar_8C2ED58.bin"

	mAlignWord
DirectSoundWaveData_356:
	.incbin "sound/direct_sound_samples/guitar_8C2F314.bin"

	mAlignWord
DirectSoundWaveData_357: @ 0x8C2F978
	.incbin "sound/direct_sound_samples/korg_01_w__a81_flute.bin"

	mAlignWord
DirectSoundWaveData_358: @ 0x8C30F08
	.incbin "sound/direct_sound_samples/korg_01_w__combi__bank_a__a14_whammy_and_pad.bin"

	mAlignWord
DirectSoundWaveData_359:
	.incbin "sound/direct_sound_samples/some_heavy_guitar__8C34DFC.bin"

	mAlignWord
DirectSoundWaveData_360:
	.incbin "sound/direct_sound_samples/some_synth_maybe__8C35C68.bin"

	mAlignWord
DirectSoundWaveData_361: @ 0x8C37240
	.incbin "sound/direct_sound_samples/roland_u220__p11_heavy_guitar_011.bin"

	mAlignWord
DirectSoundWaveData_362:
	.incbin "sound/direct_sound_samples/some_unk_organ__8C382F4.bin"

	mAlignWord
DirectSoundWaveData_363:
	.incbin "sound/direct_sound_samples/some_unk_organ__8C3A298.bin"

	mAlignWord
DirectSoundWaveData_364:
	.incbin "sound/direct_sound_samples/unk_crash__8C3BC34.bin"

	mAlignWord
DirectSoundWaveData_365:
	.incbin "sound/direct_sound_samples/unknown_synth__8C3D53C.bin"

	mAlignWord
DirectSoundWaveData_366:
	.incbin "sound/direct_sound_samples/unknown_8C3F3E0.bin"

	mAlignWord
DirectSoundWaveData_367:
	.incbin "sound/direct_sound_samples/unknown_8C40314.bin"

	mAlignWord
DirectSoundWaveData_368:
	.incbin "sound/direct_sound_samples/unknown_8C41284.bin"

	mAlignWord
DirectSoundWaveData_369: @ 0x8C41820
	.incbin "sound/direct_sound_samples/korg_01_w__b_b22_brass1.bin"

	mAlignWord
DirectSoundWaveData_370:
	.incbin "sound/direct_sound_samples/unknown_piano__8C42488.bin"

	mAlignWord
DirectSoundWaveData_371:
	.incbin "sound/direct_sound_samples/unknown_piano__8C46A48.bin"

	mAlignWord
DirectSoundWaveData_372:
	.incbin "sound/direct_sound_samples/unknown_piano__8C4991C.bin"

	mAlignWord
DirectSoundWaveData_373:
	.incbin "sound/direct_sound_samples/korg_01_w__prog__bank_a__a83_flute__b83_englishHm.bin"

	mAlignWord
DirectSoundWaveData_374:
	.incbin "sound/direct_sound_samples/unknown_piano__8C4E120.bin"

	mAlignWord
DirectSoundWaveData_375:
	.incbin "sound/direct_sound_samples/unknown_8C50304.bin"

	mAlignWord
DirectSoundWaveData_376:
	.incbin "sound/direct_sound_samples/unk_harmonica__8C517B0.bin"

	mAlignWord
DirectSoundWaveData_377:
	.incbin "sound/direct_sound_samples/roland_jv2080__pr_d__019_organ_3__10.bin"

	mAlignWord
DirectSoundWaveData_378:
	.incbin "sound/direct_sound_samples/roland_jv2080__pr_d__019_organ_3__11.bin"

	mAlignWord
DirectSoundWaveData_379:
	.incbin "sound/direct_sound_samples/roland_jv2080__pr_d__019_organ_3__12.bin"
