	.align 2
ProgrammableWaveData_1:
	.incbin "sound/programmable_wave_samples/01.pcm"

	.align 2
ProgrammableWaveData_2:
	.incbin "sound/programmable_wave_samples/02.pcm"

	.align 2
ProgrammableWaveData_3:
	.incbin "sound/programmable_wave_samples/03.pcm"

	.align 2
ProgrammableWaveData_4:
	.incbin "sound/programmable_wave_samples/04.pcm"

	.align 2
ProgrammableWaveData_5:
	.incbin "sound/programmable_wave_samples/05.pcm"

	.align 2
ProgrammableWaveData_6:
	.incbin "sound/programmable_wave_samples/06.pcm"

	.align 2
ProgrammableWaveData_7:
	.incbin "sound/programmable_wave_samples/07.pcm"

	.align 2
ProgrammableWaveData_8:
	.incbin "sound/programmable_wave_samples/08.pcm"

	.align 2
ProgrammableWaveData_9:
	.incbin "sound/programmable_wave_samples/09.pcm"

	.align 2
ProgrammableWaveData_10:
	.incbin "sound/programmable_wave_samples/10.pcm"
