	.align 2
	.global gUnknown_08AD4E44
gUnknown_08AD4E44:
	.incbin "sound/programmable_wave_samples/08AD4E44.pcm"

	.align 2
	.global gUnknown_08AD4E8C
gUnknown_08AD4E8C:
	.incbin "sound/programmable_wave_samples/08AD4E8C.pcm"

	.align 2
	.global gUnknown_08AD4E9C
gUnknown_08AD4E9C:
	.incbin "sound/programmable_wave_samples/08AD4E9C.pcm"

	.align 2
	.global gUnknown_08AD4EAC
gUnknown_08AD4EAC:
	.incbin "sound/programmable_wave_samples/08AD4EAC.pcm"

	.align 2
	.global gUnknown_08AD4EBC
gUnknown_08AD4EBC:
	.incbin "sound/programmable_wave_samples/08AD4EBC.pcm"

	.align 2
	.global gUnknown_08AD4ECC
gUnknown_08AD4ECC:
	.incbin "sound/programmable_wave_samples/08AD4ECC.pcm"

	.align 2
	.global gUnknown_08AD4EDC
gUnknown_08AD4EDC:
	.incbin "sound/programmable_wave_samples/08AD4EDC.pcm"

	.align 2
	.global gUnknown_08AD4EEC
gUnknown_08AD4EEC:
	.incbin "sound/programmable_wave_samples/08AD4EEC.pcm"

	.align 2
	.global gUnknown_08AD4EFC
gUnknown_08AD4EFC:
	.incbin "sound/programmable_wave_samples/08AD4EFC.pcm"

	.align 2
	.global gUnknown_08AD4F0C
gUnknown_08AD4F0C:
	.incbin "sound/programmable_wave_samples/08AD4F0C.pcm"
