	mAlignWord
	.global C_DECL(gSongTable)
C_DECL(gSongTable):	@ 0x08AD4F4C
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(mus_intro), 0, 0
mAlignWord
	song C_DECL(mus_title_fanfare), 0, 0
mAlignWord
	song C_DECL(mus_character_selection), 0, 0
mAlignWord
	song C_DECL(mus_ta_course_selection), 0, 0
mAlignWord
	song C_DECL(mus_course_selection_2), 0, 0
mAlignWord
	song C_DECL(mus_course_selection_3), 0, 0
mAlignWord
	song C_DECL(mus_time_attack_menu), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(mus_options), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(mus_leaf_forest__act_1), 0, 0
mAlignWord
	song C_DECL(mus_leaf_forest__act_2), 0, 0
mAlignWord
	song C_DECL(mus_hot_crater__act_1), 0, 0
mAlignWord
	song C_DECL(mus_hot_crater__act_2), 0, 0
mAlignWord
	song C_DECL(mus_music_plant__act_1), 0, 0
mAlignWord
	song C_DECL(mus_music_plant__act_2), 0, 0
mAlignWord
	song C_DECL(mus_ice_paradise__act_1), 0, 0
mAlignWord
	song C_DECL(mus_ice_paradise__act_2), 0, 0
mAlignWord
	song C_DECL(mus_sky_canyon__act_1), 0, 0
mAlignWord
	song C_DECL(mus_sky_canyon__act_2), 0, 0
mAlignWord
	song C_DECL(mus_techno_base__act_1), 0, 0
mAlignWord
	song C_DECL(mus_techno_base__act_2), 0, 0
mAlignWord
	song C_DECL(mus_egg_utopia__act_1), 0, 0
mAlignWord
	song C_DECL(mus_egg_utopia__act_2), 0, 0
mAlignWord
	song C_DECL(mus_xx__final_zone), 0, 0
mAlignWord
	song C_DECL(mus_true_area_53), 0, 0
mAlignWord
	song C_DECL(mus_invincibility), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(mus_drowning), 0, 0
mAlignWord
	song C_DECL(mus_boss), 0, 0
mAlignWord
	song C_DECL(mus_boss_pinch), 0, 0
mAlignWord
	song C_DECL(mus_boss_knuckles), 0, 0
mAlignWord
	song C_DECL(mus_7_boss), 0, 0
mAlignWord
	song C_DECL(mus_7_boss_pinch), 0, 0
mAlignWord
	song C_DECL(mus_final_boss), 0, 0
mAlignWord
	song C_DECL(mus_final_boss_pinch), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(mus_game_over), 0, 0
mAlignWord
	song C_DECL(mus_final_ending), 0, 0
mAlignWord
	song C_DECL(mus_extra_ending), 0, 0
mAlignWord
	song C_DECL(mus_staff_credits), 0, 0
mAlignWord
	song C_DECL(mus_demo_1), 0, 0
mAlignWord
	song C_DECL(mus_demo_2), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(mus_extra_demo_1), 0, 0
mAlignWord
	song C_DECL(mus_extra_demo_2), 0, 0
mAlignWord
	song C_DECL(mus_special_stage_intro), 0, 0
mAlignWord
	song C_DECL(mus_special_stage), 0, 0
mAlignWord
	song C_DECL(mus_special_stage_pinch), 0, 0
mAlignWord
	song C_DECL(mus_achievement), 0, 0
mAlignWord
	song C_DECL(mus_special_stage_clear), 0, 0
mAlignWord
	song C_DECL(mus_special_stage_result), 0, 0
mAlignWord
	song C_DECL(mus_chaos_emerald), 0, 0
mAlignWord
	song C_DECL(mus_special_stage_result_lose), 0, 0
mAlignWord
	song C_DECL(mus_vs_2), 0, 0
mAlignWord
	song C_DECL(mus_vs_3), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(mus_connection_pending), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(mus_vs_lobby), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(mus_vs_select_pak_mode), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(se_ring), 3, 3
mAlignWord
	song C_DECL(se_shift), 3, 3
mAlignWord
	song C_DECL(se_success), 3, 3
mAlignWord
	song C_DECL(se_abort), 3, 3
mAlignWord
	song C_DECL(se_select), 2, 2
mAlignWord
	song C_DECL(se_return), 2, 2
mAlignWord
	song C_DECL(se_menu_cursor_move), 2, 2
mAlignWord
	song C_DECL(se_spin_attack), 3, 3
mAlignWord
	song C_DECL(se_spin_dash_release), 2, 2
mAlignWord
	song C_DECL(se_sonic_skid_attack), 3, 3
mAlignWord
	song C_DECL(se_sonic_midair_somersault), 3, 3
mAlignWord
	song C_DECL(se_sonic_insta_shield), 2, 2
mAlignWord
	song C_DECL(se_grinding), 2, 2
mAlignWord
	song C_DECL(se_brake), 2, 2
mAlignWord
	song C_DECL(se_jump), 2, 2
mAlignWord
	song C_DECL(se_ring_copy), 3, 3
mAlignWord
	song C_DECL(se_rings_lost), 3, 3
mAlignWord
	song C_DECL(se_life_lost), 2, 2
mAlignWord
	song C_DECL(se_tails_propeller_flying), 3, 3
mAlignWord
	song C_DECL(se_tails_tail_swipe), 3, 3
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(se_125), 3, 3
mAlignWord
	song C_DECL(se_126), 3, 3
mAlignWord
	song C_DECL(se_127), 3, 3
mAlignWord
	song C_DECL(se_amy_ground_hammer), 3, 3
mAlignWord
	song C_DECL(se_amy_super_hammer_attack), 3, 3
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(se_amy_hammer_swirl), 3, 3
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(se_sa1_goal_post), 3, 3
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(se_item_box), 2, 2
mAlignWord
	song C_DECL(se_timer), 2, 2
mAlignWord
	song C_DECL(se_stage_result_counter), 2, 2
mAlignWord
	song C_DECL(se_stage_result_counter_done), 3, 3
mAlignWord
	song C_DECL(se_pause_screen), 3, 3
mAlignWord
	song C_DECL(se_143), 1, 1
mAlignWord
	song C_DECL(se_144), 3, 3
mAlignWord
	song C_DECL(se_145), 3, 3
mAlignWord
	song C_DECL(se_146), 3, 3
mAlignWord
	song C_DECL(se_spin), 2, 2
mAlignWord
	song C_DECL(se_148), 3, 3
mAlignWord
	song C_DECL(se_time_up), 3, 3
mAlignWord
	song C_DECL(se_item_box_2), 2, 2
mAlignWord
	song C_DECL(se_151), 2, 2
mAlignWord
	song C_DECL(se_checkpoint), 2, 2
mAlignWord
	song C_DECL(se_spring), 2, 2
mAlignWord
	song C_DECL(se_spikes), 2, 2
mAlignWord
	song C_DECL(se_speed_booster), 2, 2
mAlignWord
	song C_DECL(se_156), 2, 2
mAlignWord
	song C_DECL(se_157), 2, 2
mAlignWord
	song C_DECL(se_air_bubble), 2, 2
mAlignWord
	song C_DECL(se_alarm_1), 3, 3
mAlignWord
	song C_DECL(se_alarm_2), 3, 3
mAlignWord
	song C_DECL(se_alarm_3), 3, 3
mAlignWord
	song C_DECL(se_alarm_4), 3, 3
mAlignWord
	song C_DECL(se_alarm_5), 3, 3
mAlignWord
	song C_DECL(se_alarm_6), 3, 3
mAlignWord
	song C_DECL(se_alarm_7), 3, 3
mAlignWord
	song C_DECL(se_alarm_8), 3, 3
mAlignWord
	song C_DECL(se_alarm_9), 3, 3
mAlignWord
	song C_DECL(se_alarm_10), 3, 3
mAlignWord
	song C_DECL(se_springy_pole), 2, 2
mAlignWord
	song C_DECL(se_springy_spring), 2, 2
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(voice__announcer__sonic_advance_2), 2, 2
mAlignWord
	song C_DECL(voice__announcer__sonic), 2, 2
mAlignWord
	song C_DECL(voice__announcer__tails), 2, 2
mAlignWord
	song C_DECL(voice__announcer__knuckles), 2, 2
mAlignWord
	song C_DECL(voice__announcer__amy), 2, 2
mAlignWord
	song C_DECL(voice__announcer__cream), 2, 2
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(voice__announcer__3), 2, 2
mAlignWord
	song C_DECL(voice__announcer__2), 2, 2
mAlignWord
	song C_DECL(voice__announcer__1), 2, 2
mAlignWord
	song C_DECL(voice__announcer__go), 2, 2
mAlignWord
	song C_DECL(voice__announcer__congratulations), 2, 2
mAlignWord
	song C_DECL(se_map_move), 2, 2
mAlignWord
	song C_DECL(se_map_214), 2, 2
mAlignWord
	song C_DECL(se_map_move_end), 2, 2
mAlignWord
	song C_DECL(se_216), 2, 2
mAlignWord
	song C_DECL(se_217), 2, 2
mAlignWord
	song C_DECL(se_218), 2, 2
mAlignWord
	song C_DECL(se_219), 2, 2
mAlignWord
	song C_DECL(se_delete_game_data), 2, 2
mAlignWord
	song C_DECL(se_221), 2, 2
mAlignWord
	song C_DECL(se_222), 2, 2
mAlignWord
	song C_DECL(se_223), 2, 2
mAlignWord
	song C_DECL(se_224), 2, 2
mAlignWord
	song C_DECL(se_225), 2, 2
mAlignWord
	song C_DECL(se_226), 2, 2
mAlignWord
	song C_DECL(se_cream_flying), 3, 3
mAlignWord
	song C_DECL(se_228), 2, 2
mAlignWord
	song C_DECL(se_cream_cheese_attack), 2, 2
mAlignWord
	song C_DECL(se_230), 2, 2
mAlignWord
	song C_DECL(se_231), 2, 2
mAlignWord
	song C_DECL(se_long_brake), 2, 2
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(se_234), 2, 2
mAlignWord
	song C_DECL(se_235), 2, 2
mAlignWord
	song C_DECL(se_236), 2, 2
mAlignWord
	song C_DECL(se_237), 2, 2
mAlignWord
	song C_DECL(se_238), 2, 2
mAlignWord
	song C_DECL(se_239), 2, 2
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(se_241), 2, 2
mAlignWord
	song C_DECL(se_242), 2, 2
mAlignWord
	song C_DECL(se_243), 2, 2
mAlignWord
	song C_DECL(se_244), 2, 2
mAlignWord
	song C_DECL(se_245), 2, 2
mAlignWord
	song C_DECL(se_246), 2, 2
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(se_248), 2, 2
mAlignWord
	song C_DECL(se_249), 2, 2
mAlignWord
	song C_DECL(se_250), 2, 2
mAlignWord
	song C_DECL(se_251), 2, 2
mAlignWord
	song C_DECL(se_252), 2, 2
mAlignWord
	song C_DECL(se_253), 2, 2
mAlignWord
	song C_DECL(se_254), 2, 2
mAlignWord
	song C_DECL(se_255), 2, 2
mAlignWord
	song C_DECL(se_256), 2, 2
mAlignWord
	song C_DECL(se_257), 2, 2
mAlignWord
	song C_DECL(se_258), 2, 2
mAlignWord
	song C_DECL(se_259), 2, 2
mAlignWord
	song C_DECL(se_260), 2, 2
mAlignWord
	song C_DECL(se_261), 2, 2
mAlignWord
	song C_DECL(se_262), 2, 2
mAlignWord
	song C_DECL(se_263), 2, 2
mAlignWord
	song C_DECL(se_264), 2, 2
mAlignWord
	song C_DECL(se_265), 2, 2
mAlignWord
	song C_DECL(se_266), 2, 2
mAlignWord
	song C_DECL(se_267), 2, 2
mAlignWord
	song C_DECL(se_268), 2, 2
mAlignWord
	song C_DECL(se_269), 2, 2
mAlignWord
	song C_DECL(se_suction), 2, 2
mAlignWord
	song C_DECL(se_271), 2, 2
mAlignWord
	song C_DECL(se_272), 2, 2
mAlignWord
	song C_DECL(se_273), 2, 2
mAlignWord
	song C_DECL(se_274), 2, 2
mAlignWord
	song C_DECL(se_275), 2, 2
mAlignWord
	song C_DECL(se_276), 2, 2
mAlignWord
	song C_DECL(se_277), 2, 2
mAlignWord
	song C_DECL(se_278), 2, 2
mAlignWord
	song C_DECL(se_279), 2, 2
mAlignWord
	song C_DECL(se_280), 2, 2
mAlignWord
	song C_DECL(se_281), 2, 2
mAlignWord
	song C_DECL(se_282), 2, 2
mAlignWord
	song C_DECL(se_283), 2, 2
mAlignWord
	song C_DECL(se_284), 2, 2
mAlignWord
	song C_DECL(se_285), 2, 2
mAlignWord
	song C_DECL(se_286), 2, 2
mAlignWord
	song C_DECL(se_287), 2, 2
mAlignWord
	song C_DECL(se_288), 2, 2
mAlignWord
	song C_DECL(se_289), 2, 2
mAlignWord
	song C_DECL(se_290), 2, 2
mAlignWord
	song C_DECL(se_291), 2, 2
mAlignWord
	song C_DECL(se_ice_paradise_slide), 2, 2
mAlignWord
	song C_DECL(se_293), 2, 2
mAlignWord
	song C_DECL(se_techno_base_note_block), 2, 2
mAlignWord
	song C_DECL(se_295), 2, 2
mAlignWord
	song C_DECL(se_296), 2, 2
mAlignWord
	song C_DECL(se_297), 2, 2
mAlignWord
	song C_DECL(se_special_ring), 2, 2
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(se_music_plant_spring_1), 2, 2
mAlignWord
	song C_DECL(se_music_plant_spring_2), 2, 2
mAlignWord
	song C_DECL(se_music_plant_spring_3), 2, 2
mAlignWord
	song C_DECL(se_music_plant_spring_4), 2, 2
mAlignWord
	song C_DECL(se_music_plant_crash_hit), 2, 2
mAlignWord
	song C_DECL(se_music_plant_notes_1), 2, 2
mAlignWord
	song C_DECL(se_music_plant_notes_2), 2, 2
mAlignWord
	song C_DECL(se_music_plant_notes_3), 2, 2
mAlignWord
	song C_DECL(se_music_plant_notes_4), 2, 2
mAlignWord
	song C_DECL(se_music_plant_notes_5), 2, 2
mAlignWord
	song C_DECL(se_music_plant_notes_6), 2, 2
mAlignWord
	song C_DECL(se_music_plant_notes_7), 2, 2
mAlignWord
	song C_DECL(se_music_plant_notes_8), 2, 2
mAlignWord
	song C_DECL(se_music_plant_glockenspiel_1), 2, 2
mAlignWord
	song C_DECL(se_music_plant_glockenspiel_2), 2, 2
mAlignWord
	song C_DECL(se_music_plant_glockenspiel_3), 2, 2
mAlignWord
	song C_DECL(se_music_plant_glockenspiel_4), 2, 2
mAlignWord
	song C_DECL(se_music_plant_glockenspiel_5), 2, 2
mAlignWord
	song C_DECL(se_music_plant_glockenspiel_6), 2, 2
mAlignWord
	song C_DECL(se_music_plant_enter_horn), 2, 2
mAlignWord
	song C_DECL(se_music_plant_exit_horn), 2, 2
mAlignWord
	song C_DECL(se_music_plant_enter_horn2), 2, 2
mAlignWord
	song C_DECL(se_music_plant_exit_horn2), 2, 2
mAlignWord
	song C_DECL(se_music_plant_horn3), 2, 2
mAlignWord
	song C_DECL(se_music_plant_chord), 2, 2
mAlignWord
	song C_DECL(se_music_plant_piano), 2, 2
mAlignWord
	song C_DECL(se_music_plant_flute_1), 2, 2
mAlignWord
	song C_DECL(se_music_plant_flute_2), 2, 2
mAlignWord
	song C_DECL(se_music_plant_flute_3), 2, 2
mAlignWord
	song C_DECL(se_music_plant_flute_4), 2, 2
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(se_331), 2, 2
mAlignWord
	song C_DECL(se_332), 2, 2
mAlignWord
	song C_DECL(se_333), 2, 2
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(mus_act_clear), 0, 0
mAlignWord
	song C_DECL(mus_boss_clear), 0, 0
mAlignWord
	song C_DECL(mus_final_clear), 0, 0
mAlignWord
	song C_DECL(mus_extra_clear), 0, 0
mAlignWord
	song C_DECL(mus_time_attack_2), 0, 0
mAlignWord
	song C_DECL(mus_time_attack_3), 0, 0
mAlignWord
	song C_DECL(mus_1_up), 0, 0
mAlignWord
	song C_DECL(mus_message_2), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(mus_got_all_chaos_emeralds), 0, 0
mAlignWord
	song C_DECL(mus_fanfare), 1, 1
mAlignWord
	song C_DECL(mus_vs_exit), 1, 1
mAlignWord
	song C_DECL(mus_vs_success), 1, 1
mAlignWord
	song C_DECL(mus_vs_miss), 1, 1
mAlignWord
	song C_DECL(mus_message), 1, 1
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(mus_504), 0, 0
mAlignWord
	song C_DECL(mus_505), 0, 0
mAlignWord
	song C_DECL(mus_506), 0, 0

	mAlignWord
C_DECL(dummy_song_header):
	.byte 0, 0, 0, 0
