	mAlignWord
	.global voicegroup000
voicegroup000:	@ 0x08ACDF50
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@08ACDF50
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08ACDF5C
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACDF68
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@08ACDF74
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACDF80
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACDF8C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACDF98
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACDFA4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACDFB0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACDFBC
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@08ACDFC8
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08ACDFD4
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACDFE0
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@08ACDFEC
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACDFF8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE004
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE010
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE01C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE028
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE034
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE040
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE04C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE058
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE064
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE070
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE07C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE088
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE094
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0A0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0AC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0B8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0C4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0D0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0DC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0F4
mAlignWord
	voice_square_2_alt 1, 1, 0, 15, 0	@08ACE100
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE10C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE118
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE124
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 4, 4, 0	@08ACE130
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_3, 0, 0, 15, 0	@08ACE13C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_4, 0, 0, 15, 0	@08ACE148
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_5, 0, 0, 15, 0	@08ACE154
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08ACE160
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08ACE16C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08ACE178
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08ACE184
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08ACE190
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE19C
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACE1A8
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACE1B4
mAlignWord
	voice_square_2_alt 2, 0, 3, 0, 0	@08ACE1C0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08ACE1CC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08ACE1D8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08ACE1E4
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 5	@08ACE1F0
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@08ACE1FC
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACE208
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACE214
mAlignWord
	voice_square_2_alt 0, 0, 4, 0, 0	@08ACE220
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 4, 0, 0	@08ACE22C
mAlignWord
	voice_square_2_alt 0, 0, 4, 4, 0	@08ACE238
mAlignWord
	voice_square_2_alt 1, 0, 3, 0, 0	@08ACE244
mAlignWord
	voice_square_2_alt 1, 0, 2, 0, 0	@08ACE250
mAlignWord
	voice_square_2_alt 3, 0, 1, 0, 1	@08ACE25C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08ACE268
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08ACE274
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08ACE280
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08ACE28C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_1, 255, 0, 255, 0	@08ACE298
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_2, 255, 0, 255, 0	@08ACE2A4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_3, 255, 0, 255, 0	@08ACE2B0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_4, 255, 0, 255, 0	@08ACE2BC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08ACE2C8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_6, 255, 0, 255, 127	@08ACE2D4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_7, 255, 0, 255, 0	@08ACE2E0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_8, 255, 235, 38, 165	@08ACE2EC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_9, 255, 0, 255, 127	@08ACE2F8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_10, 255, 0, 255, 0	@08ACE304
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08ACE310
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_12, 255, 0, 255, 127	@08ACE31C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_13, 255, 0, 255, 127	@08ACE328
mAlignWord
	voice_keysplit voicegroup002, KeySplitTable1	@08ACE334
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_14, 255, 246, 64, 149	@08ACE340
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_15, 255, 0, 255, 127	@08ACE34C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_16, 255, 0, 255, 127	@08ACE358
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_17, 255, 0, 255, 127	@08ACE364
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_18, 255, 0, 255, 127	@08ACE370
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08ACE37C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_19, 255, 0, 255, 127	@08ACE388
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_20, 255, 231, 0, 188	@08ACE394
