	mAlignWord
	.global voicegroup007
voicegroup007:	@ 0x08ACF510
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@08ACF510
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08ACF51C
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08ACF528
mAlignWord
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@08ACF534
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@08ACF540
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF54C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF558
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF564
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF570
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF57C
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@08ACF588
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08ACF594
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACF5A0
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@08ACF5AC
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACF5B8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF5C4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF5D0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF5DC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF5E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF5F4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF600
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF60C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF618
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF624
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF630
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF63C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF648
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF654
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF660
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF66C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF678
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF684
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF690
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF69C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF6A8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF6B4
mAlignWord
	voice_square_1_alt 0, 1, 1, 0, 15, 0	@08ACF6C0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF6CC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF6D8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF6E4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 4, 4, 0	@08ACF6F0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_3, 0, 0, 15, 0	@08ACF6FC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_4, 0, 0, 15, 0	@08ACF708
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_5, 0, 0, 15, 0	@08ACF714
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08ACF720
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08ACF72C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08ACF738
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08ACF744
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08ACF750
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF75C
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF768
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACF774
mAlignWord
	voice_square_1_alt 0, 2, 0, 3, 0, 0	@08ACF780
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08ACF78C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08ACF798
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08ACF7A4
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 5	@08ACF7B0
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@08ACF7BC
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACF7C8
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACF7D4
mAlignWord
	voice_square_1_alt 0, 0, 0, 4, 0, 0	@08ACF7E0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 4, 0, 0	@08ACF7EC
mAlignWord
	voice_square_2_alt 0, 0, 4, 4, 0	@08ACF7F8
mAlignWord
	voice_square_1_alt 0, 1, 0, 3, 0, 0	@08ACF804
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@08ACF810
mAlignWord
	voice_square_1_alt 0, 3, 0, 1, 0, 1	@08ACF81C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08ACF828
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08ACF834
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08ACF840
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08ACF84C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_1, 255, 0, 255, 0	@08ACF858
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_2, 255, 0, 255, 0	@08ACF864
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_3, 255, 0, 255, 0	@08ACF870
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_4, 255, 0, 255, 0	@08ACF87C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08ACF888
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_6, 255, 0, 255, 127	@08ACF894
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_7, 255, 0, 255, 0	@08ACF8A0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_8, 255, 235, 38, 165	@08ACF8AC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_9, 255, 0, 255, 127	@08ACF8B8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_10, 255, 0, 255, 0	@08ACF8C4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08ACF8D0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_12, 255, 0, 255, 127	@08ACF8DC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_13, 255, 0, 255, 127	@08ACF8E8
mAlignWord
	voice_keysplit voicegroup002, KeySplitTable1	@08ACF8F4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_14, 255, 246, 64, 149	@08ACF900
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_15, 255, 0, 255, 127	@08ACF90C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_16, 255, 0, 255, 127	@08ACF918
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_17, 255, 0, 255, 127	@08ACF924
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_18, 255, 0, 255, 127	@08ACF930
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08ACF93C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_19, 255, 0, 255, 127	@08ACF948
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_20, 255, 231, 0, 188	@08ACF954
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_21, 255, 0, 255, 0	@08ACF960
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_22, 255, 0, 255, 149	@08ACF96C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_23, 255, 235, 25, 165	@08ACF978
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_24, 255, 0, 255, 149	@08ACF984
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_25, 255, 0, 255, 0	@08ACF990
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_26, 37, 0, 255, 165	@08ACF99C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_26, 255, 0, 255, 165	@08ACF9A8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_27, 255, 252, 0, 149	@08ACF9B4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF9C0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF9CC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF9D8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF9E4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF9F0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF9FC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA08
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA14
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA20
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA2C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA38
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA44
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA50
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA5C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA68
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA74
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_28, 255, 0, 255, 0	@08ACFA80
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_29, 255, 250, 18, 250	@08ACFA8C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_30, 255, 216, 25, 0	@08ACFA98
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_31, 37, 0, 255, 149	@08ACFAA4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_32, 255, 0, 255, 0	@08ACFAB0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_33, 255, 0, 255, 0	@08ACFABC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_34, 255, 0, 255, 149	@08ACFAC8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 5, 1, 0	@08ACFAD4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_35, 255, 216, 25, 0	@08ACFAE0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 4, 4, 0	@08ACFAEC
mAlignWord
	voice_keysplit_all voicegroup004	@08ACFAF8
mAlignWord
	voice_keysplit_all voicegroup001	@08ACFB04
