	mAlignWord
	.global voicegroup021
voicegroup021:	@ 0x08AD36BC
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08AD36BC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08AD36C8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD36D4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08AD36E0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_17, 255, 0, 255, 127	@08AD36EC
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08AD36F8
mAlignWord
	voice_square_1_alt 0, 3, 0, 6, 1, 0	@08AD3704
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_94, 255, 0, 255, 127	@08AD3710
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_95, 255, 0, 255, 0	@08AD371C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_96, 255, 0, 255, 0	@08AD3728
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_97, 255, 235, 25, 165	@08AD3734
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 4, 3, 0	@08AD3740
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_24, 255, 0, 255, 149	@08AD374C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3758
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3764
mAlignWord
	voice_noise_alt 60, 0, 0, 0, 2, 6, 1, 0	@08AD3770
mAlignWord
	voice_noise_alt 60, 0, 0, 1, 0, 0, 15, 0	@08AD377C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3788
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3794
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD37A0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD37AC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD37B8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD37C4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD37D0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD37DC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD37E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD37F4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3800
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD380C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3818
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3824
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3830
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD383C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3848
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3854
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3860
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD386C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3878
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3884
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3890
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD389C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD38A8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD38B4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD38C0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD38CC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD38D8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD38E4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD38F0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD38FC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3908
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3914
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3920
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD392C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3938
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3944
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3950
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD395C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3968
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3974
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3980
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD398C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3998
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD39A4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD39B0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD39BC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD39C8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD39D4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD39E0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD39EC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD39F8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3A04
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3A10
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3A1C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3A28
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3A34
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3A40
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3A4C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3A58
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3A64
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3A70
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3A7C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3A88
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3A94
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3AA0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3AAC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3AB8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3AC4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3AD0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3ADC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3AE8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3AF4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3B00
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3B0C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3B18
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3B24
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3B30
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3B3C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3B48
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3B54
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3B60
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3B6C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3B78
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3B84
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3B90
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3B9C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3BA8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3BB4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3BC0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3BCC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3BD8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3BE4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3BF0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3BFC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3C08
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3C14
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3C20
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3C2C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3C38
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3C44
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3C50
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3C5C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3C68
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3C74
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3C80
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3C8C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3C98
mAlignWord
	voice_keysplit_all voicegroup004	@08AD3CA4
mAlignWord
	voice_keysplit_all voicegroup012	@08AD3CB0
