	mAlignWord
	.global voicegroup008
voicegroup008:	@ 0x08ACFB10
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@08ACFB10
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08ACFB1C
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08ACFB28
mAlignWord
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@08ACFB34
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@08ACFB40
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFB4C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFB58
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFB64
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFB70
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFB7C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFB88
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08ACFB94
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_13, 255, 0, 255, 127	@08ACFBA0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08ACFBAC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFBB8
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08ACFBC4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_7, 255, 0, 255, 0	@08ACFBD0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08ACFBDC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFBE8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_78, 255, 0, 255, 0	@08ACFBF4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_79, 255, 0, 255, 0	@08ACFC00
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACFC0C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_22, 255, 0, 255, 149	@08ACFC18
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 7, 0	@08ACFC24
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08ACFC30
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_80, 255, 0, 255, 0	@08ACFC3C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFC48
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08ACFC54
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_6, 255, 0, 255, 127	@08ACFC60
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08ACFC6C
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACFC78
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 7, 0	@08ACFC84
mAlignWord
	voice_square_1_alt 0, 2, 0, 3, 4, 0	@08ACFC90
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFC9C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFCA8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFCB4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFCC0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFCCC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFCD8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFCE4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFCF0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFCFC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFD08
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFD14
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFD20
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFD2C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFD38
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFD44
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFD50
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFD5C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFD68
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFD74
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFD80
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFD8C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFD98
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFDA4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFDB0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFDBC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFDC8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFDD4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFDE0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFDEC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFDF8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFE04
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFE10
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFE1C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFE28
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFE34
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFE40
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFE4C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFE58
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFE64
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFE70
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFE7C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFE88
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFE94
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFEA0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFEAC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFEB8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFEC4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFED0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFEDC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFEE8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFEF4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFF00
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFF0C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFF18
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFF24
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFF30
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFF3C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFF48
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFF54
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFF60
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFF6C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFF78
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFF84
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFF90
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFF9C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFFA8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFFB4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFFC0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFFCC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFFD8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFFE4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFFF0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFFFC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0008
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0014
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0020
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD002C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0038
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0044
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0050
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD005C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0068
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0074
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0080
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD008C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0098
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD00A4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD00B0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD00BC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD00C8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD00D4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD00E0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD00EC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD00F8
mAlignWord
	voice_keysplit_all voicegroup012	@08AD0104
