	mAlignWord
	.global voicegroup017
voicegroup017:	@ 0x08AD2558
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2558
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2564
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2570
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD257C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2588
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2594
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD25A0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_169, 255, 0, 255, 0	@08AD25AC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_170, 255, 0, 255, 0	@08AD25B8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_171, 255, 0, 255, 0	@08AD25C4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_172, 255, 0, 255, 0	@08AD25D0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_173, 255, 0, 255, 0	@08AD25DC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_174, 255, 0, 255, 0	@08AD25E8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_175, 255, 0, 255, 0	@08AD25F4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_176, 255, 0, 255, 0	@08AD2600
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_177, 255, 0, 255, 0	@08AD260C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_178, 255, 0, 255, 0	@08AD2618
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_179, 255, 0, 255, 0	@08AD2624
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_180, 255, 0, 255, 0	@08AD2630
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_181, 255, 0, 255, 0	@08AD263C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_182, 255, 0, 255, 0	@08AD2648
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_183, 255, 0, 255, 0	@08AD2654
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_184, 255, 0, 255, 0	@08AD2660
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_185, 255, 0, 255, 0	@08AD266C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_186, 255, 0, 255, 0	@08AD2678
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_187, 255, 0, 255, 0	@08AD2684
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_188, 255, 0, 255, 0	@08AD2690
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_189, 255, 0, 255, 0	@08AD269C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_190, 255, 0, 255, 0	@08AD26A8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_191, 255, 0, 255, 0	@08AD26B4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_192, 255, 0, 255, 0	@08AD26C0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_193, 255, 0, 255, 0	@08AD26CC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_194, 255, 0, 255, 0	@08AD26D8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_195, 255, 0, 255, 0	@08AD26E4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_196, 255, 0, 255, 0	@08AD26F0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_197, 255, 0, 255, 0	@08AD26FC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_198, 255, 0, 255, 0	@08AD2708
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_199, 255, 0, 255, 0	@08AD2714
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_200, 255, 0, 255, 0	@08AD2720
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_201, 255, 0, 255, 0	@08AD272C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_202, 255, 0, 255, 0	@08AD2738
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_203, 255, 0, 255, 0	@08AD2744
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_204, 255, 0, 255, 0	@08AD2750
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_205, 255, 0, 255, 0	@08AD275C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_206, 255, 0, 255, 0	@08AD2768
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_207, 255, 0, 255, 0	@08AD2774
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_208, 255, 0, 255, 0	@08AD2780
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_209, 255, 0, 255, 0	@08AD278C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_210, 255, 0, 255, 0	@08AD2798
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_211, 255, 0, 255, 0	@08AD27A4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_212, 255, 0, 255, 0	@08AD27B0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_213, 255, 0, 255, 0	@08AD27BC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD27C8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD27D4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD27E0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD27EC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD27F8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2804
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2810
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD281C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2828
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2834
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2840
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_214, 255, 0, 255, 0	@08AD284C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_215, 255, 0, 255, 0	@08AD2858
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_216, 255, 0, 255, 0	@08AD2864
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_217, 255, 0, 255, 0	@08AD2870
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_218, 255, 0, 255, 0	@08AD287C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_219, 255, 0, 255, 0	@08AD2888
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_220, 255, 0, 255, 0	@08AD2894
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_221, 255, 0, 255, 0	@08AD28A0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_222, 255, 0, 255, 0	@08AD28AC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_223, 255, 0, 255, 0	@08AD28B8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_224, 255, 0, 255, 0	@08AD28C4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_225, 255, 0, 255, 0	@08AD28D0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_226, 255, 0, 255, 0	@08AD28DC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_227, 255, 0, 255, 0	@08AD28E8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_228, 255, 0, 255, 0	@08AD28F4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_229, 255, 0, 255, 0	@08AD2900
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_230, 255, 0, 255, 0	@08AD290C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_231, 255, 0, 255, 0	@08AD2918
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_232, 255, 0, 255, 0	@08AD2924
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_233, 255, 0, 255, 0	@08AD2930
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_234, 255, 0, 255, 0	@08AD293C
