	mAlignWord
	.global voicegroup012
voicegroup012:	@ 0x08AD1160
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1160
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD116C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1178
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1184
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1190
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD119C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD11A8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD11B4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD11C0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD11CC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD11D8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD11E4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD11F0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD11FC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1208
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1214
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1220
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD122C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1238
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1244
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1250
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD125C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1268
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1274
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1280
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD128C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1298
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD12A4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD12B0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD12BC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD12C8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD12D4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD12E0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD12EC
mAlignWord
	voice_keysplit_all voicegroup004	@08AD12F8
mAlignWord
	voice_keysplit_all voicegroup012	@08AD1304
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_36, 255, 255, 255, 0	@08AD1310
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_37, 255, 0, 255, 0	@08AD131C
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 1, 0, 0	@08AD1328
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 2, 0, 0	@08AD1334
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 3, 7, 0	@08AD1340
mAlignWord
	voice_directsound 45, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08AD134C
mAlignWord
	voice_directsound 50, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08AD1358
mAlignWord
	voice_directsound 55, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08AD1364
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08AD1370
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08AD137C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_39, 255, 0, 255, 0	@08AD1388
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_40, 255, 0, 255, 0	@08AD1394
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_41, 255, 0, 255, 0	@08AD13A0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08AD13AC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_43, 255, 0, 255, 0	@08AD13B8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_44, 255, 0, 255, 0	@08AD13C4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_45, 255, 0, 255, 0	@08AD13D0
mAlignWord
	voice_directsound 57, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08AD13DC
mAlignWord
	voice_directsound 59, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08AD13E8
mAlignWord
	voice_directsound 61, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08AD13F4
mAlignWord
	voice_directsound 45, 0, DirectSoundWaveData_46, 255, 0, 255, 0	@08AD1400
mAlignWord
	voice_directsound 50, 0, DirectSoundWaveData_46, 255, 0, 255, 0	@08AD140C
mAlignWord
	voice_directsound 55, 0, DirectSoundWaveData_46, 255, 0, 255, 0	@08AD1418
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_46, 255, 0, 255, 0	@08AD1424
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_46, 255, 0, 255, 0	@08AD1430
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD143C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1448
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1454
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1460
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD146C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1478
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1484
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1490
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD149C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD14A8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD14B4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD14C0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD14CC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD14D8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD14E4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD14F0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD14FC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1508
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1514
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1520
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD152C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_47, 255, 0, 255, 0	@08AD1538
