	mAlignWord
	.global voicegroup014
voicegroup014:	@ 0x08AD1B44
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@08AD1B44
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08AD1B50
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD1B5C
mAlignWord
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@08AD1B68
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@08AD1B74
mAlignWord
	voice_noise_alt 60, 0, 0, 0, 0, 0, 15, 0	@08AD1B80
mAlignWord
	voice_noise_alt 60, 0, 0, 1, 0, 0, 15, 0	@08AD1B8C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1B98
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1BA4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1BB0
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@08AD1BBC
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08AD1BC8
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD1BD4
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@08AD1BE0
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08AD1BEC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1BF8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C04
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C10
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C1C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C28
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C34
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C40
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C4C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C58
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C64
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C70
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C7C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C88
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C94
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1CA0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1CAC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1CB8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1CC4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1CD0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1CDC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1CE8
mAlignWord
	voice_square_1_alt 0, 1, 1, 0, 15, 0	@08AD1CF4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1D00
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1D0C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1D18
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 4, 4, 0	@08AD1D24
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_3, 0, 0, 15, 0	@08AD1D30
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_4, 0, 0, 15, 0	@08AD1D3C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_5, 0, 0, 15, 0	@08AD1D48
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08AD1D54
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08AD1D60
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD1D6C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08AD1D78
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08AD1D84
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 4, 3, 0	@08AD1D90
mAlignWord
	voice_square_1_alt 0, 3, 0, 6, 1, 0	@08AD1D9C
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 2	@08AD1DA8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 2, 0, 15, 2	@08AD1DB4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_3, 0, 4, 3, 0	@08AD1DC0
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 0	@08AD1DCC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 3, 6, 4, 2	@08AD1DD8
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 1, 0	@08AD1DE4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1DF0
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 0	@08AD1DFC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_101, 255, 0, 255, 127	@08AD1E08
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_102, 255, 0, 255, 127	@08AD1E14
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_103, 255, 0, 255, 127	@08AD1E20
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_104, 255, 0, 255, 127	@08AD1E2C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD1E38
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_9, 255, 0, 255, 127	@08AD1E44
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_105, 255, 249, 0, 127	@08AD1E50
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_95, 255, 0, 255, 127	@08AD1E5C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_96, 255, 0, 255, 127	@08AD1E68
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_106, 255, 0, 255, 127	@08AD1E74
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_105, 26, 0, 255, 188	@08AD1E80
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_107, 255, 235, 128, 127	@08AD1E8C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_108, 255, 249, 51, 127	@08AD1E98
mAlignWord
	voice_square_1_alt 0, 3, 0, 6, 6, 0	@08AD1EA4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_109, 26, 0, 255, 188	@08AD1EB0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 3, 3, 0	@08AD1EBC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 4, 7, 0	@08AD1EC8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_110, 255, 0, 255, 0	@08AD1ED4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_111, 255, 249, 25, 0	@08AD1EE0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_112, 255, 249, 25, 127	@08AD1EEC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_94, 255, 0, 255, 127	@08AD1EF8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1F04
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1F10
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_13, 255, 0, 255, 127	@08AD1F1C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1F28
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_14, 255, 246, 64, 149	@08AD1F34
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1F40
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1F4C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_17, 255, 0, 255, 127	@08AD1F58
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_113, 255, 0, 255, 127	@08AD1F64
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08AD1F70
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_19, 255, 0, 255, 127	@08AD1F7C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_20, 255, 231, 0, 188	@08AD1F88
