	mAlignWord
	.global voicegroup018
voicegroup018:	@ 0x08AD2948
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_235, 255, 0, 255, 0	@08AD2948
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_236, 255, 0, 255, 0	@08AD2954
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_237, 255, 0, 255, 0	@08AD2960
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_238, 255, 0, 255, 0	@08AD296C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_239, 255, 0, 255, 0	@08AD2978
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_240, 255, 0, 255, 0	@08AD2984
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_241, 255, 0, 255, 0	@08AD2990
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_242, 255, 0, 255, 0	@08AD299C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_243, 255, 0, 255, 0	@08AD29A8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_244, 255, 0, 255, 0	@08AD29B4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_245, 255, 0, 255, 0	@08AD29C0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_246, 255, 0, 255, 0	@08AD29CC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_247, 255, 0, 255, 0	@08AD29D8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_248, 255, 0, 255, 0	@08AD29E4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_249, 255, 0, 255, 0	@08AD29F0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_250, 255, 0, 255, 0	@08AD29FC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_251, 255, 0, 255, 0	@08AD2A08
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_252, 255, 0, 255, 0	@08AD2A14
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_253, 255, 0, 255, 0	@08AD2A20
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_254, 255, 0, 255, 0	@08AD2A2C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_255, 255, 0, 255, 0	@08AD2A38
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_256, 255, 0, 255, 0	@08AD2A44
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_257, 255, 0, 255, 0	@08AD2A50
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_258, 255, 0, 255, 0	@08AD2A5C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_259, 255, 0, 255, 0	@08AD2A68
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_260, 255, 0, 255, 0	@08AD2A74
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_261, 255, 0, 255, 0	@08AD2A80
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_262, 255, 0, 255, 0	@08AD2A8C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_263, 255, 0, 255, 0	@08AD2A98
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_264, 255, 0, 255, 0	@08AD2AA4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_265, 255, 0, 255, 0	@08AD2AB0
