	mAlignWord
	.global voicegroup009
voicegroup009:	@ 0x08AD0110
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@08AD0110
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08AD011C
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD0128
mAlignWord
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@08AD0134
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@08AD0140
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD014C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0158
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0164
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0170
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD017C
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@08AD0188
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08AD0194
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD01A0
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@08AD01AC
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08AD01B8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD01C4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD01D0
mAlignWord
	voice_square_2_alt 0, 0, 3, 0, 2	@08AD01DC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 4, 0	@08AD01E8
mAlignWord
	voice_square_2_alt 2, 0, 2, 2, 0	@08AD01F4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_22, 255, 0, 255, 149	@08AD0200
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_81, 255, 0, 255, 149	@08AD020C
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD0218
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 7, 0	@08AD0224
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD0230
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 9, 6	@08AD023C
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD0248
mAlignWord
	voice_square_2_alt 2, 0, 4, 0, 6	@08AD0254
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD0260
mAlignWord
	voice_square_2_alt 2, 0, 4, 13, 6	@08AD026C
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@08AD0278
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08AD0284
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD0290
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 4	@08AD029C
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD02A8
mAlignWord
	voice_square_1_alt 0, 1, 0, 6, 0, 6	@08AD02B4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 2, 0, 15, 0	@08AD02C0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 2	@08AD02CC
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD02D8
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD02E4
mAlignWord
	voice_square_1_alt 0, 1, 0, 6, 0, 6	@08AD02F0
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 6	@08AD02FC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD0308
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD0314
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD0320
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD032C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 4	@08AD0338
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 6	@08AD0344
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 6, 0, 6	@08AD0350
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD035C
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08AD0368
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 4	@08AD0374
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD0380
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD038C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 3	@08AD0398
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD03A4
mAlignWord
	voice_square_1_alt 0, 1, 2, 0, 10, 3	@08AD03B0
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@08AD03BC
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08AD03C8
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08AD03D4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_78, 255, 0, 255, 0	@08AD03E0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_79, 255, 0, 255, 0	@08AD03EC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_82, 255, 0, 255, 0	@08AD03F8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_83, 255, 0, 255, 0	@08AD0404
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_80, 255, 0, 255, 0	@08AD0410
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_78, 255, 0, 255, 0	@08AD041C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_79, 255, 0, 255, 0	@08AD0428
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_82, 255, 250, 18, 250	@08AD0434
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_83, 255, 250, 18, 250	@08AD0440
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_80, 255, 250, 18, 250	@08AD044C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_1, 255, 0, 255, 0	@08AD0458
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_2, 255, 0, 255, 0	@08AD0464
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_3, 255, 0, 255, 0	@08AD0470
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_4, 255, 0, 255, 0	@08AD047C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD0488
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_6, 255, 0, 255, 127	@08AD0494
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_7, 255, 0, 255, 0	@08AD04A0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_8, 255, 235, 38, 165	@08AD04AC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_9, 255, 0, 255, 127	@08AD04B8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_10, 255, 0, 255, 0	@08AD04C4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08AD04D0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_12, 255, 0, 255, 127	@08AD04DC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_13, 255, 0, 255, 127	@08AD04E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD04F4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0500
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD050C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0518
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 1	@08AD0524
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0530
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD053C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_19, 255, 0, 255, 0	@08AD0548
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_20, 255, 0, 255, 0	@08AD0554
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_21, 255, 0, 255, 0	@08AD0560
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD056C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0578
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0584
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0590
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD059C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD05A8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD05B4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD05C0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD05CC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD05D8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD05E4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD05F0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD05FC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0608
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_84, 255, 0, 255, 0	@08AD0614
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_85, 255, 0, 255, 0	@08AD0620
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_86, 255, 0, 255, 0	@08AD062C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_87, 255, 0, 255, 0	@08AD0638
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_88, 255, 0, 255, 0	@08AD0644
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_89, 255, 0, 255, 0	@08AD0650
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_90, 255, 0, 255, 0	@08AD065C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_91, 255, 0, 255, 0	@08AD0668
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_92, 255, 0, 255, 0	@08AD0674
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_60, 255, 0, 255, 0	@08AD0680
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_61, 255, 0, 255, 0	@08AD068C
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08AD0698
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 2	@08AD06A4
mAlignWord
	voice_noise 60, 0, 0, 1, 1, 0, 12, 2	@08AD06B0
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@08AD06BC
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 2	@08AD06C8
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08AD06D4
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 2	@08AD06E0
mAlignWord
	voice_square_1_alt 0, 2, 3, 0, 10, 3	@08AD06EC
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@08AD06F8
mAlignWord
	voice_keysplit_all voicegroup012	@08AD0704
