	mAlignWord
	.global voicegroup007
voicegroup007:	@ 0x08ACF510
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@08ACF510
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08ACF51C
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08ACF528
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@08ACF534
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@08ACF540
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF54C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF558
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF564
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF570
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF57C
	voice_square_2_alt 0, 0, 0, 15, 0	@08ACF588
	voice_square_2_alt 1, 0, 0, 15, 0	@08ACF594
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACF5A0
	voice_square_2_alt 3, 0, 0, 15, 0	@08ACF5AC
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACF5B8
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF5C4
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF5D0
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF5DC
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF5E8
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF5F4
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF600
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF60C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF618
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF624
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF630
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF63C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF648
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF654
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF660
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF66C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF678
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF684
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF690
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF69C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF6A8
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF6B4
	voice_square_1_alt 0, 1, 1, 0, 15, 0	@08ACF6C0
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF6CC
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF6D8
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF6E4
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 4, 4, 0	@08ACF6F0
	voice_programmable_wave_alt ProgrammableWaveData_3, 0, 0, 15, 0	@08ACF6FC
	voice_programmable_wave_alt ProgrammableWaveData_4, 0, 0, 15, 0	@08ACF708
	voice_programmable_wave_alt ProgrammableWaveData_5, 0, 0, 15, 0	@08ACF714
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08ACF720
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08ACF72C
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08ACF738
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08ACF744
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08ACF750
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF75C
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF768
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACF774
	voice_square_1_alt 0, 2, 0, 3, 0, 0	@08ACF780
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08ACF78C
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08ACF798
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08ACF7A4
	voice_square_1_alt 0, 0, 0, 0, 15, 5	@08ACF7B0
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@08ACF7BC
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACF7C8
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACF7D4
	voice_square_1_alt 0, 0, 0, 4, 0, 0	@08ACF7E0
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 4, 0, 0	@08ACF7EC
	voice_square_2_alt 0, 0, 4, 4, 0	@08ACF7F8
	voice_square_1_alt 0, 1, 0, 3, 0, 0	@08ACF804
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@08ACF810
	voice_square_1_alt 0, 3, 0, 1, 0, 1	@08ACF81C
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08ACF828
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08ACF834
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08ACF840
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08ACF84C
	voice_directsound 60, 0, DirectSoundWaveData_1, 255, 0, 255, 0	@08ACF858
	voice_directsound 60, 0, DirectSoundWaveData_2, 255, 0, 255, 0	@08ACF864
	voice_directsound 60, 0, DirectSoundWaveData_3, 255, 0, 255, 0	@08ACF870
	voice_directsound 60, 0, DirectSoundWaveData_4, 255, 0, 255, 0	@08ACF87C
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08ACF888
	voice_directsound 60, 0, DirectSoundWaveData_6, 255, 0, 255, 127	@08ACF894
	voice_directsound 60, 0, DirectSoundWaveData_7, 255, 0, 255, 0	@08ACF8A0
	voice_directsound 60, 0, DirectSoundWaveData_8, 255, 235, 38, 165	@08ACF8AC
	voice_directsound 60, 0, DirectSoundWaveData_9, 255, 0, 255, 127	@08ACF8B8
	voice_directsound 60, 0, DirectSoundWaveData_10, 255, 0, 255, 0	@08ACF8C4
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08ACF8D0
	voice_directsound 60, 0, DirectSoundWaveData_12, 255, 0, 255, 127	@08ACF8DC
	voice_directsound 60, 0, DirectSoundWaveData_13, 255, 0, 255, 127	@08ACF8E8
	voice_keysplit voicegroup002, KeySplitTable1	@08ACF8F4
	voice_directsound 60, 0, DirectSoundWaveData_14, 255, 246, 64, 149	@08ACF900
	voice_directsound 60, 0, DirectSoundWaveData_15, 255, 0, 255, 127	@08ACF90C
	voice_directsound 60, 0, DirectSoundWaveData_16, 255, 0, 255, 127	@08ACF918
	voice_directsound 60, 0, DirectSoundWaveData_17, 255, 0, 255, 127	@08ACF924
	voice_directsound 60, 0, DirectSoundWaveData_18, 255, 0, 255, 127	@08ACF930
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08ACF93C
	voice_directsound 60, 0, DirectSoundWaveData_19, 255, 0, 255, 127	@08ACF948
	voice_directsound 60, 0, DirectSoundWaveData_20, 255, 231, 0, 188	@08ACF954
	voice_directsound 60, 0, DirectSoundWaveData_21, 255, 0, 255, 0	@08ACF960
	voice_directsound 60, 0, DirectSoundWaveData_22, 255, 0, 255, 149	@08ACF96C
	voice_directsound 60, 0, DirectSoundWaveData_23, 255, 235, 25, 165	@08ACF978
	voice_directsound 60, 0, DirectSoundWaveData_24, 255, 0, 255, 149	@08ACF984
	voice_directsound 60, 0, DirectSoundWaveData_25, 255, 0, 255, 0	@08ACF990
	voice_directsound 60, 0, DirectSoundWaveData_26, 37, 0, 255, 165	@08ACF99C
	voice_directsound 60, 0, DirectSoundWaveData_26, 255, 0, 255, 165	@08ACF9A8
	voice_directsound 60, 0, DirectSoundWaveData_27, 255, 252, 0, 149	@08ACF9B4
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF9C0
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF9CC
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF9D8
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF9E4
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF9F0
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF9FC
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA08
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA14
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA20
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA2C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA38
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA44
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA50
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA5C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA68
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACFA74
	voice_directsound 60, 0, DirectSoundWaveData_28, 255, 0, 255, 0	@08ACFA80
	voice_directsound 60, 0, DirectSoundWaveData_29, 255, 250, 18, 250	@08ACFA8C
	voice_directsound 60, 0, DirectSoundWaveData_30, 255, 216, 25, 0	@08ACFA98
	voice_directsound 60, 0, DirectSoundWaveData_31, 37, 0, 255, 149	@08ACFAA4
	voice_directsound 60, 0, DirectSoundWaveData_32, 255, 0, 255, 0	@08ACFAB0
	voice_directsound 60, 0, DirectSoundWaveData_33, 255, 0, 255, 0	@08ACFABC
	voice_directsound 60, 0, DirectSoundWaveData_34, 255, 0, 255, 149	@08ACFAC8
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 5, 1, 0	@08ACFAD4
	voice_directsound 60, 0, DirectSoundWaveData_35, 255, 216, 25, 0	@08ACFAE0
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 4, 4, 0	@08ACFAEC
	voice_keysplit_all voicegroup004	@08ACFAF8
	voice_keysplit_all voicegroup001	@08ACFB04
