	.align 2
	.global voicegroup010
voicegroup010:	@ 0x08AD0710
	voice_square_1_alt 0, 2, 0, 3, 1, 3	@08AD0710
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD071C
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 3, 0	@08AD0728
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD0734
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD0740
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 4, 0	@08AD074C
	voice_square_2_alt 0, 0, 0, 15, 0	@08AD0758
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD0764
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD0770
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 7, 0	@08AD077C
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD0788
	voice_square_1_alt 0, 2, 0, 3, 4, 0	@08AD0794
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD07A0
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 7, 0	@08AD07AC
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 3, 0	@08AD07B8
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD07C4
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD07D0
	voice_square_2_alt 2, 0, 3, 1, 2	@08AD07DC
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD07E8
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 7, 0	@08AD07F4
	voice_directsound 60, 0, gUnknown_08AF6F80, 255, 0, 255, 149	@08AD0800
	voice_directsound 60, 0, gUnknown_08B91D70, 255, 0, 255, 149	@08AD080C
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD0818
	voice_square_2_alt 0, 0, 0, 15, 0	@08AD0824
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 3	@08AD0830
	voice_square_1_alt 0, 2, 2, 0, 9, 6	@08AD083C
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD0848
	voice_square_2_alt 2, 0, 4, 0, 6	@08AD0854
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD0860
	voice_square_2_alt 2, 0, 4, 13, 6	@08AD086C
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@08AD0878
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08AD0884
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD0890
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 4	@08AD089C
	voice_square_1_alt 0, 2, 0, 6, 0, 6	@08AD08A8
	voice_square_2_alt 1, 0, 6, 0, 6	@08AD08B4
	voice_programmable_wave_alt ProgrammableWaveData_8, 2, 0, 15, 0	@08AD08C0
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 2	@08AD08CC
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD08D8
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD08E4
	voice_square_1_alt 0, 1, 0, 6, 0, 6	@08AD08F0
	voice_square_1_alt 0, 2, 0, 6, 0, 6	@08AD08FC
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD0908
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD0914
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD0920
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD092C
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 4	@08AD0938
	voice_square_1_alt 0, 2, 0, 6, 0, 6	@08AD0944
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 6, 0, 6	@08AD0950
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD095C
	voice_square_2_alt 1, 0, 0, 15, 0	@08AD0968
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 4	@08AD0974
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD0980
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD098C
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 3	@08AD0998
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD09A4
	voice_square_1_alt 0, 1, 2, 0, 10, 3	@08AD09B0
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@08AD09BC
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08AD09C8
	voice_directsound 60, 0, gUnknown_08B9DB80, 255, 0, 128, 235	@08AD09D4
	voice_directsound 60, 0, gUnknown_08B80688, 255, 0, 255, 0	@08AD09E0
	voice_directsound 60, 0, gUnknown_08B84450, 255, 0, 255, 0	@08AD09EC
	voice_directsound 60, 0, gUnknown_08B940F0, 255, 0, 255, 0	@08AD09F8
	voice_directsound 60, 0, gUnknown_08B98840, 255, 0, 255, 0	@08AD0A04
	voice_directsound 60, 0, gUnknown_08B8A5F8, 255, 0, 255, 0	@08AD0A10
	voice_directsound 60, 0, gUnknown_08B80688, 255, 0, 255, 0	@08AD0A1C
	voice_directsound 60, 0, gUnknown_08B84450, 255, 0, 255, 0	@08AD0A28
	voice_directsound 60, 0, gUnknown_08B940F0, 255, 250, 18, 250	@08AD0A34
	voice_directsound 60, 0, gUnknown_08B98840, 255, 250, 18, 250	@08AD0A40
	voice_directsound 60, 0, gUnknown_08B8A5F8, 255, 250, 18, 250	@08AD0A4C
	voice_directsound 60, 0, gUnknown_08AD5F28, 255, 0, 255, 0	@08AD0A58
	voice_directsound 60, 0, gUnknown_08AD73FC, 255, 0, 255, 0	@08AD0A64
	voice_directsound 60, 0, gUnknown_08AD8810, 255, 0, 255, 0	@08AD0A70
	voice_directsound 60, 0, gUnknown_08AD9140, 255, 0, 255, 0	@08AD0A7C
	voice_directsound 60, 0, gUnknown_08AD98B0, 255, 0, 255, 127	@08AD0A88
	voice_directsound 60, 0, gUnknown_08ADB1A4, 255, 0, 255, 127	@08AD0A94
	voice_directsound 60, 0, gUnknown_08ADE2D0, 255, 0, 255, 0	@08AD0AA0
	voice_directsound 60, 0, gUnknown_08ADE918, 255, 235, 38, 165	@08AD0AAC
	voice_directsound 60, 0, gUnknown_08AE200C, 255, 0, 255, 127	@08AD0AB8
	voice_directsound 60, 0, gUnknown_08AE4FE8, 255, 0, 255, 0	@08AD0AC4
	voice_directsound 60, 0, gUnknown_08AE7F2C, 255, 0, 255, 0	@08AD0AD0
	voice_directsound 60, 0, gUnknown_08AE98B4, 255, 0, 255, 127	@08AD0ADC
	voice_directsound 60, 0, gUnknown_08AE9BB4, 255, 0, 255, 127	@08AD0AE8
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 3	@08AD0AF4
	voice_square_2_alt 2, 0, 4, 10, 0	@08AD0B00
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD0B0C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0B18
	voice_noise 60, 0, 0, 1, 0, 0, 15, 1	@08AD0B24
	voice_square_1_alt 0, 2, 0, 6, 0, 2	@08AD0B30
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0B3C
	voice_directsound 60, 0, gUnknown_08AF39C8, 255, 0, 255, 0	@08AD0B48
	voice_directsound 60, 0, gUnknown_08AF5F44, 255, 0, 255, 0	@08AD0B54
	voice_directsound 60, 0, gUnknown_08AF65D8, 255, 0, 255, 0	@08AD0B60
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 7, 2	@08AD0B6C
	voice_square_1_alt 0, 2, 1, 0, 10, 2	@08AD0B78
	voice_square_2_alt 2, 0, 6, 0, 2	@08AD0B84
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 2, 9, 2	@08AD0B90
	voice_square_2_alt 2, 1, 0, 10, 3	@08AD0B9C
	voice_square_1_alt 0, 2, 0, 4, 10, 0	@08AD0BA8
	voice_square_2_alt 3, 1, 6, 0, 0	@08AD0BB4
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD0BC0
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@08AD0BCC
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 2, 9, 2	@08AD0BD8
	voice_programmable_wave_alt ProgrammableWaveData_8, 1, 2, 9, 2	@08AD0BE4
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD0BF0
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD0BFC
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@08AD0C08
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 2, 9, 2	@08AD0C14
	voice_square_2_alt 2, 0, 4, 0, 4	@08AD0C20
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@08AD0C2C
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD0C38
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@08AD0C44
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 2, 9, 2	@08AD0C50
	voice_square_2_alt 2, 1, 3, 3, 5	@08AD0C5C
	voice_square_1_alt 0, 2, 1, 3, 3, 5	@08AD0C68
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD0C74
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0C80
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0C8C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0C98
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0CA4
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@08AD0CB0
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 2, 9, 2	@08AD0CBC
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 7, 2	@08AD0CC8
	voice_square_2_alt 2, 0, 6, 0, 2	@08AD0CD4
	voice_square_1_alt 0, 2, 1, 0, 10, 2	@08AD0CE0
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD0CEC
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08AD0CF8
	voice_keysplit_all voicegroup012	@08AD0D04
	