	.align 2
	.global voicegroup022
voicegroup022:	@ 0x08AD3CBC
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@08AD3CBC
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08AD3CC8
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD3CD4
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@08AD3CE0
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@08AD3CEC
	voice_square_1_alt 0, 3, 2, 4, 1, 3	@08AD3CF8
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3D04
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3D10
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3D1C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3D28
	voice_square_2_alt 0, 0, 0, 15, 0	@08AD3D34
	voice_square_2_alt 1, 0, 0, 15, 0	@08AD3D40
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD3D4C
	voice_square_2_alt 3, 0, 0, 15, 0	@08AD3D58
	voice_square_2_alt 2, 2, 0, 15, 0	@08AD3D64
	voice_square_2_alt 1, 2, 4, 1, 3	@08AD3D70
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3D7C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3D88
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3D94
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DA0
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DAC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DB8
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DC4
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DD0
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DDC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DE8
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DF4
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E00
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E0C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E18
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E24
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E30
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E3C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E48
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E54
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E60
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E6C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E78
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E84
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E90
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 4, 4, 0	@08AD3E9C
	voice_programmable_wave_alt ProgrammableWaveData_3, 0, 0, 15, 0	@08AD3EA8
	voice_programmable_wave_alt ProgrammableWaveData_4, 0, 0, 15, 0	@08AD3EB4
	voice_programmable_wave_alt ProgrammableWaveData_5, 0, 0, 15, 0	@08AD3EC0
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08AD3ECC
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08AD3ED8
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD3EE4
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08AD3EF0
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08AD3EFC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3F08
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08AD3F14
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08AD3F20
	voice_square_1_alt 0, 2, 0, 3, 0, 0	@08AD3F2C
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08AD3F38
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08AD3F44
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08AD3F50
	voice_square_1_alt 0, 0, 0, 0, 15, 5	@08AD3F5C
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@08AD3F68
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08AD3F74
	voice_noise 60, 0, 0, 0, 0, 2, 0, 3	@08AD3F80
	voice_square_1_alt 0, 0, 0, 4, 0, 0	@08AD3F8C
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 4, 0, 0	@08AD3F98
	voice_square_2_alt 0, 0, 4, 4, 0	@08AD3FA4
	voice_square_1_alt 0, 1, 0, 3, 0, 0	@08AD3FB0
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@08AD3FBC
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08AD3FC8
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08AD3FD4
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08AD3FE0
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD3FEC
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 3, 7, 2	@08AD3FF8
	voice_directsound 60, 0, DirectSoundWaveData_1, 255, 0, 255, 0	@08AD4004
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4010
	voice_directsound 60, 0, DirectSoundWaveData_362, 255, 0, 255, 0	@08AD401C
	voice_directsound 60, 0, DirectSoundWaveData_363, 255, 0, 255, 0	@08AD4028
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD4034
	voice_directsound 60, 0, DirectSoundWaveData_6, 255, 0, 255, 127	@08AD4040
	voice_directsound 60, 0, DirectSoundWaveData_7, 255, 0, 255, 0	@08AD404C
	voice_directsound 60, 0, DirectSoundWaveData_8, 255, 235, 38, 165	@08AD4058
	voice_directsound 60, 0, DirectSoundWaveData_9, 255, 0, 255, 127	@08AD4064
	voice_directsound 60, 0, DirectSoundWaveData_10, 255, 0, 255, 0	@08AD4070
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08AD407C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4088
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4094
	voice_directsound 60, 0, DirectSoundWaveData_364, 255, 0, 255, 127	@08AD40A0
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD40AC
	voice_directsound 60, 0, DirectSoundWaveData_15, 255, 0, 255, 127	@08AD40B8
	voice_directsound 60, 0, DirectSoundWaveData_16, 255, 0, 255, 127	@08AD40C4
	voice_directsound 60, 0, DirectSoundWaveData_17, 255, 0, 255, 127	@08AD40D0
	voice_directsound 60, 0, DirectSoundWaveData_18, 255, 0, 255, 127	@08AD40DC
	voice_directsound 60, 0, DirectSoundWaveData_365, 255, 0, 255, 149	@08AD40E8
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD40F4
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4100
	voice_directsound 60, 0, DirectSoundWaveData_21, 255, 0, 255, 0	@08AD410C
	voice_directsound 60, 0, DirectSoundWaveData_22, 255, 0, 255, 149	@08AD4118
	voice_directsound 60, 0, DirectSoundWaveData_23, 255, 235, 25, 165	@08AD4124
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4130
	voice_directsound 60, 0, DirectSoundWaveData_25, 255, 0, 255, 0	@08AD413C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4148
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4154
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4160
	voice_directsound 60, 0, DirectSoundWaveData_355, 255, 0, 255, 0	@08AD416C
	voice_directsound 60, 0, DirectSoundWaveData_356, 255, 0, 255, 0	@08AD4178
	voice_directsound 60, 0, DirectSoundWaveData_357, 255, 0, 255, 0	@08AD4184
	voice_directsound 60, 0, DirectSoundWaveData_358, 255, 0, 255, 0	@08AD4190
	voice_directsound 60, 0, DirectSoundWaveData_359, 255, 0, 255, 0	@08AD419C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD41A8
	voice_directsound 60, 0, DirectSoundWaveData_361, 255, 0, 255, 0	@08AD41B4
	voice_directsound 60, 0, DirectSoundWaveData_366, 255, 0, 255, 0	@08AD41C0
	voice_directsound 60, 0, DirectSoundWaveData_367, 255, 0, 255, 0	@08AD41CC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD41D8
	voice_directsound 60, 0, DirectSoundWaveData_368, 255, 0, 255, 0	@08AD41E4
	voice_directsound 60, 0, DirectSoundWaveData_369, 255, 0, 255, 0	@08AD41F0
	voice_directsound 60, 0, DirectSoundWaveData_370, 255, 0, 255, 188	@08AD41FC
	voice_directsound 60, 0, DirectSoundWaveData_371, 255, 0, 255, 188	@08AD4208
	voice_directsound 60, 0, DirectSoundWaveData_372, 255, 0, 255, 188	@08AD4214
	voice_directsound 60, 0, DirectSoundWaveData_373, 255, 0, 255, 196	@08AD4220
	voice_directsound 60, 0, DirectSoundWaveData_374, 255, 0, 255, 0	@08AD422C
	voice_directsound 60, 0, DirectSoundWaveData_100, 255, 0, 255, 0	@08AD4238
	voice_directsound 60, 0, DirectSoundWaveData_375, 255, 0, 255, 0	@08AD4244
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4250
	voice_directsound 60, 0, DirectSoundWaveData_376, 255, 0, 255, 188	@08AD425C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4268
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4274
	voice_directsound 60, 0, DirectSoundWaveData_370, 255, 235, 25, 204	@08AD4280
	voice_directsound 60, 0, DirectSoundWaveData_371, 255, 235, 25, 204	@08AD428C
	voice_directsound 60, 0, DirectSoundWaveData_372, 255, 235, 25, 204	@08AD4298
	voice_directsound 60, 0, DirectSoundWaveData_374, 255, 235, 25, 204	@08AD42A4
	voice_keysplit_all voicegroup001	@08AD42B0
