	mAlignWord
	.global voicegroup000
voicegroup000:	@ 0x08ACDF50
	voice_square_2_alt 0, 0, 0, 15, 0	@08ACDF50
	voice_square_2_alt 1, 0, 0, 15, 0	@08ACDF5C
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACDF68
	voice_square_2_alt 3, 0, 0, 15, 0	@08ACDF74
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACDF80
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACDF8C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACDF98
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACDFA4
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACDFB0
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACDFBC
	voice_square_2_alt 0, 0, 0, 15, 0	@08ACDFC8
	voice_square_2_alt 1, 0, 0, 15, 0	@08ACDFD4
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACDFE0
	voice_square_2_alt 3, 0, 0, 15, 0	@08ACDFEC
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACDFF8
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE004
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE010
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE01C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE028
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE034
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE040
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE04C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE058
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE064
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE070
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE07C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE088
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE094
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0A0
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0AC
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0B8
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0C4
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0D0
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0DC
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0E8
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE0F4
	voice_square_2_alt 1, 1, 0, 15, 0	@08ACE100
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE10C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE118
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE124
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 4, 4, 0	@08ACE130
	voice_programmable_wave_alt ProgrammableWaveData_3, 0, 0, 15, 0	@08ACE13C
	voice_programmable_wave_alt ProgrammableWaveData_4, 0, 0, 15, 0	@08ACE148
	voice_programmable_wave_alt ProgrammableWaveData_5, 0, 0, 15, 0	@08ACE154
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08ACE160
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08ACE16C
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08ACE178
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08ACE184
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08ACE190
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE19C
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACE1A8
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACE1B4
	voice_square_2_alt 2, 0, 3, 0, 0	@08ACE1C0
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08ACE1CC
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08ACE1D8
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08ACE1E4
	voice_square_2_alt 0, 0, 0, 15, 5	@08ACE1F0
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@08ACE1FC
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACE208
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACE214
	voice_square_2_alt 0, 0, 4, 0, 0	@08ACE220
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 4, 0, 0	@08ACE22C
	voice_square_2_alt 0, 0, 4, 4, 0	@08ACE238
	voice_square_2_alt 1, 0, 3, 0, 0	@08ACE244
	voice_square_2_alt 1, 0, 2, 0, 0	@08ACE250
	voice_square_2_alt 3, 0, 1, 0, 1	@08ACE25C
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08ACE268
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08ACE274
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08ACE280
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08ACE28C
	voice_directsound 60, 0, DirectSoundWaveData_1, 255, 0, 255, 0	@08ACE298
	voice_directsound 60, 0, DirectSoundWaveData_2, 255, 0, 255, 0	@08ACE2A4
	voice_directsound 60, 0, DirectSoundWaveData_3, 255, 0, 255, 0	@08ACE2B0
	voice_directsound 60, 0, DirectSoundWaveData_4, 255, 0, 255, 0	@08ACE2BC
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08ACE2C8
	voice_directsound 60, 0, DirectSoundWaveData_6, 255, 0, 255, 127	@08ACE2D4
	voice_directsound 60, 0, DirectSoundWaveData_7, 255, 0, 255, 0	@08ACE2E0
	voice_directsound 60, 0, DirectSoundWaveData_8, 255, 235, 38, 165	@08ACE2EC
	voice_directsound 60, 0, DirectSoundWaveData_9, 255, 0, 255, 127	@08ACE2F8
	voice_directsound 60, 0, DirectSoundWaveData_10, 255, 0, 255, 0	@08ACE304
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08ACE310
	voice_directsound 60, 0, DirectSoundWaveData_12, 255, 0, 255, 127	@08ACE31C
	voice_directsound 60, 0, DirectSoundWaveData_13, 255, 0, 255, 127	@08ACE328
	voice_keysplit voicegroup002, KeySplitTable1	@08ACE334
	voice_directsound 60, 0, DirectSoundWaveData_14, 255, 246, 64, 149	@08ACE340
	voice_directsound 60, 0, DirectSoundWaveData_15, 255, 0, 255, 127	@08ACE34C
	voice_directsound 60, 0, DirectSoundWaveData_16, 255, 0, 255, 127	@08ACE358
	voice_directsound 60, 0, DirectSoundWaveData_17, 255, 0, 255, 127	@08ACE364
	voice_directsound 60, 0, DirectSoundWaveData_18, 255, 0, 255, 127	@08ACE370
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08ACE37C
	voice_directsound 60, 0, DirectSoundWaveData_19, 255, 0, 255, 127	@08ACE388
	voice_directsound 60, 0, DirectSoundWaveData_20, 255, 231, 0, 188	@08ACE394
