	mAlignWord
	.global voicegroup016
voicegroup016:	@ 0x08AD2108
mAlignWord
	voice_keysplit_all voicegroup019	@08AD2108
mAlignWord
	voice_keysplit_all voicegroup018	@08AD2114
mAlignWord
	voice_keysplit_all voicegroup017	@08AD2120
mAlignWord
	voice_keysplit_all voicegroup016	@08AD212C
mAlignWord
	voice_keysplit_all voicegroup015	@08AD2138
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_36, 255, 255, 255, 0	@08AD2144
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_37, 255, 0, 255, 0	@08AD2150
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 1, 0, 0	@08AD215C
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 2, 0, 0	@08AD2168
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 3, 7, 0	@08AD2174
mAlignWord
	voice_directsound 45, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08AD2180
mAlignWord
	voice_directsound 50, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08AD218C
mAlignWord
	voice_directsound 55, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08AD2198
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08AD21A4
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08AD21B0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_39, 255, 0, 255, 0	@08AD21BC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_40, 255, 0, 255, 0	@08AD21C8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_41, 255, 0, 255, 0	@08AD21D4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08AD21E0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_43, 255, 0, 255, 0	@08AD21EC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_44, 255, 0, 255, 0	@08AD21F8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_45, 255, 0, 255, 0	@08AD2204
mAlignWord
	voice_directsound 57, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08AD2210
mAlignWord
	voice_directsound 59, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08AD221C
mAlignWord
	voice_directsound 61, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08AD2228
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2234
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2240
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD224C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2258
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2264
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_123, 255, 0, 255, 0	@08AD2270
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_124, 255, 242, 51, 0	@08AD227C
mAlignWord
	voice_directsound 70, 0, DirectSoundWaveData_125, 255, 0, 255, 0	@08AD2288
mAlignWord
	voice_directsound 64, 0, DirectSoundWaveData_126, 255, 0, 255, 0	@08AD2294
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD22A0
mAlignWord
	voice_directsound 64, 0, DirectSoundWaveData_127, 255, 0, 255, 0	@08AD22AC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_128, 255, 0, 255, 0	@08AD22B8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_129, 255, 0, 255, 0	@08AD22C4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_130, 255, 0, 255, 0	@08AD22D0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_131, 255, 0, 255, 0	@08AD22DC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_132, 255, 0, 255, 0	@08AD22E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD22F4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2300
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD230C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_133, 255, 0, 255, 0	@08AD2318
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_134, 255, 0, 255, 0	@08AD2324
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_135, 255, 0, 255, 0	@08AD2330
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_136, 255, 0, 255, 0	@08AD233C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_137, 255, 0, 255, 0	@08AD2348
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_138, 255, 0, 255, 0	@08AD2354
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_139, 255, 0, 255, 0	@08AD2360
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_140, 255, 0, 255, 0	@08AD236C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_141, 255, 0, 255, 0	@08AD2378
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_142, 255, 0, 255, 0	@08AD2384
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_143, 255, 0, 255, 0	@08AD2390
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_144, 255, 0, 255, 0	@08AD239C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_145, 255, 0, 255, 0	@08AD23A8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_146, 255, 0, 255, 0	@08AD23B4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_147, 255, 0, 255, 0	@08AD23C0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_148, 255, 0, 255, 0	@08AD23CC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_149, 255, 0, 255, 0	@08AD23D8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_150, 255, 0, 255, 0	@08AD23E4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_151, 255, 0, 255, 0	@08AD23F0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_152, 255, 0, 255, 0	@08AD23FC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_153, 255, 0, 255, 0	@08AD2408
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2414
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2420
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD242C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_154, 255, 0, 255, 0	@08AD2438
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_155, 255, 0, 255, 0	@08AD2444
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_156, 255, 0, 255, 0	@08AD2450
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_157, 255, 0, 255, 0	@08AD245C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_158, 255, 0, 255, 0	@08AD2468
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_159, 255, 0, 255, 0	@08AD2474
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_160, 255, 0, 255, 0	@08AD2480
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_161, 255, 0, 255, 0	@08AD248C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_162, 255, 0, 255, 0	@08AD2498
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_163, 255, 0, 255, 0	@08AD24A4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_164, 255, 0, 255, 0	@08AD24B0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_165, 255, 0, 255, 0	@08AD24BC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_166, 255, 0, 255, 0	@08AD24C8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_167, 255, 0, 255, 0	@08AD24D4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_168, 255, 0, 255, 0	@08AD24E0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD24EC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD24F8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2504
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2510
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD251C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2528
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2534
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2540
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD254C
