	.align 2
	.global voicegroup001
voicegroup001:	@ 0x08ACE3A0
	voice_directsound 60, 0, DirectSoundWaveData_21, 255, 0, 255, 0	@08ACE3A0
	voice_directsound 60, 0, DirectSoundWaveData_22, 255, 0, 255, 149	@08ACE3AC
	voice_directsound 60, 0, DirectSoundWaveData_23, 255, 235, 25, 165	@08ACE3B8
	voice_directsound 60, 0, DirectSoundWaveData_24, 255, 0, 255, 149	@08ACE3C4
	voice_directsound 60, 0, DirectSoundWaveData_25, 255, 0, 255, 0	@08ACE3D0
	voice_directsound 60, 0, DirectSoundWaveData_26, 37, 0, 255, 165	@08ACE3DC
	voice_directsound 60, 0, DirectSoundWaveData_26, 255, 0, 255, 165	@08ACE3E8
	voice_directsound 60, 0, DirectSoundWaveData_27, 255, 252, 0, 149	@08ACE3F4
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE400
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE40C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE418
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE424
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE430
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE43C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE448
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE454
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE460
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE46C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE478
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE484
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE490
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE49C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE4A8
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE4B4
	voice_directsound 60, 0, DirectSoundWaveData_28, 255, 0, 255, 0	@08ACE4C0
	voice_directsound 60, 0, DirectSoundWaveData_29, 255, 250, 18, 250	@08ACE4CC
	voice_directsound 60, 0, DirectSoundWaveData_30, 255, 216, 25, 0	@08ACE4D8
	voice_directsound 60, 0, DirectSoundWaveData_31, 37, 0, 255, 149	@08ACE4E4
	voice_directsound 60, 0, DirectSoundWaveData_32, 255, 0, 255, 0	@08ACE4F0
	voice_directsound 60, 0, DirectSoundWaveData_33, 255, 0, 255, 0	@08ACE4FC
	voice_directsound 60, 0, DirectSoundWaveData_34, 255, 0, 255, 149	@08ACE508
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 5, 1, 0	@08ACE514
	voice_directsound 60, 0, DirectSoundWaveData_35, 255, 216, 25, 0	@08ACE520
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 4, 4, 0	@08ACE52C
	voice_keysplit_all voicegroup004	@08ACE538
	voice_keysplit_all voicegroup001	@08ACE544
