	mAlignWord
	.global voicegroup002
voicegroup002:	@ 0x08ACE550
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_36, 255, 255, 255, 0	@08ACE550
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_37, 255, 0, 255, 0	@08ACE55C
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 1, 0, 0	@08ACE568
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 2, 0, 0	@08ACE574
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 3, 7, 0	@08ACE580
mAlignWord
	voice_directsound 45, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08ACE58C
mAlignWord
	voice_directsound 50, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08ACE598
mAlignWord
	voice_directsound 55, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08ACE5A4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08ACE5B0
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08ACE5BC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_39, 255, 0, 255, 0	@08ACE5C8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_40, 255, 0, 255, 0	@08ACE5D4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_41, 255, 0, 255, 0	@08ACE5E0
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08ACE5EC
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_43, 255, 0, 255, 0	@08ACE5F8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_44, 255, 0, 255, 0	@08ACE604
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_45, 255, 0, 255, 0	@08ACE610
mAlignWord
	voice_directsound 57, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08ACE61C
mAlignWord
	voice_directsound 59, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08ACE628
mAlignWord
	voice_directsound 61, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08ACE634
mAlignWord
	voice_directsound 45, 0, DirectSoundWaveData_46, 255, 0, 255, 0	@08ACE640
mAlignWord
	voice_directsound 50, 0, DirectSoundWaveData_46, 255, 0, 255, 0	@08ACE64C
mAlignWord
	voice_directsound 55, 0, DirectSoundWaveData_46, 255, 0, 255, 0	@08ACE658
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_46, 255, 0, 255, 0	@08ACE664
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_46, 255, 0, 255, 0	@08ACE670
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE67C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE688
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE694
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6A0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6AC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6B8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6C4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6D0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6DC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6F4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE700
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE70C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE718
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE724
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE730
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE73C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE748
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE754
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE760
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE76C
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_47, 255, 0, 255, 0	@08ACE778
