	.align 2
	.global voicegroup002
voicegroup002:	@ 0x08ACE550
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_36, 255, 255, 255, 0	@08ACE550
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_37, 255, 0, 255, 0	@08ACE55C
	voice_noise 84, 0, 192, 0, 0, 1, 0, 0	@08ACE568
	voice_noise 84, 0, 192, 0, 0, 2, 0, 0	@08ACE574
	voice_noise 84, 0, 192, 0, 0, 3, 7, 0	@08ACE580
	voice_directsound 45, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08ACE58C
	voice_directsound 50, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08ACE598
	voice_directsound 55, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08ACE5A4
	voice_directsound 60, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08ACE5B0
	voice_directsound 65, 0, DirectSoundWaveData_38, 255, 0, 255, 0	@08ACE5BC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_39, 255, 0, 255, 0	@08ACE5C8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_40, 255, 0, 255, 0	@08ACE5D4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_41, 255, 0, 255, 0	@08ACE5E0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08ACE5EC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_43, 255, 0, 255, 0	@08ACE5F8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_44, 255, 0, 255, 0	@08ACE604
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_45, 255, 0, 255, 0	@08ACE610
	voice_directsound 57, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08ACE61C
	voice_directsound 59, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08ACE628
	voice_directsound 61, 0, DirectSoundWaveData_42, 255, 0, 255, 0	@08ACE634
	voice_directsound 45, 0, DirectSoundWaveData_46, 255, 0, 255, 0	@08ACE640
	voice_directsound 50, 0, DirectSoundWaveData_46, 255, 0, 255, 0	@08ACE64C
	voice_directsound 55, 0, DirectSoundWaveData_46, 255, 0, 255, 0	@08ACE658
	voice_directsound 60, 0, DirectSoundWaveData_46, 255, 0, 255, 0	@08ACE664
	voice_directsound 65, 0, DirectSoundWaveData_46, 255, 0, 255, 0	@08ACE670
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE67C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE688
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE694
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6A0
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6AC
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6B8
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6C4
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6D0
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6DC
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6E8
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE6F4
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE700
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE70C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE718
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE724
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE730
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE73C
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE748
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE754
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE760
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE76C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_47, 255, 0, 255, 0	@08ACE778
	