	mAlignWord
	.global voicegroup015
voicegroup015:	@ 0x08AD1F94
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1F94
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_25, 255, 0, 255, 149	@08AD1FA0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1FAC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_24, 255, 0, 255, 149	@08AD1FB8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_114, 255, 249, 90, 165	@08AD1FC4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_26, 19, 0, 255, 165	@08AD1FD0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_26, 255, 0, 255, 165	@08AD1FDC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_115, 255, 0, 255, 127	@08AD1FE8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_116, 255, 0, 255, 127	@08AD1FF4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_117, 255, 0, 255, 127	@08AD2000
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_97, 255, 235, 25, 165	@08AD200C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 4, 4, 0	@08AD2018
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2024
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2030
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD203C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2048
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2054
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2060
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_118, 255, 0, 255, 127	@08AD206C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_119, 255, 0, 255, 127	@08AD2078
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_120, 255, 0, 255, 127	@08AD2084
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_121, 255, 0, 255, 127	@08AD2090
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_122, 255, 0, 255, 127	@08AD209C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD20A8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD20B4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD20C0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD20CC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD20D8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD20E4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD20F0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD20FC
