	mAlignWord
	.global voicegroup022
voicegroup022:	@ 0x08AD3CBC
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@08AD3CBC
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08AD3CC8
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD3CD4
mAlignWord
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@08AD3CE0
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@08AD3CEC
mAlignWord
	voice_square_1_alt 0, 3, 2, 4, 1, 3	@08AD3CF8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3D04
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3D10
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3D1C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3D28
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@08AD3D34
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08AD3D40
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD3D4C
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@08AD3D58
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08AD3D64
mAlignWord
	voice_square_2_alt 1, 2, 4, 1, 3	@08AD3D70
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3D7C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3D88
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3D94
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DA0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DAC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DB8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DC4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DD0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DDC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DE8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3DF4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E00
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E0C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E18
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E24
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E30
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E3C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E48
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E54
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E60
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E6C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E78
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E84
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3E90
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 4, 4, 0	@08AD3E9C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_3, 0, 0, 15, 0	@08AD3EA8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_4, 0, 0, 15, 0	@08AD3EB4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_5, 0, 0, 15, 0	@08AD3EC0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08AD3ECC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08AD3ED8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD3EE4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08AD3EF0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08AD3EFC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3F08
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08AD3F14
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08AD3F20
mAlignWord
	voice_square_1_alt 0, 2, 0, 3, 0, 0	@08AD3F2C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08AD3F38
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08AD3F44
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08AD3F50
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 5	@08AD3F5C
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@08AD3F68
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08AD3F74
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 2, 0, 3	@08AD3F80
mAlignWord
	voice_square_1_alt 0, 0, 0, 4, 0, 0	@08AD3F8C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 4, 0, 0	@08AD3F98
mAlignWord
	voice_square_2_alt 0, 0, 4, 4, 0	@08AD3FA4
mAlignWord
	voice_square_1_alt 0, 1, 0, 3, 0, 0	@08AD3FB0
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@08AD3FBC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08AD3FC8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08AD3FD4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08AD3FE0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD3FEC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 3, 7, 2	@08AD3FF8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_1, 255, 0, 255, 0	@08AD4004
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4010
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_362, 255, 0, 255, 0	@08AD401C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_363, 255, 0, 255, 0	@08AD4028
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD4034
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_6, 255, 0, 255, 127	@08AD4040
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_7, 255, 0, 255, 0	@08AD404C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_8, 255, 235, 38, 165	@08AD4058
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_9, 255, 0, 255, 127	@08AD4064
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_10, 255, 0, 255, 0	@08AD4070
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08AD407C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4088
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4094
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_364, 255, 0, 255, 127	@08AD40A0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD40AC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_15, 255, 0, 255, 127	@08AD40B8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_16, 255, 0, 255, 127	@08AD40C4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_17, 255, 0, 255, 127	@08AD40D0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_18, 255, 0, 255, 127	@08AD40DC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_365, 255, 0, 255, 149	@08AD40E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD40F4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4100
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_21, 255, 0, 255, 0	@08AD410C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_22, 255, 0, 255, 149	@08AD4118
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_23, 255, 235, 25, 165	@08AD4124
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4130
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_25, 255, 0, 255, 0	@08AD413C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4148
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4154
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4160
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_355, 255, 0, 255, 0	@08AD416C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_356, 255, 0, 255, 0	@08AD4178
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_357, 255, 0, 255, 0	@08AD4184
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_358, 255, 0, 255, 0	@08AD4190
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_359, 255, 0, 255, 0	@08AD419C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD41A8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_361, 255, 0, 255, 0	@08AD41B4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_366, 255, 0, 255, 0	@08AD41C0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_367, 255, 0, 255, 0	@08AD41CC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD41D8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_368, 255, 0, 255, 0	@08AD41E4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_369, 255, 0, 255, 0	@08AD41F0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_370, 255, 0, 255, 188	@08AD41FC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_371, 255, 0, 255, 188	@08AD4208
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_372, 255, 0, 255, 188	@08AD4214
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_373, 255, 0, 255, 196	@08AD4220
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_374, 255, 0, 255, 0	@08AD422C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_100, 255, 0, 255, 0	@08AD4238
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_375, 255, 0, 255, 0	@08AD4244
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4250
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_376, 255, 0, 255, 188	@08AD425C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4268
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4274
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_370, 255, 235, 25, 204	@08AD4280
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_371, 255, 235, 25, 204	@08AD428C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_372, 255, 235, 25, 204	@08AD4298
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_374, 255, 235, 25, 204	@08AD42A4
mAlignWord
	voice_keysplit_all voicegroup001	@08AD42B0
