	mAlignWord
	.global voicegroup023
voicegroup023:	@ 0x08AD42BC
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@08AD42BC
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08AD42C8
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD42D4
mAlignWord
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@08AD42E0
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@08AD42EC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD42F8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4304
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4310
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD431C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4328
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@08AD4334
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08AD4340
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD434C
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@08AD4358
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08AD4364
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4370
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD437C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4388
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4394
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43A0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43AC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43B8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43C4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43D0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43DC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43F4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4400
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD440C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4418
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4424
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4430
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD443C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4448
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4454
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4460
mAlignWord
	voice_square_1_alt 0, 1, 1, 0, 15, 0	@08AD446C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4478
mAlignWord
	voice_square_2_alt 1, 0, 2, 0, 0	@08AD4484
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 1	@08AD4490
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 4, 4, 0	@08AD449C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_3, 0, 0, 15, 0	@08AD44A8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_4, 0, 0, 15, 0	@08AD44B4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_5, 0, 0, 15, 0	@08AD44C0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08AD44CC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08AD44D8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD44E4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08AD44F0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08AD44FC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4508
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08AD4514
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08AD4520
mAlignWord
	voice_square_2_alt 2, 0, 3, 0, 0	@08AD452C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08AD4538
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08AD4544
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08AD4550
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 5	@08AD455C
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@08AD4568
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08AD4574
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08AD4580
mAlignWord
	voice_square_2_alt 0, 0, 4, 0, 0	@08AD458C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 4, 0, 0	@08AD4598
mAlignWord
	voice_square_2_alt 0, 0, 4, 4, 0	@08AD45A4
mAlignWord
	voice_square_1_alt 0, 1, 0, 3, 0, 0	@08AD45B0
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@08AD45BC
mAlignWord
	voice_square_1_alt 0, 3, 0, 1, 0, 1	@08AD45C8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08AD45D4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08AD45E0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD45EC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08AD45F8
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 2	@08AD4604
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4610
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD461C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4628
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4634
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4640
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD464C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4658
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4664
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4670
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD467C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 5, 1, 0	@08AD4688
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4694
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 0	@08AD46A0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD46AC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD46B8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD46C4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD46D0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD46DC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD46E8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 4, 3, 0	@08AD46F4
mAlignWord
	voice_square_1_alt 0, 3, 0, 6, 1, 0	@08AD4700
