	mAlignWord
	.global voicegroup003
voicegroup003:	@ 0x08ACE784
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_48, 255, 0, 255, 0	@08ACE784
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_49, 255, 0, 255, 0	@08ACE790
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_50, 255, 0, 255, 0	@08ACE79C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_51, 255, 0, 255, 0	@08ACE7A8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_52, 255, 0, 255, 0	@08ACE7B4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE7C0
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACE7CC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE7D8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE7E4
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACE7F0
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@08ACE7FC
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08ACE808
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACE814
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@08ACE820
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACE82C
mAlignWord
	voice_noise 60, 0, 0, 1, 1, 0, 12, 2	@08ACE838
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 12, 2	@08ACE844
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08ACE850
mAlignWord
	voice_square_2_alt 1, 0, 0, 5, 3	@08ACE85C
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 12, 2	@08ACE868
mAlignWord
	voice_noise 60, 0, 0, 1, 1, 0, 12, 2	@08ACE874
mAlignWord
	voice_noise 60, 0, 0, 1, 4, 0, 12, 2	@08ACE880
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACE88C
mAlignWord
	voice_square_2_alt 1, 0, 0, 5, 4	@08ACE898
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 5	@08ACE8A4
mAlignWord
	voice_square_2_alt 2, 0, 2, 0, 0	@08ACE8B0
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACE8BC
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 2	@08ACE8C8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE8D4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE8E0
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACE8EC
mAlignWord
	voice_noise 60, 0, 0, 0, 3, 0, 15, 4	@08ACE8F8
mAlignWord
	voice_square_2_alt 1, 0, 2, 0, 0	@08ACE904
mAlignWord
	voice_square_2_alt 1, 0, 2, 0, 0	@08ACE910
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACE91C
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@08ACE928
mAlignWord
	voice_square_2_alt 1, 1, 0, 15, 0	@08ACE934
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACE940
mAlignWord
	voice_square_2_alt 1, 0, 2, 0, 0	@08ACE94C
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 1	@08ACE958
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 4, 4, 0	@08ACE964
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_3, 0, 0, 15, 0	@08ACE970
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_4, 0, 0, 15, 0	@08ACE97C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_5, 0, 0, 15, 0	@08ACE988
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08ACE994
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08ACE9A0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08ACE9AC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08ACE9B8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08ACE9C4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACE9D0
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACE9DC
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACE9E8
mAlignWord
	voice_square_2_alt 2, 0, 3, 0, 0	@08ACE9F4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08ACEA00
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08ACEA0C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08ACEA18
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 5	@08ACEA24
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@08ACEA30
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACEA3C
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACEA48
mAlignWord
	voice_square_2_alt 0, 0, 4, 0, 0	@08ACEA54
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 4, 0, 0	@08ACEA60
mAlignWord
	voice_square_2_alt 0, 0, 4, 4, 0	@08ACEA6C
mAlignWord
	voice_square_2_alt 1, 0, 3, 0, 0	@08ACEA78
mAlignWord
	voice_square_2_alt 1, 0, 2, 0, 0	@08ACEA84
mAlignWord
	voice_square_2_alt 3, 0, 1, 0, 1	@08ACEA90
mAlignWord
	voice_square_2_alt 2, 0, 2, 2, 2	@08ACEA9C
mAlignWord
	voice_square_2_alt 2, 1, 0, 10, 3	@08ACEAA8
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACEAB4
mAlignWord
	voice_square_2_alt 1, 0, 2, 0, 0	@08ACEAC0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_1, 255, 0, 255, 0	@08ACEACC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_2, 255, 0, 255, 0	@08ACEAD8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_3, 255, 0, 255, 0	@08ACEAE4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_4, 255, 0, 255, 0	@08ACEAF0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08ACEAFC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_6, 255, 0, 255, 127	@08ACEB08
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_7, 255, 0, 255, 0	@08ACEB14
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_8, 255, 235, 38, 165	@08ACEB20
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_9, 255, 0, 255, 127	@08ACEB2C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_10, 255, 0, 255, 0	@08ACEB38
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08ACEB44
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_12, 255, 0, 255, 127	@08ACEB50
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_13, 255, 0, 255, 127	@08ACEB5C
mAlignWord
	voice_noise 60, 0, 0, 0, 3, 0, 15, 4	@08ACEB68
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACEB74
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08ACEB80
mAlignWord
	voice_square_2_alt 2, 0, 2, 0, 0	@08ACEB8C
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 1	@08ACEB98
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACEBA4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACEBB0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_19, 255, 0, 255, 0	@08ACEBBC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_20, 255, 0, 255, 0	@08ACEBC8
