	mAlignWord
	.global voicegroup005
voicegroup005:	@ 0x08ACED90
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACED90
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_voice__announcer__sonic_advance_2, 255, 0, 255, 0	@08ACED9C
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_voice__announcer__sonic, 255, 0, 255, 0	@08ACEDA8
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_62, 255, 0, 255, 0	@08ACEDB4
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_63, 255, 0, 255, 0	@08ACEDC0
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_64, 255, 0, 255, 0	@08ACEDCC
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_voice__announcer__cream, 255, 0, 255, 0	@08ACEDD8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACEDE4
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_65, 255, 0, 255, 0	@08ACEDF0
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_66, 255, 0, 255, 0	@08ACEDFC
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_67, 255, 0, 255, 0	@08ACEE08
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_68, 255, 0, 255, 0	@08ACEE14
mAlignWord
	voice_directsound 65, 0, DirectSoundWaveData_69, 255, 0, 255, 0	@08ACEE20
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACEE2C
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACEE38
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACEE44
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08ACEE50
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08ACEE5C
mAlignWord
	voice_square_2_alt 0, 2, 0, 15, 5	@08ACEE68
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACEE74
mAlignWord
	voice_square_2_alt 1, 2, 0, 3, 3	@08ACEE80
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACEE8C
mAlignWord
	voice_noise 60, 0, 0, 0, 2, 0, 15, 0	@08ACEE98
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACEEA4
mAlignWord
	voice_noise 60, 0, 0, 0, 3, 0, 15, 2	@08ACEEB0
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 12, 2	@08ACEEBC
mAlignWord
	voice_noise 60, 0, 0, 1, 4, 0, 12, 2	@08ACEEC8
mAlignWord
	voice_noise 60, 0, 0, 1, 1, 0, 12, 2	@08ACEED4
mAlignWord
	voice_square_2_alt 2, 3, 0, 10, 4	@08ACEEE0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_56, 255, 0, 255, 0	@08ACEEEC
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 4	@08ACEEF8
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACEF04
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACEF10
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACEF1C
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACEF28
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACEF34
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACEF40
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACEF4C
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 4	@08ACEF58
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 12, 2	@08ACEF64
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACEF70
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 12, 2	@08ACEF7C
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACEF88
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 2	@08ACEF94
mAlignWord
	voice_square_2_alt 2, 2, 0, 9, 6	@08ACEFA0
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 12, 2	@08ACEFAC
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACEFB8
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACEFC4
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACEFD0
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 2	@08ACEFDC
mAlignWord
	voice_noise 60, 0, 0, 1, 4, 0, 12, 2	@08ACEFE8
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 2	@08ACEFF4
mAlignWord
	voice_square_2_alt 0, 0, 3, 13, 0	@08ACF000
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@08ACF00C
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08ACF018
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08ACF024
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACF030
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACF03C
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF048
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 2	@08ACF054
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACF060
mAlignWord
	voice_square_2_alt 0, 0, 3, 0, 2	@08ACF06C
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF078
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF084
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF090
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACF09C
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF0A8
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 2	@08ACF0B4
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF0C0
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF0CC
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF0D8
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACF0E4
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACF0F0
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF0FC
mAlignWord
	voice_square_1_alt 0, 2, 0, 2, 0, 0	@08ACF108
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACF114
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF120
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF12C
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF138
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACF144
mAlignWord
	voice_noise 60, 0, 0, 0, 2, 0, 15, 0	@08ACF150
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@08ACF15C
mAlignWord
	voice_noise 60, 0, 0, 0, 3, 0, 15, 4	@08ACF168
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF174
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACF180
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF18C
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACF198
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACF1A4
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@08ACF1B0
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACF1BC
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 10, 3	@08ACF1C8
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 12, 2	@08ACF1D4
mAlignWord
	voice_square_2_alt 2, 0, 2, 2, 0	@08ACF1E0
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08ACF1EC
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACF1F8
mAlignWord
	voice_square_2_alt 2, 0, 4, 13, 6	@08ACF204
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACF210
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 12, 2	@08ACF21C
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08ACF228
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACF234
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08ACF240
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 2	@08ACF24C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_50, 255, 0, 255, 0	@08ACF258
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 0	@08ACF264
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF270
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08ACF27C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF288
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF294
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF2A0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF2AC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF2B8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF2C4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF2D0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF2DC
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@08ACF2E8
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08ACF2F4
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACF300
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@08ACF30C
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACF318
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@08ACF324
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08ACF330
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08ACF33C
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@08ACF348
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACF354
mAlignWord
	voice_square_2_alt 1, 1, 0, 15, 0	@08ACF360
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08ACF36C
mAlignWord
	voice_square_2_alt 0, 2, 0, 15, 0	@08ACF378
