	.align 2
	.global voicegroup014
voicegroup014:	@ 0x08AD1B44
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@08AD1B44
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08AD1B50
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD1B5C
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@08AD1B68
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@08AD1B74
	voice_noise_alt 60, 0, 0, 0, 0, 0, 15, 0	@08AD1B80
	voice_noise_alt 60, 0, 0, 1, 0, 0, 15, 0	@08AD1B8C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1B98
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1BA4
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1BB0
	voice_square_2_alt 0, 0, 0, 15, 0	@08AD1BBC
	voice_square_2_alt 1, 0, 0, 15, 0	@08AD1BC8
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD1BD4
	voice_square_2_alt 3, 0, 0, 15, 0	@08AD1BE0
	voice_square_2_alt 2, 2, 0, 15, 0	@08AD1BEC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1BF8
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C04
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C10
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C1C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C28
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C34
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C40
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C4C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C58
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C64
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C70
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C7C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C88
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1C94
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1CA0
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1CAC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1CB8
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1CC4
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1CD0
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1CDC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1CE8
	voice_square_1_alt 0, 1, 1, 0, 15, 0	@08AD1CF4
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1D00
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1D0C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1D18
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 4, 4, 0	@08AD1D24
	voice_programmable_wave_alt ProgrammableWaveData_3, 0, 0, 15, 0	@08AD1D30
	voice_programmable_wave_alt ProgrammableWaveData_4, 0, 0, 15, 0	@08AD1D3C
	voice_programmable_wave_alt ProgrammableWaveData_5, 0, 0, 15, 0	@08AD1D48
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08AD1D54
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08AD1D60
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD1D6C
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08AD1D78
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08AD1D84
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 4, 3, 0	@08AD1D90
	voice_square_1_alt 0, 3, 0, 6, 1, 0	@08AD1D9C
	voice_square_1_alt 0, 2, 2, 0, 15, 2	@08AD1DA8
	voice_programmable_wave_alt ProgrammableWaveData_7, 2, 0, 15, 2	@08AD1DB4
	voice_programmable_wave_alt ProgrammableWaveData_3, 0, 4, 3, 0	@08AD1DC0
	voice_square_1_alt 0, 2, 0, 6, 0, 0	@08AD1DCC
	voice_programmable_wave_alt ProgrammableWaveData_9, 3, 6, 4, 2	@08AD1DD8
	voice_square_1_alt 0, 2, 0, 6, 1, 0	@08AD1DE4
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1DF0
	voice_square_2_alt 2, 0, 6, 0, 0	@08AD1DFC
	voice_directsound 60, 0, DirectSoundWaveData_101, 255, 0, 255, 127	@08AD1E08
	voice_directsound 60, 0, DirectSoundWaveData_102, 255, 0, 255, 127	@08AD1E14
	voice_directsound 60, 0, DirectSoundWaveData_103, 255, 0, 255, 127	@08AD1E20
	voice_directsound 60, 0, DirectSoundWaveData_104, 255, 0, 255, 127	@08AD1E2C
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD1E38
	voice_directsound 60, 0, DirectSoundWaveData_9, 255, 0, 255, 127	@08AD1E44
	voice_directsound 60, 0, DirectSoundWaveData_105, 255, 249, 0, 127	@08AD1E50
	voice_directsound 60, 0, DirectSoundWaveData_95, 255, 0, 255, 127	@08AD1E5C
	voice_directsound 60, 0, DirectSoundWaveData_96, 255, 0, 255, 127	@08AD1E68
	voice_directsound 60, 0, DirectSoundWaveData_106, 255, 0, 255, 127	@08AD1E74
	voice_directsound 60, 0, DirectSoundWaveData_105, 26, 0, 255, 188	@08AD1E80
	voice_directsound 60, 0, DirectSoundWaveData_107, 255, 235, 128, 127	@08AD1E8C
	voice_directsound 60, 0, DirectSoundWaveData_108, 255, 249, 51, 127	@08AD1E98
	voice_square_1_alt 0, 3, 0, 6, 6, 0	@08AD1EA4
	voice_directsound 60, 0, DirectSoundWaveData_109, 26, 0, 255, 188	@08AD1EB0
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 3, 3, 0	@08AD1EBC
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 4, 7, 0	@08AD1EC8
	voice_directsound 60, 0, DirectSoundWaveData_110, 255, 0, 255, 0	@08AD1ED4
	voice_directsound 60, 0, DirectSoundWaveData_111, 255, 249, 25, 0	@08AD1EE0
	voice_directsound 60, 0, DirectSoundWaveData_112, 255, 249, 25, 127	@08AD1EEC
	voice_directsound 60, 0, DirectSoundWaveData_94, 255, 0, 255, 127	@08AD1EF8
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1F04
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1F10
	voice_directsound 60, 0, DirectSoundWaveData_13, 255, 0, 255, 127	@08AD1F1C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1F28
	voice_directsound 60, 0, DirectSoundWaveData_14, 255, 246, 64, 149	@08AD1F34
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1F40
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1F4C
	voice_directsound 60, 0, DirectSoundWaveData_17, 255, 0, 255, 127	@08AD1F58
	voice_directsound 60, 0, DirectSoundWaveData_113, 255, 0, 255, 127	@08AD1F64
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08AD1F70
	voice_directsound 60, 0, DirectSoundWaveData_19, 255, 0, 255, 127	@08AD1F7C
	voice_directsound 60, 0, DirectSoundWaveData_20, 255, 231, 0, 188	@08AD1F88
