	mAlignWord
	.global voicegroup010
voicegroup010:	@ 0x08AD0710
mAlignWord
	voice_square_1_alt 0, 2, 0, 3, 1, 3	@08AD0710
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD071C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 3, 0	@08AD0728
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD0734
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD0740
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 4, 0	@08AD074C
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@08AD0758
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD0764
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD0770
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 7, 0	@08AD077C
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD0788
mAlignWord
	voice_square_1_alt 0, 2, 0, 3, 4, 0	@08AD0794
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD07A0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 7, 0	@08AD07AC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 3, 0	@08AD07B8
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD07C4
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD07D0
mAlignWord
	voice_square_2_alt 2, 0, 3, 1, 2	@08AD07DC
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD07E8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 7, 0	@08AD07F4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_22, 255, 0, 255, 149	@08AD0800
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_81, 255, 0, 255, 149	@08AD080C
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD0818
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@08AD0824
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 3	@08AD0830
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 9, 6	@08AD083C
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD0848
mAlignWord
	voice_square_2_alt 2, 0, 4, 0, 6	@08AD0854
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD0860
mAlignWord
	voice_square_2_alt 2, 0, 4, 13, 6	@08AD086C
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@08AD0878
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08AD0884
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD0890
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 4	@08AD089C
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 6	@08AD08A8
mAlignWord
	voice_square_2_alt 1, 0, 6, 0, 6	@08AD08B4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 2, 0, 15, 0	@08AD08C0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 2	@08AD08CC
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD08D8
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD08E4
mAlignWord
	voice_square_1_alt 0, 1, 0, 6, 0, 6	@08AD08F0
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 6	@08AD08FC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD0908
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD0914
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD0920
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD092C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 4	@08AD0938
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 6	@08AD0944
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 6, 0, 6	@08AD0950
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD095C
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08AD0968
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 4	@08AD0974
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD0980
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD098C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 3	@08AD0998
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD09A4
mAlignWord
	voice_square_1_alt 0, 1, 2, 0, 10, 3	@08AD09B0
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@08AD09BC
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08AD09C8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_93, 255, 0, 128, 235	@08AD09D4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_78, 255, 0, 255, 0	@08AD09E0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_79, 255, 0, 255, 0	@08AD09EC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_82, 255, 0, 255, 0	@08AD09F8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_83, 255, 0, 255, 0	@08AD0A04
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_80, 255, 0, 255, 0	@08AD0A10
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_78, 255, 0, 255, 0	@08AD0A1C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_79, 255, 0, 255, 0	@08AD0A28
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_82, 255, 250, 18, 250	@08AD0A34
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_83, 255, 250, 18, 250	@08AD0A40
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_80, 255, 250, 18, 250	@08AD0A4C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_1, 255, 0, 255, 0	@08AD0A58
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_2, 255, 0, 255, 0	@08AD0A64
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_3, 255, 0, 255, 0	@08AD0A70
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_4, 255, 0, 255, 0	@08AD0A7C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD0A88
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_6, 255, 0, 255, 127	@08AD0A94
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_7, 255, 0, 255, 0	@08AD0AA0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_8, 255, 235, 38, 165	@08AD0AAC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_9, 255, 0, 255, 127	@08AD0AB8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_10, 255, 0, 255, 0	@08AD0AC4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08AD0AD0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_12, 255, 0, 255, 127	@08AD0ADC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_13, 255, 0, 255, 127	@08AD0AE8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 3	@08AD0AF4
mAlignWord
	voice_square_2_alt 2, 0, 4, 10, 0	@08AD0B00
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@08AD0B0C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0B18
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 1	@08AD0B24
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 2	@08AD0B30
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0B3C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_19, 255, 0, 255, 0	@08AD0B48
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_20, 255, 0, 255, 0	@08AD0B54
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_21, 255, 0, 255, 0	@08AD0B60
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 7, 2	@08AD0B6C
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 2	@08AD0B78
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 2	@08AD0B84
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 2, 9, 2	@08AD0B90
mAlignWord
	voice_square_2_alt 2, 1, 0, 10, 3	@08AD0B9C
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 10, 0	@08AD0BA8
mAlignWord
	voice_square_2_alt 3, 1, 6, 0, 0	@08AD0BB4
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD0BC0
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@08AD0BCC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 2, 9, 2	@08AD0BD8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 1, 2, 9, 2	@08AD0BE4
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD0BF0
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD0BFC
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@08AD0C08
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 2, 9, 2	@08AD0C14
mAlignWord
	voice_square_2_alt 2, 0, 4, 0, 4	@08AD0C20
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@08AD0C2C
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD0C38
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@08AD0C44
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 2, 9, 2	@08AD0C50
mAlignWord
	voice_square_2_alt 2, 1, 3, 3, 5	@08AD0C5C
mAlignWord
	voice_square_1_alt 0, 2, 1, 3, 3, 5	@08AD0C68
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD0C74
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0C80
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0C8C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0C98
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0CA4
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@08AD0CB0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 2, 9, 2	@08AD0CBC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 7, 2	@08AD0CC8
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 2	@08AD0CD4
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 2	@08AD0CE0
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD0CEC
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08AD0CF8
mAlignWord
	voice_keysplit_all voicegroup012	@08AD0D04
