	mAlignWord
	.global voicegroup004
voicegroup004:	@ 0x08ACEBD4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_21, 255, 0, 255, 0	@08ACEBD4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08ACEBE0
mAlignWord
	voice_noise 60, 0, 0, 1, 1, 0, 12, 2	@08ACEBEC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACEBF8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACEC04
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACEC10
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACEC1C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACEC28
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_53, 255, 0, 255, 0	@08ACEC34
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_54, 255, 0, 255, 0	@08ACEC40
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_55, 255, 0, 255, 0	@08ACEC4C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_56, 255, 0, 255, 0	@08ACEC58
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_57, 255, 0, 255, 0	@08ACEC64
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_58, 255, 0, 255, 0	@08ACEC70
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_59, 255, 0, 255, 0	@08ACEC7C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACEC88
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACEC94
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACECA0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACECAC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACECB8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACECC4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACECD0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACECDC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACECE8
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_60, 255, 0, 255, 0	@08ACECF4
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_61, 255, 0, 255, 0	@08ACED00
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08ACED0C
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 2	@08ACED18
mAlignWord
	voice_noise 60, 0, 0, 1, 1, 0, 12, 2	@08ACED24
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@08ACED30
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 2	@08ACED3C
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08ACED48
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 2	@08ACED54
mAlignWord
	voice_square_2_alt 2, 3, 0, 10, 3	@08ACED60
mAlignWord
	voice_square_2_alt 1, 0, 2, 0, 0	@08ACED6C
mAlignWord
	voice_keysplit_all voicegroup001	@08ACED78
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_32, 255, 0, 255, 0	@08ACED84
