	.align 2
	.global voicegroup023
voicegroup023:	@ 0x08AD42BC
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@08AD42BC
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08AD42C8
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD42D4
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@08AD42E0
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@08AD42EC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD42F8
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4304
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4310
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD431C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4328
	voice_square_2_alt 0, 0, 0, 15, 0	@08AD4334
	voice_square_2_alt 1, 0, 0, 15, 0	@08AD4340
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD434C
	voice_square_2_alt 3, 0, 0, 15, 0	@08AD4358
	voice_square_2_alt 2, 2, 0, 15, 0	@08AD4364
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4370
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD437C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4388
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4394
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43A0
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43AC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43B8
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43C4
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43D0
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43DC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43E8
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD43F4
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4400
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD440C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4418
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4424
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4430
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD443C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4448
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4454
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4460
	voice_square_1_alt 0, 1, 1, 0, 15, 0	@08AD446C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4478
	voice_square_2_alt 1, 0, 2, 0, 0	@08AD4484
	voice_square_2_alt 2, 2, 0, 15, 1	@08AD4490
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 4, 4, 0	@08AD449C
	voice_programmable_wave_alt ProgrammableWaveData_3, 0, 0, 15, 0	@08AD44A8
	voice_programmable_wave_alt ProgrammableWaveData_4, 0, 0, 15, 0	@08AD44B4
	voice_programmable_wave_alt ProgrammableWaveData_5, 0, 0, 15, 0	@08AD44C0
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08AD44CC
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08AD44D8
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD44E4
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08AD44F0
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08AD44FC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4508
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08AD4514
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08AD4520
	voice_square_2_alt 2, 0, 3, 0, 0	@08AD452C
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08AD4538
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08AD4544
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08AD4550
	voice_square_1_alt 0, 0, 0, 0, 15, 5	@08AD455C
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@08AD4568
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08AD4574
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08AD4580
	voice_square_2_alt 0, 0, 4, 0, 0	@08AD458C
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 4, 0, 0	@08AD4598
	voice_square_2_alt 0, 0, 4, 4, 0	@08AD45A4
	voice_square_1_alt 0, 1, 0, 3, 0, 0	@08AD45B0
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@08AD45BC
	voice_square_1_alt 0, 3, 0, 1, 0, 1	@08AD45C8
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08AD45D4
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08AD45E0
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD45EC
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08AD45F8
	voice_noise 60, 0, 0, 0, 1, 0, 15, 2	@08AD4604
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4610
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD461C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4628
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4634
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4640
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD464C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4658
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4664
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4670
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD467C
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 5, 1, 0	@08AD4688
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4694
	voice_square_1_alt 0, 2, 0, 6, 0, 0	@08AD46A0
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD46AC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD46B8
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD46C4
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD46D0
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD46DC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD46E8
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 4, 3, 0	@08AD46F4
	voice_square_1_alt 0, 3, 0, 6, 1, 0	@08AD4700
	