	mAlignWord
	.global voicegroup011
voicegroup011:	@ 0x08AD0D10
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08AD0D10
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08AD0D1C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD0D28
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08AD0D34
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_17, 255, 0, 255, 127	@08AD0D40
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08AD0D4C
mAlignWord
	voice_square_1_alt 0, 3, 0, 6, 1, 0	@08AD0D58
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_94, 255, 0, 255, 127	@08AD0D64
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_95, 255, 0, 255, 0	@08AD0D70
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_96, 255, 0, 255, 0	@08AD0D7C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_97, 255, 235, 25, 165	@08AD0D88
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 4, 3, 0	@08AD0D94
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0DA0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0DAC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0DB8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0DC4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0DD0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0DDC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0DE8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0DF4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0E00
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0E0C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0E18
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0E24
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0E30
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0E3C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0E48
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0E54
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0E60
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0E6C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0E78
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0E84
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0E90
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0E9C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0EA8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0EB4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0EC0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0ECC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0ED8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0EE4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0EF0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0EFC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0F08
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0F14
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0F20
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0F2C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0F38
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0F44
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0F50
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0F5C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0F68
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0F74
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0F80
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0F8C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0F98
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0FA4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0FB0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0FBC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0FC8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0FD4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0FE0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0FEC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD0FF8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1004
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1010
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD101C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1028
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1034
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1040
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD104C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1058
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1064
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1070
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD107C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1088
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1094
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD10A0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD10AC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD10B8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD10C4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD10D0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD10DC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD10E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD10F4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1100
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD110C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1118
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1124
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1130
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD113C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1148
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1154
