	mAlignWord
	.global voicegroup019
voicegroup019:	@ 0x08AD2ABC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_266, 255, 0, 255, 0	@08AD2ABC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_267, 255, 0, 255, 0	@08AD2AC8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_268, 255, 0, 255, 0	@08AD2AD4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_269, 255, 0, 255, 0	@08AD2AE0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_270, 255, 0, 255, 0	@08AD2AEC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_271, 255, 0, 255, 0	@08AD2AF8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_272, 255, 0, 255, 0	@08AD2B04
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_273, 255, 0, 255, 0	@08AD2B10
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_274, 255, 0, 255, 0	@08AD2B1C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_275, 255, 0, 255, 0	@08AD2B28
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_276, 255, 0, 255, 0	@08AD2B34
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_277, 255, 0, 255, 0	@08AD2B40
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_278, 255, 0, 255, 0	@08AD2B4C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_279, 255, 0, 255, 0	@08AD2B58
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_280, 255, 0, 255, 0	@08AD2B64
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_281, 255, 0, 255, 0	@08AD2B70
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_282, 255, 0, 255, 0	@08AD2B7C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_283, 255, 0, 255, 0	@08AD2B88
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_284, 255, 0, 255, 0	@08AD2B94
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_285, 255, 0, 255, 0	@08AD2BA0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_286, 255, 0, 255, 0	@08AD2BAC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_287, 255, 0, 255, 0	@08AD2BB8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_288, 255, 0, 255, 0	@08AD2BC4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_289, 255, 0, 255, 0	@08AD2BD0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_290, 255, 0, 255, 0	@08AD2BDC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_291, 255, 0, 255, 0	@08AD2BE8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_292, 255, 0, 255, 0	@08AD2BF4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_293, 255, 0, 255, 0	@08AD2C00
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_294, 255, 0, 255, 0	@08AD2C0C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_295, 255, 0, 255, 0	@08AD2C18
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_296, 255, 0, 255, 0	@08AD2C24
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_297, 255, 0, 255, 0	@08AD2C30
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_298, 255, 0, 255, 0	@08AD2C3C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_299, 255, 0, 255, 0	@08AD2C48
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_300, 255, 0, 255, 0	@08AD2C54
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_301, 255, 0, 255, 0	@08AD2C60
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_302, 255, 0, 255, 0	@08AD2C6C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_303, 255, 0, 255, 0	@08AD2C78
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_304, 255, 0, 255, 0	@08AD2C84
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_305, 255, 0, 255, 0	@08AD2C90
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_306, 255, 0, 255, 0	@08AD2C9C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_307, 255, 0, 255, 0	@08AD2CA8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_308, 255, 0, 255, 0	@08AD2CB4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_309, 255, 0, 255, 0	@08AD2CC0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_310, 255, 0, 255, 0	@08AD2CCC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_311, 255, 0, 255, 0	@08AD2CD8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_312, 255, 0, 255, 0	@08AD2CE4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_313, 255, 0, 255, 0	@08AD2CF0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_314, 255, 0, 255, 0	@08AD2CFC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_315, 255, 0, 255, 0	@08AD2D08
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_316, 255, 0, 255, 0	@08AD2D14
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_317, 255, 0, 255, 0	@08AD2D20
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_318, 255, 0, 255, 0	@08AD2D2C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_319, 255, 0, 255, 0	@08AD2D38
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_320, 255, 0, 255, 0	@08AD2D44
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_321, 255, 0, 255, 0	@08AD2D50
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_322, 255, 0, 255, 0	@08AD2D5C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_323, 255, 0, 255, 0	@08AD2D68
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_324, 255, 0, 255, 0	@08AD2D74
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_325, 255, 0, 255, 0	@08AD2D80
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_326, 255, 0, 255, 0	@08AD2D8C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_327, 255, 0, 255, 0	@08AD2D98
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_328, 255, 0, 255, 0	@08AD2DA4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_329, 255, 0, 255, 0	@08AD2DB0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_330, 255, 0, 255, 0	@08AD2DBC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_331, 255, 0, 255, 0	@08AD2DC8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_332, 255, 0, 255, 0	@08AD2DD4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_333, 255, 0, 255, 0	@08AD2DE0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_334, 255, 0, 255, 0	@08AD2DEC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_335, 255, 0, 255, 0	@08AD2DF8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_336, 255, 0, 255, 0	@08AD2E04
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_337, 255, 0, 255, 0	@08AD2E10
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_338, 255, 0, 255, 0	@08AD2E1C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_339, 255, 0, 255, 0	@08AD2E28
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_340, 255, 0, 255, 0	@08AD2E34
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_341, 255, 0, 255, 0	@08AD2E40
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_342, 255, 0, 255, 0	@08AD2E4C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_343, 255, 0, 255, 0	@08AD2E58
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_344, 255, 0, 255, 0	@08AD2E64
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_345, 255, 0, 255, 0	@08AD2E70
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_346, 255, 0, 255, 0	@08AD2E7C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_347, 255, 0, 255, 0	@08AD2E88
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_348, 255, 0, 255, 0	@08AD2E94
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_349, 255, 0, 255, 0	@08AD2EA0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_350, 255, 0, 255, 0	@08AD2EAC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_351, 255, 0, 255, 0	@08AD2EB8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_352, 255, 0, 255, 0	@08AD2EC4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_353, 255, 0, 255, 0	@08AD2ED0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_354, 255, 0, 255, 0	@08AD2EDC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2EE8
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2EF4
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2F00
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2F0C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2F18
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2F24
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2F30
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2F3C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2F48
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2F54
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_169, 255, 0, 255, 0	@08AD2F60
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_170, 255, 0, 255, 0	@08AD2F6C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_171, 255, 0, 255, 0	@08AD2F78
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_172, 255, 0, 255, 0	@08AD2F84
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_173, 255, 0, 255, 0	@08AD2F90
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_174, 255, 0, 255, 0	@08AD2F9C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_175, 255, 0, 255, 0	@08AD2FA8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_176, 255, 0, 255, 0	@08AD2FB4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_177, 255, 0, 255, 0	@08AD2FC0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_178, 255, 0, 255, 0	@08AD2FCC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_179, 255, 0, 255, 0	@08AD2FD8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_180, 255, 0, 255, 0	@08AD2FE4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_181, 255, 0, 255, 0	@08AD2FF0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_182, 255, 0, 255, 0	@08AD2FFC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_183, 255, 0, 255, 0	@08AD3008
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_184, 255, 0, 255, 0	@08AD3014
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_185, 255, 0, 255, 0	@08AD3020
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_186, 255, 0, 255, 0	@08AD302C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_187, 255, 0, 255, 0	@08AD3038
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_188, 255, 0, 255, 0	@08AD3044
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_189, 255, 0, 255, 0	@08AD3050
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_190, 255, 0, 255, 0	@08AD305C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_191, 255, 0, 255, 0	@08AD3068
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_192, 255, 0, 255, 0	@08AD3074
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_193, 255, 0, 255, 0	@08AD3080
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_194, 255, 0, 255, 0	@08AD308C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_195, 255, 0, 255, 0	@08AD3098
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_196, 255, 0, 255, 0	@08AD30A4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_197, 255, 0, 255, 0	@08AD30B0
