	mAlignWord
	.global voicegroup024
voicegroup024: @ 0x08AD470C
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 2	@08AD470C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 2, 0, 15, 2	@08AD4718
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_3, 0, 4, 3, 0	@08AD4724
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 0	@08AD4730
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 3, 6, 4, 2	@08AD473C
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 1, 0	@08AD4748
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 1, 0	@08AD4754
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 0	@08AD4760
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_377, 255, 0, 255, 127	@08AD476C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_378, 255, 0, 255, 127	@08AD4778
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_379, 255, 0, 255, 127	@08AD4784
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_377, 255, 249, 77, 127	@08AD4790
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_378, 255, 249, 77, 127	@08AD479C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_379, 255, 249, 77, 127	@08AD47A8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD47B4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD47C0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD47CC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD47D8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD47E4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD47F0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD47FC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4808
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4814
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4820
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD482C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4838
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4844
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4850
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD485C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4868
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4874
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4880
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD488C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4898
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD48A4
mAlignWord
	voice_keysplit_all voicegroup024	@08AD48B0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD48BC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD48C8
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 1, 0, 0	@08AD48D4
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 2, 0, 0	@08AD48E0
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 3, 7, 0	@08AD48EC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD48F8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4904
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4910
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD491C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4928
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4934
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4940
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD494C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4958
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4964
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_44, 255, 0, 255, 0	@08AD4970
mAlignWord
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_45, 255, 0, 255, 0	@08AD497C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4988
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4994
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD49A0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD49AC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD49B8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD49C4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD49D0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD49DC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD49E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD49F4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4A00
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4A0C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4A18
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4A24
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4A30
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4A3C
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08AD4A48
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4A54
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4A60
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4A6C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4A78
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4A84
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4A90
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4A9C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4AA8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4AB4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4AC0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4ACC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4AD8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4AE4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4AF0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4AFC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4B08
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4B14
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4B20
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4B2C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4B38
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4B44
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4B50
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4B5C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4B68
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4B74
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4B80
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4B8C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4B98
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4BA4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4BB0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4BBC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4BC8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4BD4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4BE0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4BEC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4BF8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4C04
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4C10
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4C1C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4C28
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4C34
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4C40
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4C4C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4C58
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4C64
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4C70
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4C7C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4C88
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4C94
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4CA0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4CAC
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08AD4CB8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4CC4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4CD0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4CDC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4CE8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4CF4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4D00
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4D0C
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08AD4D18
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4D24
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4D30
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4D3C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4D48
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4D54
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4D60
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4D6C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4D78
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4D84
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4D90
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4D9C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4DA8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4DB4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4DC0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4DCC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4DD8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4DE4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4DF0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4DFC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4E08
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD4E14
