	mAlignWord
	.global voicegroup006
voicegroup006:	@ 0x08ACF384
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF384
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_70, 255, 0, 255, 0	@08ACF390
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF39C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF3A8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF3B4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_71, 255, 0, 255, 0	@08ACF3C0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_72, 255, 0, 255, 0	@08ACF3CC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF3D8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF3E4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF3F0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF3FC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF408
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF414
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF420
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_73, 255, 0, 255, 0	@08ACF42C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF438
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF444
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF450
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF45C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF468
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF474
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF480
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_74, 64, 0, 255, 0	@08ACF48C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF498
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF4A4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_75, 64, 0, 255, 0	@08ACF4B0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF4BC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08ACF4C8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_76, 255, 0, 255, 0	@08ACF4D4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_77, 255, 0, 255, 0	@08ACF4E0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_22, 255, 0, 255, 149	@08ACF4EC
mAlignWord
	voice_square_2_alt 2, 0, 2, 1, 0	@08ACF4F8
mAlignWord
	voice_square_2_alt 2, 0, 2, 2, 6	@08ACF504
