	mAlignWord
	.global voicegroup013
voicegroup013:	@ 0x08AD1544
mAlignWord
	voice_square_1_alt 0, 2, 0, 3, 1, 3	@08AD1544
mAlignWord
	voice_square_2_alt 2, 0, 4, 4, 6	@08AD1550
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 3, 0	@08AD155C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD1568
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_98, 255, 250, 18, 250	@08AD1574
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD1580
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08AD158C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 3, 0	@08AD1598
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_26, 255, 0, 255, 165	@08AD15A4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08AD15B0
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 3	@08AD15BC
mAlignWord
	voice_square_2_alt 2, 1, 6, 0, 4	@08AD15C8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 13, 0	@08AD15D4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD15E0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_82, 255, 250, 18, 250	@08AD15EC
mAlignWord
	voice_square_1_alt 0, 2, 1, 6, 7, 3	@08AD15F8
mAlignWord
	voice_square_2_alt 2, 1, 6, 7, 4	@08AD1604
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1610
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD161C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_99, 255, 0, 255, 127	@08AD1628
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 3, 0	@08AD1634
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 3	@08AD1640
mAlignWord
	voice_square_2_alt 2, 1, 6, 0, 4	@08AD164C
mAlignWord
	voice_square_1_alt 0, 2, 1, 6, 7, 3	@08AD1658
mAlignWord
	voice_square_2_alt 2, 1, 6, 7, 4	@08AD1664
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_100, 255, 0, 255, 0	@08AD1670
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_20, 255, 0, 255, 0	@08AD167C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_78, 255, 0, 255, 0	@08AD1688
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD1694
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD16A0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08AD16AC
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 7, 0	@08AD16B8
mAlignWord
	voice_square_2_alt 2, 0, 0, 7, 0	@08AD16C4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 1	@08AD16D0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD16DC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_20, 255, 0, 255, 0	@08AD16E8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_26, 255, 0, 255, 165	@08AD16F4
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 13, 1	@08AD1700
mAlignWord
	voice_square_2_alt 1, 0, 0, 13, 1	@08AD170C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_100, 255, 0, 255, 0	@08AD1718
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08AD1724
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 7, 0	@08AD1730
mAlignWord
	voice_square_2_alt 2, 0, 0, 7, 0	@08AD173C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 3	@08AD1748
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_80, 255, 0, 255, 0	@08AD1754
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_26, 255, 0, 255, 165	@08AD1760
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_98, 255, 250, 18, 250	@08AD176C
mAlignWord
	voice_square_1_alt 0, 1, 0, 3, 1, 3	@08AD1778
mAlignWord
	voice_square_2_alt 1, 0, 4, 4, 6	@08AD1784
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1790
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD179C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD17A8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 3	@08AD17B4
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 7, 0	@08AD17C0
mAlignWord
	voice_square_2_alt 2, 0, 0, 7, 0	@08AD17CC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08AD17D8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_93, 255, 0, 128, 235	@08AD17E4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_12, 255, 0, 255, 127	@08AD17F0
mAlignWord
	voice_square_1_alt 0, 2, 0, 3, 1, 3	@08AD17FC
mAlignWord
	voice_square_2_alt 2, 0, 3, 1, 3	@08AD1808
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1814
mAlignWord
	voice_square_1_alt 0, 2, 1, 6, 7, 3	@08AD1820
mAlignWord
	voice_square_2_alt 2, 1, 6, 7, 4	@08AD182C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 3	@08AD1838
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_20, 255, 0, 255, 0	@08AD1844
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_78, 255, 0, 255, 0	@08AD1850
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_80, 255, 0, 255, 0	@08AD185C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_100, 255, 0, 255, 0	@08AD1868
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD1874
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_82, 255, 0, 255, 0	@08AD1880
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08AD188C
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 7, 0	@08AD1898
mAlignWord
	voice_square_2_alt 2, 0, 0, 7, 0	@08AD18A4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 1	@08AD18B0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD18BC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_20, 255, 0, 255, 0	@08AD18C8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_26, 255, 0, 255, 165	@08AD18D4
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 13, 1	@08AD18E0
mAlignWord
	voice_square_2_alt 1, 0, 0, 13, 1	@08AD18EC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_100, 255, 0, 255, 0	@08AD18F8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08AD1904
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 7, 0	@08AD1910
mAlignWord
	voice_square_2_alt 2, 0, 0, 7, 0	@08AD191C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 1, 1	@08AD1928
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD1934
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_20, 255, 0, 255, 0	@08AD1940
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_26, 255, 0, 255, 165	@08AD194C
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 13, 1	@08AD1958
mAlignWord
	voice_square_2_alt 1, 0, 0, 13, 1	@08AD1964
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_100, 255, 0, 255, 0	@08AD1970
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_19, 255, 0, 255, 127	@08AD197C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1988
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1994
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD19A0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD19AC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD19B8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD19C4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD19D0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD19DC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD19E8
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD19F4
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@08AD1A00
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 2, 9, 2	@08AD1A0C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 1, 2, 9, 2	@08AD1A18
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD1A24
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD1A30
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@08AD1A3C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 2, 9, 2	@08AD1A48
mAlignWord
	voice_square_2_alt 2, 0, 4, 0, 4	@08AD1A54
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@08AD1A60
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD1A6C
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@08AD1A78
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 2, 9, 2	@08AD1A84
mAlignWord
	voice_square_2_alt 2, 1, 3, 3, 5	@08AD1A90
mAlignWord
	voice_square_1_alt 0, 2, 1, 3, 3, 5	@08AD1A9C
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD1AA8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1AB4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1AC0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1ACC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD1AD8
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@08AD1AE4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 2, 9, 2	@08AD1AF0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 3, 7, 2	@08AD1AFC
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 2	@08AD1B08
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 2	@08AD1B14
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@08AD1B20
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08AD1B2C
mAlignWord
	voice_keysplit_all voicegroup012	@08AD1B38
