	.align 2
	.global voicegroup017
voicegroup017:	@ 0x08AD2558
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2558
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2564
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2570
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD257C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2588
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2594
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD25A0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_169, 255, 0, 255, 0	@08AD25AC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_170, 255, 0, 255, 0	@08AD25B8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_171, 255, 0, 255, 0	@08AD25C4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_172, 255, 0, 255, 0	@08AD25D0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_173, 255, 0, 255, 0	@08AD25DC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_174, 255, 0, 255, 0	@08AD25E8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_175, 255, 0, 255, 0	@08AD25F4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_176, 255, 0, 255, 0	@08AD2600
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_177, 255, 0, 255, 0	@08AD260C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_178, 255, 0, 255, 0	@08AD2618
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_179, 255, 0, 255, 0	@08AD2624
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_180, 255, 0, 255, 0	@08AD2630
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_181, 255, 0, 255, 0	@08AD263C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_182, 255, 0, 255, 0	@08AD2648
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_183, 255, 0, 255, 0	@08AD2654
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_184, 255, 0, 255, 0	@08AD2660
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_185, 255, 0, 255, 0	@08AD266C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_186, 255, 0, 255, 0	@08AD2678
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_187, 255, 0, 255, 0	@08AD2684
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_188, 255, 0, 255, 0	@08AD2690
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_189, 255, 0, 255, 0	@08AD269C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_190, 255, 0, 255, 0	@08AD26A8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_191, 255, 0, 255, 0	@08AD26B4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_192, 255, 0, 255, 0	@08AD26C0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_193, 255, 0, 255, 0	@08AD26CC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_194, 255, 0, 255, 0	@08AD26D8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_195, 255, 0, 255, 0	@08AD26E4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_196, 255, 0, 255, 0	@08AD26F0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_197, 255, 0, 255, 0	@08AD26FC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_198, 255, 0, 255, 0	@08AD2708
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_199, 255, 0, 255, 0	@08AD2714
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_200, 255, 0, 255, 0	@08AD2720
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_201, 255, 0, 255, 0	@08AD272C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_202, 255, 0, 255, 0	@08AD2738
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_203, 255, 0, 255, 0	@08AD2744
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_204, 255, 0, 255, 0	@08AD2750
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_205, 255, 0, 255, 0	@08AD275C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_206, 255, 0, 255, 0	@08AD2768
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_207, 255, 0, 255, 0	@08AD2774
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_208, 255, 0, 255, 0	@08AD2780
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_209, 255, 0, 255, 0	@08AD278C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_210, 255, 0, 255, 0	@08AD2798
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_211, 255, 0, 255, 0	@08AD27A4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_212, 255, 0, 255, 0	@08AD27B0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_213, 255, 0, 255, 0	@08AD27BC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD27C8
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD27D4
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD27E0
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD27EC
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD27F8
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2804
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2810
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD281C
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2828
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2834
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD2840
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_214, 255, 0, 255, 0	@08AD284C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_215, 255, 0, 255, 0	@08AD2858
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_216, 255, 0, 255, 0	@08AD2864
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_217, 255, 0, 255, 0	@08AD2870
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_218, 255, 0, 255, 0	@08AD287C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_219, 255, 0, 255, 0	@08AD2888
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_220, 255, 0, 255, 0	@08AD2894
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_221, 255, 0, 255, 0	@08AD28A0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_222, 255, 0, 255, 0	@08AD28AC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_223, 255, 0, 255, 0	@08AD28B8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_224, 255, 0, 255, 0	@08AD28C4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_225, 255, 0, 255, 0	@08AD28D0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_226, 255, 0, 255, 0	@08AD28DC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_227, 255, 0, 255, 0	@08AD28E8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_228, 255, 0, 255, 0	@08AD28F4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_229, 255, 0, 255, 0	@08AD2900
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_230, 255, 0, 255, 0	@08AD290C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_231, 255, 0, 255, 0	@08AD2918
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_232, 255, 0, 255, 0	@08AD2924
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_233, 255, 0, 255, 0	@08AD2930
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_234, 255, 0, 255, 0	@08AD293C
	