	mAlignWord
	.global voicegroup020
voicegroup020:	@ 0x08AD30BC
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@08AD30BC
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@08AD30C8
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@08AD30D4
mAlignWord
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@08AD30E0
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@08AD30EC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD30F8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3104
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3110
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD311C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3128
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@08AD3134
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@08AD3140
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@08AD314C
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@08AD3158
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@08AD3164
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3170
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD317C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3188
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3194
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD31A0
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08AD31AC
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 2	@08AD31B8
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 2	@08AD31C4
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 2	@08AD31D0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD31DC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD31E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD31F4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3200
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD320C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3218
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3224
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3230
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD323C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3248
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3254
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3260
mAlignWord
	voice_square_1_alt 0, 1, 1, 0, 15, 0	@08AD326C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3278
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3284
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3290
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 4, 4, 0	@08AD329C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_3, 0, 0, 15, 0	@08AD32A8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_4, 0, 0, 15, 0	@08AD32B4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_5, 0, 0, 15, 0	@08AD32C0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08AD32CC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08AD32D8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD32E4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08AD32F0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08AD32FC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 4, 3, 0	@08AD3308
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@08AD3314
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08AD3320
mAlignWord
	voice_square_1_alt 0, 2, 0, 3, 0, 0	@08AD332C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08AD3338
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 3, 0, 2	@08AD3344
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_2, 0, 0, 15, 0	@08AD3350
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 5	@08AD335C
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@08AD3368
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@08AD3374
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@08AD3380
mAlignWord
	voice_square_1_alt 0, 0, 0, 4, 0, 0	@08AD338C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_10, 0, 4, 0, 0	@08AD3398
mAlignWord
	voice_square_2_alt 0, 0, 4, 4, 0	@08AD33A4
mAlignWord
	voice_square_1_alt 0, 1, 0, 3, 0, 0	@08AD33B0
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@08AD33BC
mAlignWord
	voice_square_1_alt 0, 3, 0, 1, 0, 1	@08AD33C8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 0, 15, 0	@08AD33D4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08AD33E0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_8, 0, 0, 15, 0	@08AD33EC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_9, 0, 0, 15, 0	@08AD33F8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_1, 255, 0, 255, 0	@08AD3404
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_2, 255, 0, 255, 0	@08AD3410
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_3, 255, 0, 255, 0	@08AD341C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_4, 255, 0, 255, 0	@08AD3428
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_5, 255, 0, 255, 127	@08AD3434
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_6, 255, 0, 255, 127	@08AD3440
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_7, 255, 0, 255, 0	@08AD344C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_8, 255, 235, 38, 165	@08AD3458
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_9, 255, 0, 255, 127	@08AD3464
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_10, 255, 0, 255, 0	@08AD3470
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_11, 255, 0, 255, 0	@08AD347C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_12, 255, 0, 255, 127	@08AD3488
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_13, 255, 0, 255, 127	@08AD3494
mAlignWord
	voice_keysplit voicegroup002, KeySplitTable1	@08AD34A0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_14, 255, 246, 64, 149	@08AD34AC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_15, 255, 0, 255, 127	@08AD34B8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_16, 255, 0, 255, 127	@08AD34C4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_17, 255, 0, 255, 127	@08AD34D0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_18, 255, 0, 255, 127	@08AD34DC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_7, 0, 0, 15, 0	@08AD34E8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_19, 255, 0, 255, 127	@08AD34F4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_20, 255, 231, 0, 188	@08AD3500
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_21, 255, 0, 255, 0	@08AD350C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_22, 255, 0, 255, 149	@08AD3518
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_23, 255, 235, 25, 165	@08AD3524
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_24, 255, 0, 255, 149	@08AD3530
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_25, 255, 0, 255, 0	@08AD353C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_26, 37, 0, 255, 165	@08AD3548
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_26, 255, 0, 255, 165	@08AD3554
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_27, 255, 252, 0, 149	@08AD3560
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_355, 255, 0, 255, 0	@08AD356C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_356, 255, 0, 255, 0	@08AD3578
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_357, 255, 0, 255, 0	@08AD3584
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_358, 255, 0, 255, 0	@08AD3590
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_359, 255, 0, 255, 0	@08AD359C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_360, 255, 0, 255, 0	@08AD35A8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_361, 255, 0, 255, 0	@08AD35B4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_24, 255, 0, 255, 149	@08AD35C0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_114, 255, 249, 90, 165	@08AD35CC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_26, 19, 0, 255, 165	@08AD35D8
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_26, 255, 0, 255, 165	@08AD35E4
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_95, 255, 0, 255, 127	@08AD35F0
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_96, 255, 0, 255, 127	@08AD35FC
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_106, 255, 0, 255, 127	@08AD3608
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3614
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD3620
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_28, 255, 0, 255, 0	@08AD362C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_29, 255, 250, 18, 250	@08AD3638
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_30, 255, 216, 25, 0	@08AD3644
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_31, 37, 0, 255, 149	@08AD3650
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_32, 255, 0, 255, 0	@08AD365C
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_33, 255, 0, 255, 0	@08AD3668
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_34, 255, 0, 255, 149	@08AD3674
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 5, 1, 0	@08AD3680
mAlignWord
	voice_directsound 60, 0, DirectSoundWaveData_35, 255, 216, 25, 0	@08AD368C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_6, 0, 4, 4, 0	@08AD3698
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@08AD36A4
mAlignWord
	voice_keysplit_all voicegroup001	@08AD36B0
