#ifndef GUARD_INTERACTABLE_NOTIFICATION_RING_BONUS_H
#define GUARD_INTERACTABLE_NOTIFICATION_RING_BONUS_H

#include "global.h"
#include "game/entity.h"

void CreateEntity_8080368(MapEntity *, u16, u16, u8);

#endif // GUARD_INTERACTABLE_NOTIFICATION_RING_BONUS_H
