./tools/gbagfx/gbagfx ./data/maps/zone1/act1/enemies.bin ./data/maps/zone1/act1/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone1/act1/interactables.bin ./data/maps/zone1/act1/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone1/act1/itemboxes.bin ./data/maps/zone1/act1/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone1/act1/rings.bin ./data/maps/zone1/act1/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone1/act2/enemies.bin ./data/maps/zone1/act2/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone1/act2/interactables.bin ./data/maps/zone1/act2/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone1/act2/itemboxes.bin ./data/maps/zone1/act2/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone1/act2/rings.bin ./data/maps/zone1/act2/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone1/boss/enemies.bin ./data/maps/zone1/boss/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone1/boss/interactables.bin ./data/maps/zone1/boss/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone1/boss/itemboxes.bin ./data/maps/zone1/boss/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone1/boss/rings.bin ./data/maps/zone1/boss/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone2/act1/enemies.bin ./data/maps/zone2/act1/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone2/act1/interactables.bin ./data/maps/zone2/act1/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone2/act1/itemboxes.bin ./data/maps/zone2/act1/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone2/act1/rings.bin ./data/maps/zone2/act1/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone2/act2/enemies.bin ./data/maps/zone2/act2/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone2/act2/interactables.bin ./data/maps/zone2/act2/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone2/act2/itemboxes.bin ./data/maps/zone2/act2/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone2/act2/rings.bin ./data/maps/zone2/act2/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone2/boss/enemies.bin ./data/maps/zone2/boss/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone2/boss/interactables.bin ./data/maps/zone2/boss/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone2/boss/itemboxes.bin ./data/maps/zone2/boss/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone2/boss/rings.bin ./data/maps/zone2/boss/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone3/act1/enemies.bin ./data/maps/zone3/act1/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone3/act1/interactables.bin ./data/maps/zone3/act1/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone3/act1/itemboxes.bin ./data/maps/zone3/act1/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone3/act1/rings.bin ./data/maps/zone3/act1/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone3/act2/enemies.bin ./data/maps/zone3/act2/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone3/act2/interactables.bin ./data/maps/zone3/act2/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone3/act2/itemboxes.bin ./data/maps/zone3/act2/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone3/act2/rings.bin ./data/maps/zone3/act2/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone3/boss/enemies.bin ./data/maps/zone3/boss/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone3/boss/interactables.bin ./data/maps/zone3/boss/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone3/boss/itemboxes.bin ./data/maps/zone3/boss/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone3/boss/rings.bin ./data/maps/zone3/boss/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone4/act1/enemies.bin ./data/maps/zone4/act1/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone4/act1/interactables.bin ./data/maps/zone4/act1/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone4/act1/itemboxes.bin ./data/maps/zone4/act1/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone4/act1/rings.bin ./data/maps/zone4/act1/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone4/act2/enemies.bin ./data/maps/zone4/act2/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone4/act2/interactables.bin ./data/maps/zone4/act2/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone4/act2/itemboxes.bin ./data/maps/zone4/act2/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone4/act2/rings.bin ./data/maps/zone4/act2/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone4/boss/enemies.bin ./data/maps/zone4/boss/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone4/boss/interactables.bin ./data/maps/zone4/boss/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone4/boss/itemboxes.bin ./data/maps/zone4/boss/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone4/boss/rings.bin ./data/maps/zone4/boss/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone5/act1/enemies.bin ./data/maps/zone5/act1/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone5/act1/interactables.bin ./data/maps/zone5/act1/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone5/act1/itemboxes.bin ./data/maps/zone5/act1/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone5/act1/rings.bin ./data/maps/zone5/act1/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone5/act2/enemies.bin ./data/maps/zone5/act2/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone5/act2/interactables.bin ./data/maps/zone5/act2/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone5/act2/itemboxes.bin ./data/maps/zone5/act2/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone5/act2/rings.bin ./data/maps/zone5/act2/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone5/boss/enemies.bin ./data/maps/zone5/boss/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone5/boss/interactables.bin ./data/maps/zone5/boss/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone5/boss/itemboxes.bin ./data/maps/zone5/boss/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone5/boss/rings.bin ./data/maps/zone5/boss/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone6/act1/enemies.bin ./data/maps/zone6/act1/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone6/act1/interactables.bin ./data/maps/zone6/act1/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone6/act1/itemboxes.bin ./data/maps/zone6/act1/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone6/act1/rings.bin ./data/maps/zone6/act1/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone6/act2/enemies.bin ./data/maps/zone6/act2/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone6/act2/interactables.bin ./data/maps/zone6/act2/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone6/act2/itemboxes.bin ./data/maps/zone6/act2/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone6/act2/rings.bin ./data/maps/zone6/act2/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone6/boss/enemies.bin ./data/maps/zone6/boss/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone6/boss/interactables.bin ./data/maps/zone6/boss/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone6/boss/itemboxes.bin ./data/maps/zone6/boss/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone6/boss/rings.bin ./data/maps/zone6/boss/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone7/act1/enemies.bin ./data/maps/zone7/act1/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone7/act1/interactables.bin ./data/maps/zone7/act1/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone7/act1/itemboxes.bin ./data/maps/zone7/act1/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone7/act1/rings.bin ./data/maps/zone7/act1/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone7/act2/enemies.bin ./data/maps/zone7/act2/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone7/act2/interactables.bin ./data/maps/zone7/act2/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone7/act2/itemboxes.bin ./data/maps/zone7/act2/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone7/act2/rings.bin ./data/maps/zone7/act2/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone7/boss/enemies.bin ./data/maps/zone7/boss/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone7/boss/interactables.bin ./data/maps/zone7/boss/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone7/boss/itemboxes.bin ./data/maps/zone7/boss/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone7/boss/rings.bin ./data/maps/zone7/boss/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone8/act1/enemies.bin ./data/maps/zone8/act1/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone8/act1/interactables.bin ./data/maps/zone8/act1/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone8/act1/itemboxes.bin ./data/maps/zone8/act1/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone8/act1/rings.bin ./data/maps/zone8/act1/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone8/act2/enemies.bin ./data/maps/zone8/act2/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone8/act2/interactables.bin ./data/maps/zone8/act2/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone8/act2/itemboxes.bin ./data/maps/zone8/act2/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone8/act2/rings.bin ./data/maps/zone8/act2/rings.rl
./tools/gbagfx/gbagfx ./data/maps/zone8/boss/enemies.bin ./data/maps/zone8/boss/enemies.rl
./tools/gbagfx/gbagfx ./data/maps/zone8/boss/interactables.bin ./data/maps/zone8/boss/interactables.rl
./tools/gbagfx/gbagfx ./data/maps/zone8/boss/itemboxes.bin ./data/maps/zone8/boss/itemboxes.rl
./tools/gbagfx/gbagfx ./data/maps/zone8/boss/rings.bin ./data/maps/zone8/boss/rings.rl
