#ifndef GUARD_PLAYER_TRANSITIONS_H
#define GUARD_PLAYER_TRANSITIONS_H

#define PLTRANS_SPRING_UP         14
#define PLTRANS_SPRING_DOWN       15
#define PLTRANS_SPRING_LEFT       16
#define PLTRANS_SPRING_RIGHT      17
#define PLTRANS_SPRING_UP_LEFT    18
#define PLTRANS_SPRING_UP_RIGHT   19
#define PLTRANS_SPRING_DOWN_LEFT  20
#define PLTRANS_SPRING_DOWN_RIGHT 21

#endif // GUARD_PLAYER_TRANSITIONS_H