#ifndef GUARD_CONSTANTS_SONGS_H
#define GUARD_CONSTANTS_SONGS_H

#define MUS_DUMMY 0
#define MUS_INTRO 1
#define MUS_TITLE_FANFARE 2

#define MUS_TA_COURSE_SELECTION 4

#define MUS_OPTIONS 9

#define SE_SELECT 106
#define SE_RETURN 107
#define SE_MENU_CURSOR_MOVE 108

#define SS_TITLE_SCREEN_ANNOUNCEMENT 201
#define SE_DELETE_GAME_DATA 220

#endif 
