#define NUM_LANGUAGES 6

#define LANGUAGE_DEFAULT 0
#define LANGUAGE_JAPANESE 1
#define LANGUAGE_ENGLISH 2
#define LANGUAGE_GERMAN 3
#define LANGUAGE_FRENCH 4
#define LANGUAGE_SPANISH 5
#define LANGUAGE_ITALIAN 6
