#ifndef GUARD_DATA_ANIMATIONS_H
#define GUARD_DATA_ANIMATIONS_H

#include "core.h"
#include "animation_commands.h"
#include "sprite.h"

#if !ENABLE_DECOMP_CREDITS
// TODO: Auto-generate this number once animations get autogenerated
#define NUM_SPRITE_ANIMATIONS 1133
#else
// For "Decomp Credits"
#define NUM_SPRITE_ANIMATIONS (1133 + 1)
#endif

extern const ACmd **const gAnimations[NUM_SPRITE_ANIMATIONS];
extern const SpriteOffset *const gSpriteDimensions[NUM_SPRITE_ANIMATIONS];
extern const OamDataShort *const gSpriteOamData[NUM_SPRITE_ANIMATIONS];
extern const u16 gSpritePalettes[][16];

#endif
