#ifndef GUARD_VRAM_HARDCODED_H
#define GUARD_VRAM_HARDCODED_H

#define VRAM_RESERVED_DUST_EFFECT_BRAKING ((void *)OBJ_VRAM0 + 0x2300)

#ifndef COLLECT_RINGS_ROM
#define RESERVED_INDICATOR_TILES_VRAM (void *)(OBJ_VRAM0 + 0x2700)
#else
#define RESERVED_INDICATOR_TILES_VRAM (void *)(OBJ_VRAM0 + 0x3640)
#endif

#define VRAM_RESERVED_WATER_SURFACE (void *)(OBJ_VRAM0 + 0x2980)
#define VRAM_RESERVED_BUBBLES_SMALL (void *)(OBJ_VRAM0 + 0x2A40)
#define VRAM_RESERVED_BUBBLES_GROUP (void *)(OBJ_VRAM0 + 0x2AC0)

#endif // GUARD_VRAM_HARDCODED_H
