
	.align 2
	.global gUnknown_02016E68
gUnknown_02016E68:
	.incbin "sound/direct_sound_samples/02016E68.bin"

	.align 2
	.global gUnknown_02017368
gUnknown_02017368:
	.incbin "sound/direct_sound_samples/02017368.bin"

	.align 2
	.global gUnknown_020178A0
gUnknown_020178A0:
	.incbin "sound/direct_sound_samples/020178A0.bin"

	.align 2
	.global gUnknown_02017D58
gUnknown_02017D58:
	.incbin "sound/direct_sound_samples/02017D58.bin"

	.align 2
	.global gUnknown_02018260
gUnknown_02018260:
	.incbin "sound/direct_sound_samples/02018260.bin"

	.align 2
	.global gUnknown_020186F4
gUnknown_020186F4:
	.incbin "sound/direct_sound_samples/020186F4.bin"

	.align 2
	.global gUnknown_020197C8
gUnknown_020197C8:
	.incbin "sound/direct_sound_samples/020197C8.bin"
