	.align 2
	.global ProgrammableWaveData_2016CCC
ProgrammableWaveData_2016CCC:
	.incbin "sound/programmable_wave_samples/02016CCC.pcm"

	.align 2
	.global ProgrammableWaveData_2016CDC
ProgrammableWaveData_2016CDC:
	.incbin "sound/programmable_wave_samples/02016CDC.pcm"

	.align 2
	.global ProgrammableWaveData_2016CEC
ProgrammableWaveData_2016CEC:
	.incbin "sound/programmable_wave_samples/02016CEC.pcm"

	.align 2
	.global ProgrammableWaveData_2016CFC
ProgrammableWaveData_2016CFC:
	.incbin "sound/programmable_wave_samples/02016CFC.pcm"

	.align 2
	.global ProgrammableWaveData_2016D0C
ProgrammableWaveData_2016D0C:
	.incbin "sound/programmable_wave_samples/02016D0C.pcm"

	.align 2
	.global ProgrammableWaveData_2016D1C
ProgrammableWaveData_2016D1C:
	.incbin "sound/programmable_wave_samples/02016D1C.pcm"

	.align 2
	.global ProgrammableWaveData_2016D2C
ProgrammableWaveData_2016D2C:
	.incbin "sound/programmable_wave_samples/02016D2C.pcm"

	.align 2
	.global ProgrammableWaveData_2016D3C
ProgrammableWaveData_2016D3C:
	.incbin "sound/programmable_wave_samples/02016D3C.pcm"

	.align 2
	.global ProgrammableWaveData_2016D4C
ProgrammableWaveData_2016D4C:
	.incbin "sound/programmable_wave_samples/02016D4C.pcm"
