	.align 2
	.global ProgrammableWaveData_2016CCC
ProgrammableWaveData_2016CCC:
	.incbin "sound/programmable_wave_samples/02.pcm"

	.align 2
	.global ProgrammableWaveData_2016CDC
ProgrammableWaveData_2016CDC:
	.incbin "sound/programmable_wave_samples/03.pcm"

	.align 2
	.global ProgrammableWaveData_2016CEC
ProgrammableWaveData_2016CEC:
	.incbin "sound/programmable_wave_samples/04.pcm"

	.align 2
	.global ProgrammableWaveData_2016CFC
ProgrammableWaveData_2016CFC:
	.incbin "sound/programmable_wave_samples/05.pcm"

	.align 2
	.global ProgrammableWaveData_2016D0C
ProgrammableWaveData_2016D0C:
	.incbin "sound/programmable_wave_samples/06.pcm"

	.align 2
	.global ProgrammableWaveData_2016D1C
ProgrammableWaveData_2016D1C:
	.incbin "sound/programmable_wave_samples/07.pcm"

	.align 2
	.global ProgrammableWaveData_2016D2C
ProgrammableWaveData_2016D2C:
	.incbin "sound/programmable_wave_samples/08.pcm"

	.align 2
	.global ProgrammableWaveData_2016D3C
ProgrammableWaveData_2016D3C:
	.incbin "sound/programmable_wave_samples/09.pcm"

	.align 2
	.global ProgrammableWaveData_2016D4C
ProgrammableWaveData_2016D4C:
	.incbin "sound/programmable_wave_samples/10.pcm"
