    mAlignWord
	.global gUnknown_086DE134
gUnknown_086DE134:
	.incbin "sound/sa1/direct_sound_samples/086DE134.bin"

	mAlignWord
	.global gUnknown_086DF608
gUnknown_086DF608:
	.incbin "sound/sa1/direct_sound_samples/086DF608.bin"

	mAlignWord
	.global gUnknown_086E0A1C
gUnknown_086E0A1C:
	.incbin "sound/sa1/direct_sound_samples/086E0A1C.bin"

	mAlignWord
	.global gUnknown_086E134C
gUnknown_086E134C:
	.incbin "sound/sa1/direct_sound_samples/086E134C.bin"

	mAlignWord
	.global gUnknown_086E1ABC
gUnknown_086E1ABC:
	.incbin "sound/sa1/direct_sound_samples/086E1ABC.bin"

	mAlignWord
	.global gUnknown_086E33B0
gUnknown_086E33B0:
	.incbin "sound/sa1/direct_sound_samples/086E33B0.bin"

	mAlignWord
	.global gUnknown_086E64DC
gUnknown_086E64DC:
	.incbin "sound/sa1/direct_sound_samples/086E64DC.bin"

	mAlignWord
	.global gUnknown_086E6B24
gUnknown_086E6B24:
	.incbin "sound/sa1/direct_sound_samples/086E6B24.bin"

	mAlignWord
	.global gUnknown_086EA218
gUnknown_086EA218:
	.incbin "sound/sa1/direct_sound_samples/086EA218.bin"

	mAlignWord
	.global gUnknown_086ED1F4
gUnknown_086ED1F4:
	.incbin "sound/sa1/direct_sound_samples/086ED1F4.bin"

	mAlignWord
	.global gUnknown_086F0138
gUnknown_086F0138:
	.incbin "sound/sa1/direct_sound_samples/086F0138.bin"

	mAlignWord
	.global gUnknown_086F1AC0
gUnknown_086F1AC0:
	.incbin "sound/sa1/direct_sound_samples/086F1AC0.bin"

	mAlignWord
	.global gUnknown_086F1DC0
gUnknown_086F1DC0:
	.incbin "sound/sa1/direct_sound_samples/086F1DC0.bin"

	mAlignWord
	.global gUnknown_086F2994
gUnknown_086F2994:
	.incbin "sound/sa1/direct_sound_samples/086F2994.bin"

	mAlignWord
	.global gUnknown_086F5578
gUnknown_086F5578:
	.incbin "sound/sa1/direct_sound_samples/086F5578.bin"

	mAlignWord
	.global gUnknown_086F836C
gUnknown_086F836C:
	.incbin "sound/sa1/direct_sound_samples/086F836C.bin"

	mAlignWord
	.global gUnknown_086FA790
gUnknown_086FA790:
	.incbin "sound/sa1/direct_sound_samples/086FA790.bin"

	mAlignWord
	.global gUnknown_086FAEA4
gUnknown_086FAEA4:
	.incbin "sound/sa1/direct_sound_samples/086FAEA4.bin"

	mAlignWord
	.global gUnknown_086FBBD4
gUnknown_086FBBD4:
	.incbin "sound/sa1/direct_sound_samples/086FBBD4.bin"

	mAlignWord
	.global gUnknown_086FE150
gUnknown_086FE150:
	.incbin "sound/sa1/direct_sound_samples/086FE150.bin"

	mAlignWord
	.global gUnknown_086FE7E4
gUnknown_086FE7E4:
	.incbin "sound/sa1/direct_sound_samples/086FE7E4.bin"

	mAlignWord
	.global gUnknown_086FF18C
gUnknown_086FF18C:
	.incbin "sound/sa1/direct_sound_samples/086FF18C.bin"

	mAlignWord
	.global gUnknown_0870224C
gUnknown_0870224C:
	.incbin "sound/sa1/direct_sound_samples/0870224C.bin"

	mAlignWord
	.global gUnknown_08702F60
gUnknown_08702F60:
	.incbin "sound/sa1/direct_sound_samples/08702F60.bin"

	mAlignWord
	.global gUnknown_0870613C
gUnknown_0870613C:
	.incbin "sound/sa1/direct_sound_samples/0870613C.bin"

	mAlignWord
	.global gUnknown_08708210
gUnknown_08708210:
	.incbin "sound/sa1/direct_sound_samples/08708210.bin"

	mAlignWord
	.global gUnknown_0870A724
gUnknown_0870A724:
	.incbin "sound/sa1/direct_sound_samples/0870A724.bin"

	mAlignWord
	.global gUnknown_0870CA4C
gUnknown_0870CA4C:
	.incbin "sound/sa1/direct_sound_samples/0870CA4C.bin"

	mAlignWord
	.global gUnknown_0870D7EC
gUnknown_0870D7EC:
	.incbin "sound/sa1/direct_sound_samples/0870D7EC.bin"

	mAlignWord
	.global gUnknown_0870DC84
gUnknown_0870DC84:
	.incbin "sound/sa1/direct_sound_samples/0870DC84.bin"

	mAlignWord
	.global gUnknown_0870E60C
gUnknown_0870E60C:
	.incbin "sound/sa1/direct_sound_samples/0870E60C.bin"

	mAlignWord
	.global gUnknown_0870EA00
gUnknown_0870EA00:
	.incbin "sound/sa1/direct_sound_samples/0870EA00.bin"

	mAlignWord
	.global gUnknown_0870EE50
gUnknown_0870EE50:
	.incbin "sound/sa1/direct_sound_samples/0870EE50.bin"

	mAlignWord
	.global gUnknown_0870F254
gUnknown_0870F254:
	.incbin "sound/sa1/direct_sound_samples/0870F254.bin"

	mAlignWord
	.global gUnknown_0870FBC0
gUnknown_0870FBC0:
	.incbin "sound/sa1/direct_sound_samples/0870FBC0.bin"

	mAlignWord
	.global gUnknown_0870FFA0
gUnknown_0870FFA0:
	.incbin "sound/sa1/direct_sound_samples/0870FFA0.bin"

	mAlignWord
	.global gUnknown_087103F8
gUnknown_087103F8:
	.incbin "sound/sa1/direct_sound_samples/087103F8.bin"

	mAlignWord
	.global gUnknown_08710D74
gUnknown_08710D74:
	.incbin "sound/sa1/direct_sound_samples/08710D74.bin"

	mAlignWord
	.global gUnknown_087111D4
gUnknown_087111D4:
	.incbin "sound/sa1/direct_sound_samples/087111D4.bin"

	mAlignWord
	.global gUnknown_08711640
gUnknown_08711640:
	.incbin "sound/sa1/direct_sound_samples/08711640.bin"

	mAlignWord
	.global gUnknown_08711ACC
gUnknown_08711ACC:
	.incbin "sound/sa1/direct_sound_samples/08711ACC.bin"

	mAlignWord
	.global gUnknown_087123F8
gUnknown_087123F8:
	.incbin "sound/sa1/direct_sound_samples/087123F8.bin"

	mAlignWord
	.global gUnknown_08712950
gUnknown_08712950:
	.incbin "sound/sa1/direct_sound_samples/08712950.bin"

	mAlignWord
	.global gUnknown_08712DB8
gUnknown_08712DB8:
	.incbin "sound/sa1/direct_sound_samples/08712DB8.bin"

	mAlignWord
	.global gUnknown_0871375C
gUnknown_0871375C:
	.incbin "sound/sa1/direct_sound_samples/0871375C.bin"

	mAlignWord
	.global gUnknown_0871AED4
gUnknown_0871AED4:
	.incbin "sound/sa1/direct_sound_samples/0871AED4.bin"

	mAlignWord
	.global spectrasonics__symphony_of_voices__partition_d__big_chord__big_min__c4_r
spectrasonics__symphony_of_voices__partition_d__big_chord__big_min__c4_r:
	.incbin "sound/sa1/direct_sound_samples/spectrasonics__symphony_of_voices__partition_d__big_chord__big_min__c4_r.bin"

	mAlignWord
	.global gUnknown_0871EF30
gUnknown_0871EF30:
	.incbin "sound/sa1/direct_sound_samples/0871EF30.bin"

	mAlignWord
	.global gUnknown_08727348
gUnknown_08727348:
	.incbin "sound/sa1/direct_sound_samples/08727348.bin"

	mAlignWord
	.global gUnknown_0872CF68
gUnknown_0872CF68:
	.incbin "sound/sa1/direct_sound_samples/0872CF68.bin"

	mAlignWord
	.global gUnknown_0872E77C
gUnknown_0872E77C:
	.incbin "sound/sa1/direct_sound_samples/0872E77C.bin"

	mAlignWord
	.global gUnknown_08730340
gUnknown_08730340:
	.incbin "sound/sa1/direct_sound_samples/08730340.bin"

	mAlignWord
	.global gUnknown_08730BF0
gUnknown_08730BF0:
	.incbin "sound/sa1/direct_sound_samples/08730BF0.bin"

	mAlignWord
	.global gUnknown_08731868
gUnknown_08731868:
	.incbin "sound/sa1/direct_sound_samples/08731868.bin"

	mAlignWord
	.global gUnknown_08732A00
gUnknown_08732A00:
	.incbin "sound/sa1/direct_sound_samples/08732A00.bin"

	mAlignWord
	.global gUnknown_08733304
gUnknown_08733304:
	.incbin "sound/sa1/direct_sound_samples/08733304.bin"

	mAlignWord
	.global gUnknown_08733D74
gUnknown_08733D74:
	.incbin "sound/sa1/direct_sound_samples/08733D74.bin"

	mAlignWord
	.global gUnknown_08737EB4
gUnknown_08737EB4:
	.incbin "sound/sa1/direct_sound_samples/08737EB4.bin"

	mAlignWord
	.global gUnknown_0873BCBC
gUnknown_0873BCBC:
	.incbin "sound/sa1/direct_sound_samples/0873BCBC.bin"

	mAlignWord
	.global gUnknown_0873C470
gUnknown_0873C470:
	.incbin "sound/sa1/direct_sound_samples/0873C470.bin"

	mAlignWord
	.global gUnknown_0873CC80
gUnknown_0873CC80:
	.incbin "sound/sa1/direct_sound_samples/0873CC80.bin"

	mAlignWord
	.global gUnknown_0873D430
gUnknown_0873D430:
	.incbin "sound/sa1/direct_sound_samples/0873D430.bin"

	mAlignWord
	.global gUnknown_0873DF74
gUnknown_0873DF74:
	.incbin "sound/sa1/direct_sound_samples/0873DF74.bin"

	mAlignWord
	.global gUnknown_0873ECE8
gUnknown_0873ECE8:
	.incbin "sound/sa1/direct_sound_samples/0873ECE8.bin"

	mAlignWord
	.global gUnknown_0873F1C0
gUnknown_0873F1C0:
	.incbin "sound/sa1/direct_sound_samples/0873F1C0.bin"

	mAlignWord
	.global gUnknown_0873F654
gUnknown_0873F654:
	.incbin "sound/sa1/direct_sound_samples/0873F654.bin"

	mAlignWord
	.global gUnknown_0873FAB8
gUnknown_0873FAB8:
	.incbin "sound/sa1/direct_sound_samples/0873FAB8.bin"

	mAlignWord
	.global gUnknown_0873FF64
gUnknown_0873FF64:
	.incbin "sound/sa1/direct_sound_samples/0873FF64.bin"

	mAlignWord
	.global gUnknown_087403FC
gUnknown_087403FC:
	.incbin "sound/sa1/direct_sound_samples/087403FC.bin"

	mAlignWord
	.global gUnknown_08740854
gUnknown_08740854:
	.incbin "sound/sa1/direct_sound_samples/08740854.bin"

	mAlignWord
	.global gUnknown_08740D00
gUnknown_08740D00:
	.incbin "sound/sa1/direct_sound_samples/08740D00.bin"

	mAlignWord
	.global gUnknown_08741248
gUnknown_08741248:
	.incbin "sound/sa1/direct_sound_samples/08741248.bin"

	mAlignWord
	.global gUnknown_08741694
gUnknown_08741694:
	.incbin "sound/sa1/direct_sound_samples/08741694.bin"

	mAlignWord
	.global gUnknown_08741B00
gUnknown_08741B00:
	.incbin "sound/sa1/direct_sound_samples/08741B00.bin"

	mAlignWord
	.global gUnknown_0874216C
gUnknown_0874216C:
	.incbin "sound/sa1/direct_sound_samples/0874216C.bin"

	mAlignWord
	.global gUnknown_087424D8
gUnknown_087424D8:
	.incbin "sound/sa1/direct_sound_samples/087424D8.bin"

	mAlignWord
	.global gUnknown_0874267C
gUnknown_0874267C:
	.incbin "sound/sa1/direct_sound_samples/0874267C.bin"

	mAlignWord
	.global gUnknown_08742E90
gUnknown_08742E90:
	.incbin "sound/sa1/direct_sound_samples/08742E90.bin"

	mAlignWord
	.global gUnknown_087432F0
gUnknown_087432F0:
	.incbin "sound/sa1/direct_sound_samples/087432F0.bin"

	mAlignWord
	.global gUnknown_087436FC
gUnknown_087436FC:
	.incbin "sound/sa1/direct_sound_samples/087436FC.bin"

	mAlignWord
	.global gUnknown_08743BEC
gUnknown_08743BEC:
	.incbin "sound/sa1/direct_sound_samples/08743BEC.bin"

	mAlignWord
	.global gUnknown_0874408C
gUnknown_0874408C:
	.incbin "sound/sa1/direct_sound_samples/0874408C.bin"

	mAlignWord
	.global gUnknown_087444B4
gUnknown_087444B4:
	.incbin "sound/sa1/direct_sound_samples/087444B4.bin"

	mAlignWord
	.global gUnknown_087449BC
gUnknown_087449BC:
	.incbin "sound/sa1/direct_sound_samples/087449BC.bin"

	mAlignWord
	.global gUnknown_0874621C
gUnknown_0874621C:
	.incbin "sound/sa1/direct_sound_samples/0874621C.bin"

	mAlignWord
	.global gUnknown_08746C04
gUnknown_08746C04:
	.incbin "sound/sa1/direct_sound_samples/08746C04.bin"

	mAlignWord
	.global gUnknown_08747908
gUnknown_08747908:
	.incbin "sound/sa1/direct_sound_samples/08747908.bin"

	mAlignWord
	.global gUnknown_08747D18
gUnknown_08747D18:
	.incbin "sound/sa1/direct_sound_samples/08747D18.bin"

	mAlignWord
	.global gUnknown_08748108
gUnknown_08748108:
	.incbin "sound/sa1/direct_sound_samples/08748108.bin"

	mAlignWord
	.global gUnknown_08748BD8
gUnknown_08748BD8:
	.incbin "sound/sa1/direct_sound_samples/08748BD8.bin"

	mAlignWord
	.global gUnknown_087493A4
gUnknown_087493A4:
	.incbin "sound/sa1/direct_sound_samples/087493A4.bin"

	mAlignWord
	.global gUnknown_08749864
gUnknown_08749864:
	.incbin "sound/sa1/direct_sound_samples/08749864.bin"

	mAlignWord
	.global gUnknown_08749D20
gUnknown_08749D20:
	.incbin "sound/sa1/direct_sound_samples/08749D20.bin"

	mAlignWord
	.global gUnknown_0874A750
gUnknown_0874A750:
	.incbin "sound/sa1/direct_sound_samples/0874A750.bin"

	mAlignWord
	.global gUnknown_0874AAF8
gUnknown_0874AAF8:
	.incbin "sound/sa1/direct_sound_samples/0874AAF8.bin"

	mAlignWord
	.global gUnknown_0874B5D0
gUnknown_0874B5D0:
	.incbin "sound/sa1/direct_sound_samples/0874B5D0.bin"

	mAlignWord
	.global gUnknown_0874B844
gUnknown_0874B844:
	.incbin "sound/sa1/direct_sound_samples/0874B844.bin"

	mAlignWord
	.global gUnknown_0874CAFC
gUnknown_0874CAFC:
	.incbin "sound/sa1/direct_sound_samples/0874CAFC.bin"

	mAlignWord
	.global gUnknown_0874D4D0
gUnknown_0874D4D0:
	.incbin "sound/sa1/direct_sound_samples/0874D4D0.bin"

	mAlignWord
	.global gUnknown_0874DDCC
gUnknown_0874DDCC:
	.incbin "sound/sa1/direct_sound_samples/0874DDCC.bin"

	mAlignWord
	.global gUnknown_0874E228
gUnknown_0874E228:
	.incbin "sound/sa1/direct_sound_samples/0874E228.bin"

	mAlignWord
	.global gUnknown_0874E6D0
gUnknown_0874E6D0:
	.incbin "sound/sa1/direct_sound_samples/0874E6D0.bin"

	mAlignWord
	.global gUnknown_08753AEC
gUnknown_08753AEC:
	.incbin "sound/sa1/direct_sound_samples/08753AEC.bin"

	mAlignWord
	.global gUnknown_08758BB4
gUnknown_08758BB4:
	.incbin "sound/sa1/direct_sound_samples/08758BB4.bin"

	mAlignWord
	.global gUnknown_0875A76C
gUnknown_0875A76C:
	.incbin "sound/sa1/direct_sound_samples/0875A76C.bin"

	mAlignWord
	.global gUnknown_0875E854
gUnknown_0875E854:
	.incbin "sound/sa1/direct_sound_samples/0875E854.bin"

	mAlignWord
	.global gUnknown_087634B0
gUnknown_087634B0:
	.incbin "sound/sa1/direct_sound_samples/087634B0.bin"

	mAlignWord
	.global gUnknown_08763F44
gUnknown_08763F44:
	.incbin "sound/sa1/direct_sound_samples/08763F44.bin"

	mAlignWord
	.global gUnknown_087644B8
gUnknown_087644B8:
	.incbin "sound/sa1/direct_sound_samples/087644B8.bin"

	mAlignWord
	.global gUnknown_08764A24
gUnknown_08764A24:
	.incbin "sound/sa1/direct_sound_samples/08764A24.bin"

	mAlignWord
	.global gUnknown_08764EC8
gUnknown_08764EC8:
	.incbin "sound/sa1/direct_sound_samples/08764EC8.bin"

	mAlignWord
	.global gUnknown_08765524
gUnknown_08765524:
	.incbin "sound/sa1/direct_sound_samples/08765524.bin"

	mAlignWord
	.global gUnknown_08765FF0
gUnknown_08765FF0:
	.incbin "sound/sa1/direct_sound_samples/08765FF0.bin"

	mAlignWord
	.global gUnknown_087665C8
gUnknown_087665C8:
	.incbin "sound/sa1/direct_sound_samples/087665C8.bin"

	mAlignWord
	.global gUnknown_08766AE4
gUnknown_08766AE4:
	.incbin "sound/sa1/direct_sound_samples/08766AE4.bin"

	mAlignWord
	.global gUnknown_0876701C
gUnknown_0876701C:
	.incbin "sound/sa1/direct_sound_samples/0876701C.bin"

	mAlignWord
	.global gUnknown_08767588
gUnknown_08767588:
	.incbin "sound/sa1/direct_sound_samples/08767588.bin"

	mAlignWord
	.global gUnknown_08767A20
gUnknown_08767A20:
	.incbin "sound/sa1/direct_sound_samples/08767A20.bin"

	mAlignWord
	.global gUnknown_08768070
gUnknown_08768070:
	.incbin "sound/sa1/direct_sound_samples/08768070.bin"

	mAlignWord
	.global gUnknown_08768BA0
gUnknown_08768BA0:
	.incbin "sound/sa1/direct_sound_samples/08768BA0.bin"

	mAlignWord
	.global gUnknown_087692C0
gUnknown_087692C0:
	.incbin "sound/sa1/direct_sound_samples/087692C0.bin"

	mAlignWord
	.global gUnknown_0876995C
gUnknown_0876995C:
	.incbin "sound/sa1/direct_sound_samples/0876995C.bin"

	mAlignWord
	.global gUnknown_0876A058
gUnknown_0876A058:
	.incbin "sound/sa1/direct_sound_samples/0876A058.bin"

	mAlignWord
	.global gUnknown_0876A7E8
gUnknown_0876A7E8:
	.incbin "sound/sa1/direct_sound_samples/0876A7E8.bin"

	mAlignWord
	.global gUnknown_0876AE6C
gUnknown_0876AE6C:
	.incbin "sound/sa1/direct_sound_samples/0876AE6C.bin"

	mAlignWord
	.global gUnknown_0876B5CC
gUnknown_0876B5CC:
	.incbin "sound/sa1/direct_sound_samples/0876B5CC.bin"

	mAlignWord
	.global gUnknown_0876BCBC
gUnknown_0876BCBC:
	.incbin "sound/sa1/direct_sound_samples/0876BCBC.bin"

	mAlignWord
	.global gUnknown_0876C1C4
gUnknown_0876C1C4:
	.incbin "sound/sa1/direct_sound_samples/0876C1C4.bin"

	mAlignWord
	.global gUnknown_0876C974
gUnknown_0876C974:
	.incbin "sound/sa1/direct_sound_samples/0876C974.bin"

	mAlignWord
	.global gUnknown_0876D0E8
gUnknown_0876D0E8:
	.incbin "sound/sa1/direct_sound_samples/0876D0E8.bin"

	mAlignWord
	.global gUnknown_0876D79C
gUnknown_0876D79C:
	.incbin "sound/sa1/direct_sound_samples/0876D79C.bin"

	mAlignWord
	.global gUnknown_0876DF8C
gUnknown_0876DF8C:
	.incbin "sound/sa1/direct_sound_samples/0876DF8C.bin"

	mAlignWord
	.global gUnknown_0876E614
gUnknown_0876E614:
	.incbin "sound/sa1/direct_sound_samples/0876E614.bin"

	mAlignWord
	.global gUnknown_0876ED88
gUnknown_0876ED88:
	.incbin "sound/sa1/direct_sound_samples/0876ED88.bin"

	mAlignWord
	.global gUnknown_0876F47C
gUnknown_0876F47C:
	.incbin "sound/sa1/direct_sound_samples/0876F47C.bin"

	mAlignWord
	.global gUnknown_0876FB20
gUnknown_0876FB20:
	.incbin "sound/sa1/direct_sound_samples/0876FB20.bin"

	mAlignWord
	.global gUnknown_08771CC4
gUnknown_08771CC4:
	.incbin "sound/sa1/direct_sound_samples/08771CC4.bin"

	mAlignWord
	.global gUnknown_08773848
gUnknown_08773848:
	.incbin "sound/sa1/direct_sound_samples/08773848.bin"

	mAlignWord
	.global gUnknown_08775640
gUnknown_08775640:
	.incbin "sound/sa1/direct_sound_samples/08775640.bin"

	mAlignWord
	.global gUnknown_08775E7C
gUnknown_08775E7C:
	.incbin "sound/sa1/direct_sound_samples/08775E7C.bin"

	mAlignWord
	.global gUnknown_08778D48
gUnknown_08778D48:
	.incbin "sound/sa1/direct_sound_samples/08778D48.bin"

	mAlignWord
	.global gUnknown_08779EDC
gUnknown_08779EDC:
	.incbin "sound/sa1/direct_sound_samples/08779EDC.bin"

	mAlignWord
	.global gUnknown_0877AD00
gUnknown_0877AD00:
	.incbin "sound/sa1/direct_sound_samples/0877AD00.bin"

	mAlignWord
	.global gUnknown_0877B9A0
gUnknown_0877B9A0:
	.incbin "sound/sa1/direct_sound_samples/0877B9A0.bin"

	mAlignWord
	.global gUnknown_0877CF24
gUnknown_0877CF24:
	.incbin "sound/sa1/direct_sound_samples/0877CF24.bin"

	mAlignWord
	.global gUnknown_0877F2A4
gUnknown_0877F2A4:
	.incbin "sound/sa1/direct_sound_samples/0877F2A4.bin"

	mAlignWord
	.global gUnknown_0878306C
gUnknown_0878306C:
	.incbin "sound/sa1/direct_sound_samples/0878306C.bin"

	mAlignWord
	.global gUnknown_08789214
gUnknown_08789214:
	.incbin "sound/sa1/direct_sound_samples/08789214.bin"

	mAlignWord
	.global gUnknown_0878D964
gUnknown_0878D964:
	.incbin "sound/sa1/direct_sound_samples/0878D964.bin"

	mAlignWord
	.global gUnknown_0878FAAC
gUnknown_0878FAAC:
	.incbin "sound/sa1/direct_sound_samples/0878FAAC.bin"

	mAlignWord
	.global gUnknown_08797224
gUnknown_08797224:
	.incbin "sound/sa1/direct_sound_samples/08797224.bin"
