	mAlignWord
	.global ProgrammableWaveData_86DD6D0
ProgrammableWaveData_86DD6D0:
	.incbin "sound/shared/programmable_wave_samples/02.pcm"

	mAlignWord
	.global ProgrammableWaveData_86DD6E0
ProgrammableWaveData_86DD6E0:
	.incbin "sound/shared/programmable_wave_samples/03.pcm"

	mAlignWord
	.global ProgrammableWaveData_86DD6F0
ProgrammableWaveData_86DD6F0:
	.incbin "sound/shared/programmable_wave_samples/04.pcm"

	mAlignWord
	.global ProgrammableWaveData_86DD700
ProgrammableWaveData_86DD700:
	.incbin "sound/shared/programmable_wave_samples/05.pcm"

	mAlignWord
	.global ProgrammableWaveData_86DD710
ProgrammableWaveData_86DD710:
	.incbin "sound/shared/programmable_wave_samples/06.pcm"

	mAlignWord
	.global ProgrammableWaveData_86DD720
ProgrammableWaveData_86DD720:
	.incbin "sound/shared/programmable_wave_samples/07.pcm"

	mAlignWord
	.global ProgrammableWaveData_86DD730
ProgrammableWaveData_86DD730:
	.incbin "sound/shared/programmable_wave_samples/08.pcm"

	mAlignWord
	.global ProgrammableWaveData_86DD740
ProgrammableWaveData_86DD740:
	.incbin "sound/shared/programmable_wave_samples/09.pcm"

	mAlignWord
	.global ProgrammableWaveData_86DD750
ProgrammableWaveData_86DD750:
	.incbin "sound/shared/programmable_wave_samples/10.pcm"
