    mAlignWord
	.global C_DECL(gSongTable)
C_DECL(gSongTable):	@ 0x086DD790
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(song001), 0, 0
mAlignWord
	song C_DECL(song002), 0, 0
mAlignWord
	song C_DECL(song003), 0, 0
mAlignWord
	song C_DECL(song004), 0, 0
mAlignWord
	song C_DECL(song005), 0, 0
mAlignWord
	song C_DECL(song006), 0, 0
mAlignWord
	song C_DECL(song007), 0, 0
mAlignWord
	song C_DECL(song008), 0, 0
mAlignWord
	song C_DECL(song009), 0, 0
mAlignWord
	song C_DECL(song010), 0, 0
mAlignWord
	song C_DECL(song011), 0, 0
mAlignWord
	song C_DECL(song012), 0, 0
mAlignWord
	song C_DECL(song013), 0, 0
mAlignWord
	song C_DECL(song014), 0, 0
mAlignWord
	song C_DECL(song015), 0, 0
mAlignWord
	song C_DECL(song016), 0, 0
mAlignWord
	song C_DECL(song017), 0, 0
mAlignWord
	song C_DECL(song018), 0, 0
mAlignWord
	song C_DECL(song019), 0, 0
mAlignWord
	song C_DECL(song020), 0, 0
mAlignWord
	song C_DECL(song021), 0, 0
mAlignWord
	song C_DECL(song022), 0, 0
mAlignWord
	song C_DECL(song023), 0, 0
mAlignWord
	song C_DECL(song024), 0, 0
mAlignWord
	song C_DECL(song025), 0, 0
mAlignWord
	song C_DECL(song026), 0, 0
mAlignWord
	song C_DECL(song027), 0, 0
mAlignWord
	song C_DECL(song028), 0, 0
mAlignWord
	song C_DECL(song029), 0, 0
mAlignWord
	song C_DECL(song030), 0, 0
mAlignWord
	song C_DECL(song031), 0, 0
mAlignWord
	song C_DECL(song032), 0, 0
mAlignWord
	song C_DECL(song033), 0, 0
mAlignWord
	song C_DECL(song034), 0, 0
mAlignWord
	song C_DECL(song035), 0, 0
mAlignWord
	song C_DECL(song036), 0, 0
mAlignWord
	song C_DECL(song037), 0, 0
mAlignWord
	song C_DECL(song038), 1, 1
mAlignWord
	song C_DECL(song039), 1, 1
mAlignWord
	song C_DECL(song040), 1, 1
mAlignWord
	song C_DECL(song041), 0, 0
mAlignWord
	song C_DECL(song042), 0, 0
mAlignWord
	song C_DECL(mus_sp_stage_trick), 0, 0
mAlignWord
	song C_DECL(song044), 0, 0
mAlignWord
	song C_DECL(song045), 0, 0
mAlignWord
	song C_DECL(song046), 0, 0
mAlignWord
	song C_DECL(song047), 0, 0
mAlignWord
	song C_DECL(song048), 0, 0
mAlignWord
	song C_DECL(song049), 0, 0
mAlignWord
	song C_DECL(song050), 0, 0
mAlignWord
	song C_DECL(song051), 0, 0
mAlignWord
	song C_DECL(song052), 0, 0
mAlignWord
	song C_DECL(song053), 0, 0
mAlignWord
	song C_DECL(song054), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(song102), 3, 3
mAlignWord
	song C_DECL(song103), 3, 3
mAlignWord
	song C_DECL(song104), 3, 3
mAlignWord
	song C_DECL(song105), 3, 3
mAlignWord
	song C_DECL(song106), 2, 2
mAlignWord
	song C_DECL(song107), 2, 2
mAlignWord
	song C_DECL(song108), 2, 2
mAlignWord
	song C_DECL(song109), 3, 3
mAlignWord
	song C_DECL(song110), 2, 2
mAlignWord
	song C_DECL(song111), 3, 3
mAlignWord
	song C_DECL(song112), 3, 3
mAlignWord
	song C_DECL(song113), 2, 2
mAlignWord
	song C_DECL(song114), 2, 2
mAlignWord
	song C_DECL(song115), 2, 2
mAlignWord
	song C_DECL(song116), 2, 2
mAlignWord
	song C_DECL(se_ring_copy), 3, 3
mAlignWord
	song C_DECL(song118), 3, 3
mAlignWord
	song C_DECL(song119), 2, 2
mAlignWord
	song C_DECL(song120), 3, 3
mAlignWord
	song C_DECL(song121), 3, 3
mAlignWord
	song C_DECL(song122), 3, 3
mAlignWord
	song C_DECL(song123), 3, 3
mAlignWord
	song C_DECL(song124), 3, 3
mAlignWord
	song C_DECL(song125), 3, 3
mAlignWord
	song C_DECL(song126), 3, 3
mAlignWord
	song C_DECL(song127), 3, 3
mAlignWord
	song C_DECL(song128), 3, 3
mAlignWord
	song C_DECL(song129), 3, 3
mAlignWord
	song C_DECL(song130), 3, 3
mAlignWord
	song C_DECL(song131), 3, 3
mAlignWord
	song C_DECL(song132), 3, 3
mAlignWord
	song C_DECL(song133), 3, 3
mAlignWord
	song C_DECL(song134), 3, 3
mAlignWord
	song C_DECL(song135), 3, 3
mAlignWord
	song C_DECL(song136), 3, 3
mAlignWord
	song C_DECL(song137), 3, 3
mAlignWord
	song C_DECL(song138), 2, 2
mAlignWord
	song C_DECL(song139), 2, 2
mAlignWord
	song C_DECL(song140), 2, 2
mAlignWord
	song C_DECL(song141), 3, 3
mAlignWord
	song C_DECL(song142), 3, 3
mAlignWord
	song C_DECL(song143), 1, 1
mAlignWord
	song C_DECL(song144), 3, 3
mAlignWord
	song C_DECL(song145), 3, 3
mAlignWord
	song C_DECL(song146), 3, 3
mAlignWord
	song C_DECL(song147), 3, 3
mAlignWord
	song C_DECL(song148), 3, 3
mAlignWord
	song C_DECL(song149), 3, 3
mAlignWord
	song C_DECL(song150), 3, 3
mAlignWord
	song C_DECL(song151), 3, 3
mAlignWord
	song C_DECL(song152), 3, 3
mAlignWord
	song C_DECL(song153), 3, 3
mAlignWord
	song C_DECL(song154), 3, 3
mAlignWord
	song C_DECL(song155), 3, 3
mAlignWord
	song C_DECL(song156), 3, 3
mAlignWord
	song C_DECL(song157), 3, 3
mAlignWord
	song C_DECL(song158), 3, 3
mAlignWord
	song C_DECL(song159), 3, 3
mAlignWord
	song C_DECL(song160), 3, 3
mAlignWord
	song C_DECL(song161), 3, 3
mAlignWord
	song C_DECL(song162), 3, 3
mAlignWord
	song C_DECL(song163), 3, 3
mAlignWord
	song C_DECL(song164), 3, 3
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(song166), 3, 3
mAlignWord
	song C_DECL(song167), 2, 2
mAlignWord
	song C_DECL(song168), 2, 2
mAlignWord
	song C_DECL(song169), 2, 2
mAlignWord
	song C_DECL(song170), 2, 2
mAlignWord
	song C_DECL(song171), 2, 2
mAlignWord
	song C_DECL(song172), 2, 2
mAlignWord
	song C_DECL(song173), 2, 2
mAlignWord
	song C_DECL(song174), 2, 2
mAlignWord
	song C_DECL(song175), 2, 2
mAlignWord
	song C_DECL(song176), 2, 2
mAlignWord
	song C_DECL(song177), 2, 2
mAlignWord
	song C_DECL(song178), 2, 2
mAlignWord
	song C_DECL(song179), 2, 2
mAlignWord
	song C_DECL(song180), 2, 2
mAlignWord
	song C_DECL(song181), 2, 2
mAlignWord
	song C_DECL(song182), 2, 2
mAlignWord
	song C_DECL(song183), 2, 2
mAlignWord
	song C_DECL(song184), 2, 2
mAlignWord
	song C_DECL(song185), 2, 2
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(song188), 2, 2
mAlignWord
	song C_DECL(song189), 2, 2
mAlignWord
	song C_DECL(song190), 2, 2
mAlignWord
	song C_DECL(song191), 2, 2
mAlignWord
	song C_DECL(song192), 2, 2
mAlignWord
	song C_DECL(song193), 2, 2
mAlignWord
	song C_DECL(song194), 2, 2
mAlignWord
	song C_DECL(song195), 2, 2
mAlignWord
	song C_DECL(song196), 2, 2
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(song198), 2, 2
mAlignWord
	song C_DECL(song199), 2, 2
mAlignWord
	song C_DECL(song200), 2, 2
mAlignWord
	song C_DECL(song201), 2, 2
mAlignWord
	song C_DECL(song202), 2, 2
mAlignWord
	song C_DECL(song203), 2, 2
mAlignWord
	song C_DECL(song204), 2, 2
mAlignWord
	song C_DECL(song205), 2, 2
mAlignWord
	song C_DECL(song206), 2, 2
mAlignWord
	song C_DECL(song207), 2, 2
mAlignWord
	song C_DECL(song208), 2, 2
mAlignWord
	song C_DECL(song209), 2, 2
mAlignWord
	song C_DECL(song210), 2, 2
mAlignWord
	song C_DECL(song211), 2, 2
mAlignWord
	song C_DECL(song212), 2, 2
mAlignWord
	song C_DECL(song213), 2, 2
mAlignWord
	song C_DECL(song214), 2, 2
mAlignWord
	song C_DECL(song215), 3, 3
mAlignWord
	song C_DECL(song216), 3, 3
mAlignWord
	song C_DECL(song217), 3, 3
mAlignWord
	song C_DECL(song218), 3, 3
mAlignWord
	song C_DECL(song219), 3, 3
mAlignWord
	song C_DECL(song220), 3, 3
mAlignWord
	song C_DECL(song221), 3, 3
mAlignWord
	song C_DECL(song222), 3, 3
mAlignWord
	song C_DECL(song223), 3, 3
mAlignWord
	song C_DECL(song224), 3, 3
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(dummy_song_header), 0, 0
mAlignWord
	song C_DECL(song301), 0, 0
mAlignWord
	song C_DECL(song302), 0, 0
mAlignWord
	song C_DECL(song303), 0, 0
mAlignWord
	song C_DECL(song304), 0, 0
mAlignWord
	song C_DECL(song305), 0, 0
mAlignWord
	song C_DECL(song306), 0, 0
mAlignWord
	song C_DECL(song307), 0, 0

    mAlignWord
C_DECL(dummy_song_header):	@ 0x086DE130
	.byte	0		@ trackCount
	.byte	0		@ blockCount
	.byte	0		@ priority
	.byte	0		@ reverb
