

anim_data__0925_0:
	mGetPalette 0x1CF, 16, 0x60
	.4byte	30, -1

	mGetPalette 0x1D0, 16, 0x60
	.4byte	7, -1

	mGetPalette 0x1D1, 16, 0x60
	.4byte	7, -1

	mGetPalette 0x1D2, 16, 0x60
	.4byte	7, -1

	mGetPalette 0x1D3, 16, 0x60
	.4byte	7, -1

	mGetPalette 0x1D4, 16, 0x60
	.4byte	30, -1

	mGetPalette 0x1D5, 16, 0x60
	.4byte	7, -1

	mGetPalette 0x1D6, 16, 0x60
	.4byte	7, -1

	mGetPalette 0x1D7, 16, 0x60
	.4byte	7, -1

	mGetPalette 0x1D8, 16, 0x60
	.4byte	7, -1

	mGetPalette 0x1D9, 16, 0x60
	.4byte	30, -1

	mGetPalette 0x1DA, 16, 0x60
	.4byte	7, -1

	mGetPalette 0x1DB, 16, 0x60
	.4byte	7, -1

	mGetPalette 0x1DC, 16, 0x60
	.4byte	7, -1

	mGetPalette 0x1DD, 16, 0x60
	.4byte	7, -1

	mJumpBack 0x4B


anim_0925:
	.4byte anim_data__0925_0
