

anim_data__0943_0:
	mGetPalette 0x289 16 0xE0
	.4byte	40, -1

	mGetPalette 0x28A 16 0xE0
	.4byte	7, -1

	mGetPalette 0x28B 16 0xE0
	.4byte	7, -1

	mGetPalette 0x28C 16 0xE0
	.4byte	7, -1

	mGetPalette 0x28D 16 0xE0
	.4byte	7, -1

	mGetPalette 0x28E 16 0xE0
	.4byte	7, -1

	mGetPalette 0x28F 16 0xE0
	.4byte	40, -1

	mGetPalette 0x28E 16 0xE0
	.4byte	7, -1

	mGetPalette 0x28D 16 0xE0
	.4byte	7, -1

	mGetPalette 0x28C 16 0xE0
	.4byte	7, -1

	mGetPalette 0x28B 16 0xE0
	.4byte	7, -1

	mGetPalette 0x28A 16 0xE0
	.4byte	7, -1

	mJumpBack 0x3C


anim_0943:
	.4byte anim_data__0943_0
