

anim_data__0739_0:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1ECC4, 64
	.4byte	1, 0

	mAnimCmd4 

anim_data__0739_1:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1ED04, 64
	.4byte	1, 1

	mAnimCmd4 

anim_data__0739_2:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1ED44, 64
	.4byte	1, 2

	mAnimCmd4 

anim_data__0739_3:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1ED84, 64
	.4byte	1, 3

	mAnimCmd4 

anim_data__0739_4:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EDC4, 64
	.4byte	1, 4

	mAnimCmd4 

anim_data__0739_5:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EE04, 64
	.4byte	1, 5

	mAnimCmd4 

anim_data__0739_6:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EE44, 64
	.4byte	1, 6

	mAnimCmd4 

anim_data__0739_7:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EE84, 64
	.4byte	1, 7

	mAnimCmd4 

anim_data__0739_8:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EEC4, 64
	.4byte	1, 8

	mAnimCmd4 

anim_data__0739_9:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EF04, 64
	.4byte	1, 9

	mAnimCmd4 

anim_data__0739_10:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EF44, 64
	.4byte	1, 10

	mAnimCmd4 

anim_data__0739_11:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EF84, 64
	.4byte	1, 11

	mAnimCmd4 


anim_0739:
	.4byte anim_data__0739_0
	.4byte anim_data__0739_1
	.4byte anim_data__0739_2
	.4byte anim_data__0739_3
	.4byte anim_data__0739_4
	.4byte anim_data__0739_5
	.4byte anim_data__0739_6
	.4byte anim_data__0739_7
	.4byte anim_data__0739_8
	.4byte anim_data__0739_9
	.4byte anim_data__0739_10
	.4byte anim_data__0739_11
