

anim_data__0885_0:
	mGetPalette 0xA3, 16, 0x70
	mGetTiles 0x242C2, 2
	.4byte	1, 0

	mAnimCmd4 

anim_data__0885_1:
	mGetPalette 0xA3, 16, 0x70
	mGetTiles 0x242C4, 2
	.4byte	1, 1

	mAnimCmd4 

anim_data__0885_2:
	mGetPalette 0xA3, 16, 0x70
	mGetTiles 0x242C6, 2
	.4byte	1, 2

	mAnimCmd4 

anim_data__0885_3:
	mGetPalette 0xA3, 16, 0x70
	mGetTiles 0x242C8, 2
	.4byte	1, 3

	mAnimCmd4 

anim_data__0885_4:
	mGetPalette 0xA3, 16, 0x70
	mGetTiles 0x242CA, 2
	.4byte	1, 4

	mAnimCmd4 

anim_data__0885_5:
	mGetPalette 0xA3, 16, 0x70
	mGetTiles 0x242CC, 2
	.4byte	1, 5

	mAnimCmd4 

anim_data__0885_6:
	mGetPalette 0xA3, 16, 0x70
	mGetTiles 0x242CE, 2
	.4byte	1, 6

	mAnimCmd4 

anim_data__0885_7:
	mGetPalette 0xA3, 16, 0x70
	mGetTiles 0x242D0, 2
	.4byte	1, 7

	mAnimCmd4 


anim_0885:
	.4byte anim_data__0885_0
	.4byte anim_data__0885_1
	.4byte anim_data__0885_2
	.4byte anim_data__0885_3
	.4byte anim_data__0885_4
	.4byte anim_data__0885_5
	.4byte anim_data__0885_6
	.4byte anim_data__0885_7
