

anim_data__0737_0:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EABC, 16
	.4byte	1, 0

	mAnimCmd4 

anim_data__0737_1:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EACC, 16
	.4byte	1, 1

	mAnimCmd4 

anim_data__0737_2:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EADC, 16
	.4byte	1, 2

	mAnimCmd4 

anim_data__0737_3:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EAEC, 16
	.4byte	1, 3

	mAnimCmd4 

anim_data__0737_4:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EAFC, 16
	.4byte	1, 4

	mAnimCmd4 

anim_data__0737_5:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EB0C, 64
	.4byte	1, 5

	mAnimCmd4 

anim_data__0737_6:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EB4C, 64
	.4byte	1, 6

	mAnimCmd4 

anim_data__0737_7:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EB8C, 64
	.4byte	1, 7

	mAnimCmd4 

anim_data__0737_8:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EBCC, 64
	.4byte	1, 8

	mAnimCmd4 

anim_data__0737_9:
	mGetPalette 0xAC, 16, 0x20
	mGetTiles 0x1EC0C, 64
	.4byte	1, 9

	mAnimCmd4 


anim_0737:
	.4byte anim_data__0737_0
	.4byte anim_data__0737_1
	.4byte anim_data__0737_2
	.4byte anim_data__0737_3
	.4byte anim_data__0737_4
	.4byte anim_data__0737_5
	.4byte anim_data__0737_6
	.4byte anim_data__0737_7
	.4byte anim_data__0737_8
	.4byte anim_data__0737_9
