

anim_data__1077_0:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28E64 6
	.4byte	1, 0

	mAnimCmd4 

anim_data__1077_1:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28E6A 6
	.4byte	1, 1

	mAnimCmd4 

anim_data__1077_2:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28E70 12
	.4byte	1, 2

	mAnimCmd4 

anim_data__1077_3:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28E7C 8
	.4byte	1, 3

	mAnimCmd4 

anim_data__1077_4:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28E84 8
	.4byte	1, 4

	mAnimCmd4 

anim_data__1077_5:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28E8C 8
	.4byte	1, 5

	mAnimCmd4 

anim_data__1077_6:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28E94 8
	.4byte	1, 6

	mAnimCmd4 

anim_data__1077_7:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28E9C 12
	.4byte	1, 7

	mAnimCmd4 


anim_1077:
	.4byte anim_data__1077_0
	.4byte anim_data__1077_1
	.4byte anim_data__1077_2
	.4byte anim_data__1077_3
	.4byte anim_data__1077_4
	.4byte anim_data__1077_5
	.4byte anim_data__1077_6
	.4byte anim_data__1077_7
