

anim_data__0462_0:
	mGetPalette 0x27 16 0xE0
	mGetTiles 0x17F80 9
	.4byte	4, 0

	mGetTiles 0x17F89 9
	.4byte	4, 1

	mGetTiles 0x17F92 9
	.4byte	4, 2

	mGetTiles 0x17F9B 9
	.4byte	4, 3

	mGetTiles 0x17FA4 9
	.4byte	4, 4

	mGetTiles 0x17FAD 9
	.4byte	4, 5

	mGetTiles 0x17FB6 9
	.4byte	4, 6

	mGetTiles 0x17FBF 9
	.4byte	4, 7

	mGetTiles 0x17FC8 9
	.4byte	4, 8

	mGetTiles 0x17FD1 9
	.4byte	4, 9

	mGetTiles 0x17FDA 9
	.4byte	4, 10

	mGetTiles 0x17FE3 9
	.4byte	4, 11

	mGetTiles 0x17FEC 9
	.4byte	4, 12

	mGetTiles 0x17FF5 9
	.4byte	4, 13

	mGetTiles 0x17FFE 9
	.4byte	4, 14

	mGetTiles 0x18007 9
	.4byte	4, 15

	mGetTiles 0x18010 9
	.4byte	4, 16

	mGetTiles 0x18019 9
	.4byte	4, 17

	mJumpBack 0x5D


anim_0462:
	.4byte anim_data__0462_0
