

anim_data__0060_0:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x3439, 28
	mAnimCmd6 0x0, 0xF806DAFA
	.4byte	1, 0

	mAnimCmd4 

anim_data__0060_1:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x3455, 18
	mAnimCmd6 0x0, 0xF8FEDCEC
	.4byte	1, 1

	mAnimCmd4 

anim_data__0060_2:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x3467, 24
	mAnimCmd6 0x0, 0xFEF8EAE6
	.4byte	1, 2

	mAnimCmd4 

anim_data__0060_3:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x347F, 25
	mAnimCmd6 0x0, 0xAF2F5DD
	.4byte	1, 3

	mAnimCmd4 

anim_data__0060_4:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x3498, 24
	mAnimCmd6 0x0, 0x16F802D8
	.4byte	1, 4

	mAnimCmd4 

anim_data__0060_5:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x34B0, 30
	mAnimCmd6 0x0, 0x1EFE0AE4
	.4byte	1, 5

	mAnimCmd4 

anim_data__0060_6:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x34CE, 21
	mAnimCmd6 0x0, 0x2A060CFA
	.4byte	1, 6

	mAnimCmd4 

anim_data__0060_7:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x34E3, 30
	mAnimCmd6 0x0, 0x221C0804
	.4byte	1, 7

	mAnimCmd4 

anim_data__0060_8:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x3501, 24
	mAnimCmd6 0x0, 0x12240208
	.4byte	1, 8

	mAnimCmd4 

anim_data__0060_9:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x3519, 24
	mAnimCmd6 0x0, 0x826F80A
	.4byte	1, 9

	mAnimCmd4 

anim_data__0060_10:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x3531, 20
	mAnimCmd6 0x0, 0xFE1EEC08
	.4byte	1, 10

	mAnimCmd4 

anim_data__0060_11:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x3545, 28
	mAnimCmd6 0x0, 0xF610DE00
	.4byte	1, 11

	mAnimCmd4 


anim_0060:
	.4byte anim_data__0060_0
	.4byte anim_data__0060_1
	.4byte anim_data__0060_2
	.4byte anim_data__0060_3
	.4byte anim_data__0060_4
	.4byte anim_data__0060_5
	.4byte anim_data__0060_6
	.4byte anim_data__0060_7
	.4byte anim_data__0060_8
	.4byte anim_data__0060_9
	.4byte anim_data__0060_10
	.4byte anim_data__0060_11
