

anim_data__0758_0:
	mGetPalette 0xA3 16 0x90
	mGetTiles 0x1F745 4
	.4byte	1, 0

	mAnimCmd4 

anim_data__0758_1:
	mGetPalette 0xA3 16 0x90
	mGetTiles 0x1F749 4
	.4byte	1, 1

	mAnimCmd4 

anim_data__0758_2:
	mGetPalette 0xA3 16 0x90
	mGetTiles 0x1F74D 4
	.4byte	1, 2

	mAnimCmd4 

anim_data__0758_3:
	mGetPalette 0xA3 16 0x90
	mGetTiles 0x1F751 4
	.4byte	1, 3

	mAnimCmd4 

anim_data__0758_4:
	mGetPalette 0xA3 16 0x90
	mGetTiles 0x1F755 4
	.4byte	1, 4

	mAnimCmd4 

anim_data__0758_5:
	mGetPalette 0xA3 16 0x90
	mGetTiles 0x1F759 4
	.4byte	1, 5

	mAnimCmd4 

anim_data__0758_6:
	mGetPalette 0xA3 16 0x90
	mGetTiles 0x1F75D 4
	.4byte	1, 6

	mAnimCmd4 


anim_0758:
	.4byte anim_data__0758_0
	.4byte anim_data__0758_1
	.4byte anim_data__0758_2
	.4byte anim_data__0758_3
	.4byte anim_data__0758_4
	.4byte anim_data__0758_5
	.4byte anim_data__0758_6
