

anim_data__1119_0:
	mGetPalette 0xA3 16 0x60
	.4byte	1, -1

	mAnimCmd4 

anim_data__1119_1:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8DC 2
	.4byte	1, 0

	mAnimCmd4 

anim_data__1119_2:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8DE 1
	.4byte	1, 1

	mAnimCmd4 

anim_data__1119_3:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8DF 2
	.4byte	1, 2

	mAnimCmd4 

anim_data__1119_4:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8E1 2
	.4byte	1, 3

	mAnimCmd4 

anim_data__1119_5:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8E3 2
	.4byte	1, 4

	mAnimCmd4 

anim_data__1119_6:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8E5 2
	.4byte	1, 5

	mAnimCmd4 

anim_data__1119_7:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8E7 1
	.4byte	1, 6

	mAnimCmd4 

anim_data__1119_8:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8E8 2
	.4byte	1, 7

	mAnimCmd4 

anim_data__1119_9:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8EA 2
	.4byte	1, 8

	mAnimCmd4 

anim_data__1119_10:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8EC 2
	.4byte	1, 9

	mAnimCmd4 

anim_data__1119_11:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8EE 2
	.4byte	1, 10

	mAnimCmd4 

anim_data__1119_12:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8F0 1
	.4byte	1, 11

	mAnimCmd4 

anim_data__1119_13:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8F1 1
	.4byte	1, 12

	mAnimCmd4 

anim_data__1119_14:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8F2 1
	.4byte	1, 13

	mAnimCmd4 

anim_data__1119_15:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8F3 2
	.4byte	1, 14

	mAnimCmd4 

anim_data__1119_16:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8F5 2
	.4byte	1, 15

	mAnimCmd4 

anim_data__1119_17:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8F7 2
	.4byte	1, 16

	mAnimCmd4 

anim_data__1119_18:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8F9 2
	.4byte	1, 17

	mAnimCmd4 

anim_data__1119_19:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8FB 2
	.4byte	1, 18

	mAnimCmd4 

anim_data__1119_20:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8FD 2
	.4byte	1, 19

	mAnimCmd4 

anim_data__1119_21:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B8FF 2
	.4byte	1, 20

	mAnimCmd4 

anim_data__1119_22:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B901 2
	.4byte	1, 21

	mAnimCmd4 

anim_data__1119_23:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B903 2
	.4byte	1, 22

	mAnimCmd4 

anim_data__1119_24:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B905 2
	.4byte	1, 23

	mAnimCmd4 

anim_data__1119_25:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B907 2
	.4byte	1, 24

	mAnimCmd4 

anim_data__1119_26:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B909 2
	.4byte	1, 25

	mAnimCmd4 

anim_data__1119_27:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B90B 2
	.4byte	1, 26

	mAnimCmd4 

anim_data__1119_28:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B90D 2
	.4byte	1, 27

	mAnimCmd4 

anim_data__1119_29:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B90F 2
	.4byte	1, 28

	mAnimCmd4 

anim_data__1119_30:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B911 2
	.4byte	1, 29

	mAnimCmd4 

anim_data__1119_31:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B913 2
	.4byte	1, 30

	mAnimCmd4 

anim_data__1119_32:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B915 2
	.4byte	1, 31

	mAnimCmd4 

anim_data__1119_33:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B917 2
	.4byte	1, 32

	mAnimCmd4 

anim_data__1119_34:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B919 2
	.4byte	1, 33

	mAnimCmd4 

anim_data__1119_35:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B91B 2
	.4byte	1, 34

	mAnimCmd4 

anim_data__1119_36:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B91D 2
	mAnimCmd6 0x0 0xFF00FF00
	.4byte	1, 35

	mAnimCmd4 

anim_data__1119_37:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B91F 2
	.4byte	1, 36

	mAnimCmd4 

anim_data__1119_38:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B921 2
	.4byte	1, 37

	mAnimCmd4 

anim_data__1119_39:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B923 2
	.4byte	1, 38

	mAnimCmd4 

anim_data__1119_40:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B925 2
	.4byte	1, 39

	mAnimCmd4 

anim_data__1119_41:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B927 2
	.4byte	1, 40

	mAnimCmd4 

anim_data__1119_42:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B929 2
	.4byte	1, 41

	mAnimCmd4 

anim_data__1119_43:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B92B 2
	.4byte	1, 42

	mAnimCmd4 

anim_data__1119_44:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B92D 2
	.4byte	1, 43

	mAnimCmd4 

anim_data__1119_45:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B92F 2
	.4byte	1, 44

	mAnimCmd4 

anim_data__1119_46:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B931 2
	.4byte	1, 45

	mAnimCmd4 

anim_data__1119_47:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B933 2
	.4byte	1, 46

	mAnimCmd4 

anim_data__1119_48:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B935 2
	.4byte	1, 47

	mAnimCmd4 

anim_data__1119_49:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B937 2
	.4byte	1, 48

	mAnimCmd4 

anim_data__1119_50:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B939 2
	.4byte	1, 49

	mAnimCmd4 

anim_data__1119_51:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B93B 2
	.4byte	1, 50

	mAnimCmd4 

anim_data__1119_52:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B93D 2
	.4byte	1, 51

	mAnimCmd4 

anim_data__1119_53:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B93F 2
	.4byte	1, 52

	mAnimCmd4 

anim_data__1119_54:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B941 2
	.4byte	1, 53

	mAnimCmd4 

anim_data__1119_55:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B943 2
	.4byte	1, 54

	mAnimCmd4 

anim_data__1119_56:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B945 2
	.4byte	1, 55

	mAnimCmd4 

anim_data__1119_57:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B947 2
	.4byte	1, 56

	mAnimCmd4 

anim_data__1119_58:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B949 2
	.4byte	1, 57

	mAnimCmd4 

anim_data__1119_59:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B94B 2
	.4byte	1, 58

	mAnimCmd4 

anim_data__1119_60:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B94D 2
	.4byte	1, 59

	mAnimCmd4 

anim_data__1119_61:
	mGetTiles 0x2B94F 2
	.4byte	1, 60

	mJumpBack 0x5

anim_data__1119_62:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B951 1
	.4byte	1, 61

	mAnimCmd4 

anim_data__1119_63:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B952 1
	.4byte	1, 62

	mAnimCmd4 

anim_data__1119_64:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B953 1
	.4byte	1, 63

	mAnimCmd4 

anim_data__1119_65:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B954 1
	.4byte	1, 64

	mAnimCmd4 

anim_data__1119_66:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B955 1
	.4byte	1, 65

	mAnimCmd4 

anim_data__1119_67:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B956 1
	.4byte	1, 66

	mAnimCmd4 

anim_data__1119_68:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B957 1
	.4byte	1, 67

	mAnimCmd4 

anim_data__1119_69:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B958 1
	.4byte	1, 68

	mAnimCmd4 

anim_data__1119_70:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B959 1
	.4byte	1, 69

	mAnimCmd4 

anim_data__1119_71:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B95A 2
	.4byte	1, 70

	mAnimCmd4 

anim_data__1119_72:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B95C 1
	.4byte	1, 71

	mAnimCmd4 

anim_data__1119_73:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B95D 1
	.4byte	1, 72

	mAnimCmd4 

anim_data__1119_74:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B95E 2
	.4byte	1, 73

	mAnimCmd4 

anim_data__1119_75:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B960 1
	mAnimCmd6 0x0 0xD150D15
	.4byte	1, 74

	mAnimCmd4 

anim_data__1119_76:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B961 1
	.4byte	1, 75

	mAnimCmd4 

anim_data__1119_77:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B962 1
	.4byte	1, 76

	mAnimCmd4 

anim_data__1119_78:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B963 1
	.4byte	1, 77

	mAnimCmd4 

anim_data__1119_79:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B964 1
	.4byte	1, 78

	mAnimCmd4 

anim_data__1119_80:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B965 2
	.4byte	1, 79

	mAnimCmd4 

anim_data__1119_81:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B967 2
	.4byte	1, 80

	mAnimCmd4 

anim_data__1119_82:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B969 1
	.4byte	1, 81

	mAnimCmd4 

anim_data__1119_83:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B96A 1
	.4byte	1, 82

	mAnimCmd4 

anim_data__1119_84:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B96B 1
	.4byte	1, 83

	mAnimCmd4 

anim_data__1119_85:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B96C 1
	.4byte	1, 84

	mAnimCmd4 

anim_data__1119_86:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B96D 1
	.4byte	1, 85

	mAnimCmd4 

anim_data__1119_87:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B96E 1
	.4byte	1, 86

	mAnimCmd4 

anim_data__1119_88:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B96F 1
	.4byte	1, 87

	mAnimCmd4 

anim_data__1119_89:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B970 2
	.4byte	1, 88

	mAnimCmd4 

anim_data__1119_90:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B972 1
	.4byte	1, 89

	mAnimCmd4 

anim_data__1119_91:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B973 2
	.4byte	1, 90

	mAnimCmd4 

anim_data__1119_92:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B975 2
	.4byte	1, 91

	mAnimCmd4 

anim_data__1119_93:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B977 2
	.4byte	1, 92

	mAnimCmd4 

anim_data__1119_94:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x2B979 1
	.4byte	1, 93

	mAnimCmd4 


anim_1119:
	.4byte anim_data__1119_0
	.4byte anim_data__1119_1
	.4byte anim_data__1119_2
	.4byte anim_data__1119_3
	.4byte anim_data__1119_4
	.4byte anim_data__1119_5
	.4byte anim_data__1119_6
	.4byte anim_data__1119_7
	.4byte anim_data__1119_8
	.4byte anim_data__1119_9
	.4byte anim_data__1119_10
	.4byte anim_data__1119_11
	.4byte anim_data__1119_12
	.4byte anim_data__1119_13
	.4byte anim_data__1119_14
	.4byte anim_data__1119_15
	.4byte anim_data__1119_16
	.4byte anim_data__1119_17
	.4byte anim_data__1119_18
	.4byte anim_data__1119_19
	.4byte anim_data__1119_20
	.4byte anim_data__1119_21
	.4byte anim_data__1119_22
	.4byte anim_data__1119_23
	.4byte anim_data__1119_24
	.4byte anim_data__1119_25
	.4byte anim_data__1119_26
	.4byte anim_data__1119_27
	.4byte anim_data__1119_28
	.4byte anim_data__1119_29
	.4byte anim_data__1119_30
	.4byte anim_data__1119_31
	.4byte anim_data__1119_32
	.4byte anim_data__1119_33
	.4byte anim_data__1119_34
	.4byte anim_data__1119_35
	.4byte anim_data__1119_36
	.4byte anim_data__1119_37
	.4byte anim_data__1119_38
	.4byte anim_data__1119_39
	.4byte anim_data__1119_40
	.4byte anim_data__1119_41
	.4byte anim_data__1119_42
	.4byte anim_data__1119_43
	.4byte anim_data__1119_44
	.4byte anim_data__1119_45
	.4byte anim_data__1119_46
	.4byte anim_data__1119_47
	.4byte anim_data__1119_48
	.4byte anim_data__1119_49
	.4byte anim_data__1119_50
	.4byte anim_data__1119_51
	.4byte anim_data__1119_52
	.4byte anim_data__1119_53
	.4byte anim_data__1119_54
	.4byte anim_data__1119_55
	.4byte anim_data__1119_56
	.4byte anim_data__1119_57
	.4byte anim_data__1119_58
	.4byte anim_data__1119_59
	.4byte anim_data__1119_60
	.4byte anim_data__1119_61
	.4byte anim_data__1119_62
	.4byte anim_data__1119_63
	.4byte anim_data__1119_64
	.4byte anim_data__1119_65
	.4byte anim_data__1119_66
	.4byte anim_data__1119_67
	.4byte anim_data__1119_68
	.4byte anim_data__1119_69
	.4byte anim_data__1119_70
	.4byte anim_data__1119_71
	.4byte anim_data__1119_72
	.4byte anim_data__1119_73
	.4byte anim_data__1119_74
	.4byte anim_data__1119_75
	.4byte anim_data__1119_76
	.4byte anim_data__1119_77
	.4byte anim_data__1119_78
	.4byte anim_data__1119_79
	.4byte anim_data__1119_80
	.4byte anim_data__1119_81
	.4byte anim_data__1119_82
	.4byte anim_data__1119_83
	.4byte anim_data__1119_84
	.4byte anim_data__1119_85
	.4byte anim_data__1119_86
	.4byte anim_data__1119_87
	.4byte anim_data__1119_88
	.4byte anim_data__1119_89
	.4byte anim_data__1119_90
	.4byte anim_data__1119_91
	.4byte anim_data__1119_92
	.4byte anim_data__1119_93
	.4byte anim_data__1119_94
