

anim_time_attack_digits_variant_0:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x273B7 4
	.4byte	1, 0

	mAnimCmd4 

anim_time_attack_digits_variant_1:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x273BB 4
	.4byte	1, 1

	mAnimCmd4 

anim_time_attack_digits_variant_2:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x273BF 4
	.4byte	1, 2

	mAnimCmd4 

anim_time_attack_digits_variant_3:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x273C3 4
	.4byte	1, 3

	mAnimCmd4 

anim_time_attack_digits_variant_4:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x273C7 4
	.4byte	1, 4

	mAnimCmd4 

anim_time_attack_digits_variant_5:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x273CB 4
	.4byte	1, 5

	mAnimCmd4 

anim_time_attack_digits_variant_6:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x273CF 4
	.4byte	1, 6

	mAnimCmd4 

anim_time_attack_digits_variant_7:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x273D3 4
	.4byte	1, 7

	mAnimCmd4 

anim_time_attack_digits_variant_8:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x273D7 4
	.4byte	1, 8

	mAnimCmd4 

anim_time_attack_digits_variant_9:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x273DB 4
	.4byte	1, 9

	mAnimCmd4 

anim_time_attack_digits_variant_10:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x273DF 4
	.4byte	1, 10

	mAnimCmd4 

anim_time_attack_digits_variant_11:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x273E3 16
	.4byte	1, 11

	mAnimCmd4 

anim_time_attack_digits_variant_12:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x273F3 16
	.4byte	1, 12

	mAnimCmd4 

anim_time_attack_digits_variant_13:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x27403 16
	.4byte	1, 13

	mAnimCmd4 

anim_time_attack_digits_variant_14:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x27413 16
	.4byte	1, 14

	mAnimCmd4 

anim_time_attack_digits_variant_15:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x27423 16
	.4byte	1, 15

	mAnimCmd4 

anim_time_attack_digits_variant_16:
	mGetPalette 0xA3 16 0x60
	mGetTiles 0x27433 16
	.4byte	1, 16

	mAnimCmd4 


anim_time_attack_digits:
	.4byte anim_time_attack_digits_variant_0
	.4byte anim_time_attack_digits_variant_1
	.4byte anim_time_attack_digits_variant_2
	.4byte anim_time_attack_digits_variant_3
	.4byte anim_time_attack_digits_variant_4
	.4byte anim_time_attack_digits_variant_5
	.4byte anim_time_attack_digits_variant_6
	.4byte anim_time_attack_digits_variant_7
	.4byte anim_time_attack_digits_variant_8
	.4byte anim_time_attack_digits_variant_9
	.4byte anim_time_attack_digits_variant_10
	.4byte anim_time_attack_digits_variant_11
	.4byte anim_time_attack_digits_variant_12
	.4byte anim_time_attack_digits_variant_13
	.4byte anim_time_attack_digits_variant_14
	.4byte anim_time_attack_digits_variant_15
	.4byte anim_time_attack_digits_variant_16
