

anim_data__0874_0:
	mGetPalette 0xE5 16 0x30
	mGetTiles 0x239B4 38
	.4byte	1, 0

	mAnimCmd4 

anim_data__0874_1:
	mGetPalette 0xE5 16 0x30
	mGetTiles 0x239DA 30
	.4byte	1, 1

	mAnimCmd4 

anim_data__0874_2:
	mGetPalette 0xE5 16 0x30
	mGetTiles 0x239F8 32
	.4byte	1, 2

	mAnimCmd4 

anim_data__0874_3:
	mGetPalette 0xE5 16 0x30
	mGetTiles 0x23A18 22
	.4byte	1, 3

	mAnimCmd4 

anim_data__0874_4:
	mGetPalette 0xE5 16 0x30
	mGetTiles 0x23A2E 44
	.4byte	1, 4

	mAnimCmd4 

anim_data__0874_5:
	mGetPalette 0xE5 16 0x30
	mGetTiles 0x23A5A 34
	.4byte	1, 5

	mAnimCmd4 

anim_data__0874_6:
	mGetPalette 0xE5 16 0x30
	mGetTiles 0x23A7C 32
	.4byte	1, 6

	mAnimCmd4 


anim_0874:
	.4byte anim_data__0874_0
	.4byte anim_data__0874_1
	.4byte anim_data__0874_2
	.4byte anim_data__0874_3
	.4byte anim_data__0874_4
	.4byte anim_data__0874_5
	.4byte anim_data__0874_6
