

anim_data__0423_0:
	mGetPalette 0x1B, 16, 0x0
	mGetTiles 0x16AA1, 24
	mAnimCmd6 0x0, 0x23060AF8
	.4byte	1, 0

	mAnimCmd4 

anim_data__0423_1:
	mGetPalette 0x1B, 16, 0x0
	mGetTiles 0x16AB9, 20
	mAnimCmd6 0x0, 0x1CFD08EA
	.4byte	1, 1

	mAnimCmd4 

anim_data__0423_2:
	mGetPalette 0x1B, 16, 0x0
	mGetTiles 0x16ACD, 20
	mAnimCmd6 0x0, 0x11F600E2
	.4byte	1, 2

	mAnimCmd4 

anim_data__0423_3:
	mGetPalette 0x1B, 16, 0x0
	mGetTiles 0x16AE1, 15
	mAnimCmd6 0x0, 0x6F6F6E1
	.4byte	1, 3

	mAnimCmd4 

anim_data__0423_4:
	mGetPalette 0x1B, 16, 0x0
	mGetTiles 0x16AF0, 20
	mAnimCmd6 0x0, 0xFFFAEDE7
	.4byte	1, 4

	mAnimCmd4 

anim_data__0423_5:
	mGetPalette 0x1B, 16, 0x0
	mGetTiles 0x16B04, 20
	mAnimCmd6 0x0, 0xFAFDE4ED
	.4byte	1, 5

	mAnimCmd4 

anim_data__0423_6:
	mGetPalette 0x1B, 16, 0x0
	mGetTiles 0x16B18, 15
	mAnimCmd6 0x0, 0xF506DFF8
	.4byte	1, 6

	mAnimCmd4 

anim_data__0423_7:
	mGetPalette 0x1B, 16, 0x0
	mGetTiles 0x16B27, 18
	mAnimCmd6 0x0, 0xF912E402
	.4byte	1, 7

	mAnimCmd4 

anim_data__0423_8:
	mGetPalette 0x1B, 16, 0x0
	mGetTiles 0x16B39, 20
	mAnimCmd6 0x0, 0x21AEF09
	.4byte	1, 8

	mAnimCmd4 

anim_data__0423_9:
	mGetPalette 0x1B, 16, 0x0
	mGetTiles 0x16B4D, 15
	mAnimCmd6 0x0, 0x822FA0A
	.4byte	1, 9

	mAnimCmd4 

anim_data__0423_10:
	mGetPalette 0x1B, 16, 0x0
	mGetTiles 0x16B5C, 24
	mAnimCmd6 0x0, 0x121E0008
	.4byte	1, 10

	mAnimCmd4 

anim_data__0423_11:
	mGetPalette 0x1B, 16, 0x0
	mGetTiles 0x16B74, 25
	mAnimCmd6 0x0, 0x1E160600
	.4byte	1, 11

	mAnimCmd4 


anim_0423:
	.4byte anim_data__0423_0
	.4byte anim_data__0423_1
	.4byte anim_data__0423_2
	.4byte anim_data__0423_3
	.4byte anim_data__0423_4
	.4byte anim_data__0423_5
	.4byte anim_data__0423_6
	.4byte anim_data__0423_7
	.4byte anim_data__0423_8
	.4byte anim_data__0423_9
	.4byte anim_data__0423_10
	.4byte anim_data__0423_11
