

anim_data__0282_0:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0xED4B, 64
	mAnimCmd6 0x0, 0x1006F2FA
	.4byte	8, 0

	mGetTiles 0xED8B, 64
	.4byte	8, 1

	mGetTiles 0xEDCB, 64
	.4byte	8, 2

	mGetTiles 0xEE0B, 64
	.4byte	8, 3

	mGetTiles 0xEE4B, 64
	.4byte	8, 4

	mGetTiles 0xEE8B, 64
	.4byte	8, 5

	mGetTiles 0xEECB, 64
	.4byte	8, 6

	mGetTiles 0xEF0B, 64
	.4byte	8, 7

	mJumpBack 0x2E

anim_data__0282_1:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0xEF4B, 64
	mAnimCmd6 0x0, 0x1006F2FA
	.4byte	8, 8

	mGetTiles 0xEF8B, 64
	.4byte	8, 9

	mGetTiles 0xEFCB, 64
	.4byte	8, 10

	mGetTiles 0xF00B, 64
	.4byte	8, 11

	mGetTiles 0xF04B, 64
	.4byte	8, 12

	mGetTiles 0xF08B, 64
	.4byte	8, 13

	mGetTiles 0xF0CB, 64
	.4byte	8, 14

	mGetTiles 0xF10B, 64
	.4byte	8, 15

	mJumpBack 0x2E

anim_data__0282_2:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0xF14B, 64
	mAnimCmd6 0x0, 0x1006F2FA
	.4byte	8, 16

	mGetTiles 0xF18B, 64
	.4byte	8, 17

	mGetTiles 0xF1CB, 64
	.4byte	8, 18

	mGetTiles 0xF20B, 64
	.4byte	8, 19

	mGetTiles 0xF24B, 64
	.4byte	8, 20

	mGetTiles 0xF28B, 64
	.4byte	8, 21

	mGetTiles 0xF2CB, 64
	.4byte	8, 22

	mGetTiles 0xF30B, 64
	.4byte	8, 23

	mJumpBack 0x2E

anim_data__0282_3:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0xF34B, 64
	mAnimCmd6 0x0, 0x1006F2FA
	.4byte	8, 24

	mGetTiles 0xF38B, 64
	.4byte	8, 25

	mGetTiles 0xF3CB, 64
	.4byte	8, 26

	mGetTiles 0xF40B, 64
	.4byte	8, 27

	mGetTiles 0xF44B, 64
	.4byte	8, 28

	mGetTiles 0xF48B, 64
	.4byte	8, 29

	mGetTiles 0xF4CB, 64
	.4byte	8, 30

	mGetTiles 0xF50B, 64
	.4byte	8, 31

	mJumpBack 0x2E

anim_data__0282_4:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0xF54B, 64
	mAnimCmd6 0x0, 0x1006F2FA
	.4byte	8, 32

	mGetTiles 0xF58B, 64
	.4byte	8, 33

	mGetTiles 0xF5CB, 64
	.4byte	8, 34

	mGetTiles 0xF60B, 64
	.4byte	8, 35

	mGetTiles 0xF64B, 64
	.4byte	8, 36

	mGetTiles 0xF68B, 64
	.4byte	8, 37

	mGetTiles 0xF6CB, 64
	.4byte	8, 38

	mGetTiles 0xF70B, 64
	.4byte	8, 39

	mJumpBack 0x2E

anim_data__0282_5:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0xF54B, 64
	mAnimCmd6 0x0, 0x1006F2FA
	.4byte	8, 32

	mGetTiles 0xF58B, 64
	.4byte	8, 33

	mGetTiles 0xF5CB, 64
	.4byte	8, 34

	mGetTiles 0xF60B, 64
	.4byte	8, 35

	mGetTiles 0xF64B, 64
	.4byte	8, 36

	mGetTiles 0xF68B, 64
	.4byte	8, 37

	mGetTiles 0xF6CB, 64
	.4byte	8, 38

	mGetTiles 0xF70B, 64
	.4byte	8, 39

	mJumpBack 0x2E


anim_0282:
	.4byte anim_data__0282_0
	.4byte anim_data__0282_1
	.4byte anim_data__0282_2
	.4byte anim_data__0282_3
	.4byte anim_data__0282_4
	.4byte anim_data__0282_5
