
.align 2, 0
	anim_data__0921_0:
		mGetPalette 0x1A2 16 0x90
		.4byte	30, -1

		mGetPalette 0x1A3 16 0x90
		.4byte	7, -1

		mGetPalette 0x1A4 16 0x90
		.4byte	7, -1

		mGetPalette 0x1A5 16 0x90
		.4byte	7, -1

		mGetPalette 0x1A6 16 0x90
		.4byte	7, -1

		mGetPalette 0x1A7 16 0x90
		.4byte	30, -1

		mGetPalette 0x1A8 16 0x90
		.4byte	7, -1

		mGetPalette 0x1A9 16 0x90
		.4byte	7, -1

		mGetPalette 0x1AA 16 0x90
		.4byte	7, -1

		mGetPalette 0x1AB 16 0x90
		.4byte	7, -1

		mGetPalette 0x1AC 16 0x90
		.4byte	30, -1

		mGetPalette 0x1AD 16 0x90
		.4byte	7, -1

		mGetPalette 0x1AE 16 0x90
		.4byte	7, -1

		mGetPalette 0x1AF 16 0x90
		.4byte	7, -1

		mGetPalette 0x1B0 16 0x90
		.4byte	7, -1

		mJumpBack 0x4B


.align 2, 0
	anim_0921:
		.4byte anim_data__0921_0
