
.align 2, 0
	anim_data__0273_0:
		mGetPalette 0x16 16 0x0
		mGetTiles 0xE7BB 20
		mAnimCmd6 0x0 0x1006F2FA
		.4byte	5, 0

		mGetTiles 0xE7CF 20
		.4byte	5, 1

		mGetTiles 0xE7E3 20
		.4byte	5, 2

		mGetTiles 0xE7F7 16
		.4byte	5, 3

		mGetTiles 0xE807 20
		.4byte	5, 4

		mGetTiles 0xE7BB 20
		.4byte	5, 0

		mGetTiles 0xE7CF 20
		.4byte	5, 1

		mGetTiles 0xE7E3 20
		.4byte	5, 2

		mGetTiles 0xE7F7 16
		.4byte	5, 3

		mGetTiles 0xE807 20
		.4byte	5, 4

		mGetTiles 0xE81B 20
		.4byte	5, 5

		mGetTiles 0xE7BB 20
		.4byte	5, 0

		mGetTiles 0xE7CF 20
		.4byte	5, 1

		mGetTiles 0xE82F 20
		.4byte	5, 6

		mGetTiles 0xE843 16
		.4byte	5, 7

		mGetTiles 0xE853 20
		.4byte	5, 8

		mGetTiles 0xE81B 20
		.4byte	5, 5

		mGetTiles 0xE7BB 20
		.4byte	5, 0

		mGetTiles 0xE7CF 20
		.4byte	5, 1

		mGetTiles 0xE7E3 20
		.4byte	5, 2

		mGetTiles 0xE7F7 16
		.4byte	5, 3

		mGetTiles 0xE807 20
		mAnimCmd6 0x0 0x1008F3FA
		.4byte	5, 4

		mGetTiles 0xE867 20
		.4byte	5, 9

		mGetTiles 0xE87B 20
		.4byte	10, 10

		mGetTiles 0xE88F 20
		.4byte	5, 11

		mGetTiles 0xE8A3 20
		.4byte	5, 12

		mGetTiles 0xE8B7 20
		.4byte	5, 13

		mGetTiles 0xE867 20
		.4byte	5, 9

		mGetTiles 0xE87B 20
		.4byte	5, 10

		mGetTiles 0xE88F 20
		.4byte	5, 11

		mGetTiles 0xE8A3 20
		.4byte	5, 12

		mGetTiles 0xE8B7 20
		.4byte	12, 13

		mGetTiles 0xE867 20
		.4byte	6, 9

		mGetTiles 0xE81B 20
		.4byte	5, 5

		mGetTiles 0xE7BB 20
		.4byte	5, 0

		mGetTiles 0xE7CF 20
		.4byte	5, 1

		mGetTiles 0xE7E3 20
		.4byte	5, 2

		mGetTiles 0xE7F7 16
		.4byte	5, 3

		mGetTiles 0xE807 20
		.4byte	5, 4

		mJumpBack 0xCC


.align 2, 0
	anim_0273:
		.4byte anim_data__0273_0
