
.align 2, 0
	anim_data__0242_0:
		mGetPalette 0x9 16 0x0
		mGetTiles 0xD190 28
		mAnimCmd6 0x0 0xFA07E2F8
		.4byte	1, 0

		mAnimCmd4 

	anim_data__0242_1:
		mGetPalette 0x9 16 0x0
		mGetTiles 0xD1AC 30
		mAnimCmd6 0x0 0xFC00E8ED
		.4byte	1, 1

		mAnimCmd4 

	anim_data__0242_2:
		mGetPalette 0x9 16 0x0
		mGetTiles 0xD1CA 30
		mAnimCmd6 0x0 0xFCF1E8
		.4byte	1, 2

		mAnimCmd4 

	anim_data__0242_3:
		mGetPalette 0x9 16 0x0
		mGetTiles 0xD1E8 30
		mAnimCmd6 0x0 0x8FAFBE5
		.4byte	1, 3

		mAnimCmd4 

	anim_data__0242_4:
		mGetPalette 0x9 16 0x0
		mGetTiles 0xD206 24
		mAnimCmd6 0x0 0xFFB00E6
		.4byte	1, 4

		mAnimCmd4 

	anim_data__0242_5:
		mGetPalette 0x9 16 0x0
		mGetTiles 0xD21E 20
		mAnimCmd6 0x0 0x18FE04EC
		.4byte	1, 5

		mAnimCmd4 

	anim_data__0242_6:
		mGetPalette 0x9 16 0x0
		mGetTiles 0xD232 28
		mAnimCmd6 0x0 0x1F0709F9
		.4byte	1, 6

		mAnimCmd4 

	anim_data__0242_7:
		mGetPalette 0x9 16 0x0
		mGetTiles 0xD24E 36
		mAnimCmd6 0x0 0x1B140702
		.4byte	1, 7

		mAnimCmd4 

	anim_data__0242_8:
		mGetPalette 0x9 16 0x0
		mGetTiles 0xD272 24
		mAnimCmd6 0x0 0x121B0305
		.4byte	1, 8

		mAnimCmd4 

	anim_data__0242_9:
		mGetPalette 0x9 16 0x0
		mGetTiles 0xD28A 28
		mAnimCmd6 0x0 0x91FF807
		.4byte	1, 9

		mAnimCmd4 

	anim_data__0242_10:
		mGetPalette 0x9 16 0x0
		mGetTiles 0xD2A6 30
		mAnimCmd6 0x0 0x215ED03
		.4byte	1, 10

		mAnimCmd4 

	anim_data__0242_11:
		mGetPalette 0x9 16 0x0
		mGetTiles 0xD2C4 21
		mAnimCmd6 0x0 0xFB0EE601
		.4byte	1, 11

		mAnimCmd4 


.align 2, 0
	anim_0242:
		.4byte anim_data__0242_0
		.4byte anim_data__0242_1
		.4byte anim_data__0242_2
		.4byte anim_data__0242_3
		.4byte anim_data__0242_4
		.4byte anim_data__0242_5
		.4byte anim_data__0242_6
		.4byte anim_data__0242_7
		.4byte anim_data__0242_8
		.4byte anim_data__0242_9
		.4byte anim_data__0242_10
		.4byte anim_data__0242_11
