

anim_data__0923_0:
	mGetPalette 0x1B1, 16, 0x10
	.4byte	30, -1

	mGetPalette 0x1B2, 16, 0x10
	.4byte	7, -1

	mGetPalette 0x1B3, 16, 0x10
	.4byte	7, -1

	mGetPalette 0x1B4, 16, 0x10
	.4byte	7, -1

	mGetPalette 0x1B5, 16, 0x10
	.4byte	7, -1

	mGetPalette 0x1B6, 16, 0x10
	.4byte	30, -1

	mGetPalette 0x1B7, 16, 0x10
	.4byte	7, -1

	mGetPalette 0x1B8, 16, 0x10
	.4byte	7, -1

	mGetPalette 0x1B9, 16, 0x10
	.4byte	7, -1

	mGetPalette 0x1BA, 16, 0x10
	.4byte	7, -1

	mGetPalette 0x1BB, 16, 0x10
	.4byte	30, -1

	mGetPalette 0x1BC, 16, 0x10
	.4byte	7, -1

	mGetPalette 0x1BD, 16, 0x10
	.4byte	7, -1

	mGetPalette 0x1BE, 16, 0x10
	.4byte	7, -1

	mGetPalette 0x1BF, 16, 0x10
	.4byte	7, -1

	mJumpBack 0x4B


anim_0923:
	.4byte anim_data__0923_0
