

anim_data__0064_0:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x388D, 20
	mAnimCmd6 0x0, 0xFF07E1FB
	.4byte	2, 0

	mGetTiles 0x38A1, 30
	mAnimCmd6 0x0, 0xFFF7E1EB
	.4byte	2, 1

	mGetTiles 0x38BF, 24
	mAnimCmd6 0x0, 0xFFEFE1E3
	.4byte	4, 2

	mGetTiles 0x38D7, 25
	mAnimCmd6 0x0, 0xFFF7E1EB
	.4byte	3, 3

	mGetTiles 0x38F0, 15
	mAnimCmd6 0x0, 0xFF07E1FB
	.4byte	2, 4

	mGetTiles 0x38FF, 24
	mAnimCmd6 0x0, 0xFF17E10B
	.4byte	2, 5

	mGetTiles 0x3917, 28
	mAnimCmd6 0x0, 0xFF1FE113
	.4byte	4, 6

	mGetTiles 0x3933, 20
	mAnimCmd6 0x0, 0xFF17E10B
	.4byte	3, 7

	mGetTiles 0x388D, 20
	mAnimCmd6 0x0, 0xFF07E1FB
	.4byte	2, 0

	mGetTiles 0x38A1, 30
	mAnimCmd6 0x0, 0xFFF7E1EB
	.4byte	2, 1

	mGetTiles 0x38BF, 24
	mAnimCmd6 0x0, 0xFFEFE1E3
	.4byte	4, 2

	mGetTiles 0x38D7, 25
	mAnimCmd6 0x0, 0xFFF7E1EB
	.4byte	3, 3

	mGetTiles 0x38F0, 15
	mAnimCmd6 0x0, 0xFF07E1FB
	.4byte	2, 4

	mAnimCmd4 


anim_0064:
	.4byte anim_data__0064_0
