

anim_data__0241_0:
	mGetPalette 0x9, 16, 0x0
	mGetTiles 0xD031, 30
	mAnimCmd6 0x0, 0x1F0709F9
	.4byte	1, 0

	mAnimCmd4 

anim_data__0241_1:
	mGetPalette 0x9, 16, 0x0
	mGetTiles 0xD04F, 30
	mAnimCmd6 0x0, 0x18FE04EC
	.4byte	1, 1

	mAnimCmd4 

anim_data__0241_2:
	mGetPalette 0x9, 16, 0x0
	mGetTiles 0xD06D, 36
	mAnimCmd6 0x0, 0xFFB00E6
	.4byte	1, 2

	mAnimCmd4 

anim_data__0241_3:
	mGetPalette 0x9, 16, 0x0
	mGetTiles 0xD091, 24
	mAnimCmd6 0x0, 0x8FAFBE5
	.4byte	1, 3

	mAnimCmd4 

anim_data__0241_4:
	mGetPalette 0x9, 16, 0x0
	mGetTiles 0xD0A9, 30
	mAnimCmd6 0x0, 0xFCF1E8
	.4byte	1, 4

	mAnimCmd4 

anim_data__0241_5:
	mGetPalette 0x9, 16, 0x0
	mGetTiles 0xD0C7, 30
	mAnimCmd6 0x0, 0xFC00E8ED
	.4byte	1, 5

	mAnimCmd4 

anim_data__0241_6:
	mGetPalette 0x9, 16, 0x0
	mGetTiles 0xD0E5, 30
	mAnimCmd6 0x0, 0xFA07E2F8
	.4byte	1, 6

	mAnimCmd4 

anim_data__0241_7:
	mGetPalette 0x9, 16, 0x0
	mGetTiles 0xD103, 30
	mAnimCmd6 0x0, 0xFB0EE601
	.4byte	1, 7

	mAnimCmd4 

anim_data__0241_8:
	mGetPalette 0x9, 16, 0x0
	mGetTiles 0xD121, 25
	mAnimCmd6 0x0, 0x215ED03
	.4byte	1, 8

	mAnimCmd4 

anim_data__0241_9:
	mGetPalette 0x9, 16, 0x0
	mGetTiles 0xD13A, 25
	mAnimCmd6 0x0, 0x91FF807
	.4byte	1, 9

	mAnimCmd4 

anim_data__0241_10:
	mGetPalette 0x9, 16, 0x0
	mGetTiles 0xD153, 25
	mAnimCmd6 0x0, 0x121B0305
	.4byte	1, 10

	mAnimCmd4 

anim_data__0241_11:
	mGetPalette 0x9, 16, 0x0
	mGetTiles 0xD16C, 36
	mAnimCmd6 0x0, 0x1B140702
	.4byte	1, 11

	mAnimCmd4 


anim_0241:
	.4byte anim_data__0241_0
	.4byte anim_data__0241_1
	.4byte anim_data__0241_2
	.4byte anim_data__0241_3
	.4byte anim_data__0241_4
	.4byte anim_data__0241_5
	.4byte anim_data__0241_6
	.4byte anim_data__0241_7
	.4byte anim_data__0241_8
	.4byte anim_data__0241_9
	.4byte anim_data__0241_10
	.4byte anim_data__0241_11
