

anim_data__1118_0:
	mGetPalette 0x2DC, 16, 0xF0
	mGetTiles 0x2B882, 9
	.4byte	1, 0

	mAnimCmd4 

anim_data__1118_1:
	mGetPalette 0x2DC, 16, 0xF0
	mGetTiles 0x2B88B, 9
	.4byte	1, 1

	mAnimCmd4 

anim_data__1118_2:
	mGetPalette 0x2DC, 16, 0xF0
	mGetTiles 0x2B894, 9
	.4byte	1, 2

	mAnimCmd4 

anim_data__1118_3:
	mGetPalette 0x2DC, 16, 0xF0
	mGetTiles 0x2B89D, 9
	.4byte	1, 3

	mAnimCmd4 

anim_data__1118_4:
	mGetPalette 0x2DC, 16, 0xF0
	mGetTiles 0x2B8A6, 9
	.4byte	1, 4

	mAnimCmd4 

anim_data__1118_5:
	mGetPalette 0x2DC, 16, 0xF0
	mGetTiles 0x2B8AF, 9
	.4byte	1, 5

	mAnimCmd4 

anim_data__1118_6:
	mGetPalette 0x2DC, 16, 0xF0
	mGetTiles 0x2B8B8, 9
	.4byte	1, 6

	mAnimCmd4 

anim_data__1118_7:
	mGetPalette 0x2DC, 16, 0xF0
	mGetTiles 0x2B8C1, 9
	.4byte	1, 7

	mAnimCmd4 

anim_data__1118_8:
	mGetPalette 0x2DC, 16, 0xF0
	mGetTiles 0x2B8CA, 9
	.4byte	1, 8

	mAnimCmd4 

anim_data__1118_9:
	mGetPalette 0x2DC, 16, 0xF0
	mGetTiles 0x2B8D3, 9
	.4byte	1, 9

	mAnimCmd4 


anim_1118:
	.4byte anim_data__1118_0
	.4byte anim_data__1118_1
	.4byte anim_data__1118_2
	.4byte anim_data__1118_3
	.4byte anim_data__1118_4
	.4byte anim_data__1118_5
	.4byte anim_data__1118_6
	.4byte anim_data__1118_7
	.4byte anim_data__1118_8
	.4byte anim_data__1118_9
