

anim_data__0924_0:
	mGetPalette 0x1C0, 16, 0x50
	.4byte	30, -1

	mGetPalette 0x1C1, 16, 0x50
	.4byte	7, -1

	mGetPalette 0x1C2, 16, 0x50
	.4byte	7, -1

	mGetPalette 0x1C3, 16, 0x50
	.4byte	7, -1

	mGetPalette 0x1C4, 16, 0x50
	.4byte	7, -1

	mGetPalette 0x1C5, 16, 0x50
	.4byte	30, -1

	mGetPalette 0x1C6, 16, 0x50
	.4byte	7, -1

	mGetPalette 0x1C7, 16, 0x50
	.4byte	7, -1

	mGetPalette 0x1C8, 16, 0x50
	.4byte	7, -1

	mGetPalette 0x1C9, 16, 0x50
	.4byte	7, -1

	mGetPalette 0x1CA, 16, 0x50
	.4byte	30, -1

	mGetPalette 0x1CB, 16, 0x50
	.4byte	7, -1

	mGetPalette 0x1CC, 16, 0x50
	.4byte	7, -1

	mGetPalette 0x1CD, 16, 0x50
	.4byte	7, -1

	mGetPalette 0x1CE, 16, 0x50
	.4byte	7, -1

	mJumpBack 0x4B


anim_0924:
	.4byte anim_data__0924_0
