

anim_data__0761_0:
	mGetPalette 0xB5 16 0xA0
	mGetTiles 0x1F7BD 30
	.4byte	1, 0

	mAnimCmd4 

anim_data__0761_1:
	mGetPalette 0xB5 16 0xA0
	mGetTiles 0x1F7DB 28
	.4byte	1, 1

	mAnimCmd4 

anim_data__0761_2:
	mGetPalette 0xB5 16 0xA0
	mGetTiles 0x1F7F7 38
	.4byte	1, 2

	mAnimCmd4 

anim_data__0761_3:
	mGetPalette 0xB5 16 0xA0
	mGetTiles 0x1F81D 36
	.4byte	1, 3

	mAnimCmd4 

anim_data__0761_4:
	mGetPalette 0xB5 16 0xA0
	mGetTiles 0x1F841 32
	.4byte	1, 4

	mAnimCmd4 

anim_data__0761_5:
	mGetPalette 0xB5 16 0xA0
	mGetTiles 0x1F861 24
	.4byte	1, 5

	mAnimCmd4 

anim_data__0761_6:
	mGetPalette 0xB5 16 0xA0
	mGetTiles 0x1F879 32
	.4byte	1, 6

	mAnimCmd4 

anim_data__0761_7:
	mGetPalette 0xB5 16 0xA0
	mGetTiles 0x1F899 30
	.4byte	1, 7

	mAnimCmd4 

anim_data__0761_8:
	mGetPalette 0xB5 16 0xA0
	mGetTiles 0x1F8B7 34
	.4byte	1, 8

	mAnimCmd4 


anim_0761:
	.4byte anim_data__0761_0
	.4byte anim_data__0761_1
	.4byte anim_data__0761_2
	.4byte anim_data__0761_3
	.4byte anim_data__0761_4
	.4byte anim_data__0761_5
	.4byte anim_data__0761_6
	.4byte anim_data__0761_7
	.4byte anim_data__0761_8
