

anim_itembox_type_variant_0:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x1D979, 4
	.4byte	1, 0

	mAnimCmd4 

anim_itembox_type_variant_1:
	mGetPalette 0x7, 16, 0x0
	mGetTiles 0x1D97D, 4
	.4byte	1, 1

	mAnimCmd4 

anim_itembox_type_variant_2:
	mGetPalette 0x9, 16, 0x0
	mGetTiles 0x1D981, 4
	.4byte	1, 2

	mAnimCmd4 

anim_itembox_type_variant_3:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0x1D985, 4
	.4byte	1, 3

	mAnimCmd4 

anim_itembox_type_variant_4:
	mGetPalette 0x9F, 16, 0x0
	mGetTiles 0x1D989, 4
	.4byte	1, 4

	mAnimCmd4 

anim_itembox_type_variant_5:
	mGetPalette 0x2, 16, 0x50
	mGetTiles 0x1D98D, 4
	.4byte	1, 5

	mAnimCmd4 

anim_itembox_type_variant_6:
	mGetPalette 0xA0, 16, 0xA0
	mGetTiles 0x1D991, 4
	.4byte	1, 6

	mAnimCmd4 

anim_itembox_type_variant_7:
	mGetPalette 0xA0, 16, 0xA0
	mGetTiles 0x1D995, 4
	.4byte	1, 7

	mAnimCmd4 

anim_itembox_type_variant_8:
	mGetPalette 0xA0, 16, 0xA0
	mGetTiles 0x1D999, 4
	.4byte	1, 8

	mAnimCmd4 

anim_itembox_type_variant_9:
	mGetPalette 0xA1, 16, 0x60
	mGetTiles 0x1D99D, 4
	.4byte	1, 9

	mAnimCmd4 

anim_itembox_type_variant_10:
	mGetPalette 0xA1, 16, 0x60
	mGetTiles 0x1D9A1, 4
	.4byte	1, 10

	mAnimCmd4 

anim_itembox_type_variant_11:
	mGetPalette 0xA1, 16, 0x60
	mGetTiles 0x1D9A5, 4
	.4byte	1, 11

	mAnimCmd4 

anim_itembox_type_variant_12:
	mGetPalette 0xA1, 16, 0x60
	mGetTiles 0x1D9A9, 4
	.4byte	1, 12

	mAnimCmd4 

anim_itembox_type_variant_13:
	mGetPalette 0xA0, 16, 0xA0
	mGetTiles 0x1D9AD, 4
	.4byte	1, 13

	mAnimCmd4 

anim_itembox_type_variant_14:
	mGetPalette 0xA0, 16, 0xA0
	mGetTiles 0x1D9B1, 4
	.4byte	1, 14

	mAnimCmd4 

anim_itembox_type_variant_15:
	mGetPalette 0x2, 16, 0x50
	mGetTiles 0x1D9B5, 4
	.4byte	1, 15

	mAnimCmd4 

anim_itembox_type_variant_16:
	mGetPalette 0xA0, 16, 0xA0
	mGetTiles 0x1D9B9, 4
	.4byte	1, 16

	mAnimCmd4 


anim_itembox_type:
	.4byte anim_itembox_type_variant_0
	.4byte anim_itembox_type_variant_1
	.4byte anim_itembox_type_variant_2
	.4byte anim_itembox_type_variant_3
	.4byte anim_itembox_type_variant_4
	.4byte anim_itembox_type_variant_5
	.4byte anim_itembox_type_variant_6
	.4byte anim_itembox_type_variant_7
	.4byte anim_itembox_type_variant_8
	.4byte anim_itembox_type_variant_9
	.4byte anim_itembox_type_variant_10
	.4byte anim_itembox_type_variant_11
	.4byte anim_itembox_type_variant_12
	.4byte anim_itembox_type_variant_13
	.4byte anim_itembox_type_variant_14
	.4byte anim_itembox_type_variant_15
	.4byte anim_itembox_type_variant_16
