
.align 2, 0
	anim_data__0575_0:
		mGetPalette 0x6C 16 0x70
		mGetTiles 0x1AFB9 4
		.4byte	1, 0

		mAnimCmd4 

	anim_data__0575_1:
		mGetPalette 0x69 16 0x60
		mGetTiles 0x1AFBD 4
		.4byte	1, 1

		mAnimCmd4 

	anim_data__0575_2:
		mGetPalette 0x69 16 0x60
		mGetTiles 0x1AFC1 4
		.4byte	1, 2

		mAnimCmd4 

	anim_data__0575_3:
		mGetPalette 0x68 16 0x50
		mGetTiles 0x1AFC5 4
		.4byte	1, 3

		mAnimCmd4 

	anim_data__0575_4:
		mGetPalette 0x68 16 0x50
		mGetTiles 0x1AFC9 4
		.4byte	1, 4

		mAnimCmd4 

	anim_data__0575_5:
		mGetPalette 0x44 16 0x80
		mGetTiles 0x1AFCD 4
		.4byte	1, 5

		mAnimCmd4 

	anim_data__0575_6:
		mGetPalette 0x44 16 0x80
		mGetTiles 0x1AFD1 4
		.4byte	1, 6

		mAnimCmd4 

	anim_data__0575_7:
		mGetPalette 0x6C 16 0x70
		mGetTiles 0x1AFD5 6
		.4byte	1, 7

		mAnimCmd4 

	anim_data__0575_8:
		mGetPalette 0x17 16 0x40
		mGetTiles 0x1AFDB 6
		.4byte	1, 8

		mAnimCmd4 

	anim_data__0575_9:
		mGetPalette 0x6D 16 0xB0
		mGetTiles 0x1AFE1 6
		.4byte	1, 9

		mAnimCmd4 

	anim_data__0575_10:
		mGetPalette 0x6D 16 0xB0
		mGetTiles 0x1AFE7 6
		.4byte	1, 10

		mAnimCmd4 

	anim_data__0575_11:
		mGetPalette 0x68 16 0x50
		mGetTiles 0x1AFED 6
		.4byte	1, 11

		mAnimCmd4 

	anim_data__0575_12:
		mGetPalette 0x68 16 0x50
		mGetTiles 0x1AFF3 6
		.4byte	1, 12

		mAnimCmd4 

	anim_data__0575_13:
		mGetPalette 0x17 16 0x40
		mGetTiles 0x1AFF9 6
		.4byte	1, 13

		mAnimCmd4 

	anim_data__0575_14:
		mGetPalette 0x44 16 0x80
		mGetTiles 0x1AFFF 6
		.4byte	1, 14

		mAnimCmd4 

	anim_data__0575_15:
		mGetPalette 0x6C 16 0x70
		mGetTiles 0x1B005 1
		.4byte	1, 15

		mAnimCmd4 


.align 2, 0
	anim_0575:
		.4byte anim_data__0575_0
		.4byte anim_data__0575_1
		.4byte anim_data__0575_2
		.4byte anim_data__0575_3
		.4byte anim_data__0575_4
		.4byte anim_data__0575_5
		.4byte anim_data__0575_6
		.4byte anim_data__0575_7
		.4byte anim_data__0575_8
		.4byte anim_data__0575_9
		.4byte anim_data__0575_10
		.4byte anim_data__0575_11
		.4byte anim_data__0575_12
		.4byte anim_data__0575_13
		.4byte anim_data__0575_14
		.4byte anim_data__0575_15
