

anim_data__0214_0:
	mGetPalette 0xA 16 0x0
	mGetTiles 0xB853 20
	.4byte	2, 0

	mGetTiles 0xB867 20
	.4byte	6, 1

	mGetTiles 0xB87B 20
	.4byte	4, 2

	mGetTiles 0xB88F 20
	.4byte	4, 3

	mGetTiles 0xB87B 20
	.4byte	4, 2

	mGetTiles 0xB88F 20
	.4byte	4, 3

	mGetTiles 0xB87B 20
	.4byte	4, 2

	mGetTiles 0xB88F 20
	.4byte	4, 3

	mGetTiles 0xB87B 20
	.4byte	4, 2

	mGetTiles 0xB88F 20
	.4byte	4, 3

	mGetTiles 0xB87B 20
	.4byte	4, 2

	mGetTiles 0xB88F 20
	.4byte	4, 3

	mGetTiles 0xB87B 20
	.4byte	4, 2

	mGetTiles 0xB88F 20
	.4byte	4, 3

	mGetTiles 0xB8A3 20
	.4byte	8, 4

	mGetTiles 0xB8B7 20
	.4byte	2, 5

	mGetTiles 0xB8CB 20
	.4byte	3, 6

	mGetTiles 0xB8DF 25
	.4byte	4, 7

	mGetTiles 0xB8F8 20
	.4byte	4, 8

	mGetTiles 0xB90C 20
	.4byte	12, 9

	mAnimCmd4 


anim_0214:
	.4byte anim_data__0214_0
