

anim_data__0239_0:
	mGetPalette 0x10 16 0x0
	mGetTiles 0xCD65 24
	mAnimCmd6 0x0 0xA06F6FA
	.4byte	1, 0

	mAnimCmd4 

anim_data__0239_1:
	mGetPalette 0x10 16 0x0
	mGetTiles 0xCD7D 28
	mAnimCmd6 0x0 0xA06F6FA
	.4byte	1, 1

	mAnimCmd4 

anim_data__0239_2:
	mGetPalette 0x10 16 0x0
	mGetTiles 0xCD99 24
	mAnimCmd6 0x0 0xA06F6FA
	.4byte	1, 2

	mAnimCmd4 

anim_data__0239_3:
	mGetPalette 0x10 16 0x0
	mGetTiles 0xCDB1 28
	mAnimCmd6 0x0 0xA06F6FA
	.4byte	1, 3

	mAnimCmd4 

anim_data__0239_4:
	mGetPalette 0x10 16 0x0
	mGetTiles 0xCDCD 28
	mAnimCmd6 0x0 0xA06F6FA
	.4byte	1, 4

	mAnimCmd4 

anim_data__0239_5:
	mGetPalette 0x10 16 0x0
	mGetTiles 0xCDE9 24
	mAnimCmd6 0x0 0xA06F6FA
	.4byte	1, 5

	mAnimCmd4 

anim_data__0239_6:
	mGetPalette 0x10 16 0x0
	mGetTiles 0xCE01 24
	mAnimCmd6 0x0 0xA06F6FA
	.4byte	1, 6

	mAnimCmd4 

anim_data__0239_7:
	mGetPalette 0x10 16 0x0
	mGetTiles 0xCE19 24
	mAnimCmd6 0x0 0xA06F6FA
	.4byte	1, 7

	mAnimCmd4 


anim_0239:
	.4byte anim_data__0239_0
	.4byte anim_data__0239_1
	.4byte anim_data__0239_2
	.4byte anim_data__0239_3
	.4byte anim_data__0239_4
	.4byte anim_data__0239_5
	.4byte anim_data__0239_6
	.4byte anim_data__0239_7
