

anim_data__1078_0:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28EA8 4
	.4byte	1, 0

	mJumpBack 0x8

anim_data__1078_1:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28EAC 2
	.4byte	1, 1

	mJumpBack 0x8

anim_data__1078_2:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28EAE 4
	.4byte	1, 2

	mJumpBack 0x8

anim_data__1078_3:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28EB2 4
	.4byte	1, 3

	mJumpBack 0x8

anim_data__1078_4:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28EB6 4
	.4byte	1, 4

	mJumpBack 0x8

anim_data__1078_5:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28EBA 4
	.4byte	1, 5

	mJumpBack 0x8

anim_data__1078_6:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28EBE 4
	.4byte	1, 6

	mJumpBack 0x8

anim_data__1078_7:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28EC2 4
	.4byte	1, 7

	mJumpBack 0x8

anim_data__1078_8:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28EC6 4
	.4byte	1, 8

	mJumpBack 0x8

anim_data__1078_9:
	mGetPalette 0x2CE 16 0x0
	mGetTiles 0x28ECA 4
	.4byte	1, 9

	mJumpBack 0x8


anim_1078:
	.4byte anim_data__1078_0
	.4byte anim_data__1078_1
	.4byte anim_data__1078_2
	.4byte anim_data__1078_3
	.4byte anim_data__1078_4
	.4byte anim_data__1078_5
	.4byte anim_data__1078_6
	.4byte anim_data__1078_7
	.4byte anim_data__1078_8
	.4byte anim_data__1078_9
