

anim_data__0882_0:
	mGetTiles 0x23E4A 16
	mGetPalette 0xA1 16 0x70
	.4byte	6, 0

	.4byte	6, 1

	.4byte	6, 2

	.4byte	6, 3

	mJumpBack 0xB

anim_data__0882_1:
	mGetPalette 0xA1 16 0x70
	mGetTiles 0x23E5A 4
	.4byte	6, 4

	mGetTiles 0x23E5E 4
	.4byte	6, 5

	mGetTiles 0x23E62 4
	.4byte	6, 6

	mGetTiles 0x23E66 4
	.4byte	6, 7

	mJumpBack 0x17

anim_data__0882_2:
	mGetPalette 0xA1 16 0x70
	mGetTiles 0x23E6A 1
	.4byte	6, 8

	mGetTiles 0x23E6B 1
	.4byte	6, 9

	mGetTiles 0x23E6C 1
	.4byte	6, 10

	mGetTiles 0x23E6D 1
	.4byte	6, 11

	mJumpBack 0x17

anim_data__0882_3:
	mGetPalette 0xA1 16 0x70
	mGetTiles 0x23E6E 1
	.4byte	6, 12

	mGetTiles 0x23E6F 1
	.4byte	6, 13

	mGetTiles 0x23E70 1
	.4byte	6, 14

	mGetTiles 0x23E71 1
	.4byte	6, 15

	mJumpBack 0x17

anim_data__0882_4:
	mGetPalette 0xA1 16 0x70
	mGetTiles 0x23E72 1
	.4byte	6, 16

	mGetTiles 0x23E73 1
	.4byte	6, 17

	mGetTiles 0x23E74 1
	.4byte	6, 18

	mGetTiles 0x23E75 1
	.4byte	6, 19

	mJumpBack 0x17

anim_data__0882_5:
	mGetPalette 0xEB 16 0xA0
	mGetTiles 0x23E76 4
	.4byte	6, 20

	mGetTiles 0x23E7A 4
	.4byte	6, 21

	mGetTiles 0x23E7E 4
	.4byte	6, 22

	mGetTiles 0x23E82 4
	.4byte	6, 23

	mJumpBack 0x17

anim_data__0882_6:
	mGetPalette 0xEB 16 0xA0
	mGetTiles 0x23E86 4
	.4byte	6, 24

	mGetTiles 0x23E8A 4
	.4byte	6, 25

	mGetTiles 0x23E8E 4
	.4byte	6, 26

	mGetTiles 0x23E92 4
	.4byte	6, 27

	mJumpBack 0x17

anim_data__0882_7:
	mGetPalette 0xEB 16 0xA0
	mGetTiles 0x23E96 1
	.4byte	6, 28

	mGetTiles 0x23E97 1
	.4byte	6, 29

	mGetTiles 0x23E98 1
	.4byte	6, 30

	mGetTiles 0x23E99 1
	.4byte	6, 31

	mJumpBack 0x17

anim_data__0882_8:
	mGetPalette 0xEB 16 0xA0
	mGetTiles 0x23E9A 1
	.4byte	6, 32

	mGetTiles 0x23E9B 1
	.4byte	6, 33

	mGetTiles 0x23E9C 1
	.4byte	6, 34

	mGetTiles 0x23E9D 1
	.4byte	6, 35

	mJumpBack 0x17

anim_data__0882_9:
	mGetPalette 0xEB 16 0xA0
	mGetTiles 0x23E9E 1
	.4byte	6, 36

	mGetTiles 0x23E9F 1
	.4byte	6, 37

	mGetTiles 0x23EA0 1
	.4byte	6, 38

	mGetTiles 0x23EA1 1
	.4byte	6, 39

	mJumpBack 0x17

anim_data__0882_10:
	mGetPalette 0xA1 16 0x70
	mGetTiles 0x23EA2 1
	.4byte	6, 40

	mGetTiles 0x23EA3 1
	.4byte	6, 41

	mGetTiles 0x23EA4 1
	.4byte	6, 42

	mGetTiles 0x23EA5 1
	.4byte	6, 43

	mJumpBack 0x17

anim_data__0882_11:
	mGetPalette 0xA1 16 0x70
	mGetTiles 0x23EA6 1
	.4byte	6, 44

	mGetTiles 0x23EA7 1
	.4byte	6, 45

	mGetTiles 0x23EA8 1
	.4byte	6, 46

	mGetTiles 0x23EA9 1
	.4byte	6, 47

	mJumpBack 0x17

anim_data__0882_12:
	mGetPalette 0xEB 16 0xA0
	mGetTiles 0x23EAA 1
	.4byte	6, 48

	mGetTiles 0x23EAB 1
	.4byte	6, 49

	mGetTiles 0x23EAC 1
	.4byte	6, 50

	mGetTiles 0x23EAD 1
	.4byte	6, 51

	mJumpBack 0x17

anim_data__0882_13:
	mGetPalette 0xEB 16 0xA0
	mGetTiles 0x23EAE 1
	.4byte	6, 52

	mGetTiles 0x23EAF 1
	.4byte	6, 53

	mGetTiles 0x23EB0 1
	.4byte	6, 54

	mGetTiles 0x23EB1 1
	.4byte	6, 55

	mJumpBack 0x17

anim_data__0882_14:
	mGetPalette 0xA1 16 0x70
	mGetTiles 0x23EB2 1
	.4byte	6, 56

	mGetTiles 0x23EB3 1
	.4byte	6, 57

	mGetTiles 0x23EB4 1
	.4byte	6, 58

	mGetTiles 0x23EB5 1
	.4byte	6, 59

	mJumpBack 0x17

anim_data__0882_15:
	mGetPalette 0xEB 16 0xA0
	mGetTiles 0x23EB6 1
	.4byte	6, 60

	mGetTiles 0x23EB7 1
	.4byte	6, 61

	mGetTiles 0x23EB8 1
	.4byte	6, 62

	mGetTiles 0x23EB9 1
	.4byte	6, 63

	mJumpBack 0x17


anim_0882:
	.4byte anim_data__0882_0
	.4byte anim_data__0882_1
	.4byte anim_data__0882_2
	.4byte anim_data__0882_3
	.4byte anim_data__0882_4
	.4byte anim_data__0882_5
	.4byte anim_data__0882_6
	.4byte anim_data__0882_7
	.4byte anim_data__0882_8
	.4byte anim_data__0882_9
	.4byte anim_data__0882_10
	.4byte anim_data__0882_11
	.4byte anim_data__0882_12
	.4byte anim_data__0882_13
	.4byte anim_data__0882_14
	.4byte anim_data__0882_15
