
.align 2, 0
	anim_data__0953_0:
		mGetPalette 0x2B0 16 0x10
		mGetTiles 0x24619 40
		.4byte	1, 0

		mAnimCmd4 

	anim_data__0953_1:
		mGetPalette 0x2B0 16 0x10
		mGetTiles 0x24641 40
		.4byte	1, 1

		mAnimCmd4 

	anim_data__0953_2:
		mGetPalette 0x2B0 16 0x10
		mGetTiles 0x24669 40
		.4byte	1, 2

		mAnimCmd4 

	anim_data__0953_3:
		mGetPalette 0x2B0 16 0x10
		mGetTiles 0x24691 40
		.4byte	1, 3

		mAnimCmd4 

	anim_data__0953_4:
		mGetPalette 0x2B0 16 0x10
		mGetTiles 0x246B9 40
		.4byte	1, 4

		mAnimCmd4 

	anim_data__0953_5:
		mGetPalette 0x2B0 16 0x10
		mGetTiles 0x246E1 40
		.4byte	1, 5

		mAnimCmd4 

	anim_data__0953_6:
		mGetPalette 0x2B1 16 0x60
		mGetTiles 0x24709 45
		.4byte	1, 6

		mAnimCmd4 

	anim_data__0953_7:
		mGetPalette 0x2B0 16 0x10
		mGetTiles 0x24736 16
		.4byte	1, 7

		mAnimCmd4 

	anim_data__0953_8:
		mGetPalette 0x2B0 16 0x10
		mGetTiles 0x24746 16
		.4byte	1, 8

		mAnimCmd4 

	anim_data__0953_9:
		mGetPalette 0x2B0 16 0x10
		mGetTiles 0x24756 16
		.4byte	1, 9

		mAnimCmd4 

	anim_data__0953_10:
		mGetPalette 0x2B0 16 0x10
		mGetTiles 0x24766 16
		.4byte	1, 10

		mAnimCmd4 

	anim_data__0953_11:
		mGetPalette 0x2B0 16 0x10
		mGetTiles 0x24776 16
		.4byte	1, 11

		mAnimCmd4 

	anim_data__0953_12:
		mGetPalette 0x2B0 16 0x10
		mGetTiles 0x24786 16
		.4byte	1, 12

		mAnimCmd4 

	anim_data__0953_13:
		mGetPalette 0x2B2 16 0x50
		mGetTiles 0x24796 26
		.4byte	1, 13

		mAnimCmd4 


.align 2, 0
	anim_0953:
		.4byte anim_data__0953_0
		.4byte anim_data__0953_1
		.4byte anim_data__0953_2
		.4byte anim_data__0953_3
		.4byte anim_data__0953_4
		.4byte anim_data__0953_5
		.4byte anim_data__0953_6
		.4byte anim_data__0953_7
		.4byte anim_data__0953_8
		.4byte anim_data__0953_9
		.4byte anim_data__0953_10
		.4byte anim_data__0953_11
		.4byte anim_data__0953_12
		.4byte anim_data__0953_13
