

anim_data__0332_0:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0x11A6D, 35
	mAnimCmd6 0x0, 0x2A060CFA
	.4byte	1, 0

	mAnimCmd4 

anim_data__0332_1:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0x11A90, 30
	mAnimCmd6 0x0, 0x1EFE0AE4
	.4byte	1, 1

	mAnimCmd4 

anim_data__0332_2:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0x11AAE, 30
	mAnimCmd6 0x0, 0x10F802D8
	.4byte	1, 2

	mAnimCmd4 

anim_data__0332_3:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0x11ACC, 30
	mAnimCmd6 0x0, 0xAF2F5DD
	.4byte	1, 3

	mAnimCmd4 

anim_data__0332_4:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0x11AEA, 30
	mAnimCmd6 0x0, 0xFEF8EAE6
	.4byte	1, 4

	mAnimCmd4 

anim_data__0332_5:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0x11B08, 24
	mAnimCmd6 0x0, 0xF8FEDCEC
	.4byte	1, 5

	mAnimCmd4 

anim_data__0332_6:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0x11B20, 28
	mAnimCmd6 0x0, 0xF806DAFA
	.4byte	1, 6

	mAnimCmd4 

anim_data__0332_7:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0x11B3C, 28
	mAnimCmd6 0x0, 0xF610DE00
	.4byte	1, 7

	mAnimCmd4 

anim_data__0332_8:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0x11B58, 20
	mAnimCmd6 0x0, 0xFE1EEC08
	.4byte	1, 8

	mAnimCmd4 

anim_data__0332_9:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0x11B6C, 24
	mAnimCmd6 0x0, 0x826F80A
	.4byte	1, 9

	mAnimCmd4 

anim_data__0332_10:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0x11B84, 24
	mAnimCmd6 0x0, 0x12240208
	.4byte	1, 10

	mAnimCmd4 

anim_data__0332_11:
	mGetPalette 0x16, 16, 0x0
	mGetTiles 0x11B9C, 30
	mAnimCmd6 0x0, 0x221C0804
	.4byte	1, 11

	mAnimCmd4 


anim_0332:
	.4byte anim_data__0332_0
	.4byte anim_data__0332_1
	.4byte anim_data__0332_2
	.4byte anim_data__0332_3
	.4byte anim_data__0332_4
	.4byte anim_data__0332_5
	.4byte anim_data__0332_6
	.4byte anim_data__0332_7
	.4byte anim_data__0332_8
	.4byte anim_data__0332_9
	.4byte anim_data__0332_10
	.4byte anim_data__0332_11
