

anim_data__0057_0:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x3077, 25
	mAnimCmd6 0x0, 0xE06F2FA
	.4byte	1, 0

	mAnimCmd4 

anim_data__0057_1:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x3090, 16
	mAnimCmd6 0x0, 0xE06F2FA
	.4byte	1, 1

	mAnimCmd4 

anim_data__0057_2:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x30A0, 16
	mAnimCmd6 0x0, 0xE06F2FA
	.4byte	1, 2

	mAnimCmd4 

anim_data__0057_3:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x30B0, 25
	mAnimCmd6 0x0, 0xE06F2FA
	.4byte	1, 3

	mAnimCmd4 

anim_data__0057_4:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x30C9, 20
	mAnimCmd6 0x0, 0xE06F2FA
	.4byte	1, 4

	mAnimCmd4 

anim_data__0057_5:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x30DD, 16
	mAnimCmd6 0x0, 0xE06F2FA
	.4byte	1, 5

	mAnimCmd4 

anim_data__0057_6:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x30ED, 16
	mAnimCmd6 0x0, 0xE06F2FA
	.4byte	1, 6

	mAnimCmd4 

anim_data__0057_7:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x30FD, 20
	mAnimCmd6 0x0, 0xE06F2FA
	.4byte	1, 7

	mAnimCmd4 


anim_0057:
	.4byte anim_data__0057_0
	.4byte anim_data__0057_1
	.4byte anim_data__0057_2
	.4byte anim_data__0057_3
	.4byte anim_data__0057_4
	.4byte anim_data__0057_5
	.4byte anim_data__0057_6
	.4byte anim_data__0057_7
