

anim_data__0056_0:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x2E2B, 20
	mAnimCmd6 0x0, 0xC06EEFA
	.4byte	3, 0

	mGetTiles 0x2E3F, 24
	.4byte	3, 1

	mGetTiles 0x2E57, 20
	.4byte	3, 2

	mGetTiles 0x2E2B, 20
	.4byte	3, 0

	mGetTiles 0x2E3F, 24
	.4byte	3, 1

	mGetTiles 0x2E57, 20
	.4byte	3, 2

	mGetTiles 0x2E6B, 20
	.4byte	3, 3

	mGetTiles 0x2E7F, 20
	.4byte	3, 4

	mGetTiles 0x2E93, 20
	.4byte	3, 5

	mGetTiles 0x2EA7, 30
	.4byte	3, 6

	mGetTiles 0x2EC5, 24
	.4byte	3, 7

	mGetTiles 0x2EDD, 21
	.4byte	3, 8

	mGetTiles 0x2EF2, 30
	.4byte	3, 9

	mGetTiles 0x2F10, 24
	.4byte	3, 10

	mGetTiles 0x2F28, 24
	.4byte	3, 11

	mGetTiles 0x2F40, 36
	.4byte	3, 12

	mGetTiles 0x2F64, 25
	.4byte	3, 13

	mGetTiles 0x2F7D, 18
	.4byte	3, 14

	mGetTiles 0x2F8F, 30
	.4byte	3, 15

	mGetTiles 0x2FAD, 24
	.4byte	3, 16

	mGetTiles 0x2FC5, 24
	.4byte	3, 17

	mGetTiles 0x2FDD, 30
	.4byte	3, 18

	mGetTiles 0x2FFB, 24
	.4byte	3, 19

	mGetTiles 0x3013, 20
	.4byte	3, 20

	mGetTiles 0x3027, 20
	.4byte	3, 21

	mGetTiles 0x303B, 20
	.4byte	3, 22

	mGetTiles 0x304F, 20
	.4byte	3, 23

	mGetTiles 0x3063, 20
	.4byte	3, 24

	mJumpBack 0xF


anim_0056:
	.4byte anim_data__0056_0
