

anim_data__0032_0:
	mGetPalette 0x0, 16, 0x0
	mGetTiles 0x1E12, 20
	.4byte	5, 0

	mGetTiles 0x1E26, 20
	.4byte	5, 1

	mGetTiles 0x1E3A, 20
	.4byte	16, 2

	mGetTiles 0x1E4E, 20
	.4byte	3, 3

	mGetTiles 0x1E62, 20
	.4byte	3, 4

	mGetTiles 0x1E76, 20
	.4byte	3, 5

	mGetTiles 0x1E8A, 20
	.4byte	3, 6

	mGetTiles 0x1E9E, 25
	.4byte	3, 7

	mGetTiles 0x1EB7, 20
	.4byte	4, 8

	mGetTiles 0x1ECB, 20
	.4byte	4, 9

	mGetTiles 0x1EDF, 20
	.4byte	12, 10

	mGetTiles 0x1EF3, 20
	.4byte	6, 11

	mGetTiles 0x1F07, 25
	.4byte	5, 12

	mGetTiles 0x1F20, 25
	.4byte	12, 13

	mAnimCmd4 


anim_0032:
	.4byte anim_data__0032_0
