
.align 2, 0
	anim_data__0191_0:
		mGetPalette 0x9 16 0x0
		mGetTiles 0x9D5F 64
		mAnimCmd6 0x0 0x1006F6FA
		.4byte	8, 0

		mGetTiles 0x9D9F 64
		.4byte	8, 1

		mGetTiles 0x9DDF 64
		.4byte	8, 2

		mGetTiles 0x9E1F 64
		.4byte	8, 3

		mGetTiles 0x9E5F 64
		.4byte	8, 4

		mGetTiles 0x9E9F 64
		.4byte	8, 5

		mGetTiles 0x9EDF 64
		.4byte	8, 6

		mGetTiles 0x9F1F 64
		.4byte	8, 7

		mGetTiles 0x9D5F 64
		.4byte	8, 0

		mGetTiles 0x9F5F 64
		.4byte	8, 8

		mGetTiles 0x9F9F 64
		.4byte	8, 9

		mGetTiles 0x9FDF 64
		.4byte	8, 10

		mGetTiles 0x9E5F 64
		.4byte	8, 4

		mGetTiles 0x9E9F 64
		.4byte	8, 5

		mGetTiles 0x9EDF 64
		.4byte	8, 6

		mGetTiles 0x9F1F 64
		.4byte	8, 7

		mJumpBack 0x56

	anim_data__0191_1:
		mGetPalette 0x9 16 0x0
		mGetTiles 0xA01F 64
		mAnimCmd6 0x0 0x1006F6FA
		.4byte	8, 11

		mGetTiles 0xA05F 64
		.4byte	8, 12

		mGetTiles 0xA09F 64
		.4byte	8, 13

		mGetTiles 0xA0DF 64
		.4byte	8, 14

		mGetTiles 0xA11F 64
		.4byte	8, 15

		mGetTiles 0xA15F 64
		.4byte	8, 16

		mGetTiles 0xA19F 64
		.4byte	8, 17

		mGetTiles 0xA1DF 64
		.4byte	8, 18

		mGetTiles 0xA01F 64
		.4byte	8, 11

		mGetTiles 0xA21F 64
		.4byte	8, 19

		mGetTiles 0xA25F 64
		.4byte	8, 20

		mGetTiles 0xA29F 64
		.4byte	8, 21

		mGetTiles 0xA11F 64
		.4byte	8, 15

		mGetTiles 0xA15F 64
		.4byte	8, 16

		mGetTiles 0xA19F 64
		.4byte	8, 17

		mGetTiles 0xA1DF 64
		.4byte	8, 18

		mJumpBack 0x56

	anim_data__0191_2:
		mGetPalette 0xC 16 0x0
		mGetTiles 0xA2DF 64
		mAnimCmd6 0x0 0x1006F6FA
		.4byte	8, 22

		mGetTiles 0xA31F 64
		.4byte	8, 23

		mGetTiles 0xA35F 64
		.4byte	8, 24

		mGetTiles 0xA39F 64
		.4byte	8, 25

		mGetTiles 0xA3DF 64
		.4byte	8, 26

		mGetTiles 0xA41F 64
		.4byte	8, 27

		mGetTiles 0xA45F 64
		.4byte	8, 28

		mGetTiles 0xA49F 64
		.4byte	8, 29

		mGetTiles 0xA2DF 64
		.4byte	8, 22

		mGetTiles 0xA4DF 64
		.4byte	8, 30

		mGetTiles 0xA51F 64
		.4byte	8, 31

		mGetTiles 0xA55F 64
		.4byte	8, 32

		mGetTiles 0xA3DF 64
		.4byte	8, 26

		mGetTiles 0xA41F 64
		.4byte	8, 27

		mGetTiles 0xA45F 64
		.4byte	8, 28

		mGetTiles 0xA49F 64
		.4byte	8, 29

		mJumpBack 0x56

	anim_data__0191_3:
		mGetPalette 0xD 16 0x0
		mGetTiles 0xA59F 64
		mAnimCmd6 0x0 0x1006F6FA
		.4byte	8, 33

		mGetTiles 0xA5DF 64
		.4byte	8, 34

		mGetTiles 0xA61F 64
		.4byte	8, 35

		mGetTiles 0xA65F 64
		.4byte	8, 36

		mGetTiles 0xA69F 64
		.4byte	8, 37

		mGetTiles 0xA6DF 64
		.4byte	8, 38

		mGetTiles 0xA71F 64
		.4byte	8, 39

		mGetTiles 0xA75F 64
		.4byte	8, 40

		mGetTiles 0xA59F 64
		.4byte	8, 33

		mGetTiles 0xA79F 64
		.4byte	8, 41

		mGetTiles 0xA7DF 64
		.4byte	8, 42

		mGetTiles 0xA81F 64
		.4byte	8, 43

		mGetTiles 0xA69F 64
		.4byte	8, 37

		mGetTiles 0xA6DF 64
		.4byte	8, 38

		mGetTiles 0xA71F 64
		.4byte	8, 39

		mGetTiles 0xA75F 64
		.4byte	8, 40

		mJumpBack 0x56

	anim_data__0191_4:
		mGetPalette 0x9 16 0x0
		mGetTiles 0xA85F 64
		mAnimCmd6 0x0 0x1006F6FA
		.4byte	8, 44

		mGetTiles 0xA89F 64
		.4byte	8, 45

		mGetTiles 0xA8DF 64
		.4byte	8, 46

		mGetTiles 0xA91F 64
		.4byte	8, 47

		mGetTiles 0xA85F 64
		.4byte	8, 44

		mGetTiles 0xA95F 64
		.4byte	8, 48

		mGetTiles 0xA8DF 64
		.4byte	8, 46

		mGetTiles 0xA99F 64
		.4byte	8, 49

		mGetTiles 0xA9DF 64
		.4byte	8, 50

		mGetTiles 0xAA1F 64
		.4byte	8, 51

		mGetTiles 0xAA5F 64
		.4byte	8, 52

		mGetTiles 0xAA9F 64
		.4byte	8, 53

		mGetTiles 0xA9DF 64
		.4byte	8, 50

		mGetTiles 0xA89F 64
		.4byte	8, 45

		mGetTiles 0xA8DF 64
		.4byte	8, 46

		mGetTiles 0xAADF 64
		.4byte	8, 54

		mJumpBack 0x56

	anim_data__0191_5:
		mGetPalette 0x9 16 0x0
		mGetTiles 0xA85F 64
		mAnimCmd6 0x0 0x1006F6FA
		.4byte	8, 44

		mGetTiles 0xA89F 64
		.4byte	8, 45

		mGetTiles 0xA8DF 64
		.4byte	8, 46

		mGetTiles 0xA91F 64
		.4byte	8, 47

		mGetTiles 0xA85F 64
		.4byte	8, 44

		mGetTiles 0xA95F 64
		.4byte	8, 48

		mGetTiles 0xA8DF 64
		.4byte	8, 46

		mGetTiles 0xA99F 64
		.4byte	8, 49

		mGetTiles 0xA9DF 64
		.4byte	8, 50

		mGetTiles 0xAA1F 64
		.4byte	8, 51

		mGetTiles 0xAA5F 64
		.4byte	8, 52

		mGetTiles 0xAA9F 64
		.4byte	8, 53

		mGetTiles 0xA9DF 64
		.4byte	8, 50

		mGetTiles 0xA89F 64
		.4byte	8, 45

		mGetTiles 0xA8DF 64
		.4byte	8, 46

		mGetTiles 0xAADF 64
		.4byte	8, 54

		mJumpBack 0x56


.align 2, 0
	anim_0191:
		.4byte anim_data__0191_0
		.4byte anim_data__0191_1
		.4byte anim_data__0191_2
		.4byte anim_data__0191_3
		.4byte anim_data__0191_4
		.4byte anim_data__0191_5
