

anim_data__1117_0:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B48B 35
	.4byte	1, 0

	mAnimCmd4 

anim_data__1117_1:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B4AE 20
	.4byte	1, 1

	mAnimCmd4 

anim_data__1117_2:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B4C2 20
	.4byte	1, 2

	mAnimCmd4 

anim_data__1117_3:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B4D6 35
	.4byte	1, 3

	mAnimCmd4 

anim_data__1117_4:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B4F9 35
	.4byte	1, 4

	mAnimCmd4 

anim_data__1117_5:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B51C 20
	.4byte	1, 5

	mAnimCmd4 

anim_data__1117_6:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B530 20
	.4byte	1, 6

	mAnimCmd4 

anim_data__1117_7:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B544 35
	.4byte	1, 7

	mAnimCmd4 

anim_data__1117_8:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B567 35
	.4byte	1, 8

	mAnimCmd4 

anim_data__1117_9:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B58A 20
	.4byte	1, 9

	mAnimCmd4 

anim_data__1117_10:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B59E 20
	.4byte	1, 10

	mJumpBack 0x8

anim_data__1117_11:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B5B2 35
	.4byte	1, 11

	mAnimCmd4 

anim_data__1117_12:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B5D5 35
	.4byte	1, 12

	mAnimCmd4 

anim_data__1117_13:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B5F8 20
	.4byte	1, 13

	mAnimCmd4 

anim_data__1117_14:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B60C 20
	.4byte	1, 14

	mAnimCmd4 

anim_data__1117_15:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B620 35
	.4byte	1, 15

	mAnimCmd4 

anim_data__1117_16:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B643 35
	.4byte	1, 16

	mAnimCmd4 

anim_data__1117_17:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B666 20
	.4byte	1, 17

	mAnimCmd4 

anim_data__1117_18:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B67A 20
	.4byte	1, 18

	mAnimCmd4 

anim_data__1117_19:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B68E 35
	.4byte	1, 19

	mJumpBack 0x8

anim_data__1117_20:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B6B1 35
	.4byte	1, 20

	mAnimCmd4 

anim_data__1117_21:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B6D4 20
	.4byte	1, 21

	mAnimCmd4 

anim_data__1117_22:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B6E8 20
	.4byte	1, 22

	mAnimCmd4 

anim_data__1117_23:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B6FC 35
	.4byte	1, 23

	mAnimCmd4 

anim_data__1117_24:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B71F 35
	.4byte	1, 24

	mAnimCmd4 

anim_data__1117_25:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B742 20
	.4byte	1, 25

	mAnimCmd4 

anim_data__1117_26:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B756 20
	.4byte	1, 26

	mAnimCmd4 

anim_data__1117_27:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B76A 35
	.4byte	1, 27

	mAnimCmd4 

anim_data__1117_28:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B78D 25
	.4byte	1, 28

	mAnimCmd4 

anim_data__1117_29:
	mGetPalette 0x2DC 16 0xF0
	.4byte	1, -1

	mAnimCmd4 

anim_data__1117_30:
	mGetPalette 0x2DC 16 0xF0
	.4byte	1, -1

	mAnimCmd4 

anim_data__1117_31:
	mGetPalette 0x2DC 16 0xF0
	.4byte	1, -1

	mAnimCmd4 

anim_data__1117_32:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B7A6 35
	.4byte	1, 29

	mAnimCmd4 

anim_data__1117_33:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B7C9 20
	.4byte	1, 30

	mAnimCmd4 

anim_data__1117_34:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B7DD 20
	.4byte	1, 31

	mAnimCmd4 

anim_data__1117_35:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B7F1 35
	.4byte	1, 32

	mAnimCmd4 

anim_data__1117_36:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B814 35
	.4byte	1, 33

	mAnimCmd4 

anim_data__1117_37:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B837 20
	.4byte	1, 34

	mAnimCmd4 

anim_data__1117_38:
	mGetPalette 0x2DE 16 0xF0
	mGetTiles 0x2B84B 20
	.4byte	1, 35

	mAnimCmd4 

anim_data__1117_39:
	mGetPalette 0x2DC 16 0xF0
	mGetTiles 0x2B85F 35
	.4byte	1, 36

	mAnimCmd4 


anim_1117:
	.4byte anim_data__1117_0
	.4byte anim_data__1117_1
	.4byte anim_data__1117_2
	.4byte anim_data__1117_3
	.4byte anim_data__1117_4
	.4byte anim_data__1117_5
	.4byte anim_data__1117_6
	.4byte anim_data__1117_7
	.4byte anim_data__1117_8
	.4byte anim_data__1117_9
	.4byte anim_data__1117_10
	.4byte anim_data__1117_11
	.4byte anim_data__1117_12
	.4byte anim_data__1117_13
	.4byte anim_data__1117_14
	.4byte anim_data__1117_15
	.4byte anim_data__1117_16
	.4byte anim_data__1117_17
	.4byte anim_data__1117_18
	.4byte anim_data__1117_19
	.4byte anim_data__1117_20
	.4byte anim_data__1117_21
	.4byte anim_data__1117_22
	.4byte anim_data__1117_23
	.4byte anim_data__1117_24
	.4byte anim_data__1117_25
	.4byte anim_data__1117_26
	.4byte anim_data__1117_27
	.4byte anim_data__1117_28
	.4byte anim_data__1117_29
	.4byte anim_data__1117_30
	.4byte anim_data__1117_31
	.4byte anim_data__1117_32
	.4byte anim_data__1117_33
	.4byte anim_data__1117_34
	.4byte anim_data__1117_35
	.4byte anim_data__1117_36
	.4byte anim_data__1117_37
	.4byte anim_data__1117_38
	.4byte anim_data__1117_39
