

anim_data__0896_0:
	mGetPalette 0xF0 16 0xF0
	.4byte	7, -1

	mGetPalette 0xF1 16 0xF0
	.4byte	7, -1

	mGetPalette 0xF0 16 0xF0
	.4byte	7, -1

	mGetPalette 0xF1 16 0xF0
	.4byte	7, -1

	mGetPalette 0xF2 16 0xF0
	.4byte	7, -1

	mGetPalette 0xF3 16 0xF0
	.4byte	7, -1

	mGetPalette 0xF2 16 0xF0
	.4byte	7, -1

	mGetPalette 0xF1 16 0xF0
	.4byte	7, -1

	mJumpBack 0x28


anim_0896:
	.4byte anim_data__0896_0
