
.align 2, 0
	anim_data__0151_0:
		mGetPalette 0x7 16 0x0
		mGetTiles 0x8393 18
		mAnimCmd6 0x0 0xFA07E2F8
		.4byte	1, 0

		mAnimCmd4 

	anim_data__0151_1:
		mGetPalette 0x7 16 0x0
		mGetTiles 0x83A5 15
		mAnimCmd6 0x0 0xFC00E8ED
		.4byte	1, 1

		mAnimCmd4 

	anim_data__0151_2:
		mGetPalette 0x7 16 0x0
		mGetTiles 0x83B4 20
		mAnimCmd6 0x0 0xFCF1E8
		.4byte	1, 2

		mAnimCmd4 

	anim_data__0151_3:
		mGetPalette 0x7 16 0x0
		mGetTiles 0x83C8 20
		mAnimCmd6 0x0 0x8FAFBE5
		.4byte	1, 3

		mAnimCmd4 

	anim_data__0151_4:
		mGetPalette 0x7 16 0x0
		mGetTiles 0x83DC 15
		mAnimCmd6 0x0 0xFFB00E6
		.4byte	1, 4

		mAnimCmd4 

	anim_data__0151_5:
		mGetPalette 0x7 16 0x0
		mGetTiles 0x83EB 20
		mAnimCmd6 0x0 0x18FE04EC
		.4byte	1, 5

		mAnimCmd4 

	anim_data__0151_6:
		mGetPalette 0x7 16 0x0
		mGetTiles 0x83FF 18
		mAnimCmd6 0x0 0x1F0709F9
		.4byte	1, 6

		mAnimCmd4 

	anim_data__0151_7:
		mGetPalette 0x7 16 0x0
		mGetTiles 0x8411 20
		mAnimCmd6 0x0 0x1B140702
		.4byte	1, 7

		mAnimCmd4 

	anim_data__0151_8:
		mGetPalette 0x7 16 0x0
		mGetTiles 0x8425 20
		mAnimCmd6 0x0 0x121B0305
		.4byte	1, 8

		mAnimCmd4 

	anim_data__0151_9:
		mGetPalette 0x7 16 0x0
		mGetTiles 0x8439 18
		mAnimCmd6 0x0 0x91FF807
		.4byte	1, 9

		mAnimCmd4 

	anim_data__0151_10:
		mGetPalette 0x7 16 0x0
		mGetTiles 0x844B 16
		mAnimCmd6 0x0 0x215ED03
		.4byte	1, 10

		mAnimCmd4 

	anim_data__0151_11:
		mGetPalette 0x7 16 0x0
		mGetTiles 0x845B 20
		mAnimCmd6 0x0 0xFB0EE601
		.4byte	1, 11

		mAnimCmd4 


.align 2, 0
	anim_0151:
		.4byte anim_data__0151_0
		.4byte anim_data__0151_1
		.4byte anim_data__0151_2
		.4byte anim_data__0151_3
		.4byte anim_data__0151_4
		.4byte anim_data__0151_5
		.4byte anim_data__0151_6
		.4byte anim_data__0151_7
		.4byte anim_data__0151_8
		.4byte anim_data__0151_9
		.4byte anim_data__0151_10
		.4byte anim_data__0151_11
