

anim_data__0159_0:
	mGetPalette 0x7 16 0x0
	mGetTiles 0x8AF8 20
	mAnimCmd6 0x0 0x604F0FA
	.4byte	1, 0

	mAnimCmd4 

anim_data__0159_1:
	mGetPalette 0x7 16 0x0
	mGetTiles 0x8B0C 20
	mAnimCmd6 0x0 0x604F0FA
	.4byte	1, 1

	mAnimCmd4 

anim_data__0159_2:
	mGetPalette 0x7 16 0x0
	mGetTiles 0x8B20 15
	mAnimCmd6 0x0 0x604F0FA
	.4byte	1, 2

	mAnimCmd4 

anim_data__0159_3:
	mGetPalette 0x7 16 0x0
	mGetTiles 0x8B2F 20
	mAnimCmd6 0x0 0x604F0FA
	.4byte	1, 3

	mAnimCmd4 

anim_data__0159_4:
	mGetPalette 0x7 16 0x0
	mGetTiles 0x8B43 24
	mAnimCmd6 0x0 0x604F0FA
	.4byte	1, 4

	mAnimCmd4 

anim_data__0159_5:
	mGetPalette 0x7 16 0x0
	mGetTiles 0x8B5B 25
	mAnimCmd6 0x0 0x604F0FA
	.4byte	1, 5

	mAnimCmd4 

anim_data__0159_6:
	mGetPalette 0x7 16 0x0
	mGetTiles 0x8B74 20
	mAnimCmd6 0x0 0x604F0FA
	.4byte	1, 6

	mAnimCmd4 

anim_data__0159_7:
	mGetPalette 0x7 16 0x0
	mGetTiles 0x8B88 20
	mAnimCmd6 0x0 0x604F0FA
	.4byte	1, 7

	mAnimCmd4 

anim_data__0159_8:
	mGetPalette 0x7 16 0x0
	mGetTiles 0x8B9C 16
	mAnimCmd6 0x0 0x604F0FA
	.4byte	1, 8

	mAnimCmd4 

anim_data__0159_9:
	mGetPalette 0x7 16 0x0
	mGetTiles 0x8BAC 20
	mAnimCmd6 0x0 0x604F0FA
	.4byte	1, 9

	mAnimCmd4 

anim_data__0159_10:
	mGetPalette 0x7 16 0x0
	mGetTiles 0x8BC0 25
	mAnimCmd6 0x0 0x604F0FA
	.4byte	1, 10

	mAnimCmd4 


anim_0159:
	.4byte anim_data__0159_0
	.4byte anim_data__0159_1
	.4byte anim_data__0159_2
	.4byte anim_data__0159_3
	.4byte anim_data__0159_4
	.4byte anim_data__0159_5
	.4byte anim_data__0159_6
	.4byte anim_data__0159_7
	.4byte anim_data__0159_8
	.4byte anim_data__0159_9
	.4byte anim_data__0159_10
