

anim_data__0956_0:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x24BED 50
	.4byte	1, 0

	mAnimCmd4 

anim_data__0956_1:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x24C1F 50
	.4byte	1, 1

	mAnimCmd4 

anim_data__0956_2:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x24C51 50
	.4byte	1, 2

	mAnimCmd4 

anim_data__0956_3:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x24C83 50
	.4byte	1, 3

	mAnimCmd4 

anim_data__0956_4:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x24CB5 50
	.4byte	1, 4

	mAnimCmd4 

anim_data__0956_5:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x24CE7 50
	.4byte	1, 5

	mAnimCmd4 

anim_data__0956_6:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x24D19 50
	.4byte	1, 6

	mAnimCmd4 

anim_data__0956_7:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x24D4B 50
	.4byte	1, 7

	mAnimCmd4 

anim_data__0956_8:
	mGetPalette 0x2B1 16 0x60
	mGetTiles 0x24D7D 39
	.4byte	1, 8

	mAnimCmd4 


anim_0956:
	.4byte anim_data__0956_0
	.4byte anim_data__0956_1
	.4byte anim_data__0956_2
	.4byte anim_data__0956_3
	.4byte anim_data__0956_4
	.4byte anim_data__0956_5
	.4byte anim_data__0956_6
	.4byte anim_data__0956_7
	.4byte anim_data__0956_8
