

anim_data__0546_0:
	mGetPalette 0x34 16 0x70
	mGetTiles 0x1AA3A 9
	mAnimCmd6 0x0 0xC07F4F9
	.4byte	1, 0

	mJumpBack 0xB

anim_data__0546_1:
	mGetPalette 0x34 16 0x70
	mGetTiles 0x1AA43 9
	.4byte	1, 1

	mJumpBack 0x8

anim_data__0546_2:
	mGetPalette 0x34 16 0x70
	mGetTiles 0x1AA4C 9
	.4byte	1, 2

	mJumpBack 0x8

anim_data__0546_3:
	mGetPalette 0x34 16 0x70
	mGetTiles 0x1AA55 9
	.4byte	1, 3

	mJumpBack 0x8

anim_data__0546_4:
	mGetPalette 0x34 16 0x70
	mGetTiles 0x1AA5E 9
	.4byte	1, 4

	mJumpBack 0x8

anim_data__0546_5:
	mGetPalette 0x34 16 0x70
	mGetTiles 0x1AA67 9
	.4byte	1, 5

	mJumpBack 0x8

anim_data__0546_6:
	mGetPalette 0x34 16 0x70
	mGetTiles 0x1AA3A 9
	.4byte	1, 0

	mJumpBack 0x8

anim_data__0546_7:
	mGetPalette 0x34 16 0x70
	mGetTiles 0x1AA43 9
	.4byte	1, 1

	mJumpBack 0x8

anim_data__0546_8:
	mGetPalette 0x34 16 0x70
	mGetTiles 0x1AA4C 9
	.4byte	1, 2

	mJumpBack 0x8

anim_data__0546_9:
	mGetPalette 0x34 16 0x70
	mGetTiles 0x1AA55 9
	.4byte	1, 3

	mJumpBack 0x8

anim_data__0546_10:
	mGetPalette 0x34 16 0x70
	mGetTiles 0x1AA5E 9
	.4byte	1, 4

	mJumpBack 0x8

anim_data__0546_11:
	mGetPalette 0x34 16 0x70
	mGetTiles 0x1AA67 9
	.4byte	1, 5

	mJumpBack 0x8


anim_0546:
	.4byte anim_data__0546_0
	.4byte anim_data__0546_1
	.4byte anim_data__0546_2
	.4byte anim_data__0546_3
	.4byte anim_data__0546_4
	.4byte anim_data__0546_5
	.4byte anim_data__0546_6
	.4byte anim_data__0546_7
	.4byte anim_data__0546_8
	.4byte anim_data__0546_9
	.4byte anim_data__0546_10
	.4byte anim_data__0546_11
