

anim_data__0949_0:
	mGetPalette 0x2AB, 16, 0x30
	.4byte	9, -1

	mGetPalette 0x2AC, 16, 0x30
	.4byte	9, -1

	mGetPalette 0x2AD, 16, 0x30
	.4byte	9, -1

	mGetPalette 0x2AE, 16, 0x30
	.4byte	9, -1

	mGetPalette 0x2AF, 16, 0x30
	.4byte	9, -1

	mGetPalette 0x2AE, 16, 0x30
	.4byte	9, -1

	mGetPalette 0x2AD, 16, 0x30
	.4byte	9, -1

	mGetPalette 0x2AC, 16, 0x30
	.4byte	9, -1

	mJumpBack 0x28


anim_0949:
	.4byte anim_data__0949_0
