

anim_data__0978_0:
	mGetPalette 0x2B5, 16, 0x30
	mGetTiles 0x25E84, 50
	.4byte	1, 0

	mAnimCmd4 

anim_data__0978_1:
	mGetPalette 0x2B5, 16, 0x30
	mGetTiles 0x25EB6, 50
	.4byte	1, 1

	mAnimCmd4 

anim_data__0978_2:
	mGetPalette 0x2B5, 16, 0x30
	mGetTiles 0x25EE8, 50
	.4byte	1, 2

	mAnimCmd4 

anim_data__0978_3:
	mGetPalette 0x2B5, 16, 0x30
	mGetTiles 0x25F1A, 50
	.4byte	1, 3

	mAnimCmd4 

anim_data__0978_4:
	mGetPalette 0x2B5, 16, 0x30
	mGetTiles 0x25F4C, 50
	.4byte	1, 4

	mAnimCmd4 

anim_data__0978_5:
	mGetPalette 0x2B5, 16, 0x30
	mGetTiles 0x25F7E, 50
	.4byte	1, 5

	mAnimCmd4 

anim_data__0978_6:
	mGetPalette 0x2B5, 16, 0x30
	mGetTiles 0x25FB0, 50
	.4byte	1, 6

	mAnimCmd4 

anim_data__0978_7:
	mGetPalette 0x2B5, 16, 0x30
	mGetTiles 0x25FE2, 50
	.4byte	1, 7

	mAnimCmd4 

anim_data__0978_8:
	mGetPalette 0x2B1, 16, 0x60
	mGetTiles 0x26014, 30
	.4byte	1, 8

	mAnimCmd4 


anim_0978:
	.4byte anim_data__0978_0
	.4byte anim_data__0978_1
	.4byte anim_data__0978_2
	.4byte anim_data__0978_3
	.4byte anim_data__0978_4
	.4byte anim_data__0978_5
	.4byte anim_data__0978_6
	.4byte anim_data__0978_7
	.4byte anim_data__0978_8
