

anim_data__0876_0:
	mGetPalette 0xE8 16 0x30
	mGetTiles 0x23B7C 46
	.4byte	1, 0

	mAnimCmd4 

anim_data__0876_1:
	mGetPalette 0xE8 16 0x30
	mGetTiles 0x23BAA 26
	.4byte	1, 1

	mAnimCmd4 

anim_data__0876_2:
	mGetPalette 0xE8 16 0x30
	mGetTiles 0x23BC4 28
	.4byte	1, 2

	mAnimCmd4 

anim_data__0876_3:
	mGetPalette 0xE8 16 0x30
	mGetTiles 0x23BE0 20
	.4byte	1, 3

	mAnimCmd4 

anim_data__0876_4:
	mGetPalette 0xE8 16 0x30
	mGetTiles 0x23BF4 44
	.4byte	1, 4

	mAnimCmd4 

anim_data__0876_5:
	mGetPalette 0xE8 16 0x30
	mGetTiles 0x23C20 34
	.4byte	1, 5

	mAnimCmd4 

anim_data__0876_6:
	mGetPalette 0xE8 16 0x30
	mGetTiles 0x23C42 26
	.4byte	1, 6

	mAnimCmd4 


anim_0876:
	.4byte anim_data__0876_0
	.4byte anim_data__0876_1
	.4byte anim_data__0876_2
	.4byte anim_data__0876_3
	.4byte anim_data__0876_4
	.4byte anim_data__0876_5
	.4byte anim_data__0876_6
