

anim_data__0976_0:
	mGetPalette 0x2C2 16 0x30
	mGetTiles 0x25B2E 50
	.4byte	1, 0

	mAnimCmd4 

anim_data__0976_1:
	mGetPalette 0x2C2 16 0x30
	mGetTiles 0x25B60 50
	.4byte	1, 1

	mAnimCmd4 

anim_data__0976_2:
	mGetPalette 0x2C2 16 0x30
	mGetTiles 0x25B92 50
	.4byte	1, 2

	mAnimCmd4 

anim_data__0976_3:
	mGetPalette 0x2C2 16 0x30
	mGetTiles 0x25BC4 50
	.4byte	1, 3

	mAnimCmd4 

anim_data__0976_4:
	mGetPalette 0x2C2 16 0x30
	mGetTiles 0x25BF6 50
	.4byte	1, 4

	mAnimCmd4 

anim_data__0976_5:
	mGetPalette 0x2C2 16 0x30
	mGetTiles 0x25C28 50
	.4byte	1, 5

	mAnimCmd4 

anim_data__0976_6:
	mGetPalette 0x2C2 16 0x30
	mGetTiles 0x25C5A 50
	.4byte	1, 6

	mAnimCmd4 

anim_data__0976_7:
	mGetPalette 0x2C2 16 0x30
	mGetTiles 0x25C8C 50
	.4byte	1, 7

	mAnimCmd4 

anim_data__0976_8:
	mGetPalette 0x2B1 16 0x60
	mGetTiles 0x25CBE 30
	.4byte	1, 8

	mAnimCmd4 


anim_0976:
	.4byte anim_data__0976_0
	.4byte anim_data__0976_1
	.4byte anim_data__0976_2
	.4byte anim_data__0976_3
	.4byte anim_data__0976_4
	.4byte anim_data__0976_5
	.4byte anim_data__0976_6
	.4byte anim_data__0976_7
	.4byte anim_data__0976_8
