

anim_data__0977_0:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x25CDC 50
	.4byte	1, 0

	mAnimCmd4 

anim_data__0977_1:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x25D0E 50
	.4byte	1, 1

	mAnimCmd4 

anim_data__0977_2:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x25D40 50
	.4byte	1, 2

	mAnimCmd4 

anim_data__0977_3:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x25D72 50
	.4byte	1, 3

	mAnimCmd4 

anim_data__0977_4:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x25DA4 50
	.4byte	1, 4

	mAnimCmd4 

anim_data__0977_5:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x25DD6 50
	.4byte	1, 5

	mAnimCmd4 

anim_data__0977_6:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x25E08 50
	.4byte	1, 6

	mAnimCmd4 

anim_data__0977_7:
	mGetPalette 0x2B5 16 0x30
	mGetTiles 0x25E3A 50
	.4byte	1, 7

	mAnimCmd4 

anim_data__0977_8:
	mGetPalette 0x2B1 16 0x60
	mGetTiles 0x25E6C 24
	.4byte	1, 8

	mAnimCmd4 


anim_0977:
	.4byte anim_data__0977_0
	.4byte anim_data__0977_1
	.4byte anim_data__0977_2
	.4byte anim_data__0977_3
	.4byte anim_data__0977_4
	.4byte anim_data__0977_5
	.4byte anim_data__0977_6
	.4byte anim_data__0977_7
	.4byte anim_data__0977_8
