

anim_data__1064_0:
	mGetPalette 0x2C5 16 0x0
	mGetTiles 0x2869D 36
	.4byte	1, 0

	mAnimCmd4 

anim_data__1064_1:
	mGetPalette 0x2C5 16 0x0
	mGetTiles 0x286C1 34
	.4byte	1, 1

	mAnimCmd4 

anim_data__1064_2:
	mGetPalette 0x2C5 16 0x0
	mGetTiles 0x286E3 24
	.4byte	1, 2

	mAnimCmd4 

anim_data__1064_3:
	mGetPalette 0x2C5 16 0x0
	mGetTiles 0x286FB 22
	.4byte	1, 3

	mAnimCmd4 

anim_data__1064_4:
	mGetPalette 0x2C5 16 0x0
	mGetTiles 0x28711 24
	.4byte	1, 4

	mAnimCmd4 

anim_data__1064_5:
	mGetPalette 0x2C5 16 0x0
	mGetTiles 0x28729 28
	.4byte	1, 5

	mAnimCmd4 

anim_data__1064_6:
	mGetPalette 0x2C5 16 0x0
	mGetTiles 0x28745 24
	.4byte	1, 6

	mAnimCmd4 


anim_1064:
	.4byte anim_data__1064_0
	.4byte anim_data__1064_1
	.4byte anim_data__1064_2
	.4byte anim_data__1064_3
	.4byte anim_data__1064_4
	.4byte anim_data__1064_5
	.4byte anim_data__1064_6
