

anim_data__0424_0:
	mGetPalette 0x1B 16 0x0
	mGetTiles 0x16B8D 15
	mAnimCmd6 0x0 0xF506DFF8
	.4byte	1, 0

	mAnimCmd4 

anim_data__0424_1:
	mGetPalette 0x1B 16 0x0
	mGetTiles 0x16B9C 20
	mAnimCmd6 0x0 0xFAFDE4ED
	.4byte	1, 1

	mAnimCmd4 

anim_data__0424_2:
	mGetPalette 0x1B 16 0x0
	mGetTiles 0x16BB0 20
	mAnimCmd6 0x0 0xFFFAEDE7
	.4byte	1, 2

	mAnimCmd4 

anim_data__0424_3:
	mGetPalette 0x1B 16 0x0
	mGetTiles 0x16BC4 15
	mAnimCmd6 0x0 0x6F6F6E1
	.4byte	1, 3

	mAnimCmd4 

anim_data__0424_4:
	mGetPalette 0x1B 16 0x0
	mGetTiles 0x16BD3 20
	mAnimCmd6 0x0 0x11F600E2
	.4byte	1, 4

	mAnimCmd4 

anim_data__0424_5:
	mGetPalette 0x1B 16 0x0
	mGetTiles 0x16BE7 20
	mAnimCmd6 0x0 0x1CFD08EA
	.4byte	1, 5

	mAnimCmd4 

anim_data__0424_6:
	mGetPalette 0x1B 16 0x0
	mGetTiles 0x16BFB 24
	mAnimCmd6 0x0 0x23060AF8
	.4byte	1, 6

	mAnimCmd4 

anim_data__0424_7:
	mGetPalette 0x1B 16 0x0
	mGetTiles 0x16C13 25
	mAnimCmd6 0x0 0x1E160600
	.4byte	1, 7

	mAnimCmd4 

anim_data__0424_8:
	mGetPalette 0x1B 16 0x0
	mGetTiles 0x16C2C 24
	mAnimCmd6 0x0 0x121E0008
	.4byte	1, 8

	mAnimCmd4 

anim_data__0424_9:
	mGetPalette 0x1B 16 0x0
	mGetTiles 0x16C44 15
	mAnimCmd6 0x0 0x822FA0A
	.4byte	1, 9

	mAnimCmd4 

anim_data__0424_10:
	mGetPalette 0x1B 16 0x0
	mGetTiles 0x16C53 20
	mAnimCmd6 0x0 0x21AEF09
	.4byte	1, 10

	mAnimCmd4 

anim_data__0424_11:
	mGetPalette 0x1B 16 0x0
	mGetTiles 0x16C67 18
	mAnimCmd6 0x0 0xF912E402
	.4byte	1, 11

	mAnimCmd4 


anim_0424:
	.4byte anim_data__0424_0
	.4byte anim_data__0424_1
	.4byte anim_data__0424_2
	.4byte anim_data__0424_3
	.4byte anim_data__0424_4
	.4byte anim_data__0424_5
	.4byte anim_data__0424_6
	.4byte anim_data__0424_7
	.4byte anim_data__0424_8
	.4byte anim_data__0424_9
	.4byte anim_data__0424_10
	.4byte anim_data__0424_11
