

anim_data__0764_0:
	mGetPalette 0xB6, 16, 0x10
	mGetTiles 0x1FA13, 28
	.4byte	1, 0

	mAnimCmd4 

anim_data__0764_1:
	mGetPalette 0xB7, 16, 0x10
	mGetTiles 0x1FA13, 28
	.4byte	1, 0

	mAnimCmd4 

anim_data__0764_2:
	mGetPalette 0xB8, 16, 0x10
	mGetTiles 0x1FA13, 28
	.4byte	1, 0

	mAnimCmd4 

anim_data__0764_3:
	mGetPalette 0xB9, 16, 0x10
	mGetTiles 0x1FA13, 28
	.4byte	1, 0

	mAnimCmd4 

anim_data__0764_4:
	mGetPalette 0xBA, 16, 0x10
	mGetTiles 0x1FA13, 28
	.4byte	1, 0

	mAnimCmd4 


anim_0764:
	.4byte anim_data__0764_0
	.4byte anim_data__0764_1
	.4byte anim_data__0764_2
	.4byte anim_data__0764_3
	.4byte anim_data__0764_4
