

anim_data__0878_0:
	mGetPalette 0xEA 16 0x30
	mGetTiles 0x23D2E 30
	.4byte	1, 0

	mAnimCmd4 

anim_data__0878_1:
	mGetPalette 0xEA 16 0x30
	mGetTiles 0x23D4C 26
	.4byte	1, 1

	mAnimCmd4 

anim_data__0878_2:
	mGetPalette 0xEA 16 0x30
	mGetTiles 0x23D66 40
	.4byte	1, 2

	mAnimCmd4 

anim_data__0878_3:
	mGetPalette 0xEA 16 0x30
	mGetTiles 0x23D8E 18
	.4byte	1, 3

	mAnimCmd4 

anim_data__0878_4:
	mGetPalette 0xEA 16 0x30
	mGetTiles 0x23DA0 38
	.4byte	1, 4

	mAnimCmd4 

anim_data__0878_5:
	mGetPalette 0xEA 16 0x30
	mGetTiles 0x23DC6 38
	.4byte	1, 5

	mAnimCmd4 

anim_data__0878_6:
	mGetPalette 0xEA 16 0x30
	mGetTiles 0x23DEC 38
	.4byte	1, 6

	mAnimCmd4 


anim_0878:
	.4byte anim_data__0878_0
	.4byte anim_data__0878_1
	.4byte anim_data__0878_2
	.4byte anim_data__0878_3
	.4byte anim_data__0878_4
	.4byte anim_data__0878_5
	.4byte anim_data__0878_6
