

anim_data__0215_0:
	mGetPalette 0x9, 16, 0x0
	mGetTiles 0xB920, 20
	.4byte	6, 0

	mGetTiles 0xB934, 30
	.4byte	8, 1

	mGetTiles 0xB952, 20
	.4byte	4, 2

	mGetTiles 0xB966, 12
	.4byte	4, 3

	mGetTiles 0xB972, 16
	.4byte	6, 4

	mGetTiles 0xB982, 25
	.4byte	8, 5

	mGetTiles 0xB99B, 24
	.4byte	4, 6

	mGetTiles 0xB9B3, 12
	.4byte	4, 7

	mGetTiles 0xB9BF, 16
	.4byte	4, 8

	mGetTiles 0xB9CF, 20
	.4byte	4, 9

	mGetTiles 0xB9E3, 20
	.4byte	4, 10

	mGetTiles 0xB9F7, 16
	.4byte	4, 11

	mGetTiles 0xBA07, 16
	.4byte	4, 12

	mGetTiles 0xBA17, 16
	.4byte	4, 13

	mGetTiles 0xBA27, 16
	.4byte	4, 14

	mGetTiles 0xBA37, 20
	.4byte	4, 15

	mGetTiles 0xBA4B, 20
	.4byte	4, 16

	mGetTiles 0xBA5F, 20
	.4byte	8, 17

	mGetTiles 0xBA73, 20
	.4byte	4, 18

	mGetTiles 0xBA87, 25
	.4byte	4, 19

	mGetTiles 0xBAA0, 20
	.4byte	16, 20

	mGetTiles 0xBAB4, 16
	.4byte	4, 21

	mGetTiles 0xBAC4, 20
	.4byte	6, 22

	mGetTiles 0xBAD8, 25
	.4byte	5, 23

	mGetTiles 0xBAF1, 25
	.4byte	5, 24

	mGetTiles 0xBB0A, 25
	.4byte	5, 25

	mGetTiles 0xBB23, 20
	.4byte	5, 26

	mGetTiles 0xBAB4, 16
	.4byte	5, 21

	mGetTiles 0xBB37, 20
	.4byte	5, 27

	mGetTiles 0xBAD8, 25
	.4byte	5, 23

	mGetTiles 0xBAF1, 25
	.4byte	5, 24

	mGetTiles 0xBB0A, 25
	.4byte	5, 25

	mGetTiles 0xBB23, 20
	.4byte	5, 26

	mGetTiles 0xBAB4, 16
	.4byte	5, 21

	mGetTiles 0xBAC4, 20
	.4byte	5, 22

	mJumpBack 0x3C


anim_0215:
	.4byte anim_data__0215_0
