#ifndef GUARD_PARAMETERS_CHARACTERS_H
#define GUARD_PARAMETERS_CHARACTERS_H

/*** Common ***/
#define PLAYER_GRAVITY (0.033)

/*** Cream ***/
#define CREAM_FLYING_DURATION (4 * GBA_FRAMES_PER_SECOND)

/*** Tails ***/
#define TAILS_FLYING_DURATION (4 * GBA_FRAMES_PER_SECOND)

#endif // GUARD_PARAMETERS_CHARACTERS_H