@; NOTE(Jace): Try to keep the name of the AIFF-files that are in both equal to the ones of the main game.
    
    .align 2
	.global DirectSoundData_roland_sr_jv80_02__186_harp_1
DirectSoundData_roland_sr_jv80_02__186_harp_1: @ 0x201A5D0
	.incbin "sound/direct_sound_samples/roland_sr_jv80_02__186_harp_1.bin"

	.align 2
	.global DirectSoundData_roland_jv2080__pr_d__banjo
DirectSoundData_roland_jv2080__pr_d__banjo: @ 0x201AC64
	.incbin "sound/direct_sound_samples/roland_jv2080__pr_d__banjo.bin"

	.align 2
	.global DirectSoundData_roland_jv2080__pr_d__harmonica
DirectSoundData_roland_jv2080__pr_d__harmonica: @ 0x201B3E4
	.incbin "sound/direct_sound_samples/roland_jv2080__pr_d__harmonica.bin"

	.align 2
	.global DirectSoundData_roland_jv2080__pr_d__019_organ_3__5
DirectSoundData_roland_jv2080__pr_d__019_organ_3__5: @ 0x201C77C
	.incbin "sound/direct_sound_samples/roland_jv2080__pr_d__019_organ_3__5.bin"

	.align 2
	.global DirectSoundData_korg_trinity__standard_kit_1__shortened
DirectSoundData_korg_trinity__standard_kit_1__shortened: @ 0x201CE90
	.incbin "sound/direct_sound_samples/korg_trinity__standard_kit__1__shortened.bin"

	.align 2
	.global DirectSoundData_korg_trinity__standard_kit__2__shortened
DirectSoundData_korg_trinity__standard_kit__2__shortened: @ 0x201D2B4
	.incbin "sound/direct_sound_samples/korg_trinity__standard_kit__2__shortened.bin"

	.align 2
	.global DirectSoundData_roland_jv2080__jazz_drum_set1__2
DirectSoundData_roland_jv2080__jazz_drum_set1__2: @ 0x201DBEC
	.incbin "sound/direct_sound_samples/roland_jv2080__jazz_drum_set1__2.bin"
