	.align 2
	.global DirectSoundData_0201A5D0
DirectSoundData_0201A5D0:
	.incbin "sound/direct_sound_samples/0201A5D0.bin"

	.align 2
	.global DirectSoundData_0201AC64
DirectSoundData_0201AC64:
	.incbin "sound/direct_sound_samples/0201AC64.bin"

	.align 2
	.global DirectSoundData_0201B3E4
DirectSoundData_0201B3E4:
	.incbin "sound/direct_sound_samples/0201B3E4.bin"

	.align 2
	.global DirectSoundData_0201C77C
DirectSoundData_0201C77C:
	.incbin "sound/direct_sound_samples/0201C77C.bin"

	.align 2
	.global DirectSoundData_0201CE90
DirectSoundData_0201CE90:
	.incbin "sound/direct_sound_samples/0201CE90.bin"

	.align 2
	.global DirectSoundData_0201D2B4
DirectSoundData_0201D2B4:
	.incbin "sound/direct_sound_samples/0201D2B4.bin"

	.align 2
	.global DirectSoundData_0201DBEC
DirectSoundData_0201DBEC:
	.incbin "sound/direct_sound_samples/0201DBEC.bin"
