	.align 2
	.global ProgrammableWaveData_201A3E4
ProgrammableWaveData_201A3E4:
	.incbin "sound/programmable_wave_samples/0201A3E4.pcm"

	.align 2
	.global ProgrammableWaveData_201A3F4
ProgrammableWaveData_201A3F4:
	.incbin "sound/programmable_wave_samples/0201A3F4.pcm"

	.align 2
	.global ProgrammableWaveData_201A404
ProgrammableWaveData_201A404:
	.incbin "sound/programmable_wave_samples/0201A404.pcm"

	.align 2
	.global ProgrammableWaveData_201A414
ProgrammableWaveData_201A414:
	.incbin "sound/programmable_wave_samples/0201A414.pcm"

	.align 2
	.global ProgrammableWaveData_201A424
ProgrammableWaveData_201A424:
	.incbin "sound/programmable_wave_samples/0201A424.pcm"

	.align 2
	.global ProgrammableWaveData_201A434
ProgrammableWaveData_201A434:
	.incbin "sound/programmable_wave_samples/0201A434.pcm"

	.align 2
	.global ProgrammableWaveData_201A444
ProgrammableWaveData_201A444:
	.incbin "sound/programmable_wave_samples/0201A444.pcm"

	.align 2
	.global ProgrammableWaveData_201A454
ProgrammableWaveData_201A454:
	.incbin "sound/programmable_wave_samples/0201A454.pcm"

	.align 2
	.global ProgrammableWaveData_201A464
ProgrammableWaveData_201A464:
	.incbin "sound/programmable_wave_samples/0201A464.pcm"
