	.align 2
	.global gSongTable
gSongTable:	@ 0x0201A4A4
	song dummy_song_header, 0, 0
	song song0001, 0, 0
	song song0002, 0, 0
	song dummy_song_header, 0, 0
	song song0004, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song song0011, 2, 2
	song song0012, 2, 2
	song song0013, 2, 2
	song song0014, 2, 2
	song song0015, 2, 2
	song song0016, 2, 2
	song song0017, 2, 2
	song song0018, 2, 2
	song song0019, 2, 2
	song song0020, 2, 2
	song song0021, 2, 2
	song song0022, 2, 2
	song song0023, 2, 2
	song song0024, 2, 2
	song song0025, 2, 2
	song song0026, 2, 2
	song song0027, 2, 2
	song song0028, 2, 2
	song song0029, 2, 2
	song song0030, 2, 2
	song song0031, 2, 2
	song song0032, 2, 2
	song song0033, 2, 2
	song song0034, 2, 2
	song song0035, 2, 2
	song song0036, 2, 2

	.align 2
dummy_song_header:
	.byte 0, 0, 0, 0
