#ifndef GUARD_MULTIPLAYER_SINGLEPAK_CONNECTION_H
#define GUARD_MULTIPLAYER_SINGLEPAK_CONNECTION_H

#include "global.h"

void sub_8081200(void);
void StartSinglePakConnect(void);

#endif // GUARD_MULTIPLAYER_SINGLEPAK_CONNECTION_H

