#ifndef GUARD_MULTIPLAYER_COMMUNICATION_OUTCOME_H
#define GUARD_MULTIPLAYER_COMMUNICATION_OUTCOME_H

#include "global.h"

#define OUTCOME_CONNECTION_SUCCESS 0
#define OUTCOME_CONNECTION_ERROR 1

void sub_805BA10(u8 outcome);

#endif // GUARD_MULTIPLAYER_COMMUNICATION_OUTCOME_H
