#ifndef GUARD_PLAYER_H
#define GUARD_PLAYER_H

#define CHARACTER_SONIC 0
#define CHARACTER_CREAM 1
#define CHARACTER_TAILS 2
#define CHARACTER_KNUCKLES 3
#define CHARACTER_AMY 4

#endif // GUARD_PLAYER_H
