	mAlignWord
	@********************** Voicegroup **********************@

	.global voicegroup007
voicegroup007:	@ 0x086DD088
mAlignWord
	voice_square_1_alt 0, 2, 0, 3, 1, 3	@086DD088
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DD094
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 3, 0	@086DD0A0
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@086DD0AC
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@086DD0B8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 4, 0	@086DD0C4
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@086DD0D0
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@086DD0DC
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DD0E8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 7, 0	@086DD0F4
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@086DD100
mAlignWord
	voice_square_1_alt 0, 2, 0, 3, 4, 0	@086DD10C
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DD118
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 7, 0	@086DD124
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 3, 0	@086DD130
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@086DD13C
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DD148
mAlignWord
	voice_square_2_alt 2, 0, 3, 1, 2	@086DD154
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@086DD160
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 7, 0	@086DD16C
mAlignWord
	voice_directsound 60, 0, gUnknown_086FF18C, 255, 0, 255, 149	@086DD178
mAlignWord
	voice_directsound 60, 0, gUnknown_0877CF24, 255, 0, 255, 149	@086DD184
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@086DD190
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@086DD19C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 1, 3	@086DD1A8
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 9, 6	@086DD1B4
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@086DD1C0
mAlignWord
	voice_square_2_alt 2, 0, 4, 0, 6	@086DD1CC
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@086DD1D8
mAlignWord
	voice_square_2_alt 2, 0, 4, 13, 6	@086DD1E4
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@086DD1F0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD740, 0, 0, 15, 0	@086DD1FC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 0, 15, 0	@086DD208
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 1, 4	@086DD214
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 6	@086DD220
mAlignWord
	voice_square_2_alt 1, 0, 6, 0, 6	@086DD22C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 2, 0, 15, 0	@086DD238
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 1, 2	@086DD244
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DD250
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@086DD25C
mAlignWord
	voice_square_1_alt 0, 1, 0, 6, 0, 6	@086DD268
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 6	@086DD274
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 0, 15, 0	@086DD280
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@086DD28C
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@086DD298
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@086DD2A4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 1, 4	@086DD2B0
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 6	@086DD2BC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD740, 0, 6, 0, 6	@086DD2C8
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@086DD2D4
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@086DD2E0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 1, 4	@086DD2EC
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@086DD2F8
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@086DD304
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 1, 3	@086DD310
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DD31C
mAlignWord
	voice_square_1_alt 0, 1, 2, 0, 10, 3	@086DD328
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@086DD334
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@086DD340
mAlignWord
	voice_directsound 60, 0, gUnknown_08797224, 255, 0, 128, 235	@086DD34C
mAlignWord
	voice_directsound 60, 0, gUnknown_0877F2A4, 255, 0, 255, 0	@086DD358
mAlignWord
	voice_directsound 60, 0, gUnknown_0878306C, 255, 0, 255, 0	@086DD364
mAlignWord
	voice_directsound 60, 0, gUnknown_08789214, 255, 0, 255, 0	@086DD370
mAlignWord
	voice_directsound 60, 0, gUnknown_0878D964, 255, 0, 255, 0	@086DD37C
mAlignWord
	voice_directsound 60, 0, gUnknown_0878FAAC, 255, 0, 255, 0	@086DD388
mAlignWord
	voice_directsound 60, 0, gUnknown_0877F2A4, 255, 0, 255, 0	@086DD394
mAlignWord
	voice_directsound 60, 0, gUnknown_0878306C, 255, 0, 255, 0	@086DD3A0
mAlignWord
	voice_directsound 60, 0, gUnknown_08789214, 255, 250, 18, 250	@086DD3AC
mAlignWord
	voice_directsound 60, 0, gUnknown_0878D964, 255, 250, 18, 250	@086DD3B8
mAlignWord
	voice_directsound 60, 0, gUnknown_0878FAAC, 255, 250, 18, 250	@086DD3C4
mAlignWord
	voice_directsound 60, 0, gUnknown_086DE134, 255, 0, 255, 0	@086DD3D0
mAlignWord
	voice_directsound 60, 0, gUnknown_086DF608, 255, 0, 255, 0	@086DD3DC
mAlignWord
	voice_directsound 60, 0, gUnknown_086E0A1C, 255, 0, 255, 0	@086DD3E8
mAlignWord
	voice_directsound 60, 0, gUnknown_086E134C, 255, 0, 255, 0	@086DD3F4
mAlignWord
	voice_directsound 60, 0, gUnknown_086E1ABC, 255, 0, 255, 127	@086DD400
mAlignWord
	voice_directsound 60, 0, gUnknown_086E33B0, 255, 0, 255, 127	@086DD40C
mAlignWord
	voice_directsound 60, 0, gUnknown_086E64DC, 255, 0, 255, 0	@086DD418
mAlignWord
	voice_directsound 60, 0, gUnknown_086E6B24, 255, 235, 38, 165	@086DD424
mAlignWord
	voice_directsound 60, 0, gUnknown_086EA218, 255, 0, 255, 127	@086DD430
mAlignWord
	voice_directsound 60, 0, gUnknown_086ED1F4, 255, 0, 255, 0	@086DD43C
mAlignWord
	voice_directsound 60, 0, gUnknown_086F0138, 255, 0, 255, 0	@086DD448
mAlignWord
	voice_directsound 60, 0, gUnknown_086F1AC0, 255, 0, 255, 127	@086DD454
mAlignWord
	voice_directsound 60, 0, gUnknown_086F1DC0, 255, 0, 255, 127	@086DD460
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 1, 3	@086DD46C
mAlignWord
	voice_square_2_alt 2, 0, 4, 10, 0	@086DD478
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@086DD484
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DD490
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 1	@086DD49C
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 2	@086DD4A8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DD4B4
mAlignWord
	voice_directsound 60, 0, gUnknown_086FBBD4, 255, 0, 255, 0	@086DD4C0
mAlignWord
	voice_directsound 60, 0, gUnknown_086FE150, 255, 0, 255, 0	@086DD4CC
mAlignWord
	voice_directsound 60, 0, gUnknown_086FE7E4, 255, 0, 255, 0	@086DD4D8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 7, 2	@086DD4E4
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 2	@086DD4F0
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 2	@086DD4FC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 2, 9, 2	@086DD508
mAlignWord
	voice_square_2_alt 2, 1, 0, 10, 3	@086DD514
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 10, 0	@086DD520
mAlignWord
	voice_square_2_alt 3, 1, 6, 0, 0	@086DD52C
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DD538
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@086DD544
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 2, 9, 2	@086DD550
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 1, 2, 9, 2	@086DD55C
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@086DD568
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DD574
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@086DD580
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 2, 9, 2	@086DD58C
mAlignWord
	voice_square_2_alt 2, 0, 4, 0, 4	@086DD598
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@086DD5A4
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DD5B0
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@086DD5BC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 2, 9, 2	@086DD5C8
mAlignWord
	voice_square_2_alt 2, 1, 3, 3, 5	@086DD5D4
mAlignWord
	voice_square_1_alt 0, 2, 1, 3, 3, 5	@086DD5E0
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DD5EC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DD5F8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DD604
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DD610
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DD61C
mAlignWord
	voice_square_1_alt 0, 2, 0, 4, 0, 4	@086DD628
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 2, 9, 2	@086DD634
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 7, 2	@086DD640
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 2	@086DD64C
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 2	@086DD658
mAlignWord
    voice_square_2_alt 2, 0, 6, 0, 6    @086DD664
mAlignWord
    voice_square_1_alt 0, 1, 0, 0, 15, 0    @086DD670
mAlignWord
    voice_keysplit_all voicegroup001
