	mAlignWord
	@********************** Voicegroup **********************@

	.global voicegroup002
voicegroup002:	@ 0x086DBEAC
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08730340, 255, 255, 255, 0	@086DBEAC
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08730BF0, 255, 0, 255, 0	@086DBEB8
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 1, 0, 0	@086DBEC4
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 2, 0, 0	@086DBED0
mAlignWord
	voice_noise 84, 0, 192, 0, 0, 3, 7, 0	@086DBEDC
mAlignWord
	voice_directsound 45, 0, gUnknown_08731868, 255, 0, 255, 0	@086DBEE8
mAlignWord
	voice_directsound 50, 0, gUnknown_08731868, 255, 0, 255, 0	@086DBEF4
mAlignWord
	voice_directsound 55, 0, gUnknown_08731868, 255, 0, 255, 0	@086DBF00
mAlignWord
	voice_directsound 60, 0, gUnknown_08731868, 255, 0, 255, 0	@086DBF0C
mAlignWord
	voice_directsound 65, 0, gUnknown_08731868, 255, 0, 255, 0	@086DBF18
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08732A00, 255, 0, 255, 0	@086DBF24
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08733304, 255, 0, 255, 0	@086DBF30
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08733D74, 255, 0, 255, 0	@086DBF3C
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08737EB4, 255, 0, 255, 0	@086DBF48
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0873BCBC, 255, 0, 255, 0	@086DBF54
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0873C470, 255, 0, 255, 0	@086DBF60
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0873CC80, 255, 0, 255, 0	@086DBF6C
mAlignWord
	voice_directsound 57, 0, gUnknown_08737EB4, 255, 0, 255, 0	@086DBF78
mAlignWord
	voice_directsound 59, 0, gUnknown_08737EB4, 255, 0, 255, 0	@086DBF84
mAlignWord
	voice_directsound 61, 0, gUnknown_08737EB4, 255, 0, 255, 0	@086DBF90
mAlignWord
	voice_directsound 45, 0, gUnknown_0873D430, 255, 0, 255, 0	@086DBF9C
mAlignWord
	voice_directsound 50, 0, gUnknown_0873D430, 255, 0, 255, 0	@086DBFA8
mAlignWord
	voice_directsound 55, 0, gUnknown_0873D430, 255, 0, 255, 0	@086DBFB4
mAlignWord
	voice_directsound 60, 0, gUnknown_0873D430, 255, 0, 255, 0	@086DBFC0
mAlignWord
	voice_directsound 65, 0, gUnknown_0873D430, 255, 0, 255, 0	@086DBFCC
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0873DF74, 255, 0, 255, 0	@086DBFD8
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0873ECE8, 255, 0, 255, 0	@086DBFE4
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0873F1C0, 255, 0, 255, 0	@086DBFF0
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0873F654, 255, 0, 255, 0	@086DBFFC
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0873FAB8, 255, 0, 255, 0	@086DC008
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0873FF64, 255, 0, 255, 0	@086DC014
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087403FC, 255, 0, 255, 0	@086DC020
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08740854, 255, 0, 255, 0	@086DC02C
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08740D00, 255, 0, 255, 0	@086DC038
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08741248, 255, 0, 255, 0	@086DC044
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08741694, 255, 0, 255, 0	@086DC050
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08741B00, 255, 0, 255, 0	@086DC05C
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0874216C, 255, 0, 255, 0	@086DC068
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087424D8, 255, 0, 255, 0	@086DC074
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0874267C, 255, 0, 255, 0	@086DC080
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08742E90, 255, 0, 255, 0	@086DC08C
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087432F0, 255, 0, 255, 0	@086DC098
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087436FC, 255, 0, 255, 0	@086DC0A4
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08743BEC, 255, 0, 255, 0	@086DC0B0
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0874408C, 255, 0, 255, 0	@086DC0BC
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087444B4, 255, 0, 255, 0	@086DC0C8
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087449BC, 255, 0, 255, 0	@086DC0D4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC0E0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC0EC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC0F8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC104
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC110
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC11C
