	mAlignWord
	@********************** Voicegroup **********************@

	.global voicegroup003
voicegroup003:	@ 0x086DC128
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC128
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC134
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC140
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC14C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC158
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0874621C, 255, 0, 255, 0	@086DC164
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08746C04, 255, 0, 255, 0	@086DC170
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08747908, 255, 0, 255, 0	@086DC17C
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08747D18, 255, 0, 255, 0	@086DC188
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08748108, 255, 0, 255, 0	@086DC194
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08748BD8, 255, 0, 255, 0	@086DC1A0
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087493A4, 255, 0, 255, 0	@086DC1AC
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08749864, 255, 0, 255, 0	@086DC1B8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC1C4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC1D0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC1DC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC1E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC1F4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC200
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC20C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC218
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC224
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08749D20, 255, 0, 255, 0	@086DC230
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0874A750, 255, 0, 255, 0	@086DC23C
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0874AAF8, 255, 0, 255, 0	@086DC248
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0874B5D0, 255, 0, 255, 0	@086DC254
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0874B844, 255, 0, 255, 0	@086DC260
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0874CAFC, 255, 0, 255, 0	@086DC26C
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0874D4D0, 255, 0, 255, 0	@086DC278
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0874DDCC, 255, 0, 255, 0	@086DC284
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0874E228, 255, 0, 255, 0	@086DC290
