	mAlignWord
	@********************** Voicegroup **********************@

	.global voicegroup001
voicegroup001:	@ 0x086DBCFC
mAlignWord
	voice_directsound 60, 0, gUnknown_086FE7E4, 255, 0, 255, 0	@086DBCFC
mAlignWord
	voice_directsound 60, 0, gUnknown_086FF18C, 255, 0, 255, 149	@086DBD08
mAlignWord
	voice_directsound 60, 0, gUnknown_0870224C, 255, 235, 25, 165	@086DBD14
mAlignWord
	voice_directsound 60, 0, gUnknown_08702F60, 255, 0, 255, 149	@086DBD20
mAlignWord
	voice_directsound 60, 0, gUnknown_0870613C, 255, 0, 255, 0	@086DBD2C
mAlignWord
	voice_directsound 60, 0, gUnknown_08708210, 37, 0, 255, 165	@086DBD38
mAlignWord
	voice_directsound 60, 0, gUnknown_08708210, 255, 0, 255, 165	@086DBD44
mAlignWord
	voice_directsound 60, 0, gUnknown_0870A724, 255, 252, 0, 149	@086DBD50
mAlignWord
	voice_directsound 60, 0, gUnknown_0870CA4C, 255, 0, 255, 0	@086DBD5C
mAlignWord
	voice_directsound 60, 0, gUnknown_0870D7EC, 255, 0, 255, 0	@086DBD68
mAlignWord
	voice_directsound 60, 0, gUnknown_0870DC84, 255, 0, 255, 0	@086DBD74
mAlignWord
	voice_directsound 60, 0, gUnknown_0870E60C, 255, 0, 255, 0	@086DBD80
mAlignWord
	voice_directsound 60, 0, gUnknown_0870EA00, 255, 0, 255, 0	@086DBD8C
mAlignWord
	voice_directsound 60, 0, gUnknown_0870EE50, 255, 0, 255, 0	@086DBD98
mAlignWord
	voice_directsound 60, 0, gUnknown_0870F254, 255, 0, 255, 0	@086DBDA4
mAlignWord
	voice_directsound 60, 0, gUnknown_0870FBC0, 255, 0, 255, 0	@086DBDB0
mAlignWord
	voice_directsound 60, 0, gUnknown_0870FFA0, 255, 0, 255, 0	@086DBDBC
mAlignWord
	voice_directsound 60, 0, gUnknown_087103F8, 255, 0, 255, 0	@086DBDC8
mAlignWord
	voice_directsound 60, 0, gUnknown_08710D74, 255, 0, 255, 0	@086DBDD4
mAlignWord
	voice_directsound 60, 0, gUnknown_087111D4, 255, 0, 255, 0	@086DBDE0
mAlignWord
	voice_directsound 60, 0, gUnknown_08711640, 255, 0, 255, 0	@086DBDEC
mAlignWord
	voice_directsound 60, 0, gUnknown_08711ACC, 255, 0, 255, 0	@086DBDF8
mAlignWord
	voice_directsound 60, 0, gUnknown_087123F8, 255, 0, 255, 0	@086DBE04
mAlignWord
	voice_directsound 60, 0, gUnknown_08712950, 255, 0, 255, 0	@086DBE10
mAlignWord
	voice_directsound 60, 0, gUnknown_08712DB8, 255, 0, 255, 0	@086DBE1C
mAlignWord
	voice_directsound 60, 0, gUnknown_0871375C, 255, 250, 18, 250	@086DBE28
mAlignWord
	voice_directsound 60, 0, gUnknown_0871AED4, 255, 216, 25, 0	@086DBE34
mAlignWord
	voice_directsound 60, 0, spectrasonics__symphony_of_voices__partition_d__big_chord__big_min__c4_r, 37, 0, 255, 149	@086DBE40
mAlignWord
	voice_directsound 60, 0, gUnknown_0871EF30, 255, 0, 255, 0	@086DBE4C
mAlignWord
	voice_directsound 60, 0, gUnknown_08727348, 255, 0, 255, 0	@086DBE58
mAlignWord
	voice_directsound 60, 0, gUnknown_0872CF68, 255, 0, 255, 149	@086DBE64
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD710, 0, 5, 1, 0	@086DBE70
mAlignWord
	voice_directsound 60, 0, gUnknown_0872E77C, 255, 216, 25, 0	@086DBE7C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD710, 0, 4, 4, 0	@086DBE88
mAlignWord
	voice_keysplit_all voicegroup003	@086DBE94
mAlignWord
	voice_keysplit_all voicegroup001	@086DBEA0
