	mAlignWord
	@********************** Voicegroup **********************@

	.global voicegroup005
voicegroup005:	@ 0x086DC488
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@086DC488
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@086DC494
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@086DC4A0
mAlignWord
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@086DC4AC
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@086DC4B8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC4C4
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@086DC4D0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC4DC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC4E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC4F4
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@086DC500
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@086DC50C
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DC518
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@086DC524
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@086DC530
mAlignWord
	voice_noise 60, 0, 0, 1, 1, 0, 12, 2	@086DC53C
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 12, 2	@086DC548
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@086DC554
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 5, 3	@086DC560
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 12, 2	@086DC56C
mAlignWord
	voice_noise 60, 0, 0, 1, 1, 0, 12, 2	@086DC578
mAlignWord
	voice_noise 60, 0, 0, 1, 4, 0, 12, 2	@086DC584
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@086DC590
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 5, 4	@086DC59C
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 5	@086DC5A8
mAlignWord
	voice_square_1_alt 0, 2, 0, 2, 0, 0	@086DC5B4
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@086DC5C0
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 2	@086DC5CC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC5D8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC5E4
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@086DC5F0
mAlignWord
	voice_noise 60, 0, 0, 0, 3, 0, 15, 4	@086DC5FC
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@086DC608
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@086DC614
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@086DC620
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@086DC62C
mAlignWord
	voice_square_1_alt 0, 1, 1, 0, 15, 0	@086DC638
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@086DC644
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@086DC650
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 1	@086DC65C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD6D0, 0, 4, 4, 0	@086DC668
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD6E0, 0, 0, 15, 0	@086DC674
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD6F0, 0, 0, 15, 0	@086DC680
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD700, 0, 0, 15, 0	@086DC68C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD710, 0, 0, 15, 0	@086DC698
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD720, 0, 0, 15, 0	@086DC6A4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 0, 15, 0	@086DC6B0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD740, 0, 0, 15, 0	@086DC6BC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD750, 0, 3, 0, 2	@086DC6C8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC6D4
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@086DC6E0
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@086DC6EC
mAlignWord
	voice_square_1_alt 0, 2, 0, 3, 0, 0	@086DC6F8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD6D0, 0, 0, 15, 0	@086DC704
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD750, 0, 3, 0, 2	@086DC710
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD6D0, 0, 0, 15, 0	@086DC71C
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 5	@086DC728
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@086DC734
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@086DC740
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@086DC74C
mAlignWord
	voice_square_1_alt 0, 0, 0, 4, 0, 0	@086DC758
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD750, 0, 4, 0, 0	@086DC764
mAlignWord
	voice_square_2_alt 0, 0, 4, 4, 0	@086DC770
mAlignWord
	voice_square_1_alt 0, 1, 0, 3, 0, 0	@086DC77C
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@086DC788
mAlignWord
	voice_square_1_alt 0, 3, 0, 1, 0, 1	@086DC794
mAlignWord
	voice_square_1_alt 0, 2, 0, 2, 2, 2	@086DC7A0
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@086DC7AC
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@086DC7B8
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@086DC7C4
mAlignWord
	voice_directsound 60, 0, gUnknown_086DE134, 255, 0, 255, 0	@086DC7D0
mAlignWord
	voice_directsound 60, 0, gUnknown_086DF608, 255, 0, 255, 0	@086DC7DC
mAlignWord
	voice_directsound 60, 0, gUnknown_086E0A1C, 255, 0, 255, 0	@086DC7E8
mAlignWord
	voice_directsound 60, 0, gUnknown_086E134C, 255, 0, 255, 0	@086DC7F4
mAlignWord
	voice_directsound 60, 0, gUnknown_086E1ABC, 255, 0, 255, 127	@086DC800
mAlignWord
	voice_directsound 60, 0, gUnknown_086E33B0, 255, 0, 255, 127	@086DC80C
mAlignWord
	voice_directsound 60, 0, gUnknown_086E64DC, 255, 0, 255, 0	@086DC818
mAlignWord
	voice_directsound 60, 0, gUnknown_086E6B24, 255, 235, 38, 165	@086DC824
mAlignWord
	voice_directsound 60, 0, gUnknown_086EA218, 255, 0, 255, 127	@086DC830
mAlignWord
	voice_directsound 60, 0, gUnknown_086ED1F4, 255, 0, 255, 0	@086DC83C
mAlignWord
	voice_directsound 60, 0, gUnknown_086F0138, 255, 0, 255, 0	@086DC848
mAlignWord
	voice_directsound 60, 0, gUnknown_086F1AC0, 255, 0, 255, 127	@086DC854
mAlignWord
	voice_directsound 60, 0, gUnknown_086F1DC0, 255, 0, 255, 127	@086DC860
mAlignWord
	voice_noise 60, 0, 0, 0, 3, 0, 15, 4	@086DC86C
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DC878
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD720, 0, 0, 15, 0	@086DC884
mAlignWord
	voice_square_1_alt 0, 2, 0, 2, 0, 0	@086DC890
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 1	@086DC89C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC8A8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC8B4
mAlignWord
	voice_directsound 60, 0, gUnknown_086FBBD4, 255, 0, 255, 0	@086DC8C0
mAlignWord
	voice_directsound 60, 0, gUnknown_086FE150, 255, 0, 255, 0	@086DC8CC
mAlignWord
	voice_directsound 60, 0, gUnknown_086FE7E4, 255, 0, 255, 0	@086DC8D8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD750, 0, 3, 0, 2	@086DC8E4
mAlignWord
	voice_noise 60, 0, 0, 1, 1, 0, 12, 2	@086DC8F0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC8FC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC908
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC914
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC920
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC92C
mAlignWord
	voice_directsound 60, 0, gUnknown_0876FB20, 255, 0, 255, 0	@086DC938
mAlignWord
	voice_directsound 60, 0, gUnknown_08771CC4, 255, 0, 255, 0	@086DC944
mAlignWord
	voice_directsound 60, 0, gUnknown_08773848, 255, 0, 255, 0	@086DC950
mAlignWord
	voice_directsound 60, 0, gUnknown_08775640, 255, 0, 255, 0	@086DC95C
mAlignWord
	voice_directsound 60, 0, gUnknown_08775E7C, 255, 0, 255, 0	@086DC968
mAlignWord
	voice_directsound 60, 0, gUnknown_08778D48, 255, 0, 255, 0	@086DC974
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08779EDC, 255, 0, 255, 0	@086DC980
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0870FBC0, 255, 0, 255, 0	@086DC98C
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0870FFA0, 255, 0, 255, 0	@086DC998
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087103F8, 255, 0, 255, 0	@086DC9A4
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08710D74, 255, 0, 255, 0	@086DC9B0
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087111D4, 255, 0, 255, 0	@086DC9BC
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08711640, 255, 0, 255, 0	@086DC9C8
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08711ACC, 255, 0, 255, 0	@086DC9D4
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087123F8, 255, 0, 255, 0	@086DC9E0
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08712950, 255, 0, 255, 0	@086DC9EC
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0877AD00, 255, 0, 255, 0	@086DC9F8
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0877B9A0, 255, 0, 255, 0	@086DCA04
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@086DCA10
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 2	@086DCA1C
mAlignWord
	voice_noise 60, 0, 0, 1, 1, 0, 12, 2	@086DCA28
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@086DCA34
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 2	@086DCA40
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@086DCA4C
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 2	@086DCA58
mAlignWord
	voice_square_1_alt 0, 2, 3, 0, 10, 3	@086DCA64
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@086DCA70
mAlignWord
	voice_keysplit_all voicegroup001	@086DCA7C
