	mAlignWord
	@********************** Voicegroup **********************@

	.global voicegroup000
voicegroup000:	@ 0x086DB8AC
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@086DB8AC
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@086DB8B8
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@086DB8C4
mAlignWord
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@086DB8D0
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@086DB8DC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB8E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB8F4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB900
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB90C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB918
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@086DB924
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@086DB930
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DB93C
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@086DB948
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@086DB954
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB960
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB96C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB978
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB984
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB990
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB99C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB9A8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB9B4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB9C0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB9CC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB9D8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB9E4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB9F0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DB9FC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DBA08
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DBA14
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DBA20
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DBA2C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DBA38
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DBA44
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DBA50
mAlignWord
	voice_square_1_alt 0, 1, 1, 0, 15, 0	@086DBA5C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DBA68
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DBA74
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DBA80
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD6D0, 0, 4, 4, 0	@086DBA8C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD6E0, 0, 0, 15, 0	@086DBA98
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD6F0, 0, 0, 15, 0	@086DBAA4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD700, 0, 0, 15, 0	@086DBAB0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD710, 0, 0, 15, 0	@086DBABC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD720, 0, 0, 15, 0	@086DBAC8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 0, 15, 0	@086DBAD4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD740, 0, 0, 15, 0	@086DBAE0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD750, 0, 3, 0, 2	@086DBAEC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DBAF8
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@086DBB04
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@086DBB10
mAlignWord
	voice_square_1_alt 0, 2, 0, 3, 0, 0	@086DBB1C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD6D0, 0, 0, 15, 0	@086DBB28
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD750, 0, 3, 0, 2	@086DBB34
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD6D0, 0, 0, 15, 0	@086DBB40
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 5	@086DBB4C
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@086DBB58
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@086DBB64
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@086DBB70
mAlignWord
	voice_square_1_alt 0, 0, 0, 4, 0, 0	@086DBB7C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD750, 0, 4, 0, 0	@086DBB88
mAlignWord
	voice_square_2_alt 0, 0, 4, 4, 0	@086DBB94
mAlignWord
	voice_square_1_alt 0, 1, 0, 3, 0, 0	@086DBBA0
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@086DBBAC
mAlignWord
	voice_square_1_alt 0, 3, 0, 1, 0, 1	@086DBBB8
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD710, 0, 0, 15, 0	@086DBBC4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD720, 0, 0, 15, 0	@086DBBD0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 0, 15, 0	@086DBBDC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD740, 0, 0, 15, 0	@086DBBE8
mAlignWord
	voice_directsound 60, 0, gUnknown_086DE134, 255, 0, 255, 0	@086DBBF4
mAlignWord
	voice_directsound 60, 0, gUnknown_086DF608, 255, 0, 255, 0	@086DBC00
mAlignWord
	voice_directsound 60, 0, gUnknown_086E0A1C, 255, 0, 255, 0	@086DBC0C
mAlignWord
	voice_directsound 60, 0, gUnknown_086E134C, 255, 0, 255, 0	@086DBC18
mAlignWord
	voice_directsound 60, 0, gUnknown_086E1ABC, 255, 0, 255, 127	@086DBC24
mAlignWord
	voice_directsound 60, 0, gUnknown_086E33B0, 255, 0, 255, 127	@086DBC30
mAlignWord
	voice_directsound 60, 0, gUnknown_086E64DC, 255, 0, 255, 0	@086DBC3C
mAlignWord
	voice_directsound 60, 0, gUnknown_086E6B24, 255, 235, 38, 165	@086DBC48
mAlignWord
	voice_directsound 60, 0, gUnknown_086EA218, 255, 0, 255, 127	@086DBC54
mAlignWord
	voice_directsound 60, 0, gUnknown_086ED1F4, 255, 0, 255, 0	@086DBC60
mAlignWord
	voice_directsound 60, 0, gUnknown_086F0138, 255, 0, 255, 0	@086DBC6C
mAlignWord
	voice_directsound 60, 0, gUnknown_086F1AC0, 255, 0, 255, 127	@086DBC78
mAlignWord
	voice_directsound 60, 0, gUnknown_086F1DC0, 255, 0, 255, 127	@086DBC84
mAlignWord
	voice_keysplit voicegroup002, KeySplitTable1	@086DBC90
mAlignWord
	voice_directsound 60, 0, gUnknown_086F2994, 255, 246, 64, 149	@086DBC9C
mAlignWord
	voice_directsound 60, 0, gUnknown_086F5578, 255, 0, 255, 127	@086DBCA8
mAlignWord
	voice_directsound 60, 0, gUnknown_086F836C, 255, 0, 255, 127	@086DBCB4
mAlignWord
	voice_directsound 60, 0, gUnknown_086FA790, 255, 0, 255, 127	@086DBCC0
mAlignWord
	voice_directsound 60, 0, gUnknown_086FAEA4, 255, 0, 255, 127	@086DBCCC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD720, 0, 0, 15, 0	@086DBCD8
mAlignWord
	voice_directsound 60, 0, gUnknown_086FBBD4, 255, 0, 255, 127	@086DBCE4
mAlignWord
	voice_directsound 60, 0, gUnknown_086FE150, 255, 231, 0, 188	@086DBCF0
