	mAlignWord
	@********************** Voicegroup **********************@

	.global voicegroup004
voicegroup004:	@ 0x086DC29C
mAlignWord
	voice_directsound 60, 0, gUnknown_0874E6D0, 255, 0, 255, 0	@086DC29C
mAlignWord
	voice_directsound 60, 0, gUnknown_08753AEC, 255, 0, 255, 0	@086DC2A8
mAlignWord
	voice_directsound 60, 0, gUnknown_08758BB4, 255, 0, 255, 0	@086DC2B4
mAlignWord
	voice_directsound 60, 0, gUnknown_0875A76C, 255, 0, 255, 0	@086DC2C0
mAlignWord
	voice_directsound 60, 0, gUnknown_0875E854, 255, 0, 255, 0	@086DC2CC
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0871EF30, 255, 0, 255, 0	@086DC2D8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC2E4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC2F0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC2FC
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087634B0, 255, 0, 255, 0	@086DC308
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08763F44, 255, 0, 255, 0	@086DC314
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087644B8, 255, 0, 255, 0	@086DC320
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08764A24, 255, 0, 255, 0	@086DC32C
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08764EC8, 255, 0, 255, 0	@086DC338
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08765524, 255, 0, 255, 0	@086DC344
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08765FF0, 255, 0, 255, 0	@086DC350
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087665C8, 255, 0, 255, 0	@086DC35C
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08766AE4, 255, 0, 255, 0	@086DC368
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0876701C, 255, 0, 255, 0	@086DC374
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08767588, 255, 0, 255, 0	@086DC380
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08767A20, 255, 0, 255, 0	@086DC38C
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08768070, 255, 0, 255, 0	@086DC398
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC3A4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC3B0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DC3BC
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08768BA0, 255, 0, 255, 0	@086DC3C8
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087692C0, 255, 0, 255, 0	@086DC3D4
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0876995C, 255, 0, 255, 0	@086DC3E0
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0876A058, 255, 0, 255, 0	@086DC3EC
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0876A7E8, 255, 0, 255, 0	@086DC3F8
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0876AE6C, 255, 0, 255, 0	@086DC404
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0876B5CC, 255, 0, 255, 0	@086DC410
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0876BCBC, 255, 0, 255, 0	@086DC41C
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0876C1C4, 255, 0, 255, 0	@086DC428
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0876C974, 255, 0, 255, 0	@086DC434
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0876D0E8, 255, 0, 255, 0	@086DC440
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0876D79C, 255, 0, 255, 0	@086DC44C
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0876DF8C, 255, 0, 255, 0	@086DC458
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0876E614, 255, 0, 255, 0	@086DC464
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0876ED88, 255, 0, 255, 0	@086DC470
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0876F47C, 255, 0, 255, 0	@086DC47C
