	mAlignWord
	@********************** Voicegroup **********************@

	.global voicegroup006
voicegroup006:	@ 0x086DCA88
mAlignWord
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@086DCA88
mAlignWord
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@086DCA94
mAlignWord
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@086DCAA0
mAlignWord
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@086DCAAC
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@086DCAB8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCAC4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCAD0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCADC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCAE8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCAF4
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@086DCB00
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@086DCB0C
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DCB18
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@086DCB24
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@086DCB30
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCB3C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCB48
mAlignWord
	voice_square_2_alt 0, 0, 3, 0, 2	@086DCB54
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 4, 0	@086DCB60
mAlignWord
	voice_square_2_alt 2, 0, 2, 2, 0	@086DCB6C
mAlignWord
	voice_directsound 60, 0, gUnknown_086FF18C, 255, 0, 255, 149	@086DCB78
mAlignWord
	voice_directsound 60, 0, gUnknown_0877CF24, 255, 0, 255, 149	@086DCB84
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@086DCB90
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 7, 0	@086DCB9C
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DCBA8
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 9, 6	@086DCBB4
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@086DCBC0
mAlignWord
	voice_square_2_alt 2, 0, 4, 0, 6	@086DCBCC
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@086DCBD8
mAlignWord
	voice_square_2_alt 2, 0, 4, 13, 6	@086DCBE4
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@086DCBF0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD740, 0, 0, 15, 0	@086DCBFC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 0, 15, 0	@086DCC08
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 1, 4	@086DCC14
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@086DCC20
mAlignWord
	voice_square_1_alt 0, 1, 0, 6, 0, 6	@086DCC2C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 2, 0, 15, 0	@086DCC38
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 1, 2	@086DCC44
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DCC50
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@086DCC5C
mAlignWord
	voice_square_1_alt 0, 1, 0, 6, 0, 6	@086DCC68
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 6	@086DCC74
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 0, 15, 0	@086DCC80
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@086DCC8C
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@086DCC98
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@086DCCA4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 1, 4	@086DCCB0
mAlignWord
	voice_square_1_alt 0, 2, 0, 6, 0, 6	@086DCCBC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD740, 0, 6, 0, 6	@086DCCC8
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@086DCCD4
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@086DCCE0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 1, 4	@086DCCEC
mAlignWord
	voice_square_1_alt 0, 2, 1, 0, 10, 3	@086DCCF8
mAlignWord
	voice_square_2_alt 2, 0, 6, 0, 6	@086DCD04
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_86DD730, 0, 3, 1, 3	@086DCD10
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@086DCD1C
mAlignWord
	voice_square_1_alt 0, 1, 2, 0, 10, 3	@086DCD28
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@086DCD34
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@086DCD40
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@086DCD4C
mAlignWord
	voice_directsound 60, 0, gUnknown_0877F2A4, 255, 0, 255, 0	@086DCD58
mAlignWord
	voice_directsound 60, 0, gUnknown_0878306C, 255, 0, 255, 0	@086DCD64
mAlignWord
	voice_directsound 60, 0, gUnknown_08789214, 255, 0, 255, 0	@086DCD70
mAlignWord
	voice_directsound 60, 0, gUnknown_0878D964, 255, 0, 255, 0	@086DCD7C
mAlignWord
	voice_directsound 60, 0, gUnknown_0878FAAC, 255, 0, 255, 0	@086DCD88
mAlignWord
	voice_directsound 60, 0, gUnknown_0877F2A4, 255, 0, 255, 0	@086DCD94
mAlignWord
	voice_directsound 60, 0, gUnknown_0878306C, 255, 0, 255, 0	@086DCDA0
mAlignWord
	voice_directsound 60, 0, gUnknown_08789214, 255, 250, 18, 250	@086DCDAC
mAlignWord
	voice_directsound 60, 0, gUnknown_0878D964, 255, 250, 18, 250	@086DCDB8
mAlignWord
	voice_directsound 60, 0, gUnknown_0878FAAC, 255, 250, 18, 250	@086DCDC4
mAlignWord
	voice_directsound 60, 0, gUnknown_086DE134, 255, 0, 255, 0	@086DCDD0
mAlignWord
	voice_directsound 60, 0, gUnknown_086DF608, 255, 0, 255, 0	@086DCDDC
mAlignWord
	voice_directsound 60, 0, gUnknown_086E0A1C, 255, 0, 255, 0	@086DCDE8
mAlignWord
	voice_directsound 60, 0, gUnknown_086E134C, 255, 0, 255, 0	@086DCDF4
mAlignWord
	voice_directsound 60, 0, gUnknown_086E1ABC, 255, 0, 255, 127	@086DCE00
mAlignWord
	voice_directsound 60, 0, gUnknown_086E33B0, 255, 0, 255, 127	@086DCE0C
mAlignWord
	voice_directsound 60, 0, gUnknown_086E64DC, 255, 0, 255, 0	@086DCE18
mAlignWord
	voice_directsound 60, 0, gUnknown_086E6B24, 255, 235, 38, 165	@086DCE24
mAlignWord
	voice_directsound 60, 0, gUnknown_086EA218, 255, 0, 255, 127	@086DCE30
mAlignWord
	voice_directsound 60, 0, gUnknown_086ED1F4, 255, 0, 255, 0	@086DCE3C
mAlignWord
	voice_directsound 60, 0, gUnknown_086F0138, 255, 0, 255, 0	@086DCE48
mAlignWord
	voice_directsound 60, 0, gUnknown_086F1AC0, 255, 0, 255, 127	@086DCE54
mAlignWord
	voice_directsound 60, 0, gUnknown_086F1DC0, 255, 0, 255, 127	@086DCE60
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCE6C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCE78
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCE84
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCE90
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 1	@086DCE9C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCEA8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCEB4
mAlignWord
	voice_directsound 60, 0, gUnknown_086FBBD4, 255, 0, 255, 0	@086DCEC0
mAlignWord
	voice_directsound 60, 0, gUnknown_086FE150, 255, 0, 255, 0	@086DCECC
mAlignWord
	voice_directsound 60, 0, gUnknown_086FE7E4, 255, 0, 255, 0	@086DCED8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCEE4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCEF0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCEFC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCF08
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCF14
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCF20
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCF2C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCF38
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCF44
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCF50
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCF5C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCF68
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCF74
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@086DCF80
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0870FBC0, 255, 0, 255, 0	@086DCF8C
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0870FFA0, 255, 0, 255, 0	@086DCF98
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087103F8, 255, 0, 255, 0	@086DCFA4
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08710D74, 255, 0, 255, 0	@086DCFB0
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087111D4, 255, 0, 255, 0	@086DCFBC
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08711640, 255, 0, 255, 0	@086DCFC8
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08711ACC, 255, 0, 255, 0	@086DCFD4
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_087123F8, 255, 0, 255, 0	@086DCFE0
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_08712950, 255, 0, 255, 0	@086DCFEC
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0877AD00, 255, 0, 255, 0	@086DCFF8
mAlignWord
	voice_directsound_no_resample 60, 0, gUnknown_0877B9A0, 255, 0, 255, 0	@086DD004
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@086DD010
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 2	@086DD01C
mAlignWord
	voice_noise 60, 0, 0, 1, 1, 0, 12, 2	@086DD028
mAlignWord
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@086DD034
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 2	@086DD040
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@086DD04C
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 2	@086DD058
mAlignWord
	voice_square_1_alt 0, 2, 3, 0, 10, 3	@086DD064
mAlignWord
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@086DD070
mAlignWord
	voice_keysplit_all voicegroup001	@086DD07C
